### ISSUE TITLE
vespa benchmark

### ISSUE THREAD

**Issue by hahapt** [vespa-engine/vespa#10086]
I'm trying to take benchmark about vespa to see how well the performance it has, but in the README file in vespa/fbench, I can't figure out how to install the benchmark tool fbench. 
In the README file, it recommend me to consult the 'INSTALL' file about how to install fbench, but I can't find the 'INSTALL' file!
Do anyone knows how to install vespa fbench and use it?

**Comment by aressem** [comment]
vespa-fbench is installed as part of Vespa. If you have Docker installed you can use the pre built vespa images like this to run it:
```
$ docker run  --entrypoint /opt/vespa/bin/vespa-fbench  docker.io/vespaengine/vespa <your fbench options here>
``` 
Alternatively on CentOS 7/RHEL 7 hosts you can install Vespa and use vespa-fbench from that installation:
``` 
$ yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/g/vespa/vespa/repo/epel-7/group_vespa-vespa-epel-7.repo
$ yum -y install epel-release centos-release-scl
$ yum -y install vespa
$ /opt/vespa/bin/vespa-fbench <your fbench options here>
```

**Comment by bratseth** [comment]
Could we put this in the readme please?

**Comment by aressem** [comment]
PR here : https://github.com/vespa-engine/vespa/pull/10089

**Comment by hahapt** [comment]
I have start a vespa docker container following the [Blog search tutorial] in the vespa document, what should I do if I want to make benchmark about the blog data? Do I need to point out which docker I want to benchmark when I run [$ docker run  --entrypoint /opt/vespa/bin/vespa-fbench  docker.io/vespaengine/vespa <your fbench options here>] ?

**Comment by aressem** [comment]
If you look at this page:
https://docs.vespa.ai/documentation/performance/fbench.html

You will see that you need to specify hostname/IP and port for fbench to connect to. Your docker container where Vespa runs should be used.

As for the benchmark data you will need to map those in since vespa-fbench is invoked inside the container. Look at ```docker run --help``` and use the ```--volume``` option to map the data into the container.

**Comment by hahapt** [comment]
I have some other problem, I run the following command but it say it can't open the query file, I was wonder if I have something wrong.





------------------ 原始邮件 ------------------
发件人: "Arnstein Ressem"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午2:59
收件人: "vespa-engine/vespa"<vespa@noreply.github.com>;
抄送: "洪娉婷"<705641216@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vespa-engine/vespa] vespa benchmark (#10086)




If you look at this page:
 https://docs.vespa.ai/documentation/performance/fbench.html
 
You will see that you need to specify hostname/IP and port for fbench to connect to. Your docker container where Vespa runs should be used.
 
As for the benchmark data you will need to map those in since vespa-fbench is invoked inside the container. Look at docker run --help and use the --volume option to map the data into the container.
