### ISSUE TITLE
vespa benchmark on Mac OS by docker

### ISSUE THREAD

**Issue by hahapt** [vespa-engine/vespa#10211]
I use Mac OS to learn vespa by docker, and I follow the vespa document [Quick Start][Blog Search Tutorial]. Now I want to make benchmark to see it's performance, but I thought I have met a lot of problems. 

1、In the vespa-fbench github, it told me to use the following code.
` docker run --entrypoint /opt/vespa/bin/vespa-fbench  docker.io/vespaengine/vespa <your fbench options>`
once I run this code, it will build a new docker container, what if I want to make benchmark about the vespa docker container I have already build?  Like the vespa docker container I have already built follow the [Blog Search Tutorial] document, how do I take benchmark use these blog data?

2、In the [Vespa Benchmarking] document, it told me that I need to prepare query files like this pattern: /search/?query=foo&parameter=blabla. I'm confused about the meaning of [query=foo], and I'm also confused about how the queries place in the .txt file. Should one query take up one line? What's more, is there any tool to help build the query file?

3、In the README of vespa-fbench github, here is a step called 'Preparing the test date'. I can not figure out what is this step doing? And how to use [vespa-fbench-filter-file] or [splitfile] through docker?

**Comment by jobergum** [comment]
1) Enter the docker container you have already created by 
```docker exec -it vespa bash```
 and run vespa-fbench as the utility is already part of the vespaengine/vespa docker image. 

2) For GET requests it's one line and the search api is documented here https://docs.vespa.ai/documentation/search-api.html. For POST search requests it's one line with the path and the request body (json) on the following line. 

3) These utilities are available inside the docker image, see 1 but you don't need a lot of fuzz to get this working. A file with one request which matches the sample data from the quick start, e.g

```
/search/?query=bad
```

Save in query.txt

```
vespa-fbench -n 1 -c 0 -q query.txt -s 60 -p 5 localhost 
```

**Comment by hahapt** [comment]
When I run the command, it told me that it can not open the query file, I have some problem about it.





------------------ 原始邮件 ------------------
发件人: "Jo Kristian Bergum"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:42
收件人: "vespa-engine/vespa"<vespa@noreply.github.com>;
抄送: "洪娉婷"<705641216@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vespa-engine/vespa] vespa benchmark on Mac OS by docker (#10211)



 
 
Enter the docker container you have already created by
 docker exec -it vespa bash
 and run vespa-fbench as the utility is already part of the vespaengine/vespa docker image.
 
 
 
For GET requests it's one line and the search api is documented here https://docs.vespa.ai/documentation/search-api.html. For POST search requests it's one line with the path and the request body (json) on the following line.
 
 
 
These utilities are available inside the docker image, see 1 but you don't need a lot of fuzz to get this working. A file with one request which matches the sample data from the quick start, e.g
 
  /search/?query=bad  
Save in query.txt
 vespa-fbench -n 1 -c 0 -q query.txt -s 60 -p 5 localhost

**Comment by jobergum** [comment]
```
docker exec -it vespa bash
[root@vespa-container /]# echo "/search/?query=bad" > query.txt
[root@vespa-container /]# vespa-fbench -n 1 -q query.txt -c 0 localhost 8080 
Starting clients...
[dummydate]: PROGRESS: vespa-fbench: Seconds left 60
Stopping clients
Clients stopped.
.
Clients Joined.
*** HTTP keep-alive statistics ***
connection reuse count -- 24456
***************** Benchmark Summary *****************
clients:                       1
ran for:                      60 seconds
cycle time:                    0 ms
lower response limit:          0 bytes
skipped requests:              0
failed requests:               0
successful requests:       24457
cycles not held:           24457
minimum response time:      1.04 ms
maximum response time:    426.47 ms
average response time:      2.41 ms
25 percentile:              1.70 ms
50 percentile:              2.10 ms
75 percentile:              2.70 ms
90 percentile:              3.50 ms
95 percentile:              4.30 ms
99 percentile:              7.10 ms
actual query rate:        407.92 Q/s
utilization:               98.12 %
zero hit queries:          24457
http request status breakdown:
       200 :    24457 
´´´

**Comment by hahapt** [comment]
I try these command and receive benchmark result, thanks for your help.
But I have another question: what does the [query=bad] mean? And what the norm query file should obey? 




------------------ 原始邮件 ------------------
发件人: "Jo Kristian Bergum"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午3:47
收件人: "vespa-engine/vespa"<vespa@noreply.github.com>;
抄送: "洪娉婷"<705641216@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vespa-engine/vespa] vespa benchmark on Mac OS by docker (#10211)



docker exec -it vespa bash [root@vespa-container /]# echo "/search/?query=bad" > query.txt [root@vespa-container /]# vespa-fbench -n 1 -q query.txt -c 0 localhost 8080  Starting clients... [dummydate]: PROGRESS: vespa-fbench: Seconds left 60 Stopping clients Clients stopped. . Clients Joined. *** HTTP keep-alive statistics *** connection reuse count -- 24456 ***************** Benchmark Summary ***************** clients:                       1 ran for:                      60 seconds cycle time:                    0 ms lower response limit:          0 bytes skipped requests:              0 failed requests:               0 successful requests:       24457 cycles not held:           24457 minimum response time:      1.04 ms maximum response time:    426.47 ms average response time:      2.41 ms 25 percentile:              1.70 ms 50 percentile:              2.10 ms 75 percentile:              2.70 ms 90 percentile:              3.50 ms 95 percentile:              4.30 ms 99 percentile:              7.10 ms actual query rate:        407.92 Q/s utilization:               98.12 % zero hit queries:          24457 http request status breakdown:        200 :    24457  ´´´

**Comment by jobergum** [comment]
See https://docs.vespa.ai/documentation/performance/fbench.html for the input txt file format.

The ?query is a parameter in the search api (see https://docs.vespa.ai/documentation/search-api.html) and in this case it takes the value 'bad' which then searches the data for the term 'bad'.

**Comment by hahapt** [comment]
So if I want take benchmark with more clients, should I prepare query files like query000.txt, query001.txt and so on? And how do I write the command "vespa-fbench -n 1 -q query.txt -c 0 localhost 8080 " ?




------------------ 原始邮件 ------------------
发件人: "Jo Kristian Bergum"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午4:32
收件人: "vespa-engine/vespa"<vespa@noreply.github.com>;
抄送: "洪娉婷"<705641216@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vespa-engine/vespa] vespa benchmark on Mac OS by docker (#10211)




See https://docs.vespa.ai/documentation/performance/fbench.html for the input txt file format.
 
The ?query is a parameter in the search api (see https://docs.vespa.ai/documentation/search-api.html) and in this case it takes the value 'bad' which then searches the data for the term 'bad'.

**Comment by jobergum** [comment]
Please see https://docs.vespa.ai/documentation/performance/fbench.html. The number of clients/threads is controlled by the -n parameter.

**Comment by jobergum** [comment]
I'm resolving this. Thanks
