### ISSUE TITLE
TensorFlow Keras Models exported with TF 1.14's `tf.keras.experimental.export_saved_model` fail to deploy

### ISSUE THREAD

**Issue by zmjjmz** [vespa-engine/vespa#10283]
While I've been able to get a 'manually' exported `keras` model to work in Vespa, this process involves some unnecessary and deprecated code like so:
```
signature = tf.saved_model.signature_def_utils.predict_signature_def(          
    inputs={'userid': model.input}, outputs={'scores': model.output})          
                                                                               
builder = tf.saved_model.builder.SavedModelBuilder('tfkeras_model')            
builder.add_meta_graph_and_variables(                                          
    sess=tf.keras.backend.get_session(),                                       
    tags=[tf.saved_model.tag_constants.SERVING],                               
    signature_def_map={                                                        
        tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:  
            signature                                                          
    })                                                                         
builder.save()                                                                 
```

In TF 1.14 (and, in the future, TF 2) there's [`tf.experimental.export_saved_model`](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model), which allows me to avoid all of this and stay out of deprecation-land. However SavedModels generated this way appear to be broken when deployed in Vespa.

I've provided code and errors and signatures in [this gist](https://gist.github.com/zmjjmz/1ec864404e4fed80e5ccf52c7589ea30)

export_servonly_{error,signature} is the result of only exporting the serve tag-set, which is notably a different error from exporting the whole tag-set (which is definitely unnecessary). My suspicion (comparing the signatures to those generated with the above process) is the added `__saved_model_init_op` signature, but I can't make enough sense of the error I get from that case.

Caveats:
- This issue may be entangled with https://github.com/vespa-engine/vespa/issues/10282, since I need to use `tf.keras` to use `tf.keras.experimental.export_saved_model` -- however I encounter a different error in this case.
- This issue may be due to `tf.keras.experimental.export_saved_model` being broken, and not Vespa.

**Comment by lesters** [comment]
Thanks again @zmjjmz for the report and gist. I'll take a look at this and #10282 ASAP.

**Comment by lesters** [comment]
So, as you mention here, there are two distinct errors here. When using `serving_only=False` in `export_saved_model`, an `init_op` node appears in the model which Vespa doesn't handle very well as it is a no-op. I'll add a fix to this soon.

But when using `serving_only=True` you get this `Invalid application package` error which stems from TF version differences, here made clear by a protobuf problem. Vespa currently uses TF 1.12, and this `experimental.export_saved_model` requires TF 1.14. Currently, we won't upgrade to TF 1.14 as we are dependent upon the Java TF bindings and there is currently an issue with those in TF 1.14 (see https://github.com/tensorflow/tensorflow/issues/30635). Unless that is fixed we will probably wait to upgrade TF version in Vespa until 2.0 is released.

**Comment by zmjjmz** [comment]
Considering that also `tf.keras.experimental.export_saved_model` will be deprecated in favor of `tf.keras.model.save(format='tf')` (or something like that) in TF 2, I can understand that. 

Any day now, TF 2 will be released!

Should I close this then?

**Comment by lesters** [comment]
Thanks @zmjjmz, we're doing work to prepare for TF2.0 so let's close this for now.
