### ISSUE TITLE
How to change configuration defined in proton.def

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#10363]
I want to change `pruneremoveddocumentsage` defined in [proton.def](https://github.com/vespa-engine/vespa/blob/master/searchcore/src/vespa/searchcore/config/proton.def#L326). I find this file in `/path/to/vespa/share/vespa/configdefinitions/vespa.config.search.core.proton.def`, can I directly change the value in this file and restart the service?

**Comment by baldersheim** [comment]
No, that is just a default value used at build time.

You should just add this to the tuning section in the content cluster in your services.xml file and redeploy. If the change requires restart you will be told which services to restart. See https://docs.vespa.ai/documentation/content/setup-proton-tuning.html#removed-db-prune-age
....
<content>
  <engine>
    <proton>
      <searchnode>
        <tuning>
          <removed-db>
            <prune>
              <age>86400</age>            <-- 24 hours
....

BTW. How did you get down to proton.def and pruneremoveddocumentsage ?
If that was through our documentation it must be updated.

**Comment by luoyetx** [comment]
Thanks. I find the configure [here](https://docs.vespa.ai/documentation/elastic-vespa.html#data-retention-vs-size).
