### ISSUE TITLE
How does vespa deal with emoji?

### ISSUE THREAD

**Issue by fanwy11** [vespa-engine/vespa#10423]
Some fields of my document contains emoji. But I can not get the right result when search with a emoji.
My yql is `select * from INEDX_NAME where title contains "🍉";`
And the result is: 
`{
    "root": {
        "id": "toplevel",
        "relevance": 1,
        "fields": {
            "totalCount": 0
        },
        "errors": [
            {
                "code": 3,
                "summary": "Illegal query",
                "source": "INEDX_NAME",
                "message": "No query"
            }
        ]
    }
}`

**Comment by bratseth** [comment]
This is because the default linguistics module, OpenNLP doesn't treat emojis as word characters, so they are filtered away.

You'll need to configure your own linguistics processor, see https://docs.vespa.ai/documentation/linguistics.html

It could be as simple as returning emojis as-is and delegating other text to OpenNLP

**Comment by fanwy11** [comment]
> This is because the default linguistics module, OpenNLP doesn't treat emojis as word characters, so they are filtered away.
> 
> You'll need to configure your own linguistics processor, see https://docs.vespa.ai/documentation/linguistics.html
> 
> It could be as simple as returning emojis as-is and delegating other text to OpenNLP

Thanks for your quickly reply. I will try it later.

**Comment by jobergum** [comment]
With match:word or match:exact https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#match you can search for any characters but then you don't get tokenization (through mentioned OpenNLP linguistic integration).
