### ISSUE TITLE
Issue with structured data

### ISSUE THREAD

**Issue by DavideBonavitaJustis** [vespa-engine/vespa#10448]
Hello,
when I try to feed a json file with struct fields using vespa-http-client-jar-with-dependencies.jar it throws an error:

> Failure: Result for 'id:judgment:judgment::r06opoy8f91hh
1567008894257 Trace starting
1567008894516 Asked about retrying for cluster ID 0, number of retries is 1 Detail:
Detail resultType=FATAL_ERROR exception='Has created a composite field value the reader does not know how to handle: com.yahoo.document.datatypes.StringFieldValue **This is a bug**. token = START_ARRAY' endpoint=localhost:8080 ssl=false resultTimeLocally=1567008894516
1567008894527 Got detail: Detail resultType=FATAL_ERROR exception='Has created a composite field value the reader does not know how to handle: com.yahoo.document.datatypes.StringFieldValue This is a bug. token = START_ARRAY' endpoint=localhost:8080 ssl=false resultTimeLocally=1567008894516

> 
> Detail resultType=FATAL_ERROR exception='Has created a composite field value the reader does not know how to handle: com.yahoo.document.datatypes.StringFieldValue This is a bug. token = START_ARRAY' endpoint=localhost:8080 ssl=false resultTimeLocally=1567008894516
> 
> Wed Aug 28 16:14:54 UTC 2019 Result received: 1 (1 failed so far, 1 sent, success rate 0.00 docs/sec).

the application is very basic, here is the search definition and a json example:

```
search judgment {
    document judgment {
        struct propertyValuesDef {
                field citedAs type array<string> {
                }
                field title type array<string> {
                }
                field content type string {
                }
                field date type string {
                }
                field classId type string {
                }
        }
        struct relationshipsDef {
                field subjectMatter type array<string> {
                }
                field cites type array<string> {
                }
                field database type array<string> {
                }
                field issuer type array<string> {
                }
                field headnotes type array<string> {
                }
                field judge type array<string> {
                }
                field jurisdiction type array<string> {
                }
        }
        field recordId type string {
            indexing: summary | index
        }
        field propertyValues type propertyValuesDef {
                indexing: summary | index
        }
        field relationships type relationshipsDef {
                indexing: summary | index
        }
    }
    fieldset default {
        fields: propertyValues
    }
}
```

The test json file is:

```
 {
 "put": "id:judgment:judgment::r06opoy8f91hh",
 "fields":{
   "recordId": "r06opoy8f91hh",
   "propertyValues": {
     "citedAs": [
       "13 December 2016"
     ],
     "title": [
       "Test"
     ],
     "content": [
       "Test"
     ],
     "date": [
       "2016-11-16T00:00:00Z"
     ],
     "classId": [
       "a6"
     ]
   },
   "relationships": {
     "subjectMatter": [
       "http://test",
       "http://test"
     ],
     "cites": [
       "http://cte",
       "http:/test"
     ],
     "database": [
       ":r06or1kfft14e",
       "http://test"
     ],
     "issuer": [
       "http://test",
       "http://test",
       "http://test"
     ],
     "jurisdiction": [
       "http://test",
       "http://test"
     ]
   }
 
 }
 }
```

**Comment by geirst** [comment]
The `content`, `date`, and `classId` fields in `propertyValuesDef` are of type string. They cannot be provided as arrays in the json file. If you change it to the following it should work:

```
"propertyValues": {
    "citedAs": ["13 December 2016"],
    "title": ["Test"],
    "content": "Test",
    "date": "2016-11-16T00:00:00Z",
    "classId": "a6"
},
```

**Comment by geirst** [comment]
Also note that struct fields (`propertyValues`, `relationships`) can only be searched in streaming search. 
See https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#type:struct and https://docs.vespa.ai/documentation/streaming-search.html for more information.

**Comment by bratseth** [comment]
The error message here is wrong, fixed by
https://github.com/vespa-engine/vespa/pull/10463
