### ISSUE TITLE
Failed to restart vespa server

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#10451]
Hi,
We add a content cluster to the online cluster, and vespa told us the to restart the service. We found an IO exception sometimes after vespa service restarts.  It seems that vespa can't find the document directory, however the directory exists in our server.

> 1567050444.865199       n28-020-206.byted.org   2369130 searchnode2     stderr  warning terminate called after throwing an instance of 'vespalib::IoException'
1567050444.865235       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   what():  IoException: NOT FOUND: Failed to list directory './var/db/vespa/search/cluster.aweme_video_tail/n0/documents' at listDirectory in /data00/home/bianyunlong/vespa/vespa/vespalib/src/vespa/vespalib/io/fileutil.cpp:757
1567050444.865262       n28-020-206.byted.org   2369130 searchnode2     stderr  warning Backtrace:
1567050444.865269       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::IoException::IoException(vespalib::stringref, vespalib::IoException::Type, vespalib::stringref, int)+0x46) [0x7f8bd63d42e6]
1567050444.865279       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::listDirectory(vespalib::small_string<48u> const&)+0x3d7) [0x7f8bd63334b7]
1567050444.865287       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin(proton::ProtonDiskLayout::initAndPruneUnused(std::set<proton::DocTypeName, std::less<proton::DocTypeName>, std::allocator<proton::DocTypeName> > const&)+0x107) [0x577ff7]
1567050444.865296       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin(proton::ProtonConfigurer::pruneInitialDocumentDBDirs(proton::ProtonConfigSnapshot const&)+0x1dc) [0x57389c]
1567050444.865305       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin(proton::ProtonConfigurer::applyConfig(std::shared_ptr<proton::ProtonConfigSnapshot>, std::shared_ptr<vespalib::ThreadStackExecutorBase>, bool)+0x4a3) [0x574c73]
1567050444.865314       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin() [0x575014]
1567050444.865322       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::ThreadStackExecutorBase::run()+0xb6) [0x7f8bd63e0e66]
1567050444.865331       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::unnamed_nonblocking_executor(vespalib::Runnable&)+0x9) [0x7f8bd63df679]
1567050444.865339       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libfastos.so(FastOS_ThreadInterface::Hook()+0x113) [0x7f8bd61fd7c3]
1567050444.865347       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/libfastos.so(FastOS_ThreadHook+0x9) [0x7f8bd61fd969]
1567050444.865353       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /opt/tiger/vespa/lib64/vespa/malloc/libvespamalloc.so(+0x532b) [0x7f8bd901a32b]
1567050444.865359       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f8bd5dcc064]
1567050444.865366       n28-020-206.byted.org   2369130 searchnode2     stderr  warning   /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8bd1ff663d]
1567050445.054475       n28-020-206.byted.org   2364207/8204    config-sentinel config-sentinel.service event   crash/1 name="searchnode2" pid=2369130 signal="Aborted"
1567050445.054509       n28-020-206.byted.org   2364207/8204    config-sentinel config-sentinel.service info    searchnode2: incremented restart penalty to 62 seconds
1567050445.054518       n28-020-206.byted.org   2364207/8204    config-sentinel config-sentinel.service info    searchnode2: incremented restart penalty to 126 seconds
1567050445.054525       n28-020-206.byted.org   2364207/8204    config-sentinel config-sentinel.service info    searchnode2: will delay start by 125 seconds
1567050455.062743       n28-020-206.byted.org   2369329/8204    config-sentinel config-sentinel.service event   starting/1 name="searchnode"
1567050455.225110       n28-020-206.byted.org   2369329/36707   searchnode      proton.proton.server.bootstrapconfigmanager     info    Filedistributorrpc config is changed
1567050455.363732       n28-020-206.byted.org   2369329/36707   searchnode      proton.translogserverapp        config  configure Transaction Log Server tls at port 19113
1567050458.271537       n28-020-206.byted.org   2364399 container       stdout  info    [51.960s][info][gc] GC(9) Pause Young (Normal) (G1 Evacuation Pause) 380M->126M(4096M) 6.254ms
1567050469.231122       n28-020-206.byted.org   2369329 searchnode      stderr  warning terminate called after throwing an instance of 'vespalib::IoException'
1567050469.244523       n28-020-206.byted.org   2369329 searchnode      stderr  warning   what():  IoException: NOT FOUND: Failed to list directory './var/db/vespa/search/cluster.aweme_video_index_v2/n0/documents' at listDirectory in /data00/home/bianyunlong/vespa/vespa/vespalib/src/vespa/vespalib/io/fileutil.cpp:757
1567050469.244547       n28-020-206.byted.org   2369329 searchnode      stderr  warning Backtrace:
1567050469.244554       n28-020-206.byted.org   2369329 searchnode      stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::IoException::IoException(vespalib::stringref, vespalib::IoException::Type, vespalib::stringref, int)+0x46) [0x7f651e4ba2e6]
1567050469.244561       n28-020-206.byted.org   2369329 searchnode      stderr  warning   /opt/tiger/vespa/lib64/libvespalib.so(vespalib::listDirectory(vespalib::small_string<48u> const&)+0x3d7) [0x7f651e4194b7]
1567050469.244567       n28-020-206.byted.org   2369329 searchnode      stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin(proton::ProtonDiskLayout::initAndPruneUnused(std::set<proton::DocTypeName, std::less<proton::DocTypeName>, std::allocator<proton::DocTypeName> > const&)+0x107) [0x577ff7]
1567050469.244574       n28-020-206.byted.org   2369329 searchnode      stderr  warning   /opt/tiger/vespa/sbin/vespa-proton-bin(proton::ProtonConfigurer::pruneInitialDocumentDBDirs(proton::ProtonConfigS

**Comment by aressem** [comment]
Thanks for reporting. Could you share a bit more about your installation:
- Which version of Vespa are you running ?
- How was this version installed ? (The tiger in /opt/tiger/vespa/lib64/libvespalib.so looks suspicious)
- Have you explicitly set any Vespa related environment variables prior to starting Vespa on the nodes ?

**Comment by dsisds** [comment]
Thanks for reply.
1. 7.0.0. I compile vespa on my server with master branch.
2. I specified install path to be /opt/tiger when building vespa.
3. No. Following is my conf/vespa.default-env.txt.

> 
fallback VESPA_HOME /opt/tiger/vespa
override VESPA_USER tiger
override VESPA_UNPRIVILEGED no

**Comment by aressem** [comment]
Some follow up questions:
* Do you use Docker in any way to run Vespa (e.g. mapping something under /opt/tiger into Docker containers) ?
* Which tag or ref did you use for the git checkout for the source code in question ?

I will try to reproduce your observed issues. If you have checked out the source code HEAD at an arbitrary point in time please do not continue with this practice unless it is for Vespa development. Please use the release tags in https://github.com/vespa-engine/vespa/releases which are the tags of official open source releases. These are well tested in production in Verizon Media. It will also make it easier for us to track down reported bugs as we can use the exact same source code for analysis.

**Comment by dsisds** [comment]
1. No, we run Vespa on server directly.
2. vespa-7.9.16-1
3. I do make with my own account and do make install as tiger.
4. I started vespa with systemd. I tried to restart service with thee scripts, and same error occurs.

**Comment by aressem** [comment]
I have compiled and installed the same version, loaded an application, fed data and restarting the service. But, I can not reproduce the behaviour you are seeing. It would be useful to look at your systemd scripts that you use.

If you started Vespa with systemd, but manually tried to stop and start with the scripts in /opt/tiger/vespa/bin, this could be an issue. Systemd will detect that the service stopped and tried to restart at the same time you restarting manually. Not sure if this is the case, but if you use systemd you should always use ```systemctl restart <name of your Vespa service>```.

Also if you execute scripts manually, try to set ``èxport VESPA_HOME=/opt/tiger/vespa``` to see if that makes the problem go away. 

Final recommendation is to use the current Vespa RPM and install it the same way as we do in our published Docker image:
```
https://github.com/vespa-engine/docker-image/blob/master/Dockerfile 
```

**Comment by dsisds** [comment]
I tried to set VESPA_HOME=/opt/tiger/vespa and it doesn't work.
This error only occurs on a few servers. And If I remove the var directory and redeploy application,  vespa could start.

**Comment by aressem** [comment]
Ok. Without having access to all the systemd scripts and your exact commands executed when you restart Vespa, it is difficult to figure out what is going on here. Also, the version of Vespa is quite old. My next suggestion would be to upgrade to the Vespa version to the current vespa-7.99.22-1 to see if the problem is still there.

**Comment by kkraune** [comment]
https://docs.vespa.ai/en/operations/multinode-systems.html#aws-ec2 is updated with systemctl start/stop examples
