### ISSUE TITLE
Access to search definition's grammar to create a syntax coloration ?

### ISSUE THREAD

**Issue by francoisWeber** [vespa-engine/vespa#10531]
I'm starting to use Vespa through search definition files and I found no syntax coloration under VSCode (or other IDE). I thought about building a new extension to get this but I need the `.sd` language's grammar definition. 
Would it be possible to access to `.sd` grammar ? Thanks

**Comment by bratseth** [comment]
The grammar is https://github.com/vespa-engine/vespa/blob/master/config-model/src/main/javacc/SDParser.jj

If you create something please submit it back. Thanks!
