### ISSUE TITLE
Upgrading vespa version from 7.83.27-1 to 7.104.46 causes HTTPS connection failure

### ISSUE THREAD

**Issue by rameshpoti** [vespa-engine/vespa#10740]
Upgrading vespa version from 7.83.27-1 to 7.104.46 causes SSL (TLS) connection failure from .NET client (Windows server 2012 R2). Following is the error we see when connection attempt is made to vespa cluster over HTTPS. The same client is working with the earlier version of Vespa version mentioned. 

INNER EXCEPTION : System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted --- End of inner exception stack trace --- at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)

Not sure if this is related to the following change where the openssl dependency was set to 1.1.1c-1

https://github.com/vespa-engine/vespa/pull/10413

During the upgrade the following package was installed 
Dep-Install vespa-openssl-1.1.1c-1.el7.x86_64 

and the openssl package version was 1.0.2k

Did the upgrade of openssl version removed some of the older version of TLS cipher support ? Is there anyway to enable backward compatibility with older version ?

Older version of vespa supported the following ciphers 
tls1_2: ECDHE-RSA-AES256-GCM-SHA384
tls1_2: ECDHE-RSA-AES256-SHA384
tls1_2: DHE-RSA-AES256-GCM-SHA384
tls1_2: DHE-RSA-AES256-SHA256
tls1_2: ECDHE-RSA-AES128-GCM-SHA256
tls1_2: ECDHE-RSA-AES128-SHA256
tls1_2: DHE-RSA-AES128-GCM-SHA256
tls1_2: DHE-RSA-AES128-SHA256

but the new one only supports 

tls1_2: ECDHE-RSA-AES256-GCM-SHA384
tls1_2: ECDHE-RSA-AES128-GCM-SHA256

and the Windows server version does not support these ciphers.

**Comment by tokle** [comment]
The openssl change should not interfere with the serving endpoints. However we believe that #10357 have changed the set of allowed ciphers. The current allowed ciphers can be seen here: https://github.com/vespa-engine/vespa/blob/master/security-utils/src/main/java/com/yahoo/security/tls/TlsContext.java#L16-L25. 

Which of the above ciphers does your client support? We can consider adding some of them to the list of allowed ciphers if they are not in violation of our policy.

**Comment by rameshpoti** [comment]
Thank you for your prompt response. Windows 2012 R2 currently does not support any of the ciphers in ALLOWED_CIPHER_SUITES set. It will be great if at least one of the following cipher suites can be added to the allowed cipher suites set.

TLS 1.1
--
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
 
TLS 1.2
--
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

**Comment by truedigia** [comment]
Ping

**Comment by frodelu** [comment]
You need to stay Vespa 7.83.27-1 until we have added support for cipher configuration in #10798 or you have upgraded your Windows installation with a more recent security upgrade.
