### ISSUE TITLE
[question] Exception thrown using vespa-http-client-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by DavideBonavitaJustis** [vespa-engine/vespa#10792]
Hello there,
I'm trying to feed a json file using the http client in subject, but it throws an error. Most surely the json file or the search definition is misconfigured (some fields are still missing in the search definition), but the exception does not give any useful hint about the issue:

> Unexpected character ('' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: com.yahoo.vespa.http.client.core.JsonReader$InputStreamJsonElementBuffer@71d44a3; line: 1, column: 2]
Exception in thread "main" java.io.UncheckedIOException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: com.yahoo.vespa.http.client.core.JsonReader$InputStreamJsonElementBuffer@71d44a3; line: 1, column: 2]
        at com.yahoo.vespa.http.client.core.JsonReader.read(JsonReader.java:67)
        at com.yahoo.vespa.http.client.runner.Runner.send(Runner.java:39)
        at com.yahoo.vespa.http.client.runner.Runner.main(Runner.java:82)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: com.yahoo.vespa.http.client.core.JsonReader$InputStreamJsonElementBuffer@71d44a3; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
        at com.yahoo.vespa.http.client.core.JsonReader.parseOneDocument(JsonReader.java:207)
        at com.yahoo.vespa.http.client.core.JsonReader.read(JsonReader.java:45)

here is the json file:

> {
  "put": "id:judgment:judgment::r06p4uvg010fqgs",
  "fields": {
    "database": [
      "r06owa2lmaj1pdu:wu298k6v"
    ],
    "writingForTheCourt": [
      null
    ],
    "country": [
      "r06onzveuyeqg:wu298k6v"
    ],
    "partiesInTheCase": [
      null
    ],
    "cites": [
      "r06p4wnv762mvud:wu298k6v",
      "r06p4vri552r48t:wu298k6v",
      "r06p8fjhc2rat0g:wu298k6v",
      "r06p4vspreroykr:wu298k6v",
      "r06p4vj5o1stdh2:wu298k6v",
      "r06p4vcivbcqpgb:wu298k6v",
      "r06p4vnpz9kibiu:wu298k6v",
      "r06p4vorqbivlas:wu298k6v",
      "r06p4vr7pf5erxv:wu298k6v",
      "r06p4vua9ant3ud:wu298k6v",
      "r06p4wdlp2ab1cv:wu298k6v",
      "r06p4wibhga828r:wu298k6v",
      "r06p4wp5wuu170:wu298k6v",
      "r06p4wzh4gj4gjn:wu298k6v",
      "r06p4xht3o9hhn:wu298k6v",
      "r06p4va6v5ayo31:wu298k6v",
      "r06p4ytzfeudto0:wu298k6v",
      "r06p4xly8anwafn:wu298k6v",
      "r06p529h833iimf:wu298k6v",
      "r06p51prmd3gfoc:wu298k6v",
      "r06p532qneouziy:wu298k6v"
    ],
    "issuer": [
      "UaHR0cDovL3ZsZXguY29tL2Rlc2MxLzE0MDAwXzA1"
    ],
    "date": [
      "2018-02-26"
    ],
    "recordOwner": [
      "TEST"
    ],
    "content": [
        "test"
    ],
    "docketNumber": [
      "16108-14L"
    ],
    "URI": [
      "http://test"
    ],
    "title": [
      "Test"
    ],
    "p$classId": [
      "a6"
    ]
  }
}

> 

This is the search definition:

> search judgment {

    document judgment {

        field citedAs type array<string> {
                indexing: summary | index
        }

        field title type array<string> {
                indexing: summary | index
        }

        field content type array<string> {
                indexing: summary | index
        }

        field date type array<string> {
                indexing: summary | index
        }

        field classId type array<string> {
                indexing: summary | index
        }

        field subjectMatter type array<string> {
                indexing: summary | index
        }

        field cites type array<string> {
                indexing: summary | index
        }

        field database type array<string> {
                indexing: summary | index
        }

        field issuer type array<string> {
                indexing: summary | index
        }

        field headnotes type array<string> {
                indexing: summary | index
        }

        field judge type array<string> {
                indexing: summary | index
        }

        field jurisdiction type array<string> {
                indexing: summary | index
        }

        field recordId type array<string> {
            indexing: summary | index
        }

        field writingForTheCourt type array<string> {
            indexing: summary | index
        }
 }
    fieldset default {
        fields: title, content
    }

    rank-profile post inherits default {

        first-phase {
            expression:nativeRank(title, content)
        }

    }

}

**Comment by bratseth** [comment]
This error message is from JSON parsing, so not Vespa specific or dependent on your config.
FEFF is the zero-width non-breaking space character. I guess you have some of those in your JSON input (outside of strings), but they are filtered out from the JSON you posted here (probably by GitHub), so that one works fine.

You need to find and remove these characters, or if they are in your raw data write something to filter them out.
