### ISSUE TITLE
Configuration cluster not healthy after upgrading vespa

### ISSUE THREAD

**Issue by jwachmann-vs** [vespa-engine/vespa#10928]
Hello,

Ran into an issue when testing an upgrade from vespaengine/vespa:7.11.13 to vespaengine/vespa:7.113.28. We followed the upgrade procedure (https://docs.vespa.ai/documentation/operations/live-upgrade.html) and after step 2 our config cluster appears to be in an unhealthy state.

Running "vespa-get-cluster-state" gives the following error:
```
Failed to fetch cluster state of content cluster 'forum':
500 Can't connect to vespa-configserver-2.vespa-configserver.testenv.svc.cluster.local:19050 (Connection refused)
Content-Type: text/plain
Client-Date: Mon, 07 Oct 2019 18:35:11 GMT
Client-Warning: Internal response

Can't connect to vespa-configserver-2.vespa-configserver.testenv.svc.cluster.local:19050 (Connection refused)

LWP::Protocol::http::Socket: connect: Connection refused at
/usr/share/perl5/LWP/Protocol/http.pm line 51.
```
For context in our testing environment we're running vespa with a 3 node configuration cluster and a 3 node container cluster. There's nothing particularly exciting about our services.xml setup but I can supply it if needed.

Manually running `/opt/vespa/bin/vespa-start-services` on each node in the configuration cluster appears to have resolved the issue. That makes me suspect it might be related to this change to the dockerfile: https://github.com/vespa-engine/docker-image/pull/11/files.

For now we can patch our deployment to run the above after each node starts up but what I'm wondering is if it's an actual issue in the vespa dockerfile or if we're just doing something wrong.

**Comment by hmusum** [comment]
Configuration servers are meant to run on their own nodes, the same goes for content nodes (it looks like you are using 3 nodes that run both configuration server and services (content cluster)). It's beneficial both for operability and performance reasons to run configuration servers and content services on their own nodes. 

The change in https://github.com/vespa-engine/docker-image/pull/11 was done to avoid starting services on configuration servers, as that should not be done in production setups.

Look at https://docs.vespa.ai/documentation/vespa-quick-start-multinode-aws.html#configure-and-deploy if you want an example of how to map the different cluster types to nodes (ignore the AWS-specific stuff there).

**Comment by jwachmann-vs** [comment]
Our config cluster nodes are set up to run on different hosts than our container and content cluster nodes. The hosts themselves are kubernetes pods running in a kubernetes cluster so while they may run on the same physical machines they should be isolated as though they were each on their own box.

For reference here's our services.xml:
<services version="1.0">
  <admin version="2.0">
    <adminserver hostalias="config0"/>
    <configservers>
      <configserver hostalias="config0"/>
      <configserver hostalias="config1"/>
      <configserver hostalias="config2"/>
    </configservers>
    <cluster-controllers>
      <cluster-controller hostalias="config0"/>
      <cluster-controller hostalias="config1"/>
      <cluster-controller hostalias="config2"/>
    </cluster-controllers>
  </admin>

  <container id="container" version="1.0">
    <document-api />
    <search />
    <nodes>
      <node hostalias="content0" />
      <node hostalias="content1" />
      <node hostalias="content2" />
    </nodes>
  </container>

  <content id="forum" version="1.0">
    <redundancy>2</redundancy>
    <documents>
        <document type="post" mode="index" />
        <document type="thread" mode="index" />
    </documents>
    <nodes>
      <node hostalias="content0" distribution-key="0" />
      <node hostalias="content1" distribution-key="1" />
      <node hostalias="content2" distribution-key="2" />
    </nodes>
  </content>

</services>

And here's our hosts.xml:
<hosts>
  <host name="vespa-configserver-0.vespa-configserver.testenv.svc.cluster.local">
    <alias>config0</alias>
  </host>
  <host name="vespa-configserver-1.vespa-configserver.testenv.svc.cluster.local">
    <alias>config1</alias>
  </host>
  <host name="vespa-configserver-2.vespa-configserver.testenv.svc.cluster.local">
    <alias>config2</alias>
  </host>


  <host name="vespa-services-0.vespa-service.testenv.svc.cluster.local">
    <alias>content0</alias>
  </host>
  <host name="vespa-services-1.vespa-service.testenv.svc.cluster.local">
    <alias>content1</alias>
  </host>
  <host name="vespa-services-2.vespa-service.testenv.svc.cluster.local">
    <alias>content2</alias>
  </host>
</hosts>

**Comment by hmusum** [comment]
You will lose whatever state (nodes being down, in maintenance etc.) the clustercontrollers have when you do the move and it might take a little time before the new clustercontrollers have done leader election and agreed on a stable system state after the change is done. I would recommend making sure everything is up and working as expected and stop feeding if possible before doing the switch (which is as simple and updating hosts.xml & services.xml and deploying, as you say). You want to do ```/opt/vespa/bin/vespa-stop-services```  on the config server nodes after doing the change to make suring nothing is left behind running there that shouldn't, the cluster controllers should be started automatically on the nodes you are moving them to (if ```/opt/vespa/bin/vespa-start-services``` has been run)

**Comment by bratseth** [comment]
Yes, you might have a period when writes fail, although not if the cluster is otherwise stale at the time. You could avoid this by first adding new controllers and then remove the old ones in a later commit.

**Comment by jwachmann-vs** [comment]
Got it. Thanks for your help!
