### ISSUE TITLE
How to find whether a field is exist in a doc or not in yql?

### ISSUE THREAD

**Issue by alansplaza** [vespa-engine/vespa#10973]
for example 51 docs have field 'a', 49 did not have. 

How to find that how many docs have 'a' field?
 ``` select * from index where a matches '.*';``` did not work...

**Comment by jobergum** [comment]
Hello!

First, using 'matches'/regular expressions is only supported for fields defined with indexing:attribute, second there is no isEmpty/isNan query operator so searching for documents which does not have a value is not supported currently.

**Comment by alansplaza** [comment]
> Hello!
> 
> First, using 'matches'/regular expressions is only supported for fields defined with indexing:attribute, second there is no isEmpty/isNan query operator so searching for documents which does not have a value is not supported currently.

Thank you.
