### ISSUE TITLE
All search nodes are down when we enable bm25 option.

### ISSUE THREAD

**Issue by takamabe** [vespa-engine/vespa#11001]
We found an error that all search nodes were down when we enable bm25 option.

Settings：
We enable bm25 option to 24 fields.
```
index: enable-bm25
```

Environment :
```
Vespa version：7.87.44-1
The number of fields where bm25 option are enabled：24
documents：over 14,000,000
```

Error：
```
"sc0.num3 failed: Received error from backend in sc0.num3: All searchnodes are down. This might indicate that no index is available yet. (3)"
```

Log：
```
vespa-proton-bi[20748]: segfault at 7f54d9088798 ip 00007f52c1840414 sp 00007f52b53c86b0 error 4 in libsearchlib.so[7f52c10f6000+c2b000]
```

**Comment by geirst** [comment]
We fixed a bug related to the index structures used for bm25 in 7.104.23 (https://github.com/vespa-engine/vespa/pull/10542). Please upgrade to a new Vespa version to see if that fixes the problem.

**Comment by geirst** [comment]
It would also be helpful if you could paste the stack trace from the core dump:
`gdb /opt/vespa/sbin/vespa-proton-bin [core-file]`

**Comment by takamabe** [comment]
Thank you for your help.
We upgraded vespa and resolved this problem.
