### ISSUE TITLE
topleveldispatch application generation doesn't change on session activation

### ISSUE THREAD

**Issue by lukealexmiller** [vespa-engine/vespa#11192]
Following deployment of a new application package to Vespa, running 'vespa-config-status' shows topleveldispatch service to be running older versions of the application. I'm not familiar with what this service handles, but this doesn't seem like desired behaviour so thought I'd flag.
```
catalogue/search/cluster.catalogue/tlds/container.0.tld.0:fdispatch has generation 2 not 3
catalogue/search/cluster.catalogue/tlds/container.0.tld.0:fdispatch.nodemanager has generation 2 not 3
[generation not up-to-date ignored]
catalogue/search/cluster.catalogue/tlds/container.1.tld.1:fdispatch has generation 2 not 3
catalogue/search/cluster.catalogue/tlds/container.1.tld.1:fdispatch.nodemanager has generation 2 not 3
[generation not up-to-date ignored]```

**Comment by jobergum** [comment]
It's expected as the topleveldispatch service does not support live re-configuring except from when there are port changes. If you restart the toplevelservice the vespa-config-status will be at the same generation.  The topleveldispathc process was removed from Vespa around Vespa 7.110.
