### ISSUE TITLE
Return term/phrases & positions when searching

### ISSUE THREAD

**Issue by ddorian** [vespa-engine/vespa#11255]
This is needed so `bold` can be computed outside vespa. Combining this with storing `id` as an `attribute` will make `search+bold` without touching documents from disk in vespa.

**Comment by jobergum** [comment]
I think this is a bad idea for several reasons
- Keeping multiple stores in synch (Vespa and external Snippet Service) 
- There is not a 1 to 1 mapping between the matched positions and the source text without adding a character offset to the position structure 
- Certain query operators might not need position information so the position is unknown (e.g filter terms or terms which are too frequent) 
- Snippeting or dynamic summaries/bolding is not only about term matching (The document might be retrieved based on semantic search)

**Comment by bratseth** [comment]
Regarding  2: Or, without that the external store would need to have infomation about text token boundaries stemming from the same text tokenizer with the same settings. I think that's how this would have to work in any case to be able to make meaningful decisions about which snippets to generate. 

It's not impossible but you would have to have massive gains somewhere to justify the increase in complexity etc. It's hard to imagine that's a common situation.

**Comment by ddorian** [comment]
>     * Keeping multiple stores in synch (Vespa and external Snippet Service)
Correct. Can be achieved with a versioning field. So `id=x; version=y`.
> 
>     * There is not a 1 to 1 mapping between the matched positions and the source text without adding a character offset to the position structure
Then how is this done internally ? Is extra data stored on `bold` ?
> 
>     * Certain query operators might not need position information so the position is unknown (e.g filter terms or terms which are too frequent)
Then it won't return position. But a special `too_frequent` field.
> 
>     * Snippeting or dynamic summaries/bolding is not only about term matching (The document might be retrieved based on semantic search)
There can be a `what mached` field. Or several fields for each `type of matching`.
This is also needed for analytics for example. Or a score for each rank criteria that contributed to the sort (separate issue though).

> It's not impossible but you would have to have massive gains somewhere to justify the increase in complexity etc. It's hard to imagine that's a common situation.

1. Separating summary/snippet & inverted-indexes will allow for separate scaling of them. 
2. Snippet won't use CPU, summary won't use RAM.
3. Will allow to use fewer machines for search (example: high fixed query cost).
4. And allow for another `more efficient` kv-store to cache documents & compute snippets. (redis, scylladb)

I probably should really learn how bolding is done to see if my request makes sense.
