### ISSUE TITLE
Authentication & Authorization logic for application container

### ISSUE THREAD

**Issue by Muthu-cms** [vespa-engine/vespa#11409]
Hi,

I'm new to the Vespa community. I have been trying to set-up vespa as a comparison to Solr in my org. I'm trying to set-up security framework to protect the data / container. I saw one of the ways to implement authentication & authorization is using filters. Do we have any sample applications or container service files that has implemented authentication & authorization logic for vespa containers. Can someone provide guidance in this regard, Any support would be greatly helpful.

Thanks,
Muthu

**Comment by johans1** [comment]
Any update?

**Comment by baldersheim** [comment]
Timed out for **soon**

**Comment by tokle** [comment]
Example available in https://blog.vespa.ai/securing-vespa-with-mutually-authenticated-tls/
