### ISSUE TITLE
Monitoring vespa process appropriately to avoid the lost of document updating

### ISSUE THREAD

**Issue by shayakaw** [vespa-engine/vespa#11420]
Hi. 
Would you please let me ask a couple of questions regarding vespa monitoring?

# Current status.
- We use vespa with several servers.
- The Version is vespa-7.105.45-1. 
    - https://github.com/vespa-engine/vespa/tree/vespa-7.105.45-1
- We have several vespa clusters for redundancy
- Each cluster has 30 vespa servers
- When we do product release, we deploy each cluster one by one

# Trouble.

A few days ago, we deployed vespa clusters.
After that, we realized the number of documents in a cluster was different from the other clusters as below.

- Vespa cluster 1 documents: 1000
- Vespa cluster 2 documents: 1000
- Vespa cluster 3 documents: 1001    <-  vespa cluster 3 has surplus document!
- Vespa cluster 4 documents: 1000 

In addition, we found that this surplus document was the one removed a few weeks ago.
Which means possibility that update process did not have worked well at some vespa server in that cluster.

Our assumption is that one ( or more ) server had been detached from vespa cluster before deployment.

If one ( or more ) server had detached from vespa cluster with some reason, and it had not been updated appropriately for a few weeks,
then returned to cluster at deployment, it explains why document remains in one cluster.

When server detach from cluster or has any trouble in update process, we need some kind of alert at that time.
But no abnormal alert occurred in this case.

Although we monitor vespa-runserver process, this is probably not enough.

We monitor vespa-runserver by Prometheus Process-exporter as follows.

```
process-exporter --config.path=/etc/process_exporter/all.yaml --children=false

$ cat /etc/process_exporter/all.yaml
process_names:
- comm:
  - vespa-runserver
```

ref. https://github.com/ncabatoff/process-exporter

#  Scenario we assumed

We are assuming a scenario as follows.

- 1. One (or more) vespa server had detached from the whole vespa cluster accidentally before deployment.
- 2. We did not know that event, and did not even notice the failure of deleting document. ( process monitoring is not enough?)
- 3. All vespa clusters was deployed to production release. Probably, at this time, the detached vespa server was re-attached to vespa cluster.
- 4. We found the number of documents in one cluster was different from the other clusters.

# Question

Is there any possibility of server detaching from vespa cluster with no alert, although we monitor vespa-runserver process?

If it may happen, could you let us know what kind of monitoring we should do besides vespa-runsuerver?

**Comment by kkraune** [comment]
I think your analysis of what happened is correct. See https://docs.vespa.ai/documentation/elastic-vespa.html#data-retention-vs-size - after two weeks, knowledge that a document is deleted, is lost.

in https://cloud.vespa.ai/ nodes are wiped before adding back to avoid this problem. https://cloud.vespa.ai/  also automates failed node detection and handling. In your case, you will have to build something similar. Get started with https://docs.vespa.ai/documentation/content/content-nodes.html to understand processes, in particular the _cluster controller_ (its status page is quite useful). https://docs.vespa.ai/documentation/slobrok.html is also relevant. The _cluster state_ tracks changes to the cluster, when nodes go in and out

I am sorry I do not have a simple answer. It is complicated to build a service that handles this well, without creating other problems. Nodes can go in and out as servers boot for whatever reason.

We can discuss options in this ticket after you have reviewed the documentation / looked at the cluster state

**Comment by ludwig125** [comment]
Thank you for your answer to my question quickly.

Based on your comment, we read some vespa documents as follows.

vespa-get-cluster-state CLI
  - https://docs.vespa.ai/documentation/reference/vespa-cmdline-tools.html#vespa-get-cluster-state

State API 
- https://docs.vespa.ai/documentation/content/api-state-rest-api.html

However, if we could fetch these cluster-state information from prometheus metrics, it would be best.

Prometheus metrics like this
- http://`vespa`:19092/prometheus/v1/values


Do you have any plans to add such information to prometheus metrics?

**Comment by kkraune** [comment]
I am sorry, no not really, as we export a limited set to prometheus afaik

as this is open source, it is possible to build extensions, CC @gjoranv

**Comment by ludwig125** [comment]
I understand.
We would greatly appreciate if you kindly build some extensions.

For the time being, we might use CLI or API to get cluster-state-information.

Thank you.

**Comment by kkraune** [comment]
Yes, I understand your issues. The problem of handling nodes going in and out of applications is difficult (failed node detection, node/data retention, if/how/when to put back in), managing nodes overall is a really big problem, so it is hard to solve. Vespa Team has spent many man-years integrating features and procedures into https://cloud.vespa.ai/ so other teams do not need to do it themselves.

I will close this issue, as the metrics export is not planned to change shortly (but this is open source, so feel free to contribute!)
