### ISSUE TITLE
Add ranking features for matching in map and array of struct 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#11580]
Currently it's not possible to get any rank features from matching over map/array structures.  Consider the following example

```
struct person {
    field first_name type string {}
    field last_name type string {}
    field popularity type int {}
}
field identities type map<string, person> {
    indexing: summary
    struct-field key { indexing: attribute }
    struct-field value.last_name { indexing: attribute }
    struct-field value.popularity { indexing: attribute}
}
```

I think we should support the following rank features which is per document

*matches(name)*
```
matches(identities.key)
matches(identities.value.last_name) 
```

For matching/read attribute value features I think we should hook into the foreach feature so that the aggregator can be chosen by the user in case there are multiple matches (e.g when using prefix search over attribute) by introducing new dimensions, today we have 'terms', 'fields', 'attributes'. We could maybe support a map/array field as a dimension which allows iterating over the values. 

```
foreach(identities.key,key,attributeMatch(identities.key,key),">0",max)
foreach(identities.value.popularity,p,attribute(identities,p),">0",max)
```

**Comment by geirst** [comment]
Using the _matches()_ feature with the underlying attribute fields of map / array struct fields is already supported as long as those fields are searched directly. Testing of this is added in https://github.com/vespa-engine/system-test/pull/2659. 

However, if the _sameElement_ query operator is used, the _matches()_ features does not currently work. When that is fixed, the following should be possible:
```
Ranking:
matches(identities)

Query:
select * from sources * where identities contains sameElement(key contains 'foo', value.last_name contains 'John')
```
