### ISSUE TITLE
model-evaluation is broken

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#11658]
Testing the https://github.com/vespa-engine/sample-apps/tree/master/model-evaluation README

$ date; docker images
Mon Jan  6 14:09:18 CET 2020
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vespaengine/vespa   latest              1ce6fd78a0c6        2 weeks ago         1.12GB

```
$ curl -s 'http://localhost:8080/model-evaluation/v1/mnist_softmax/eval?Placeholder=%7B%7Bd1%3A0%7D%3A0.1%7D' | python -m json.tool
{
    "error": "Missing a value for dimension d0 for tensor<float>(d0[],d1[784])"
}
````

this looks odd: _d0[]_ - ther eshould be a dimension here?

http://localhost:8080/model-evaluation/v1/mnist_softmax gives
```
{
    "functions": [
        {
            "arguments": [
                {
                    "name": "Placeholder",
                    "type": "tensor<float>(d0[],d1[784])"
                }
            ],
            "eval": "http://localhost:8080/model-evaluation/v1/mnist_softmax/default.add/eval",
            "function": "default.add",
            "info": "http://localhost:8080/model-evaluation/v1/mnist_softmax/default.add"
        }
    ],
    "model": "mnist_softmax"
}
```

**Comment by lesters** [comment]
Fix in https://github.com/vespa-engine/sample-apps/pull/193
