### ISSUE TITLE
YQL matches syntax seems not working

### ISSUE THREAD

**Issue by takumahuwa** [vespa-engine/vespa#11752]
Hi,

I'm a newbie to vespa.

After I setup my environment to "9. Run a document GET request" step of the following page:
https://docs.vespa.ai/documentation/vespa-quick-start.html

I could get a result with `select * from sources * where album contains "Head";`

However, I'm not able to get any result with `select * from sources * where album matches "Head";`

Did I make the wrong query or the "matches" syntax is just not working?

**Comment by jobergum** [comment]
Hello! Using 'matches' triggers regular expression search which is only supported for fields with attribute. Use 'contains' and see if that helps?

**Comment by jobergum** [comment]
See https://docs.vespa.ai/documentation/reference/query-language-reference.html#matches

**Comment by takumahuwa** [comment]
Thank you for your kindly reply.

'contains' does help. However, 'matches' is not working as expected.

In case you need more information, mode="index" should have been configured as you can find from the following sample.
https://github.com/vespa-engine/sample-apps/blob/master/album-recommendation-selfhosted/src/main/application/services.xml
https://github.com/vespa-engine/sample-apps/blob/master/album-recommendation-selfhosted/src/main/application/searchdefinitions/music.sd

**Comment by takumahuwa** [comment]
I think I found the reason. The album field has only summary and index but no attribute.
https://github.com/vespa-engine/sample-apps/blob/master/album-recommendation-selfhosted/src/main/application/searchdefinitions/music.sd
