### ISSUE TITLE
Port configuration in Vespa Cloud makes services unavailable

### ISSUE THREAD

**Issue by oyving** [vespa-engine/vespa#11776]
Configuration ports with `services.xml` in Vespa Cloud will make the service unavailable, as Vespa Cloud assumed default port configuration. To avoid customer confusion we should make sure that custom port configuration results in an error message on deployment.

Sample `services.xml` stanza :
```xml
<container id="foo">
  <http>
    <server id="http" port="8080" />
  </http>
</container>
```

**Comment by bratseth** [comment]
Change from warning to failing on this: https://github.com/vespa-engine/vespa/pull/11792
