### ISSUE TITLE
Remove scoreThreshold from weakAnd

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#12179]
weakAnd:scoreThreshold is currently expecting an integer and not a float but as weakAnd does not expose the rawScore of the internal calculation it's kind of hard to come up with a scoreThreshold when one does not know the range. I suggest we remove scoreThreshold for weakAnd or properly expose the rawScore calculated by the weakAnd

**Comment by bratseth** [comment]
scoreThreshold marked for removal on Vespa 8.

**Comment by andrewalkermo** [comment]
@bratseth It was removed from WeakAnd? Why is it still present in the documentation?
https://docs.vespa.ai/en/reference/query-language-reference.html#scorethreshold

**Comment by bratseth** [comment]
Thanks for pointing this out. Yes it was removed from WeakAnd (not from Wand) - I'll fix the documentation.
