### ISSUE TITLE
[bundle-plugin] Bazel support

### ISSUE THREAD

**Issue by bsnisar** [vespa-engine/vespa#12301]
Hello vespa devs.

### Description
I am from Wix.com and we hevely use Vespa  in out systems. 
And also utilized bazel as a main build tool (except some parts =/)

### Question
We considering idea to fork your plugins and rewrite them to support bazel and open source them (possible under this repo?). Under **rewrite** I mean:
> extract some part of plugin(s) as a core (that do all work) from maven part and possible add some kind of CLI interface to it.

Pleas provide you feedbak regarding this question, thanks.

**Comment by bratseth** [comment]
Hi, this sounds good to me. We should really keep the core + maven wrappers in this repo - if you submit the PR's we'll work to have them merged. 

Whether the new bazel wrappers should also be should be up to you, I don't know much about Bazel but i don't see an issue with it.

@gjoranv may have opinions on the structure of a core+wrapper split.

**Comment by gjoranv** [comment]
Sounds great. Closing this, hoping you will get back to us with a pull request.
