### ISSUE TITLE
Duplicates when grouping over array and using pagination

### ISSUE THREAD

**Issue by griseau** [vespa-engine/vespa#12537]
As mentionned https://github.com/vespa-engine/vespa/issues/12497, I'm facing duplication when grouping over an array and using pagination.

I'm using Vespa 7.177.11 with 2 container nodes and 2 content nodes. 
The query I'm using is `[{ 'continuations':['actual_page',next_page''] }] all(group(set_of_words) max(1000) order(-count()) each(output(count())));`
And my field set_of_words is defined like this : 
```
set_of_words type array<string> {
            indexing: summary | attribute
        }
```
Some of the records are duplicated or triplicated.

I only face this issue when grouping over an array, it works normally when grouping over string field.

Let me know if you need more informations
Thanks !

**Comment by bratseth** [comment]
Each document will be placed in all the groups they belong to given their array values. Does that explain what you see?

**Comment by jobergum** [comment]
Also grouping does not do any transformations/normalizations of the attribute (field) value, like lowercasing so 'Foo' and 'foo' would be treated as two distinct unique values.

**Comment by griseau** [comment]
@bratseth not sure to understand but I don't think so.
@jobergum the records are exactly the same. 

For example if I run : `[{ 'continuations':['',''] }] all(group(set_of_words) max(2) order(-count()) each(output(count())));`

First page could be : 
value : hello, count : 10
value : hi, count : 5

Second page 
value : my, count : 4
value : flour, count : 3

Third page 
value : my, count : 4
value : flower, count : 2

In this case, the value my is duplicated with the exact same record

**Comment by jobergum** [comment]
I'm not able to reproduce this straight off the bat. 

```
curl "http://localhost:8081/search/?query=sddocname:face&select=all(group(hashtags)%20max(2)%20order(-count())%20each(output(count())))&hits=0&continue=" -s |python -m json.tool|egrep "count|group:string|next|this"
                                    "count()": 17
                                "id": "group:string:one",
                                    "count()": 17
                                "id": "group:string:three",
                            "next": "BGAAABEBEBC"
                    "this": ""
curl "http://localhost:8081/search/?query=sddocname:face&select=all(group(hashtags)%20max(2)%20order(-count())%20each(output(count())))&hits=0&continue=BGAAABEBEBC" -s |python -m json.tool|egrep "count|group:string|next|this"
                                    "count()": 17
                                "id": "group:string:two",
                                    "count()": 6
                                "id": "group:string:four",
                            "next": "BGAAABEBIBC",
                    "this": "BGAAABEBEA"
curl "http://localhost:8081/search/?query=sddocname:face&select=all(group(hashtags)%20max(2)%20order(-count())%20each(output(count())))&hits=0&continue=BGAAABEBEA+BGAAABEBIBC" -s |python -m json.tool|egrep "count|group:string|next|this"
                                    "count()": 4
                                "id": "group:string:five",
                                    "count()": 2
                                "id": "group:string:six",
                    "this": "BGAAABEBIA"
```

We also have a system test for pagination with both legacy continue http parameter and YQL syntax here https://github.com/vespa-engine/system-test/tree/master/tests/search/grouping_pagination

**Comment by griseau** [comment]
Unfortunately I won't have enough time this week, but I'll try next week and give you steps to reproduce

**Comment by jobergum** [comment]
One thing to note about grouping and pagination is that the result is never cached and is executed over again for every request so in cases where the underlaying data changes the ordering could also change.

**Comment by griseau** [comment]
Hi @jobergum, 

I've been pretty busy in the past weeks, I'm still having this issue but it's not blocking at the moment, so I'll get back asap. 

Thanks

**Comment by kkraune** [comment]
please reopen as needed
