### ISSUE TITLE
vespa-openssl-1.1.1g

### ISSUE THREAD

**Issue by mnagaya** [vespa-engine/vespa#13004]
Hello,

Could you rebuild vespa with OpenSSL-1.1.1g?

Our paranoids do not recommend using old version of OpenSSL, even when it is not affected by the vulnerability.

Here is the vulnerability details:
https://www.openssl.org/news/secadv/20200421.txt

Thanks

**Comment by aressem** [comment]
The vespa-openssl-1.1.1g package is now available.

- New installs using `yum install vespa` will automatically pick up the new version.
- Existing installations can be patched by `yum update vespa-openssl`
- All Vespa versions >= 7.210.x will require vespa-openssl >= 1.1.1g

**Comment by vekterli** [comment]
As an aside, it is not believed that Vespa is directly affected by this vulnerability.

- Java processes (containers, config servers etc) all use the TLS implementation provided by the JVM, not OpenSSL
- If cluster-internal TLS is enabled (not yet documented but coming Real Soon™) our OpenSSL integration code does not invoke the `SSL_check_chain()` API function. Going by the [commit message for the fix itself](https://github.com/openssl/openssl/commit/a87f3fe01a5a894aa27ccd6a239155fd129988e4), the vulnerable code segment is not implicitly called by any other parts of the library.

**Comment by mnagaya** [comment]
> The vespa-openssl-1.1.1g package is now available.

vespa-openssl-1.1.1g looks ok to me. 

> it is not believed that Vespa is directly affected by this vulnerability.

I think so too. 

Thank you for you support.
