### ISSUE TITLE
Vespa bm25 rank feature ignores phrase terms

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#13077]
https://api.cord19.vespa.ai/search/?query=covid-19+%22respiratory%20tract%20symptoms%22&type=any&ranking=bm25t5&recall=%2Bcord_uid:tmi1u224&summary=short

query=covid-19 
![image](https://user-images.githubusercontent.com/20928528/80356297-8dd22000-8879-11ea-968e-4284cbcd9e7c.png)

```
bm25(abstract): 7.761145715477682,
```

versus 
query=covid-19 "respiratory tract symptoms"
https://api.cord19.vespa.ai/search/?query=covid-19&type=any&ranking=bm25t5&recall=%2Bcord_uid:tmi1u224&summary=short

![image](https://user-images.githubusercontent.com/20928528/80356356-a3474a00-8879-11ea-94a5-a819ae0f3ed4.png)

```
bm25(abstract): 7.761145715477682,
```
versus 
query=covid-19 respiratory tract symptoms

https://api.cord19.vespa.ai/search/?query=covid-19+respiratory%20tract%20symptoms&type=any&ranking=bm25t5&recall=%2Bcord_uid:tmi1u224&summary=short

![image](https://user-images.githubusercontent.com/20928528/80356550-e43f5e80-8879-11ea-846c-951e7cc06250.png)

```
bm25(abstract): 25.102029935060447
```

**Comment by geirst** [comment]
Fixed in version >= 7.215.6.
