### ISSUE TITLE
Chinese fields cannot be tokenized correctly

### ISSUE THREAD

**Issue by sunmu01** [vespa-engine/vespa#13364]
The .sd file was written as below:
schema wxsearch {
    document wxsearch {
        field language type string {
            indexing: set_language
        }
......
        field msg_content type string {
            indexing: summary | index
        }

The feed-data.json was written in UTF-8 encoding:
{"put": "id:wxsearch:wxsearch::1", "fields": {"language": "zh-hans", ..., "msg_content": "是不是刚需？要试一试，以MVP的方式来try", ... }}
{"put": "id:wxsearch:wxsearch::2", "fields": {"language": "zh-hans", ..., "msg_content": "重构比特币是一本好书，亚马逊有售", ... }}

After successfully feeding these two documents, I execute the following command:

docker exec vespa bash -c '/opt/vespa/bin/vespa-proton-cmd --local triggerFlush &&     /opt/vespa/bin/vespa-index-inspect dumpwords   --indexdir /opt/vespa/var/db/vespa/search/cluster.wxsearch/n0/documents/wxsearch/0.ready/index/index.flush.1  --field msg_content' 

I got this:
OK: flush trigger enabled
亚马逊有售	1
以mvp的方式来try	1
是不是刚需	1
要试一试	1
重构比特币是一本好书	1

As you can see, the Chinese sentence of msg_content fields cannot be tokenized correctly.
Did I miss any linguistics settings or the format of feed-data is incorrect?

Thank you in advance for your help!

**Comment by kkraune** [comment]
Thanks for the detailed report, I am able to reproduce your findings

Vespa integrates with Apache OpenNLP for linguistics: https://docs.vespa.ai/documentation/linguistics.html

With OpenNLP, you must provide a model for the tokenization. http://opennlp.apache.org/models.html has some pointers, but it does not look like zh-hans is there, so it seems you must train it yourself or find a model somewhere else

Based on your findings, feel free to contribute back to Vespa improvements to documentation, examples and code - I think you are not the only one with this problem

**Comment by bratseth** [comment]
Just to mention one more option: An alternative to using a cjk-capable tokenizer is to use n-grams, see https://docs.vespa.ai/documentation/reference/schema-reference.html#match

**Comment by sunmu01** [comment]
> Thanks for the detailed report, I am able to reproduce your findings
> 
> Vespa integrates with Apache OpenNLP for linguistics: https://docs.vespa.ai/documentation/linguistics.html
> 
> With OpenNLP, you must provide a model for the tokenization. http://opennlp.apache.org/models.html has some pointers, but it does not look like zh-hans is there, so it seems you must train it yourself or find a model somewhere else
> 
> Based on your findings, feel free to contribute back to Vespa improvements to documentation, examples and code - I think you are not the only one with this problem

In the link https://downloads.apache.org/opennlp/models/langdetect/1.8.3/README.txt,
I found "cmn	Mandarin Chinese" which is another way of saying Simplified Chinese.

Would you tell me how to make this setting enabled in OpenNLP of Vespa Docker? 
I did not find relevant instructions in https://docs.vespa.ai/documentation/linguistics.html .
Thank you very much!

**Comment by sunmu01** [comment]
> Just to mention one more option: An alternative to using a cjk-capable tokenizer is to use n-grams, see https://docs.vespa.ai/documentation/reference/schema-reference.html#match

Thank you for your kind reminder!

**Comment by kkraune** [comment]
> In the link https://downloads.apache.org/opennlp/models/langdetect/1.8.3/README.txt,
I found "cmn Mandarin Chinese" 

that looks like language detection, not tokenization, but I have not checked it much
