### ISSUE TITLE
RangeItem with hitLimit, combined with a second query filter, doesn't work?

### ISSUE THREAD

**Issue by jonmv** [vespa-engine/vespa#13446]
The YQL query 
```
select * from db where [{\"hitLimit\": 1, \"descending\": true}] range(long_version, -Infinity, Infinity) and released_seconds > 0;
```
should return 1 hit from the intersection of documents with positive values for fields `long_version` and `released_seconds`. When run against a corpus which has such a document, it returns 0 hits. Each of the two conditions by themselves (the range search on `long_version` and the condition on `released_seconds` produce a hit for the specified document, but when combined, they do not. Reordering the conditions and/or increasing the `hitLimit` beyond the number of documents does not help. Removing `hitLimit` (and instead using `count`) works, and the desired document is found.

**Comment by jonmv** [comment]
Strange. Can't reproduce using `/search`/ endpoint. Possibly a mis-communication + range search hitLimit being applied before other filters, which is probably OK.

**Comment by jonmv** [comment]
(Issue detected using queries generated from inside the search container.)

**Comment by jonmv** [comment]
Right, so the problem is that the ordering used by `count=...` to pick the first hit isn't the same as what's used in the range search. Closing this as user error, then.

**Comment by jonmv** [comment]
Opening to request this clearly documented :)

**Comment by baldersheim** [comment]
Documentation clarified in https://github.com/vespa-engine/documentation/pull/1004

When you generate queries inside the container, it is far better to create them programatically instead of generating yql.
