### ISSUE TITLE
Add more documentation on feed concurrency setting and controlling multi-threaded indexing

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#13681]
The concurrency parameter controls the tradeoff between search and indexing on the content nodes and the node flavor cpu count is used to derive actual thread settings for various tasks. We should add a separate feature document on this.

**Comment by kkraune** [comment]
Agreed: https://docs.vespa.ai/documentation/performance/sizing-feeding.html mentions this a litte but should be improved - possibly split in a separate document, the sizing-feeding doc is a bit unstructured now.

**Comment by jobergum** [comment]
We need documentation on this. Also hearing reports that attempting to lower the value to something close to 0,  does not help much when one wants to throttle indexing CPU.

**Comment by frodelu** [comment]
Should add more details in https://docs.vespa.ai/en/performance/sizing-feeding.html#feed-vs-search on how this is used, what it means, etc.

**Comment by baldersheim** [comment]
With https://github.com/vespa-engine/documentation/pull/2883 this should be good for now.
