### ISSUE TITLE
Unexpected error parsing or serializing query

### ISSUE THREAD

**Issue by jamesbond7** [vespa-engine/vespa#13932]
I use the following YQL statement:

select * from doc_source 
where ([{"defaultIndex": "doc_fields","grammar": "web","stem": true,"allowEmpty": true}]userInput(@search_terms));

When the search_terms value is **m&m's** then the yqlRepresentation method of the Query class generates the exception:

**Unexpected error parsing or serializing query: com.yahoo.prelude.query.AndSegmentItem incompatible with com.yahoo.prelude.query.TaggableItem**

The root cause is the casting in the VespaSerializer::leafAnnotations method:

**TaggableItem connectedTo = (TaggableItem) item.getConnectedItem();**

when type of the item.getConnectedItem() is AndSegmentItem class.

I  guess that the serialization problem affects not only the yqlRepresentation method.

The problem doesn't exist in Vespa 6 version.

**Comment by bjormel** [comment]
Hi @jamesbond7 

Are you using the latest Vespa version?

Can you share your document schema? 

Can you add '&tracelevel=3' to the request and add the trace here?

Thanks!

**Comment by jamesbond7** [comment]
We use the 7.254.8 version.

[The document schema sample](https://gist.github.com/jamesbond7/edc3cf78c9b75bd4a5c17d5267e29418)

The test query request is the following one:

http://vespa7-dev1-srv-1.da-vespa.wixprod.net:8080/search/?yql=select%20%2A%20from%20test%20where%20%28%5B%7B%22defaultIndex%22%3A%20%22test%22%2C%22grammar%22%3A%20%22web%22%2C%22stem%22%3A%20true%2C%22allowEmpty%22%3A%20true%7D%5DuserInput%28%40inp%29%29%3B&inp=m%26m%27s&presentation.summary=base_summary&hits=10&user=debugging&tracelevel=3

[The trace output](https://gist.github.com/jamesbond7/6b9c0c560c63555b6e7b44b1b4b1fcf6)

**Comment by bjormel** [comment]
Thanks, I am able to reproduce this, thanks for reporting.

Your best option to handle terms with other characters than text characters is to add a specialtokens config, see https://docs.vespa.ai/documentation/query-rewriting.html#special-tokens

> Query tokens are built from text characters, as defined by isTextCharacter in com.yahoo.text.Text. To query for terms with other characters, like c++ or .net, use special tokens. Unlike query rewriting/phrasing, special tokens modifies data at feeding time, changes to configuration must hence be followed by document re-feed.

With this config you will be able to search for 'm&m', without matching documents with the single character 'm':
`<config name="vespa.configdefinition.specialtokens">
    <tokenlist>
      <item>
        <name>default</name>
        <tokens>
          <item>
            <token>m&amp;m</token>
          </item>
        </tokens>
      </item>
    </tokenlist>
  </config>`
=>
`select * from sources * where (default contains \"m&m\" AND default contains \"\\'s\");`

**Comment by bratseth** [comment]
Special tokens must be supported by the tokenizer, and unfortunately the default open source tokenizer component does not support it. We have an issue on that but haven't gotten around to it yet unfortunately.

**Comment by jamesbond7** [comment]
Thanks for the proposed solution. 
Is it possible just to fix the yqlRepresentation method output? To return a regular yql string instead of the exception message?

**Comment by bratseth** [comment]
Fixed in https://github.com/vespa-engine/vespa/pull/14003 (will be released next week).

The difference from Vespa 6 is that we changed the default from phrase segmentation to and segmentation. If you want the earlier behavior, which will also avoid this bug, add 
`query-command: phrase-segmenting
`
to the field(s) in question.
