### ISSUE TITLE
Array of reference support

### ISSUE THREAD

**Issue by agusgun** [vespa-engine/vespa#13945]
I have a case where one content can belong to some group.
Group have an id and a text field which is the name of the group.

Later, I want to fill the content with the name of all of the related group. However, the group name can change quickly. I want to use reference to solve this so I don't need to include the group field in the content and update each related content whenever there is a change in group name.

**Comment by jobergum** [comment]
It's not possible to reference multiple parents with parent child relationships.

**Comment by agusgun** [comment]
@jobergum is there any efficient way or recommendation to get parent parent document which have same schema? for now I solve this issue by using synchronous document API in one of the searcher. But, I don't know if this solution is computationally efficient or not.

**Comment by jobergum** [comment]
Sorry but I don't understand your use case, maybe you could try to explain the use case you have and why a single parent ref is not enough in this case? Examples make it easier to understand your use case as well.

**Comment by agusgun** [comment]
Sorry for not explaining the use case.
This is my use case, so for product search like in some online e-commerce, the product will be in some categories right?
For example:
Lenovo Y51 will be in some hierarchical category like: Electronics > Computer & Laptop > Laptop and Office > Laptop.

Is there any way I can generate a breadcrumb in Vespa? The breadcrumb is the hierarchical category of the product.

For this case, I have 2 schema which is a product and category.

For product schema I have:
- name
- description
- category id: which is the direct category id of the product, for the above example it is the laptop category id. 

For category schema I have:
- id: the id of this category
- text
- parentId: string which contains ids separated by comma
- childId: string which contains ids separated by comma

After this, for each hit I will do:
- get the category id of the product by filling the result first using `execution.fill(query)`
- get the category document of that id by using `synchronous document api`
- get the text of that document
- recursively do all of the 3 steps above by using the parent id until no parentId found or parentId == 0

I don't want to embed the category text into the product because the category text can be changed quickly for this case. Hope you can understand my use case and solution.

**Comment by jobergum** [comment]
Seems like a very complex and costly solution per hit in the result. Since you seem not to use the textual representation of the category and the category tree. I would instead in the Searcher use the document api to visit the category document schema and store it in a simple data structure, possible off heap storage (e.g https://github.com/yahoo/Oak) and resolve the id => category name tree per hit.

**Comment by agusgun** [comment]
I got it, however currently the off heap storage not supported by Vespa. 

I think I have another question, so suppose we get all of the breadcrumb using off heap storage. Can we return the hierarchical facet to be used later like some filter? For example:
Hit 1: Category: Laptop & Computer > Laptop
Hit 2: Category: Laptop & Computer > Computer

So from the grouping reference in docs.vespa.ai. We can do it by using grouping request, however, can we do it instead after we fill the hit with category data? Because if we do some grouping request, we need the field to be in the schema right?

Thank you for the answer

**Comment by jobergum** [comment]
>I got it, so I just need to use another library like Oak then get the category Id and then resolve the category name tree by >using Oak?
You can use the approach you are using today but it would involve quite a few calls over the network from your custom searcher to the content node(s) to resolve the textual representation of your category tree and the category tree representation is probably rather small and probably also fits into heap memory without issues (e.g just a custom data structure). 

The premise of this discussion is that your category id to category name is changing quite often and you don't want to keep the textual representation in the product (Even I don't understand this point fully as in my experience the category tree is rather fixed, at least not changing daily) 


>I think I have another question, so suppose we get all of the breadcrumb using off heap storage. Can we return the >hierarchical facet to be used later like some filter? For example:
>Hit 1: Category: Laptop & Computer > Laptop
>Hit 2: Category: Laptop & Computer > Computer

The product index contains the category id and not the textual representation so grouping would operate on the numerical representation and you need to transform both query filters drilling down into a category by the numerical representation and for display purposes resolve the category information before presenting it to the end user using the chosen strategy. 

Note that you can group on multi-valued fields as well so in the product you can have 

categories: [1,2,39]

**Comment by agusgun** [comment]
I got it Jo, thank you very much for answering the question. I will try to implement the solution

**Comment by jobergum** [comment]
I'm closing this @agusgun, thank you for your interest in Vespa.ai.
