### ISSUE TITLE
Feature request: Support for binary Tensor type (with Hamming distance)

### ISSUE THREAD

**Issue by scsong11** [vespa-engine/vespa#14133]
It'd be really useful if Tensor also supported the binary data type along with Hamming distance for the binary data. There are many use cases where feature vectors are represented in a binary form: ORB/Brief image descriptors, or binary quantization. With the new ANN search feature in Vespa, the support for the new data type will benefit these and other future use cases tremendously, I believe.

**Comment by arnej27959** [comment]
extending the tensor framework with more cell types (in particular "bit" or "bool" which is what you want) is on the backlog but not for Q4, we are going to work on sparse and mixed tensors first but taking care to make the cell type abstract at the same time, to prepare for more cell types.

however I have added a "Hamming" distance metric that you can use with tensor&lt;float&gt; where cells only have values 0 and 1, it should be slightly more efficient than Euclidean and helps you prepare for the future.   I will add it to documentation later (after you have checked that it works for your use case, preferably).

**Comment by scsong11** [comment]
Thanks for the update @arnej27959. We'll test out the Hamming distance on the float type, and look forward to the binary type support.

**Comment by scsong11** [comment]
In my preliminary testing, the Hamming distance implementation worked as expected (Thanks!).  I know you guys are not introducing the binary Tensor type (or any new type) in Q4. But could you consider introducing yet another Hamming distance computation where you count the number of different bits in the existing Tensor type? I.e. something like
```
for (size_t i = 0; i < sz; ++i) {
   sum += count_set_bits(lhs_vector[i] ^ rhs_vector[i]);
}
```
I know that the current Hamming distance is computed by [counting the number of different 4-byte values in the float array](https://github.com/vespa-engine/vespa/pull/14299/files#diff-eb20461cbeaa43bdd07c69911a38a6d1R190-R197), which is absolutely fine, but adding the bit-wise comparison above may not be too hard, and it’ll allow us (and other future Hamming distance users) to save a lot of space before the binary type support is available, as we’d be able to store 32-bit information in a float element, instead of 1-bit information we currently store.

**Comment by jobergum** [comment]
We have started work on new tensor types. 

For my understanding:

- Do you want to store (e.g 32) bits in a tensor and to brute force hamming distance over selected documents (by query) efficiently using bitwise XOR 
- Use the HNSW support with hamming distance and using a tensor<bool>(x[32])

**Comment by jobergum** [comment]
bitwise Hamming distance has been added as a distance-metric https://docs.vespa.ai/en/reference/schema-reference.html#distance-metric and also int8 support
