### ISSUE TITLE
Support for bolding and dynamic summary in array<string> field

### ISSUE THREAD

**Issue by agusgun** [vespa-engine/vespa#14173]
Hi Vespa team,

I realized that whenever I have `array<string>` field and the bolding enabled e.g.
```
        field texts type array<string> {
            indexing: index | summary
            bolding: on
        }
```

The bolding will not works and give this error:
```
Error loading model: 'bolding: on' for non-text field 'texts' (datatype Array<string> (code: -1486737430)) is not allowed
```

Can bolding supported for `array<string>`? Thank you

**Comment by geirst** [comment]
`summary: dynamic` is also currently not supported for `array<string>` fields. This feature request covers support for that as well.

**Comment by geirst** [comment]
Support for this has been added in 8.53.21.
Updated documentation:
https://docs.vespa.ai/en/reference/schema-reference.html#bolding
https://docs.vespa.ai/en/reference/schema-reference.html#summary

New system tests:
https://github.com/vespa-engine/system-test/blob/master/tests/search/bolding/bolding_array.rb
https://github.com/vespa-engine/system-test/blob/master/tests/search/dynteaser/dynteaser_array.rb
