### ISSUE TITLE
How to add new documents in Vespa Indexing Engine?

### ISSUE THREAD

**Issue by SETIADEEPANSHU** [vespa-engine/vespa#14225]
I want to use the Vespa engine for internal document search, how can I provide the documents in formats like pdf,docx, pptx, etc to the engine for indexing and searching?

**Comment by frodelu** [comment]
@SETIADEEPANSHU The vespa-engine/cord-19 repository is used explicitly for the CORD-19 Vespa search application and not Vespa in general. I have therefore moved your issue over to the vespa-engine/vespa repository where it belongs.

The short answer is that Vespa does not include any transformers for the document formats you mention. You either have to extract the text for them before feeding to Vespa or embed a third party converter that you call from a custom [document processor](https://docs.vespa.ai/documentation/document-processing.html) that you write to handle this.
