### ISSUE TITLE
Dynamically creating tensor fields with different dimensionality  - was model versions

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#14244]
Posted on behalf of a vespa user:

We have a question about a versioning problem:
We're utilizing tensors of a specific dimension:
```
field Tensor_v1 type tensor<float>(x[24]) {
    indexing: attribute
}
```

When we want to test a new version of a model and require a different tensor dimension (say, 60), I currently would add another indexed tensor like:
```
field Tensor_v2 type tensor<float>(x[60]) {
    indexing: attribute
}
```

What we're wondering is if there's a way to more arbitrarily feed new tensors for new models without having to manually add these new fields; like a map where the key could be a string (e.g. a model name we decide) and the value is some tensor, and we'd be able to access that tensor during rank time.

**Comment by kkraune** [comment]
Thanks @jobergum 

If dimensionality is unchanged between versions, you could use a mapped tensor to express version, like

`tensor<float>(v{},x[60])`

**Comment by bratseth** [comment]
The model (computation) you do depends on the dimensionality so if you change it you need to add both a new model and new fields of the right dimensionality.
