### ISSUE TITLE
How to early stop merge the post listing on match phase?

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#14307]
Any way to stop merging the post listing when there is enough documents hit the terms. For example, when search term "A" and "B", if there is many documents contains these terms, the match phase(merge post listing) may cost much time. I know we can config `max-hits` at match-phase stage, but it only affects the first-phase.

**Comment by jobergum** [comment]
Have you looked at WAND https://docs.vespa.ai/documentation/using-wand-with-vespa.html ?

**Comment by jobergum** [comment]
So the relevant documentation on **match-phase** degradation is here https://docs.vespa.ai/documentation/graceful-degradation.html#match-phase-degradation. 

>I know we can config max-hits at match-phase stage, but it only affects the first-phase.

Generally Vespa does DAAT (document-at-a-time) and not TAAT (term-at-a time) so ranking and matching is not fully two separate phases where one first find matches and later ranks them. Matching and first-phase score calculation is interleaved when using DAAT. The first-phase ranking score is assigned to the hit when it satisfies the query constraints and at that point the term iterators are positioned at the document id and one can unpack additional data from the tern posting lists,  for example for proximity used by nativeRank/nativeProximity ranking feature which also requires unpacking of positions of the term within the document. 

With **match-phase** enabled the search core starts matching and ranking using DAAT and keeps track of the fraction of the documents which is evaluated which becomes a match, after a while it can estimate the total number of hits which will match and if this estimate become larger than the configured max-hits match-phase setting it triggers match-phase degradation where it rewrites the query tree to also include the match-phase attribute which contains the document level signal and resets term iterators and starts evaluating a document at a time ordered by the match-phase attribute. 

Vespa can do a hybrid query evaluation combining TAAT and DAAT and using TAAT for subtree parts of the overall query tree which is not used for ranking, but used only for filtering where unpacking of posting lists is not needed. This can speed up the matching in some cases where the query tree is large and complex and where only small parts of the query tree is used for ranking hits (e.g ranking simply by an attribute/tensor scoring). 

For example for a query request where we take some user input from an end user by the userQuery() syntax and combine it with business logic filters. In this example a language constraint and a market constraint:

```
{
  'hits': 10,
  'ranking.profile': text-and-popularity",
  'yql': 'select * from sources * where userQuery() and \
   (language contains "en" or language contains "br") and \
   (market contains "us" or market contains "eu" or market contains "apac" or market contains ".." ... ..... ..);'
  'query': 'cat video'
}
```

With ranking profile **text-and-popularity** defined as:

```
rank-profile text-and-popularity {
  first-phase {
    expression: attribute(popularity) + log10(bm25(title))
  }
}
```
In this case the ranking profile only uses two signals, the popularity value and the bm25 score of the title as calculated from the input userQuery() terms. The language and the market constraints in the query tree are not used in the ranking score and that part of the query tree could be evaluated using TAAT and the result passed as a bit vector into the DAAT query evaluation which *could* speed up evaluation. Enabling TAAT is done by passing *ranking.matching.termwiselimit=0.01*.

**Comment by jobergum** [comment]
Added documentation on this in https://docs.vespa.ai/documentation/performance/feature-tuning.html#hybrid-taat-daat.

**Comment by luoyetx** [comment]
Thanks very much. I will tuning the query to see if weakAnd gives less time cost.
