### ISSUE TITLE
Add ability to execute a query in a single pass against content clusters

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#14434]
Today we only support doing two phased query execution where 

* search phase executes the query plan over nodes involved and computes ranking models (e.g a onnxModel) 
* summary phase where top-k hits are filled from search phase and where ranking summary features are re-computed 

With the integration of onnx-rt on the content nodes I think it would be very beneficial if we one could force a single pass as it would make several use cases faster. 

1) Model evaluation with a single document,query pair and where we want to use several outputs of the model returned as ranking summary features. E.g the model could be an embedding function which maps the input query to a dense embedding representation which is returned as a tensor which is used to retrieve in another query, e.g using ANN where we use normal two pass query execution. 

2) Model evaluation with query,[documents] where the number of documents is low and where we are only interested in the top 1-2 documents per node but for which we need several outputs of the model to further re-rank in the container level or produce the answer, e.g for a question answering task.

**Comment by bratseth** [comment]
Yes, and this should be much less work now after switching protocol and dispatching from the container.

**Comment by jobergum** [comment]
This is now possible after adding the new **match-features** feature where tensors and computations can be returned in a single execution phase. 

 https://docs.vespa.ai/en/reference/schema-reference.html#match-features
