### ISSUE TITLE
search node restart failed

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#14502]
I removed hnsw indexing from a  tensor field, and met an exception when restarting the searchnode.
![image](https://user-images.githubusercontent.com/5534548/93999213-21c3fb80-fdc8-11ea-9b47-7ec3830c878e.png)

origin field definition
![image](https://user-images.githubusercontent.com/5534548/93999321-415b2400-fdc8-11ea-9efe-2dbe2e8e3ebc.png)

delete hnsw indexing
![image](https://user-images.githubusercontent.com/5534548/93999419-5f288900-fdc8-11ea-9f99-52a1a334c274.png)

And I found the update latency is pretty high when there is a hnsw field in document. 
The write qps is only 1000- on a vespa cluster with 36 nodes.
![image](https://user-images.githubusercontent.com/5534548/93999940-07d6e880-fdc9-11ea-9a3c-6441a55708c2.png)

write latency
![image](https://user-images.githubusercontent.com/5534548/94000168-5e442700-fdc9-11ea-9461-04dce80d0037.png)

write qps without hnsw
![image](https://user-images.githubusercontent.com/5534548/94011529-1679cb80-fdda-11ea-80bd-3355f67911ea.png)

**Comment by jobergum** [comment]
Thank you for your report, 

What Vespa version are you using? The innerproduct distance metric was added recently so I'm wondering if you have a miss-match in the Vespa version of the configuration servers and the Vespa content nodes (e.g configuration server is with a recent Vespa version which accepts the innerproduct distance metric and your content nodes have a Vespa version which does not know about the innerproduct metric. Adding or removing HNSW index is a deployment operation which requires a restart of the content nodes. Could you verify this? If you have the same version could you provide the sequence of operations and output when you deploy the changed schema. 

On performance with HNSW 
- Your reported throughput is much much less than expected if your setup is 16 nodes in a flat distribution, if you have a single partition in a grouped distribution it's more inline with expectation for vanilla HW (1600 puts). Multi-threaded indexing for HNSW was also added around the same time as the innerproduct distance metric was added. 
- 128 dimensional SIFT gives about 6200 puts/s per node with default concurrency.

![image](https://user-images.githubusercontent.com/20928528/94119679-86766900-fe4f-11ea-8609-43b05a5fb5e9.png)

**Comment by dsisds** [comment]
7.286.18

**Comment by geirst** [comment]
Thanks for reporting this. I have reproduced it locally. We have a bug where we don't recognise `innerproduct` as a valid distance metric when reading header information for an attribute tensor during loading from disk. This issue can also be triggered by just restarting a content node where an attribute tensor uses:
```
attribute {
    distance-metric: innerproduct
}
```
This issue is fixed in https://github.com/vespa-engine/vespa/pull/14537.

**Comment by dsisds** [comment]
Great！The searchnode restart successfully with your configuration. Thanks.

Is there any process on low writing qps to hnsw index?

**Comment by geirst** [comment]
The fix is available in version >= 7.292.39.

**Comment by jobergum** [comment]
Hello @dsisds, 

It's easier to comment on write performance if you share more on your setup and configuration overrides/tunings.

* Type of HW - and resource usage observations? With default concurrency setting you should get close to 50% cpu usage. 
* How many fields with HNSW and settings? We expect > 6000 puts/s per node with 128 dimensions and the hnsw graph settings you have there (for a single fields). More fields with hnsw gives less throughput and more work. I assume you don't compute the embeddings as part of the feeding?
* Grouped of flat distribution ?
* What's the observed cpu usage (document processing, content nodes) - have you done any profiling (https://docs.vespa.ai/documentation/performance/profiling.html)? 
* Any specific configuration overrides in services.xml? Multi-threaded HNSW indexing is controlled by the concurrency setting in services.xml as mentioned here https://docs.vespa.ai/documentation/approximate-nn-hnsw.html. If you have some custom configuration overrides might cancel this high level configuration knob.

**Comment by dsisds** [comment]
Hello @jobergum 

![image](https://user-images.githubusercontent.com/5534548/94241583-6aee8980-ff47-11ea-8eaf-c5cccb8fd9ea.png)

1. I set feeding.concurrency to 0.8. The cpu usage is between 100% ~ 200% when add one hnsw field to a content cluster with data. The cpu usage is about 50% when feeding data to a cluster with one hnsw field. There are 35 nodes in the vespa cluster and each node has 48 cpu cores.
2. There is Only one HNSW field. All embeddings are pre-computed.
3. No groups. Check my content setttings.
![image](https://user-images.githubusercontent.com/5534548/94242780-22d06680-ff49-11ea-9e5a-7887f8a23abe.png)

4. CPU profiling.
![image](https://user-images.githubusercontent.com/5534548/94243143-97a3a080-ff49-11ea-951d-d575ee826163.png)

![image](https://user-images.githubusercontent.com/5534548/94243220-af7b2480-ff49-11ea-9de8-829d80e41880.png)

5. field settings
![image](https://user-images.githubusercontent.com/5534548/94243486-0bde4400-ff4a-11ea-9a3b-837fd12e2de1.png)

**Comment by jobergum** [comment]
If the above top screenshot is taken during feeding there is something that is seriously off as proton is using only a single cpu core (100%). The expected if there there are not bottlenecks outside of the content node would be 2400% and 50% overall cpu utilization on the host. You have enough document processing (container) instances to get enough data through?

**Comment by dsisds** [comment]
I deployed container services on all the nodes.
My cluster contains 35 container nodes, and 700M documents.

**Comment by jobergum** [comment]
@dsisds 

So to help my understanding as I'm a little confused but thanks for confirming that the container processing capability is sufficient. 

- You loaded the tensor field with summary |attribute for all 700M documents
- Then you changed the configuration to include summary|attribute|index plus the index.hnsw setting and deploy this change
- Then you observe vespa-proton-bin occupy only 1 cpu core as in the screenshot in the comment above

Is this an accurate summary?

**Comment by dsisds** [comment]
yes

**Comment by jobergum** [comment]
Thanks for clarifying @dsisds, 

In this case, the HNSW index is built when loading the *bert_embedding* tensor attribute for the first time after the schema changes and this process will be single threaded. If the schema specified hnsw index before loading it would be much faster as then the index building would be multi-threaded (controlled by mentioned concurrency parameter).

**Comment by dsisds** [comment]
Understood.
Thanks for your patience.

Is there any progress on the low performance of feeding index with an HNSW field?

**Comment by jobergum** [comment]
As I wrote earlier our performance testing with HNSW index  with similar dimensionality using SIFT 128 we achieve just north of 6000 puts/s **per node**.  Your reported performance with a larger cluster is pretty far from what I would have expected. 

So what I suggest is that you setup a single node cluster and feed 20M documents (bootstrap) with the embedding and hnsw index to it and measure the feed performance and provide us with information on hw spec of this node and resource utilization during feed, e.g using top like above and preferably also perf profiling.

**Comment by jobergum** [comment]
@dsisds any updates on this?
