### ISSUE TITLE
Document api error: DOCUMENT_EXCEPTION

### ISSUE THREAD

**Issue by kuipertan** [vespa-engine/vespa#15136]
I build vespa, and install it on phiscal machine, call /opt/vespa/bin/vespa-start-configserver  and /opt/vespa/bin/vespa-start-services .
Submit my application package normally, and  http://localhost:19071/application/v2/tenant/ourtenant/application/  show normally.
But when I feed it with one document, it failed:

_**curl -H "Content-Type:application/json" --data-binary @/opt/samples/bd-search-data/english1.json  
 http://localhost:8080/document/v1/mynamespace/kosmos/docid/1

response:
{"errors":[{"description":"DOCUMENT_EXCEPTION [ENCODE_ERROR @ localhost]: Protocol 'document' failed to encode message. ","id":-11}],"id":"id:mynamespace:kosmos::1","pathId":"/document/v1/mynamespace/kosmos/docid/1"}**_

Anyone can tell me why? Tks

**Comment by kkraune** [comment]
can you paste the contents of /opt/samples/bd-search-data/english1.json here? thanks

**Comment by kkraune** [comment]
I am sorry I have tried to feed different kinds of input to trigger this error, with no success - I assume there is something with the file data in english1.json that triggers this - reopen if you can submit the data, thanks
