### ISSUE TITLE
Go & Python Driver

### ISSUE THREAD

**Issue by batara666** [vespa-engine/vespa#15692]
Do we have one ?

**Comment by bratseth** [comment]
Go: No.
Python: https://pyvespa.readthedocs.io/en/latest/ but that's for data science.

The usual approach for queries is to just send the raw data to Vespa in a HTTP request and build the query server-side in a Searcher (you can also easily add your own custom Rest APIs).

For write operations you can also just do a HTTP request per write but for high throughput you want async. We provide a client library for that but only in Java. You can use it from other languages by piping to it, but then each such invocation should be large to avoid setting up connections too often.
