### ISSUE TITLE
Use imported tensor for ranking

### ISSUE THREAD

**Issue by daouh** [vespa-engine/vespa#15767]
I am having trouble using an imported tensor field for ranking. I have these two types of documents:

```
search doc {
  document doc {
    field id type int {
      indexing: summary | attribute
    }
    field vector type tensor<float>(x[768]) {
      indexing: summary | attribute
    }
  }
}
```

```
search companies {
  document companies {
    field doc_ref type reference<doc> {
      indexing: summary | attribute
    }

    field siret type string {
      indexing: index | summary
    }
  }
  import field doc_ref.vector as doc_vector {}
  import field doc_ref.id as doc_id {}
  rank-profile euclidean-rank inherits default {
   first-phase {
     expression: 1/(1 + sqrt(sum(join(query(vector), attribute(doc_vector), f(x,y)((x-y)*(x-y))))))
   }
  }
    document-summary my_summary {
    summary doc_id type int {}
    summary doc_vector type tensor<float>(x[768]) {}
  }
}

```
But when I try the query with the body below (where **vector** is a given vector of size 768), I always get "fields":{"totalCount":0} 

> vespa_body_ann = {
>         'yql': 'select siret from companies where [{"targetNumHits":%i}]nearestNeighbor( doc_vector, vector);' % 3,
>         'hits': 3,
>         'ranking.features.query(vector)': str(**vector**.tolist()), 
>         'ranking.profile': 'euclidean-rank',
>         'timeout': '15s',
>         'ranking.softtimeout.enable': 'false'
>       }
> r = requests.post('http://localhost:8080/search/', data = vespa_body_ann)

**Comment by jobergum** [comment]
Thank you for your interest, 

Could you run the query with &tracelevel=3 and include the part after `search to dispatch: query`

The ranking expression can be optimized (but is not the reason why you get 0 hits) to `closeness(field, vector)`

**Comment by daouh** [comment]
Thank you for your reply!

This is what I get:

> search to dispatch: query=[NEAREST_NEIGHBOR {field=doc_vector,queryTensorName=vector,hnsw.exploreAdditionalHits=0,approximate=true,targetNumHits=3}] timeout=14936ms offset=0 hits=3 rankprofile[euclidean-rank] groupingSessionCache=true sessionId=container.container.0.1607589786064.0.euclidean-rank grouping=0 :  rankproperties={\\"vector\\":[tensor<float>(x[768]):[-0.0018361546, 0.10149636, 0.023553325, -0.0037925292, 0.018341502, -0.20903696, 0.02641962, -0.037268165, 0.17490523, 0.0069107213, -0.036246162, -0.11103954, 0.11203387, 0.02799862, -0.097346656, 0.05374943, -0.07761597, -0.067480125, -0.052378476, -0.18998869, -0.075003736, -0.11463249, 0.13462664, -0.054141387, -0.34281716, -0.08499509, -0.39275983, -0.098372675, 0.08416285, 0.065785564, -0.061930913, 0.26547673, -0.056725506, -0.004240791, 0.017102549, 0.002282222, -0.13311253, -0.20257495, 0.053170305, -0.032562356, 0.18505836, 0.05386643, 0.11681671, -0.11379061, -0.056543607, -0.22504272, -0.10925043, -0.1105982, 0.10594207, -0.03727329, 0.02735552, 0.05541444, 0.1273634, -0.03724513, -0.056887995, -0.120423794, -0.04312827, 0.04785928, 0.16503473, -0.08187264, -0.045366343, -0.08859178, -0.059411418, 0.07155757, 0.16209139, 0.11151949, -0.15669769, -0.095608205, -0.101189636, 0.12465992, 0.0402848, -0.10715667, 0.045374554, 0.103684194, 0.0106097795, -0.03499445, 0.18451583, -0.12098217, -0.0813302, 0.42017338, 0.12398454, -0.057502057, -0.09845195, -0.10698218, 0.21154504, 0.20242113, 0.007893731, -0.15370464, 0.17069173, -0.022273203, 0.23802547, -0.061344028, -0.021728298, -0.030039908, 0.114139855, -0.0059708157, -0.2950601, 0.040468216, 0.15804642, -0.21266276, 0.08075746, -0.12945531, -0.27770162, -0.11218679, -0.14754136, -0.0016435484, 0.1555643, -0.009053212, -0.07881826, -0.008642484, -0.07747867, -0.045720827, 0.048024815, 0.016466571, 0.017680049, -0.011531224, -0.1792904, 0.053360384, -0.38994703, -0.07728395, 0.13949545, 0.046964604, -0.1152214, -0.10366609, 0.19355546, 0.074283145, 0.109933846, -0.13071527, -0.28479543, 0.012912142, -0.12006395, 0.0014034038, -0.13212596, -0.09322547, -0.0022011201, 0.010497455, -0.0841619, -0.06229675, -0.08900867, -0.06943069, -0.009028488, -0.09886044, 0.12444979, 0.07326015, 0.21710587, -0.02794861, -0.059275348, -0.18271524, 0.07833587, -0.0027838189, -0.03232455, -0.020097544, -0.17566335, 0.11863037, -0.038536105, 0.12807593, -0.12105731, 0.18576002, 0.0029087726, -0.1809115, 0.16092701, 0.13474023, -0.021671465, -0.24776529, 0.085353255, 0.15152694, -0.08202598, 0.06411449, 0.008263335, -0.16198537, -0.095385455, -0.055266317, -0.18342425, 0.0019175056, 0.0069453716, -0.0745674, 0.039780542, 0.079367265, -0.26976433, 0.042780817, -0.22304845, 0.13614471, 5.9753656E-4, 0.020022713, 0.15713114, -0.0130754905, -0.02707261, -0.08237755, -0.034147236, 0.039003853, -0.0050520864, -0.1290263, -0.12018197, 0.13718961, -0.023725266, -0.18472461, -0.030439267, 0.022350581, 0.015579182, 0.44654217, 0.19803838, -0.02376167, -0.2573097, -0.09468803, 0.025980344, 0.058668002, -0.0062045143, -0.09182719, 0.03719319, 0.17888218, 0.113548785, -0.06578811, -0.06837037, -0.14161418, -0.028245801, -0.2956319, -0.06747062, 0.17786467, 0.018291792, 0.039165307, -0.062134523, -0.10944658, -0.2622197, 0.056479942, 0.15056664, 0.00201681, -0.073208064, -0.03777848, 0.077360585, 0.021887874, -0.053393353, -0.47895733, 0.030893655, -0.057337154, -0.24703223, -0.04460475, -0.03864938, 0.0027845402, -0.021115316, 0.020379364, 0.048717964, -0.21499602, 0.08830299, 0.054541882, -0.058759194, -0.013293743, 0.1440239, -0.01933278, 0.20576614, 0.45909044, 0.022188758, 0.087278225, 0.09160977, -0.037187263, 0.068193905, 0.0014183713, 0.24059325, 0.1633581, 0.357497, -0.089434914, -0.015344937, 0.106113136, -0.050198734, -0.10529354, 0.40537795, -0.25931808, 0.10304087, 0.21178265, 0.15039842, 0.0911446, -0.17900853, 0.004676727, 0.9547491, 0.07723643, 1.8266331, -0.15838659, -0.012949546, -0.066364534, -0.020612517, -0.2514126, 0.020367902, 0.17625062, -0.11751457, -0.008084265, 0.04327413, 0.20600386, -0.091411345, -0.10186994, 0.12269985, -0.10160706, 0.054133113, -0.09135204, -0.075789586, -0.16525193, 0.17521201, -0.118962504, -0.29119223, 0.028002499, 0.015303403, -0.16516508, 0.20686866, -0.08814799, -0.10637388, 0.0531861, -0.059897482, -0.11418629, -0.0058635683, -0.11378337, 0.08585236, 1.0163916, 0.103862815, 0.06807662, -0.027354779, 0.032408673, 0.1326878, -0.045513224, 0.23417486, -0.06028447, 0.097339295, 0.03578578, 0.034623284, 0.04347123, -0.47088006, 0.058394235, 0.08390308, -0.05859599, 0.25738785, 0.029856741, -0.06483181, -0.097257376, 0.13489519, -0.15547101, -0.082454614, 0.1342067, 0.13794477, 0.105121575, 0.09979638, 0.03316923, 0.10569636, -0.04436763, 0.26994935, -0.29768375, 0.007538105, -0.08736316, -0.05762398, -0.09947678, 0.032012314, -0.09270383, -0.346558, 0.033157427, -0.08244844, -0.16851306, 0.06184882, 0.19370496, 0.12528013, -0.087442905, 0.09048346, -0.07443204, -0.19855686, 0.135942, -0.02362282, -0.095760785, 0.029341256, 0.11780375, 0.07229916, -0.05178763, 0.1620866, 0.057538327, -0.18859732, -0.027435092, -0.031988155, 0.1662245, -0.163175, -0.01462699, -0.21146776, 0.054998916, -0.14966993, -0.030271426, 0.039684292, -0.052090656, 0.21434103, -0.13328388, -0.03409713, 2.5226673E-4, 0.103838794, 0.07373748, -0.19172692, 0.042596996, 0.047789406, -0.001728767, -0.21631233, 0.13376515, 0.14974304, -0.04342085, -0.014147363, 0.20013185, 0.08412378, 0.007556565, 0.19571342, 0.0052498505, 0.028163144, 0.027064063, -0.101062976, -0.06652558, -0.15595262, -0.12034156, 0.24836637, -0.11909049, -0.222234, -0.05812612, -0.0639819, 0.14119488, 0.0044039004, -0.09823376, 0.014448747, 0.12470702, 0.0081259115, 0.15456344, 0.18423732, 0.05200551, -0.0886794, 0.11784486, -5.946383E-4, -0.09612987, -0.15214, -0.14349979, -0.09074531, -0.10837839, 0.039134994, 0.029997425, 0.14709537, -0.13768373, -0.10500983, 0.02352888, 0.17161678, -0.011415456, 0.028176477, 0.09653672, 0.14597873, -0.21578626, 0.15963997, 0.05122326, 0.020183226, -0.080949225, -0.034070272, 0.01832459, -0.04674528, -0.097774126, -0.05345595, -0.092174016, 0.048703205, -0.02337408, -0.0175107, 0.32838315, 0.09831965, -0.06941442, -0.26948318, 0.18314947, -0.048327923, 0.5436627, -0.032383133, -0.2499529, 0.090415694, 0.0764524, 0.13109498, -0.0988226, -0.13500223, -0.101870954, -0.036701057, 0.055060375, 0.19226395, 0.17550837, 0.037325405, 0.44177094, -0.028566828, -0.20707183, -0.13474707, 0.0394634, 0.049089286, 0.009601611, 0.33012962, 0.10477922, -0.027593082, 0.11442226, -0.02889807, -0.03572632, -0.02981659, -0.12511127, -0.05699404, -0.7603728, 0.12379277, -0.060298935, -0.15668072, -0.059740085, -0.16376992, -0.115929425, 0.21016754, 0.11943072, 0.014471638, -0.13895217, 0.13453332, 0.1718908, -0.4692041, -0.09442526, 0.02795432, 0.25969243, -0.10201002, -0.0071097873, 0.12689467, 0.012859565, -0.2387852, -0.12137297, 0.08298483, 0.0068491623, -0.03351098, -0.057354983, 0.16745971, 0.083661914, -0.07021194, -0.052228138, 0.14355229, -0.39926076, -0.123693675, -0.0015184289, 0.0717291, -0.08451744, 0.25500727, 0.06806303, 0.17228933, 0.036757946, -0.05246331, -0.1233856, 0.046055917, 0.12789197, 0.026885187, 0.039429232, 0.55147415, -0.06736331, -0.12278843, 0.017836647, 0.15553167, 0.0119205685, 0.0871863, -0.17927499, -0.029010542, 0.06195469, 0.08804053, -0.15517654, -0.0250409, -0.057322565, -0.0732119, -0.03673187, 0.0820368, 0.055929486, -0.086267345, -0.049860686, 0.0154075, 0.076081336, 0.05775449, 0.114149235, -0.11496652, 0.08029973, -0.12808746, 0.02979952, 0.007892991, 0.09897033, 0.14471962, -0.20412827, 0.12634586, 0.116624534, 0.05034234, -0.04354209, 0.08964173, 0.113174886, -0.0812065, -0.24433924, -0.0460293, 0.13325563, -0.15844436, -0.01709368, -0.13594925, -0.05054749, -0.068334214, -0.44677868, -0.08128128, -0.11228118, 0.047216833, -0.09062958, -0.02450198, 0.16880482, -0.062005203, 0.18419081, -0.121349834, 0.0064122505, 0.11605138, -0.06423304, -0.2853969, 0.046635628, -0.03487304, -0.20482928, -0.12146727, -0.09422409, 0.17902993, 0.013235852, 0.07283513, -0.04367901, -0.03791117, 0.16868772, -0.003699233, -0.011370838, -0.07182529, 0.020952733, -0.105142035, 0.06604639, 0.0334094, -0.08917744, 0.06180704, 0.049348906, -0.049067214, -0.17889248, -0.012687355, -0.113232434, -0.08465459, 0.30723545, 0.11791971, -0.12068381, 0.11829251, 0.10515797, -0.077379234, -0.016241765, 0.15830544, 0.05613251, 0.5393829, -0.30176187, 0.024883961, -0.002011155, -0.2577646, -0.007203153, 0.0054304847, 0.08699396, 0.09100851, 0.016096085, -0.053767264, -0.13337208, 0.40899673, 0.18913336, -0.0165337, 0.17245781, 0.16170573, -0.05475241, 0.041291583, -0.049433876, -0.046369698, 0.016709963, -0.1052529, -0.21195368, 0.06615417, 0.050724417, 0.059714537, 0.014423939, 0.023964427, 0.06831402, 0.0036055495, -0.13740386, -0.17995304, -0.08156175, -0.09296947, 0.2694151, 0.24193652, 0.05182828, 0.005284677, 0.03470799, -0.07816567, 0.18403442,
>  -0.057214435, -0.123870075, -0.23520845, -7.513861E-4, -0.14669968, -0.034899324, 0.04806869, -0.0155290915, 0.030511605, -0.044408243, -0.1957134, -0.06050032, -0.04947944, 0.09519034, -0.32964018, 0.06693171, -0.05810845, -0.12767835, 0.20537174, -0.58274406, -0.1178569, -0.070067644, -0.040175956, -0.0027876429, -0.03999938, 0.27404875, -0.048345204, -0.03486919, -0.106052555, -0.19659036, -0.18414305, -0.110375464, 0.012625161, 0.1480887, 0.5046873, -0.07959781, 0.023407461, -0.054667667, 0.038115848, -0.15933886, -1.4017129, 0.07265329, -0.06797766, -5.9646805E-4, 0.19524603, 0.028358111, 0.0013322657, -0.12098933, 0.05499555, 0.005743423, 0.017011456, -0.14051682, 0.0070233657, 0.042043906, 1.750129E-4, -0.05582646, -0.13564195, -0.19519037, -0.04286046, 0.14776127, -0.044234175, -0.0533216, 0.100541115, 0.11602155, -0.041839305, 0.09593838, -0.042219162, 0.33737445, -0.15615866, -0.027234396, 0.034265883, 0.21492915, 0.07680916, -0.18856527, -0.102336295, -0.008477141, -0.15995097, 0.042750996, -0.024200888, 0.07563585, 0.14215553, 0.046901435, 4.1379718E-4, 0.13741355, 0.039227083, 0.10740522, -0.27708972, 0.10129576, -0.09842041, 0.08373249, 0.15467282, 0.013996944, -0.011171703, 0.01834918]],\\"vespa.softtimeout.enable\\":[false]} restrict=[companies]"},{"message":"Current state of query tree: NEAREST_NEIGHBOR[connectedItem=null connectivity=0.0 creator=ORIG explicitSignificance=false isRanked=true significance=0.0 uniqueID=1 usePositionData=true weight=100]"},{"message":"YQL+ representation: select siret from companies where [{\\"id\\": 1, \\"targetNumHits\\": 3}]nearestNeighbor(doc_vector, vector) limit 3 timeout 14936;"},{"message":"Dispatching to search node key = 0 hostname = daf5cc009bee path = 0 in group 0 statusIsKnown = true working = true activeDocs = 2"},{"message":[{"start_time":"2020-12-10 08:43:06.147 UTC","distribution-key":0,"duration_ms":3.840909}]},{"message":"sc0.num0 dispatch response: Result (0 of total 0 hits)"}]},{"message":"Ignoring fill(null): Hits are unfillable: result.hits().getFilled()=null"},{"message":"Query time query \'NEAREST_NEIGHBOR {field=doc_vector,queryTensorName=vector,hnsw.exploreAdditionalHits=0,approximate=true,targetNumHits=3}\': 198 ms"},{"message":"Summary fetch time query \'NEAREST_NEIGHBOR {field=doc_vector,queryTensorName=vector,hnsw.exploreAdditionalHits=0,approximate=true,targetNumHits=3}\': 2 ms"}]}]},"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"coverage":{"coverage":100,"documents":0,"full":true,"nodes":1,"results":1,"resultsFull":1}}}'
>

**Comment by jobergum** [comment]
It looks like your index is empty? In the coverage the content node reports 0 docs.

```
documents":0
```

Also the trace is not consistent with the vespa_body_ann request body: 

NEAREST_NEIGHBOR {field=doc_vector..

The imported field is called 'vector'

**Comment by daouh** [comment]
Sorry I just forgot to add the documents while trying to reproduce the problem I had. I've just updated my last comment. I have 4 documents.

**Comment by jobergum** [comment]
So you try to search field=doc_vector, is there such a field in the document definition?

**Comment by daouh** [comment]
Yes I have it, I had changed the definition a bit since yesterday. I just updated the definition in the first comment.

> vespa_body_ann = {
>  'yql': 'select doc_vector from companies where siret=0;' 
>   }
>  r = requests.post('http://localhost:8080/search/', data = vespa_body_ann)
>  r.text
> Out[153]: '{"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":1},"coverage":{"coverage":100,"documents":4,"full":true,"nodes":1,"results":1,"resultsFull":1},"children":[{"id":"index:content/0/cfcd20846eec88d006bad597","relevance":0.16343879032006287,"source":"content"}]}}'

**Comment by daouh** [comment]
do you have an idea about the origin of this problem? Is there anything missing in the definition of my documents?

**Comment by geirst** [comment]
Unfortunately, searching an imported tensor with the _nearestNeighbor_ query operator is currently not supported. The following warning is emitted to the vespa log and zero results are returned:

`WARNING : searchnode       proton.searchlib.attribute.attribute_blueprint_factory     NearestNeighborTerm(pos, qpos_double): Attribute is not a dense tensor (type=tensor(x[2])). Returning empty blueprint`

I have created the following dev ticket for this issue: https://github.com/vespa-engine/vespa/issues/15783.

**Comment by daouh** [comment]
Thank you!
