### ISSUE TITLE
Support using imported tensor attribute with nearestNeighbor query operator

### ISSUE THREAD

**Issue by geirst** [vespa-engine/vespa#15783]
Currently, this is stopped in AttributeBlueprintFactory with the following example warning:

`NearestNeighborTerm(pos, qpos_double): Attribute is not a dense tensor (type=tensor(x[2])). Returning empty blueprint`

To fix this we must avoid using DenseTensorAttribute directly. Instead we need an interface that NearestNeighborBlueprint can use, that both DenseTensorAttribute and ImportedTensorAttributeVector can implement.

**Comment by geirst** [comment]
We should also consider supporting this for imported tensor attributes that have a hnsw index.

**Comment by daouh** [comment]
Could you please give an estimate of when it will be available?

**Comment by kkraune** [comment]
Hi @daouh thanks for following up on feature requests! We will do planning for next quarters in the new year, so it will not be available short term, we need to scope the work as well. We will post updates here once we know more.

**Comment by geirst** [comment]
This has been fixed in 7.384.18 (https://github.com/vespa-engine/vespa/pull/17236).
System test added in https://github.com/vespa-engine/system-test/pull/1454.
