### ISSUE TITLE
Add first-phase rerank-count 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#15855]
In cases where one uses sub-linear sparse retrieval (e.g WAND with K=x) the number of exposed hits to the first-phase ranking function is unbound as WAND exposes all hits it *evaluated* while searching for the top x hits.  There are three reasons for introducing a rank-count also for first-phase 

* Conceptually when using ANN/WAND the query retrieval phase is  candidate retrieval and our first-phase is really the first ranking phase so it makes sense to limit the number of evaluations 
* It's more work training a first-phase ranking function as during training it needs to sample hits differently then just sample from the top-k retrieved as in reality it might see some very low performing hits
* It sets upper bound on how many hits are evaluated so performance becomes more predictable 

```
rank-profile super-phased {
   first-phase {
       expression: lightgbm("trained-first-phase.json") 
       rerank-count:1000
   }
  second-phase { 
     expression: query(p1_weight)*firstPhase + (1 - query(p1_weight))*onnx("ranker.onnx") 
     rerank-count: 10
   }
}
```

With the above, *max* 1000 docs from the retrieval phase is evaluated using a trained GBDT model and top 10 re-ranked using a ONNX model.

**Comment by johans1** [comment]
wontfix
