### ISSUE TITLE
Why ranking score becomes smaller when using OR in yql

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#15876]
Perform the yql below
```
select * from index where fieldA contains termA and fieldB contains termB;
```
and
```
select * from index where (fieldA contains termA or fieldA contains termA') and fieldB contains termB;
```

The same doc returned by these two yql get different scores, the doc only contains termA and termB, and the second yql always return docs with smaller relevance score.

How to understand this behavior, where's the code calculate score with OR operator that I can read.

**Comment by jobergum** [comment]
Hello @luoyetx, 

The assigned relevancy score is calculated by the ranking profile used. 

 If you are using the default ranking profile which uses nativeRank, repeating a term in the query (termA searches for twice in fieldA) changes the number total query term numbers and consequently several of the features involved in nativeRank will also change, e.g nativeProximity and nativeFieldMatch.  Similar if you use bm25 which is not normalized to a particular score range and repeating a term in the query will cause the score for the document to increase when repeating a query term.  There are syntax in YQL and also programatically to override query term weight and if a term should be part of the ranking formulation or not.

- nativeRank https://docs.vespa.ai/documentation/reference/nativerank.html
- bm25 https://docs.vespa.ai/documentation/reference/bm25.html
