### ISSUE TITLE
Extend http-client to support cloud based certificates (AWS ACM, S3, KMS, etc)

### ISSUE THREAD

**Issue by vfil** [vespa-engine/vespa#15889]
Hello, I am trying out vespa cloud and it looks great!
Now I am making progress towards the production environment and I noticed that in http-client `ConnectionParams.Builder` accepts only `java.nio.file.Path` when using `setCertificateAndPrivateKey`. I personally find this restriction cumbersome because given serverless and containerised cloud environments, relying on the filesystem seems redundant and not desirable.
I am wondering if it's possible to extend the API to accept also a `java.io.Reader` so the vespa consumers can use something like AWS KMS or S3 or similar cloud provider services to build the vespa client?
Side note:
I suppose you are using bouncycastle under the hood and they accept `Reader` https://javadoc.io/doc/org.bouncycastle/bcprov-jdk15on/latest/org/bouncycastle/util/io/pem/PemReader.html

**Comment by tokle** [comment]
Hi @vfil, 

Can you use `setSslContext` of the `ConnectionParams.Builder` for this? If this is provided it will be used instead of the provided certificate and key.

**Comment by vfil** [comment]
@tokle good point will try that! Btw in general what is the motivation of using SSL key pairs vs just regular API tokens that users can generate in vespa cloud and use on the consumer side?

**Comment by tokle** [comment]
We are looking into other ways of providing secure access to endpoints, but currently the only approved solution is mTLS.

**Comment by baldersheim** [comment]
**Soon** has timed out
