### ISSUE TITLE
Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.6.0.2:run failed: unknown os.arch: riscv

### ISSUE THREAD

**Issue by advancedwebdeveloper** [vespa-engine/vespa#15997]
Hello.
I wasn't able to build Vespa on RISC-V port of Debian 10.

> [INFO] 
> [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ vespa-http-client ---
> [INFO] Installing /home/ivan/vespa/vespa-http-client/target/vespa-http-client.jar to /home/ivan/.m2/repository/com/yahoo/vespa/vespa-http-client/7-SNAPSHOT/vespa-http-client-7-SNAPSHOT.jar
> [INFO] Installing /home/ivan/vespa/vespa-http-client/pom.xml to /home/ivan/.m2/repository/com/yahoo/vespa/vespa-http-client/7-SNAPSHOT/vespa-http-client-7-SNAPSHOT.pom
> [INFO] Installing /home/ivan/vespa/vespa-http-client/target/vespa-http-client-sources.jar to /home/ivan/.m2/repository/com/yahoo/vespa/vespa-http-client/7-SNAPSHOT/vespa-http-client-7-SNAPSHOT-sources.jar
> [INFO] Installing /home/ivan/vespa/vespa-http-client/target/vespa-http-client-javadoc.jar to /home/ivan/.m2/repository/com/yahoo/vespa/vespa-http-client/7-SNAPSHOT/vespa-http-client-7-SNAPSHOT-javadoc.jar
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for vespa 7-SNAPSHOT:
> [INFO] 
> [INFO] container-dependency-versions ...................... SUCCESS [  7.746 s]
> [INFO] parent ............................................. SUCCESS [01:27 min]
> [INFO] yolean ............................................. SUCCESS [10:54 min]
> [INFO] testutil ........................................... SUCCESS [09:23 min]
> [INFO] vespajlib .......................................... SUCCESS [38:18 min]
> [INFO] config-lib ......................................... SUCCESS [10:54 min]
> [INFO] defaults ........................................... SUCCESS [08:31 min]
> [INFO] jdisc_core ......................................... SUCCESS [38:12 min]
> [INFO] security-utils ..................................... SUCCESS [  01:40 h]
> [INFO] jrt ................................................ SUCCESS [13:12 min]
> [INFO] http-utils ......................................... SUCCESS [06:28 min]
> [INFO] config ............................................. SUCCESS [31:04 min]
> [INFO] Vespa Log .......................................... SUCCESS [09:00 min]
> [INFO] config-bundle ...................................... SKIPPED
> [INFO] component .......................................... SKIPPED
> [INFO] configdefinitions .................................. SUCCESS [24:31 min]
> [INFO] config-provisioning ................................ SKIPPED
> [INFO] jdisc_jetty ........................................ SUCCESS [02:23 min]
> [INFO] container-accesslogging ............................ SKIPPED
> [INFO] jdisc_http_service ................................. SKIPPED
> [INFO] provided-dependencies .............................. SKIPPED
> [INFO] config-model-api ................................... SKIPPED
> [INFO] config-application-package ......................... SKIPPED
> [INFO] container-di ....................................... SKIPPED
> [INFO] chain .............................................. SKIPPED
> [INFO] processing ......................................... SKIPPED
> [INFO] linguistics ........................................ SKIPPED
> [INFO] messagebus ......................................... SKIPPED
> [INFO] predicate-search-core .............................. SUCCESS [09:23 min]
> [INFO] document ........................................... SKIPPED
> [INFO] vdslib ............................................. SKIPPED
> [INFO] documentapi-dependencies ........................... SKIPPED
> [INFO] documentapi ........................................ SKIPPED
> [INFO] container-documentapi .............................. SKIPPED
> [INFO] fileacquirer ....................................... SKIPPED
> [INFO] statistics ......................................... SKIPPED
> [INFO] container-core ..................................... SKIPPED
> [INFO] metrics ............................................ SKIPPED
> [INFO] metrics-proxy ...................................... SKIPPED
> [INFO] jdisc_messagebus_service ........................... SKIPPED
> [INFO] messagebus-disc .................................... SKIPPED
> [INFO] container-messagebus ............................... SKIPPED
> [INFO] hosted-zone-api .................................... SUCCESS [03:18 min]
> [INFO] simplemetrics ...................................... SKIPPED
> [INFO] container-disc ..................................... SKIPPED
> [INFO] searchlib .......................................... SKIPPED
> [INFO] model-integration .................................. SKIPPED
> [INFO] docproc ............................................ SKIPPED
> [INFO] fsa ................................................ SUCCESS [06:57 min]
> [INFO] container-search ................................... SKIPPED
> [INFO] container-search-and-docproc ....................... SKIPPED
> [INFO] searchcore ......................................... SUCCESS [15:49 min]
> [INFO] model-evaluation ................................... SKIPPED
> [INFO] vespa_jersey2 ...................................... SUCCESS [03:44 min]
> [INFO] container-jersey2 .................................. SKIPPED
> [INFO] container-dev ...................................... SKIPPED
> [INFO] logd ............................................... SUCCESS [03:51 min]
> [INFO] storage ............................................ SUCCESS [08:50 min]
> [INFO] vsm ................................................ SUCCESS [04:17 min]
> [INFO] vespaclient-core ................................... SKIPPED
> [INFO] indexinglanguage ................................... SKIPPED
> [INFO] searchsummary ...................................... SUCCESS [03:09 min]
> [INFO] config-model ....................................... SKIPPED
> [INFO] zookeeper-server ................................... SKIPPED
> [INFO] zookeeper-server-common ............................ SKIPPED
> [INFO] zkfacade ........................................... SKIPPED
> [INFO] standalone-container ............................... SKIPPED
> [INFO] container-search-gui ............................... SKIPPED
> [INFO] container-test-jars ................................ SUCCESS [  2.229 s]
> [INFO] jersey-resources ................................... SUCCESS [02:19 min]
> [INFO] application ........................................ SKIPPED
> [INFO] application-model .................................. SUCCESS [04:33 min]
> [INFO] application-preprocessor ........................... SKIPPED
> [INFO] flags .............................................. SKIPPED
> [INFO] vespa-athenz ....................................... SKIPPED
> [INFO] service-monitor .................................... SKIPPED
> [INFO] jaxrs_utils ........................................ SUCCESS [02:15 min]
> [INFO] orchestrator-restapi ............................... SUCCESS [03:03 min]
> [INFO] jaxrs_client_utils ................................. SUCCESS [08:44 min]
> [INFO] orchestrator ....................................... SKIPPED
> [INFO] node-repository .................................... SKIPPED
> [INFO] athenz-identity-provider-service ................... SKIPPED
> [INFO] bundle-plugin-test ................................. SUCCESS [  2.709 s]
> [INFO] test-bundles ....................................... SKIPPED
> [INFO] main ............................................... SKIPPED
> [INFO] artifact-version-for-exports-dep ................... SKIPPED
> [INFO] artifact-version-for-exports ....................... SKIPPED
> [INFO] integration-test ................................... SKIPPED
> [INFO] client ............................................. SUCCESS [16:26 min]
> [INFO] Hosted Vespa tenant CD API ......................... SUCCESS [03:53 min]
> [INFO] hosted-api ......................................... SKIPPED
> [INFO] tenant-cd-commons .................................. SKIPPED
> [INFO] Vespa Cloud tenant CD implementation ............... SKIPPED
> [INFO] vespa-http-client .................................. SUCCESS [  01:12 h]
> [INFO] vespaclient-container-plugin ....................... SKIPPED
> [INFO] container .......................................... SKIPPED
> [INFO] container-test ..................................... SKIPPED
> [INFO] Base pom for all tenant base poms .................. SKIPPED
> [INFO] Vespa Cloud tenant base ............................ SKIPPED
> [INFO] cloud-tenant-base-dependencies-enforcer ............ SKIPPED
> [INFO] clustercontroller-utils ............................ SUCCESS [11:00 min]
> [INFO] clustercontroller-core ............................. SKIPPED
> [INFO] clustercontroller-apps ............................. SKIPPED
> [INFO] clustercontroller-reindexer ........................ SKIPPED
> [INFO] fat-model-dependencies ............................. SKIPPED
> [INFO] config-model-fat ................................... SKIPPED
> [INFO] filedistribution ................................... SKIPPED
> [INFO] config-proxy ....................................... SKIPPED
> [INFO] configserver-flags ................................. SKIPPED
> [INFO] serviceview ........................................ SKIPPED
> [INFO] configserver ....................................... SKIPPED
> [INFO] config_test ........................................ SUCCESS [02:02 min]
> [INFO] container-dependencies-enforcer .................... SKIPPED
> [INFO] container-integration-test ......................... SKIPPED
> [INFO] bundle-with-provided-bundle ........................ SUCCESS [  7.933 s]
> [INFO] controller-api ..................................... SKIPPED
> [INFO] jdisc-security-filters ............................. SKIPPED
> [INFO] controller-server .................................. SKIPPED
> [INFO] docker-api ......................................... SKIPPED
> [INFO] docprocs ........................................... SKIPPED
> [INFO] Vespa DocumentGen Plugin ........................... SKIPPED
> [INFO] documentgen_test ................................... SKIPPED
> [INFO] integration-test-parent ............................ SUCCESS [  2.198 s]
> [INFO] test_bundles ....................................... SUCCESS [ 24.209 s]
> [INFO] app-a .............................................. SUCCESS [07:28 min]
> [INFO] app-b-priv ......................................... SUCCESS [07:27 min]
> [INFO] cert-a ............................................. SUCCESS [04:05 min]
> [INFO] app-ca ............................................. SUCCESS [04:42 min]
> [INFO] cert-j-priv ........................................ SUCCESS [03:32 min]
> [INFO] app-dj ............................................. SUCCESS [04:39 min]
> [INFO] app-ej-priv ........................................ SUCCESS [04:43 min]
> [INFO] app-f-more ......................................... SUCCESS [04:42 min]
> [INFO] app-g-act .......................................... SUCCESS [05:14 min]
> [INFO] app-h-log .......................................... SUCCESS [04:41 min]
> [INFO] cert-b ............................................. SUCCESS [02:10 min]
> [INFO] cert-ca ............................................ SUCCESS [04:40 min]
> [INFO] cert-dc ............................................ SUCCESS [04:40 min]
> [INFO] cert-eab ........................................... SUCCESS [04:38 min]
> [INFO] cert-fac ........................................... SUCCESS [04:37 min]
> [INFO] cert-gg ............................................ SUCCESS [03:18 min]
> [INFO] cert-hi ............................................ SUCCESS [03:22 min]
> [INFO] cert-ih ............................................ SUCCESS [03:22 min]
> [INFO] cert-k-pkgs ........................................ SUCCESS [08:20 min]
> [INFO] cert-l1 ............................................ SUCCESS [04:15 min]
> [INFO] cert-l1-dup ........................................ SUCCESS [04:14 min]
> [INFO] cert-l2 ............................................ SUCCESS [04:17 min]
> [INFO] cert-ml ............................................ SUCCESS [05:32 min]
> [INFO] cert-ml-dup ........................................ SUCCESS [05:34 min]
> [INFO] cert-nac ........................................... SUCCESS [04:34 min]
> [INFO] cert-oa-path ....................................... SUCCESS [04:38 min]
> [INFO] cert-p-jar ......................................... SUCCESS [01:46 min]
> [INFO] cert-q-frag ........................................ SUCCESS [03:25 min]
> [INFO] cert-rq ............................................ SUCCESS [04:44 min]
> [INFO] cert-s-act ......................................... SUCCESS [04:41 min]
> [INFO] cert-tp ............................................ SUCCESS [04:42 min]
> [INFO] cert-us ............................................ SUCCESS [04:42 min]
> [INFO] my-bundle-activator ................................ SUCCESS [04:51 min]
> [INFO] my-guice-module .................................... SUCCESS [05:29 min]
> [INFO] my-server-provider ................................. SUCCESS [05:19 min]
> [INFO] integration_test ................................... SUCCESS [05:13 min]
> [INFO] logserver .......................................... FAILURE [01:15 min]
> [INFO] node-admin ......................................... SKIPPED
> [INFO] predicate-search ................................... SUCCESS [25:13 min]
> [INFO] security-tools ..................................... SUCCESS [06:03 min]
> [INFO] socket_test ........................................ SUCCESS [05:56 min]
> [INFO] vespa-maven-plugin ................................. SKIPPED
> [INFO] Hosted Vespa tenant base ........................... SKIPPED
> [INFO] vespaclient-java ................................... SKIPPED
> [INFO] vespa-hadoop ....................................... SKIPPED
> [INFO] vespa-osgi-testrunner .............................. SKIPPED
> [INFO] vespa-testrunner-components ........................ SKIPPED
> [INFO] vespa_feed_perf .................................... SKIPPED
> [INFO] zookeeper-command-line-client ...................... SUCCESS [06:45 min]
> [INFO] zookeeper-server-3.5.6 ............................. SKIPPED
> [INFO] zookeeper-server-3.6.2 ............................. SKIPPED
> [INFO] vespa .............................................. SUCCESS [  7.742 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  04:37 h (Wall Clock)
> [INFO] Finished at: 2021-01-11T10:52:35Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.6.0.2:run (default) on project logserver: Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.6.0.2:run failed: unknown os.arch: riscv -> [Help 1]

Here is my environment:
> $ java -version && javac -version
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10-202007292333)
> Eclipse OpenJ9 VM AdoptOpenJDK (build master-dc7cbe4bd, JRE 11 Linux riscv-64-Bit Compressed References 20200729_78 (JIT disabled, AOT disabled)
> OpenJ9   - dc7cbe4bd
> OMR      - 1c0299f20
> JCL      - 94b9d6d2c6 based on jdk-11.0.8+10)
> javac 11.0.8

> $ cat /proc/cpuinfo
> processor	: 0
> hart		: 1
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 1
> hart		: 2
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 2
> hart		: 3
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 3
> hart		: 4
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0

> $ uname -a
> Linux test-gdams-debian10-riscv64-1.adoptopenjdk.net 5.0.0-rc1-56210-g0a657e0d72f0 #1 SMP Fri May 15 18:05:26 EDT 2020 riscv64 GNU/Linux

**Comment by kkraune** [comment]
I am not sure why the log server has requirements that differ from the other modules, Arne?

**Comment by kkraune** [comment]
protoc-jar-maven-plugin was added for protobuf support it seems, assigning to @bjorncs

**Comment by kkraune** [comment]
@advancedwebdeveloper is protoc-jar-maven-plugin available for this platform / can you help find out? We do not have an environment for building this

**Comment by advancedwebdeveloper** [comment]
@os72 , please add your 50 cents here

**Comment by os72** [comment]
protoc-jar-maven-plugin is "available" because it's java. but it's still just a wrapper around native platform-specific protoc binaries (afaik no pure java impl of protoc exists). i host a few such contributed special builds on maven central, which the plugin downloads automatically. so it all works automated, as long as a suitable binary exists

**Comment by advancedwebdeveloper** [comment]
you did not explain how to build those binaries

**Comment by advancedwebdeveloper** [comment]
I had to build the .jar file (for each of two dependencies) and install it locally, for Maven.

Vespa was built and tests where successful - while those are surely not all the possible test suites.
Looks like that is a question of hosting Maven's mirrors and sharing .jar files (for RISC-V arch).
If there is no global demand, as for now - Vespa's maintainers could configure alternative mirrors, specially for RISC-V.

**Comment by advancedwebdeveloper** [comment]
Looks like protobuf's version is 3.7.0 - compiled that easily (both C++ and Java tools).
