### ISSUE TITLE
Simple support for replacing OR by WAND

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#16360]
Most that do OR queries over text end up wanting to use WAND for performance, but switching to that is a bit of work.
This can be made easier by creating a searcher which replaces OrItems over text indexes by WeakAndItems.
This could be included as a noop by default (in the 'local' chain) and activated by a query parameter.

**Comment by jobergum** [comment]
Also relates to https://github.com/vespa-engine/vespa/issues/13076

**Comment by johans1** [comment]
Done
