### ISSUE TITLE
basic-search-on-gke is broken

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#16379]
the gke sample is broken, the entries in hosts.xml are off-by-one so the app doesn't get deployed everywhere - and because the service only points at the one node, only one container node is actually used so the error isn't noticed

Just here https://github.com/vespa-engine/sample-apps/blob/master/basic-search-on-gke/scripts/boostrap.sh#L29 -- they hostnames will start at `vespa-content-1.vespa-internal, but in a StatefulSet the first host name will be vespa-content-0

also, in this example the service makes the admin node available to public internet, which is fine (?) for the example but I think it should be made abundantly clear that this shouldn't be done - e.g. linking to the docs on security

**Comment by kkraune** [comment]
@griseau can you have a look at this (reported from a user)? thanks

**Comment by griseau** [comment]
Hey @kkraune, I'll try to have a look at it at the end of the day, I'll get back to you

**Comment by griseau** [comment]
@kkraune I made a PR to fix it, didn't had time to deploy but the config files looks better. Don't hesitate if you have any question !

**Comment by kkraune** [comment]
Much appreciated, thanks @griseau ! I will sync with the reporter of this problem to verify
