### ISSUE TITLE
Add batch POST to /document/v1/ api

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#16713]
While we wait for the fantastic new http 2 asynch api which allows feeding with high throughput from any type of client I'm thinking we could add a short time optimization allowing feeding batches of operations per http request. Api still synchronous and the reply contains the status of each operation accepted, but feed throughput will drastically improve. 

Today we allow a single operation :

```
POST /document/v1/demo/some-schema/docid/0
{
"fields": {}
}
```

We should consider add support for POST and PUT multiple 
```
POST /document/v1/demo/some-schema/
{
"put": "id:demo:some-schema::0",
"fields": {}
}, 
{
"put": "id:demo:some-schema::1",
"fields": {}
},
{
"update": "id:demo:some-schema::2",
"fields": {}
}
```

**Comment by frodelu** [comment]
This would require us to design and implement a new response API to show error codes per id, etc. Would instead like to implement a proper HTTP/2 based API sooner rather than later that solves this the correct way.
