### ISSUE TITLE
Support HTTP/2 in jdisc

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#16780]
HTTP/2 allows more efficient use of connections; client may send multiple requests in parallel over a single HTTP/2 connection. This allows for simpler client implementations (e.g vespa-http-client) and fewer connections overall on our routing layer for hosted Vespa.

Jetty 9.4 already supports running HTTP/1.1 and HTTP/2 over the same connector (using TLS ALPN), although some HTTP/2 functionality may require upgrading Jetty to 10/11.

**Comment by bjorncs** [comment]
Vespa jdisc container supports HTTP/2 from 7.425
See documentation and blog post details:

- https://docs.vespa.ai/en/performance/http2.html
- https://blog.vespa.ai/http2/
