### ISSUE TITLE
YQL string / query API builder

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#16874]
The querybuilder linked from https://docs.vespa.ai/en/vespa-quick-start.html is a bit basic.
 
Build better support for making valid YQL query strings by using a dynamic form. Split the YQL string in logically separate parts
 
(for queries, use a higher timeout, so first query is 200 OK - it seems it times out first time, bad user experience)

**Comment by sbourke** [comment]
@kkraune  Couuld you expand at all on this ? I'm looking at it as part of the hacktogether.

**Comment by kkraune** [comment]
Hi @sbourke !

http://localhost:8080/querybuilder/ is not very helpful to aid the user in building the YQL query string, ref https://docs.vespa.ai/en/query-language.html (YQL)

It would be great having a tool that looks at the schema(s) so field and schema names are known, and maybe generate an example to work from, ref the examples in https://docs.vespa.ai/en/query-language.html. generate a UI based on the available fields, maybe? think of what would make it easy for you to get started writing queries to Vespa

**Comment by kkraune** [comment]
New query builder available at https://github.com/vespa-engine/vespa/tree/master/client/js/app
