### ISSUE TITLE
How to build a new rankprofile in yql

### ISSUE THREAD

**Issue by DongHaotian97** [vespa-engine/vespa#16967]
I noticed that by using pyvespa its easy to build a new rankprofile when building yql like that:
![image](https://user-images.githubusercontent.com/41029582/111253395-16061300-864e-11eb-9966-0515d20d45a7.png)
But if we are using c++ to send the yql to vespa, is it possible to send a new rankprofile to vespa in yql?
Thanks for your reply

**Comment by DongHaotian97** [comment]
I think I misunderstood the usage of the pyvespa method and We must deploy after creating a new rankprofile

**Comment by bratseth** [comment]
Yes, ranking expressions are compiled in various ways and it would in general be too slow to send them with the query.
