### ISSUE TITLE
Add support for int8 and bfloat16 tensor type

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#17118]
Today we support double (8 bytes) and float (4 bytes) but we can observe that number of parameters is more important than precision used for the weights/data so many models uses int8 (1byte) and bfloat16 (2 bytes) instead without significant drop in accuracy but with a significant speedup and lowered memory resource.  Example of model which will greatly benefit from this is the ColBERT model described in https://github.com/vespa-engine/vespa/issues/15854 

Today using float
```
 field dt type tensor<float>(dt{}, x[32]){
      indexing: summary | attribute
    }
```
```
field dt type tensor<int8>(dt{}, x[32]){
      indexing: summary | attribute
    }
```
Would reduce memory footprint of the dt tensor by a factor of 4.

**Comment by kkraune** [comment]
As the documentation is live, it this issue ready to be closed?

**Comment by geirst** [comment]
Support for int8 and bfloat16 tensor types is part of 7.407.36 (late May 2021).
Relevant documentation:
- https://docs.vespa.ai/en/reference/tensor.html
- https://docs.vespa.ai/en/tensor-user-guide.html#bfloat16
- https://docs.vespa.ai/en/tensor-user-guide.html#int8

The int8 type can be fed using a new hex format: 
- https://docs.vespa.ai/en/reference/document-json-format.html#tensor-hex-dump
- https://github.com/vespa-engine/system-test/blob/master/tests/search/tensor_feed/tensor_feed_hex.rb

It can also be used in combination with the _hamming_ distance metric when using nearest neighbor search:
- https://docs.vespa.ai/en/reference/schema-reference.html#distance-metric
