### ISSUE TITLE
Docker vespa-dev-centos7: Unable to SSH into the container

### ISSUE THREAD

**Issue by rharige** [vespa-engine/vespa#17208]
Following the Linux guide at https://hub.docker.com/r/vespaengine/vespa-dev-centos7 - I am unable to SSH into the container with the given command:
```
ssh -A 127.0.0.1 -p 3334
```
This step failed with the message: "Permission denied, please try again."

### Environment
Ubuntu 20.04.2 LTS. It's a new guest VM in MacOS 11.2.3. 

### Other Issues 
The only other issue I faced before this SSH step, was on `docker create.. ` command. I kept getting `docker: Got permission denied while trying to connect to the Docker daemon socket at ..` message. I fixed this issue by running:
```
newgrp docker
```
after 
```
sudo groupadd docker
sudo usermod -aG docker $(id -un)
sudo systemctl restart docker
```

**Comment by kkraune** [comment]
Work note: Asked reporter to test with Docker on Mac and report detailed errors. removing entries in .ssh/known_hosts can help, depending on error

**Comment by kkraune** [comment]
work note: issue found, reporter will make a PR
