### ISSUE TITLE
document-summary not including array of complex type

### ISSUE THREAD

**Issue by lundin** [vespa-engine/vespa#17214]
Hi!

On current vespa-cloud (7.381.20) and epel-7 repo i cant add a document-summary with a array of complex type

for example below sd config is used:
https://gist.github.com/lundin/6b77971108cf3065def2540fc365c400

is not including the "techattributetree_all" field that was expected when query with: 
{
    "presentation": {
        "summary": "short"
    },
    "yql": "select * from articles where sku matches (\"32222081\");"
}

But the field alltecdoc  (of type array string) is added. So is sku, simple string, etc. Also matched-element-only does work for a array complextype but not when you want the field added in full to the summary as above. 

Removing the summary and select the techattributetree does indeed return the field so the document has it, it is just when used as a field in summary.
Also tried struct-field adding as attribute/index etc but did not help.
Thanks!

**Comment by geirst** [comment]
We have reproduced this issue. It occurs when a complex field (e.g. array of struct or map) is used in an explicit document summary with another name than it originally has. It happens for both summary only fields (_complex_ in the example below) and fields that use struct field attributes (_complex_attr_ in the example below).

Assume the given schema:
```
schema test {
    document test {
        struct my_struct {
            field name type string {}
            field value type string {}
        }
        field complex type array<my_struct> {
            indexing: summary
        }
        field complex_attr type array<my_struct> {
            indexing: summary
            struct-field name { indexing: attribute }
            struct-field value { indexing: attribute }
        }
    }
    document-summary basic {
        from-disk
        summary complex type array<my_struct> { }
        summary complex_attr type array<my_struct> { }
    }
    document-summary rename {
        from-disk
        summary new_complex type array<my_struct> { source: complex }
        summary new_complex_attr type array<my_struct> { source: complex_attr }
    }
}
```
In the _basic_ summary, the fields use the same name as in the document schema. This works as expected. In the _rename_ summary however, we rename the fields. This case is currently not working, and the query response doesn't contains these fields (they are empty).

@lundin The short term solution is to _not_ rename such fields in the explicit document summary. We will also work on a fix for this issue.

**Comment by lundin** [comment]
Thanks for that @geirst ! The one problem i encountered with using the quick fix with same name/no renaming is that had the field  in multiple summaries with different transform, i.e one with matched-element-only and one without and got "A field with the same name can not have different transforms in different summary classes"

But anyway, i removed the matched-element-only and made the filtering in the searcher instead.

Thanks!
