### ISSUE TITLE
Multinode set up - Readiness probe/env VESPA_CONFIGSERVER

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#17398]
Could you please suggest for below.

1) What should be the readiness probe url for configserver, stateless and content in multi-node set up?
    configserver : http://<configserver fqdn>:19071/ApplicationStatus
    stateless : http://<stateless container fqdn>:8080/ApplicationStatus
    content : ??
Does above make sense and what should be for content container?

2)  If more configserver is to be spin up post initial set up, how can the existing scaled containers get the env VESPA_CONFIGSERVER updated. Is it by updating config map with comma separated config server host and restart of all the existing containers?
example: 
current set up 1 configserver, 2 stateless and 2 content have a config map with VESPA_CONFIGSERVER=fqdn of configserver 1. the value of VESPA_CONFIGSERVER with single host is exported in all containers when they start. 
Now arises a need to increment configserver from 1 to 2. new set up 2 configserver, 2 stateless and 2 content. 
SI below mentioned steps the only way or there is a better way?
 - update config map VESPA_CONFIGSERVER=<configserver 1 fqdn>,<configserver 2 fqdn>
 - restart all the already existing pods for above env value to be exported as env variable.

**Comment by bratseth** [comment]
1: You can use state/v1 instead of ApplicationStatus on all services.
2: Yes.

**Comment by hmusum** [comment]
2. I have improved the doc at https://docs.vespa.ai/en/cloudconfig/configuration-server.html that describes scaling up or down a config server cluster, please have a look.

**Comment by abhimech001** [comment]
> 1. I have improved the doc at https://docs.vespa.ai/en/cloudconfig/configuration-server.html that describes scaling up or down a config server cluster, please have a look.

Thank you!!!
A quick one wrt to scaling up
it says "Add config server nodes for increased fault tolerance. There is no need to restart Vespa on other nodes during the procedure - "

how will the existing running containers like stateless and content be able to update env variable VESPA_CONFIGSERVER with new config server without restart as the env variable are set at start up only? Is this possible without restart also?

**Comment by hmusum** [comment]
The doc is ambiguous, I will clean it up, thanks for noticing. Please disregard that sentence and follow the step by step procedure.

**Comment by abhimech001** [comment]
> 1: You can use state/v1 instead of ApplicationStatus on all services.
> 2: Yes.

Thank You!!
what port should be used for readiness probe of content cluster to establish content container is up and running?
complete url will help.

**Comment by hmusum** [comment]
We use dynamic ports for content services, so you need to figure out which port is used in your setup. If you run `vespa-model-inspect service searchnode` on one of your nodes you will want to use the port tagged with `(STATE HEALTH JSON HTTP)` (assuming setup is the same on all your content nodes).

**Comment by abhimech001** [comment]
> We use dynamic ports for content services, so you need to figure out which port is used in your setup. If you run `vespa-model-inspect service searchnode` on one of your nodes you will want to use the port tagged with `(STATE HEALTH JSON HTTP)` (assuming setup is the same on all your content nodes).

Awesome. Thank you yet again for quick response.

**Comment by abhimech001** [comment]
Hi

While reading through the document I found a page https://docs.vespa.ai/en/operations/admin-procedures.html where it shows how to set a metrics dashboard for cluster controller http://hostname:port/clustercontroller-status/v1/<clustername> which gives consolidated view of all storage and distributor from all nodes.
Is there a way to set up something like above for searchnode, storagenode services where it gives consolidated view of health, metrics, config etc of all nodes at one place

**Comment by kkraune** [comment]
&gt; consolidated view ...

You will find some of this in the console in Vespa Cloud (you can explore using the free trial) - vespa.ai does not have a consolidated view of other node types
