### ISSUE TITLE
vespa-visit - Data sync from one cluster to other

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#17634]
Hi Team,

I have created two multinode cluster in kubernetes cluster 1 and 2
Now, I am trying to migrate using vespa visit from cluster 1 to cluster 2 referring to document https://docs.vespa.ai/en/content/visiting.html

Kubernetes cluster 2 : 
3 Config server, 3 Stateless, 3 Content
Cluster MusicTest is created with no data
Created service on Config server at port 19071 and http proxy on top of this service

Kubernetes cluster 1 : 
3 Config server, 3 Stateless, 3 Content
Cluster music is created and data is ingrested
Created service on Config server at port 19071 and http proxy on top of this service
fired below from vespa config server ## Limit to 'music' documents only##to sync data from Kubernetes cluster 1 music to Kubernetes cluster 2 MusicTest
vespa-visit --datahandler '[Content:config=tcp/<proxy on config server of kubernetes cluster 2 myconfigserver.mydomain.com:80>;cluster=<cluster MusicTest on kubernetes cluster 2 ]'  --selection music

On doing above we got error and unable to sync data from cluster 1 to cluster 2
Visitor error [content node 1] Node not ready : waiting to initialize policy
Error when creating policy. ConfigTimeoutException: Timed out while subscribing to 'cloud.config.slobroks','configid admin/slobrok.0'

**Comment by kkraune** [comment]
Hi,

As this is a quite complex operation, I would break it down as follows:

1: make sure the visit command works in the source cluster (cluster 1): vespa-visit -i --selection music | head 

-i is just to dump ids, for less output when debugging
you can run the vespa-visit command in any node in the cluster

2: make sure the target cluster is up and running well. the same vespa-visit command should return OK when run in cluster 2 with no errors and no data if the cluster is empty

3: then, in the source cluster, run a visit, but send documents to the target cluster (cluster 2). Your command looks ok, so I suspect it is a connectivity issue. make sure you can connect on all ports needed between the clusters. Use https://docs.vespa.ai/en/reference/vespa-cmdline-tools.html#vespa-model-inspect to dump active services / ports, and make sure ports to config servers, slobroks and content nodes are available ("telnet host port" to check connections)

**Comment by kkraune** [comment]
sorry for slow response. I have discussed with @vekterli - we are not sure if the --datahandler is supported with the use of a proxy - we have never tested for this case. Note that you must check connectivity for the "slobrok" service

I think you are better off using visit in /document/v1: https://docs.vespa.ai/documentation/reference/document-v1-api-reference.html. Use https://cloud.vespa.ai/en/dumping-data.html as inspiration for how to iterate over the data set, and let me know how this goes :-)

**Comment by bratseth** [comment]
That's on our roadmap but it won't be ready in a while yet.

**Comment by baldersheim** [comment]
Data/indexes are redistributed automatically if nodes fail, or you add or remove nodes.
See https://vespa.ai/features#operability-and-data-management

**Comment by kkraune** [comment]
As "music" and "movie" is stored in the same content cluster, both will be stored in the same 6-node cluster after scaling it up

If you want to separate, you must configure two content clusters, with "music" in one and "movie" in the other. Then use visiting as discussed to dump document from the shared cluster and feed to the new dedicated content cluster.

This makes sense if you need to scale the clusters independently - that is often not the case, so consider the tradeoff
