### ISSUE TITLE
Centralized logging

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#17654]
Hi Team,

I have defined one of the config server as logserver from services.xml of application xml.
Current set up 1 config server(which is also admin and logserver defined via service.xml of application), 3 container and 3 content node.

As per https://docs.vespa.ai/en/reference/files-processes-and-ports.html logd is responsible for shipping logs from all nodes to central logserver which is my config server in this case

logd | All nodes | **19089** | $VESPA_HOME/sbin/vespa-logd | **Reads local log files and sends them to log server**

Checked 19089 port within config server, all 3 container and 3 content server

netstat -plant|grep -i 19089
tcp              0                0.0.0.0.0:19089             0.0.0.0 :*            LISTEN             <pid>/sbin/vespa-logd

Is it enough to say logd is started in all server and will ship logs to central logserver?
If yes then where can I find logs of all node within defined logserver(config server is defined as logserver via service.xml of application) so that I can centrally check logs of all node from one server.

**Comment by kkraune** [comment]
per https://docs.vespa.ai/en/reference/logs.html: The log files are located in the $VESPA_HOME/logs/vespa/logarchive directory

> Is it enough to say logd is started in all server and will ship logs to central logserver?
Yes, logd processes will forward logs to the log server, no config needed

**Comment by abhimech001** [comment]
> per https://docs.vespa.ai/en/reference/logs.html: The log files are located in the $VESPA_HOME/logs/vespa/logarchive directory
> 
> > Is it enough to say logd is started in all server and will ship logs to central logserver?
> 
> Yes, logd processes will forward logs to the log server, no config needed

Thanks You for the reply!!!

I have checked archive folder of logserver but it only writes logs of vespa.log from each node to logserver 
What @ request and response logs which are generated in container node at ($VESPA_HOME/logs/vespa/qrs/Json*), are they not shipped to central logserver ?

**Comment by kkraune** [comment]
correct, access logs are not forwarded
