### ISSUE TITLE
Vespa not able to start the content node on Azure File mount in Kubernetes even though the drives are mounted properly.

### ISSUE THREAD

**Issue by labriedion** [vespa-engine/vespa#17825]
I've been able to run apps in Azure Kubernetes Services but Vespa fails to start when I mount /opt/vespa/var to a persistent volume. The Azure file mounts work since logs and files are written inside them when deploying the pod. Basically everything seems fine when deploying the pods, and I get no error messages when I run:

`kubectl exec vespa-0 -n vespa -- bash -c "/opt/vespa/bin/vespa-deploy prepare /vespa-app && /opt/vespa/bin/vespa-deploy activate"`

But we I try to load data or reach documents at http:/myip:8080/document/v1/{mynamespace}/{mydocumenttype}/docid/1, the connection times out. 

I think I located the error in the logs, it seems like content cluster can't even start.

> 1620740689.020670	vespa-0.vespa.vespa.svc.cluster.local	1574/5916	searchnode	proton.transactionlog.server	warning	Failed creating tickets domain. Exception = IoException: NO PERMISSION: sync(tls/tls/tls.domains.tmp): Failed, errno(13): Permission denied at sync in /builddir/build/BUILD/vespa-7.398.17/vespalib/src/vespa/vespalib/io/fileutil.cpp:408\nBacktrace:\n  /opt/vespa/lib64/libvespalib.so(vespalib::IoException::IoException(vespalib::stringref, vespalib::IoException::Type, vespalib::stringref, int)+0x41) [0x7f53cc1c7c71]\n  /opt/vespa/lib64/libvespalib.so(+0x1be077) [0x7f53cc073077]\n  /opt/vespa/lib64/libvespalib.so(vespalib::File::sync(vespalib::stringref)+0x36) [0x7f53cc102ae6]\n  /opt/vespa/lib64/libsearchlib.so(+0xaf46a7) [0x7f53ce3e26a7]\n  /opt/vespa/lib64/libsearchlib.so(search::transactionlog::TransLogServer::createDomain(FRT_RPCRequest*)+0x654) [0x7f53ce3e39b4]\n  /opt/vespa/lib64/libsearchlib.so(search::transactionlog::TransLogServer::run()+0x35b) [0x7f53ce3e401b]\n  /opt/vespa/lib64/libstaging_vespalib.so(document::Runnable::Run(FastOS_ThreadInterface*, void*)+0x50) [0x7f53cc3321d0]\n  /opt/vespa/lib64/libfastos.so(FastOS_ThreadInterface::Hook()+0x125) [0x7f53cbe92e85]\n  /opt/vespa/lib64/libfastos.so(FastOS_ThreadHook+0x9) [0x7f53cbe93019]\n  /opt/vespa/lib64/vespa/malloc/libvespamalloc.so(+0x6a4b) [0x7f53cf7a0a4b]\n  /lib64/libpthread.so.0(+0x7ea5) [0x7f53cba59ea5]\n  /lib64/libc.so.6(clone+0x6d) [0x7f53c3fc79fd]
1620740689.055689	vespa-0.vespa.vespa.svc.cluster.local	1574	searchnode	stderr	warning	terminate called after throwing an instance of 'std::runtime_error'
1620740689.086873	vespa-0.vespa.vespa.svc.cluster.local	1574	searchnode	stderr	warning	  what():  Failed creating domain 'tickets' on TLS 'tcp/vespa-0.vespa.vespa.svc.cluster.local:19111'
1620740689.272948	vespa-0.vespa.vespa.svc.cluster.local	1228/29549	config-sentinel	config-sentinel.service	event	crash/1 name="searchnode" pid=1574 signal="Aborted"

I tried to set mountOptions in Kubernetes such as:

>   mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - mfsymlinks
    - nobrl
    - uid=0
    - gid=0
    
 But nothing seems to fix it. 
 
 I think this could be an issue with Azure File similar to this one: https://github.com/MicrosoftDocs/azure-docs/issues/16481
 
 Any help would be very much appreciated. Thanks.

**Comment by baldersheim** [comment]
Have you verified the limitations in https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files ?
I would assume especially "Azure file share volume mount requires the Linux container run as root ." is important.

**Comment by labriedion** [comment]
Hi @baldersheim, yeah, I did try running the container as root as such when starting the node:

>     spec:
>       securityContext:
>         runAsUser: 0
>         runAsGroup: 0

'0' being root user and group. Unfortunately it didn't work. 

The good news though is that I spoke with @andreer in your public Slack and I realized that I don't actually need to use Azure File. See, I was under the impression that I needed to have my storage mounted as "ReadWriteMany " so that the storage could be shared between nodes. Azure File is the only way to do that in Azure.

But I apparently don't need to do that and can simply spin up Azure Disks mounted as "ReadWriteOnce" for each node, since the Vespa nodes will share the content themselves. Azure Disks mounted as ReadWriteOnce do work for me without issue, so I can go forward with my deployment.

The issue still stands with Azure File, but it seems like a non-starter since this is not needed, so you could close it if you want. 

Thanks for your help!

**Comment by baldersheim** [comment]
We made the error on sync non fatal. That might help figuring out what the root cause really is. That will be present in the next release.

**Comment by geirst** [comment]
Error on sync not being fatal is part of Vespa 7.404.14.

**Comment by labriedion** [comment]
For posterity and if someone comes across a similar issue, I spoke with Azure support and they suggested I try creating the storage with the Azure Files Container Storage Interface https://docs.microsoft.com/en-us/azure/aks/azure-files-csi. 

They also suggested trying a different storage protocol or file system type when setting up Azure File through the CSI: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#dynamic-provision

I haven't tried it since I don't have this problem anymore.
