### ISSUE TITLE
PaxHeader files in app package tarball fails deployment

### ISSUE THREAD

**Issue by AdamBelive** [vespa-engine/vespa#17837]
![image](https://user-images.githubusercontent.com/83591309/117989633-7c37ab00-b30a-11eb-8902-3d2c31e38322.png)
While doing the quick start tutorial, I did it following the guide and it work. Then, I opened the files to see what were in them (album-recommendation-selfhosted) and retried the quick start guide but an error appeared.
As you can see in this screenshot, "._root.xml" is trying to be parsed but the prefix ._ is causing the parser to throw.

**Comment by kkraune** [comment]
Work notes:

https://github.com/vespa-engine/sample-apps/blob/master/album-recommendation-selfhosted/src/main/application/search/query-profiles/types/root.xml has the correct name.

I then followed the steps in https://docs.vespa.ai/en/vespa-quick-start.html - all worked fine

Can you please check this?

`$ ls -la src/main/application/search/query-profiles/types/
total 8
drwxr-xr-x  3 kraune  staff   96 May 12 17:22 .
drwxr-xr-x  4 kraune  staff  128 May 12 17:22 ..
-rw-r--r--  1 kraune  staff  614 May 12 17:22 root.xml`

**Comment by AdamBelive** [comment]
Here's the output:

drwxr-xr-x  3 ADAM  1000   96 12 May 12:54 .
drwxr-xr-x  5 ADAM  1000  160 12 May 12:56 ..
-rw-r--r--@ 1 ADAM  1000  614 12 May 12:54 root.xml

I believe it's the sam

**Comment by kkraune** [comment]
interesting! so either there is something wrong with the tar / gzip combo, or something breaks on the vespa size when unzipping. I hope you can help by just creating the tar file / untar it and see - and maybe zip the tar file and make it available for our download?

**Comment by AdamBelive** [comment]
here the zip tar file : [application.tar.gz](https://github.com/vespa-engine/vespa/files/6468236/application.tar.gz)

**Comment by kkraune** [comment]
thanks! the archive looks right. looking at options ...

**Comment by kkraune** [comment]
I am able to replicate:

$ curl --header Content-Type:application/x-gzip --data-binary @/Users/kraune/Downloads/application.tar.gz localhost:19071/application/v2/tenant/default/prepareandactivate

{"error-code":"INVALID_APPLICATION_PACKAGE","message":"Invalid application package: default.default: Error loading model: Could not parse '._root.xml', error at line 1, column 1: Content is not allowed in prolog."}

just curious: can you try using zip instead of gzip (ref https://cloud.vespa.ai/en/getting-started for how to create the zip) - and deploy with Content-Type:application/zip ?

**Comment by kkraune** [comment]
CC @jonmv / @hmusum https://docs.vespa.ai/en/cloudconfig/deploy-rest-api-v2.html

**Comment by AdamBelive** [comment]
![image](https://user-images.githubusercontent.com/83591309/118028718-65f11580-b331-11eb-84fd-cda113744484.png)
I think that's what you wanted me to do?

**Comment by kkraune** [comment]
not really, you have to create the .zip file as in the cloud guide and POST it like

curl --header Content-Type:application/zip --data-binary @application.zip localhost:19071/application/v2/tenant/default/prepareandactivate

**Comment by AdamBelive** [comment]
it worked!

**Comment by AdamBelive** [comment]
Thanks for the help!

**Comment by kkraune** [comment]
great news! I will keep this ticket open for my own investigation to compare the tar files. Thanks for reporting!

**Comment by kkraune** [comment]
diff-ing your and my tar files:

````
$ diff --test err/e.tar ok/o.tar 
diff: unrecognized option `--test'
diff: Try `diff --help' for more information.
C02DR9A6MD6R:tmp kraune$ diff --text err/e.tar ok/o.tar 
1c1
< ./000755 000766 000024 00000000000 14051477055 011654 5ustar00kraunestaff000000 000000 ./hosts.xml000644 000766 000024 00000000623 14047004143 013524 0ustar00kraunestaff000000 000000 <?xml version="1.0" encoding="utf-8" ?>
---
> ./000755 000766 000024 00000000000 14051476363 011655 5ustar00kraunestaff000000 000000 ./hosts.xml000644 000766 000024 00000000623 14051476363 013540 0ustar00kraunestaff000000 000000 <?xml version="1.0" encoding="utf-8" ?>
17c17
< ./services.xml000644 000766 000024 00000004652 14047004143 014215 0ustar00kraunestaff000000 000000 <?xml version="1.0" encoding="utf-8" ?>
---
> ./services.xml000644 000766 000024 00000004652 14051476363 014231 0ustar00kraunestaff000000 000000 <?xml version="1.0" encoding="utf-8" ?>
81c81
< ./schemas/000755 000766 000024 00000000000 14047004143 013264 5ustar00kraunestaff000000 000000 ./search/000755 000766 000024 00000000000 14051476221 013113 5ustar00kraunestaff000000 000000 ./search/query-profiles/000755 000766 000024 00000000000 14051476237 016110 5ustar00kraunestaff000000 000000 ./search/query-profiles/types/000755 000766 000024 00000000000 14047004143 017240 5ustar00kraunestaff000000 000000 ./search/query-profiles/default.xml000644 000766 000024 00000000753 14047004143 020247 0ustar00kraunestaff000000 000000 <!-- Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
---
> ./schemas/000755 000766 000024 00000000000 14051476363 013300 5ustar00kraunestaff000000 000000 ./search/000755 000766 000024 00000000000 14051476363 013122 5ustar00kraunestaff000000 000000 ./search/query-profiles/000755 000766 000024 00000000000 14051476363 016110 5ustar00kraunestaff000000 000000 ./search/query-profiles/types/000755 000766 000024 00000000000 14051476363 017254 5ustar00kraunestaff000000 000000 ./search/query-profiles/default.xml000644 000766 000024 00000000753 14051476363 020263 0ustar00kraunestaff000000 000000 <!-- Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
93,94c93
< ./search/query-profiles/types/._root.xml000644 000766 000024 00000000260 14047004143 021160 0ustar00kraunestaff000000 000000 Mac OS X        	2~?ATTR???com.apple.lastuseddate#PS?`ă?./search/query-profiles/types/PaxHeader/root.xml000644 000766 000024 00000000035 14047004143 022714 xustar00kraunestaff000000 000000 29 mtime=1620838499.50353989
< ./search/query-profiles/types/root.xml000644 000766 000024 00000001146 14047004143 020747 0ustar00kraunestaff000000 000000 <!-- Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
---
> ./search/query-profiles/types/root.xml000644 000766 000024 00000001146 14051476363 020763 0ustar00kraunestaff000000 000000 <!-- Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
107c106
< ./schemas/music.sd000644 000766 000024 00000002264 14047004143 014740 0ustar00kraunestaff000000 000000 # Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
---
> ./schemas/music.sd000644 000766 000024 00000002264 14051476363 014754 0ustar00kraunestaff000000 000000 # Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
148c147
< 
\ No newline at end of file
---
> 
\ No newline at end of file
````

**Comment by kkraune** [comment]
I am not the tar expert, but this seems to be a problem with a PaxHeader file - I don't yet fully understand why one tar file got it and not the other, but Vespa should extract the tar correctly regardless, @jonmv

**Comment by kkraune** [comment]
https://stackoverflow.com/questions/34688392/paxheaders-in-tarball

**Comment by kkraune** [comment]
review some docs in  https://github.com/vespa-engine/documentation/pull/1326

**Comment by kkraune** [comment]
https://docs.vespa.ai/en/reference/application-packages-reference.html#deploy is updated a long time ago, use zip, not tar/gzip - and I could not find any examples of tar/gzip use in doc/sample apps - closing
