### ISSUE TITLE
Change the ownership of /opt/vespa to a non root (uid:0) user from the published Dockerfile

### ISSUE THREAD

**Issue by nehajatav** [vespa-engine/vespa#17865]
Just wanted to check if there's a possibility to change the ownership of /opt/vespa to a non root (uid:0) user from the published Dockerfile
Background: In our firm, our hosted k8s doesnt allow running as privileged user, to work around this, we have to create a new docker image which changes ownership of all folders to non-root user. However, we have restrictions on running commands as root while publishing new Docker image and would be very helpful if the published docker image itself took care of using non-root user like vespa

**Comment by aressem** [comment]
@nehajatav I will look into this, but please note that this got a `later` priority. Can you share the Dockerfile you have created with me to get a better understanding of your request ?

**Comment by test-forum** [comment]
```docker
FROM <docker site>/vespa:latest

**RUN chown -R vespa:vespa  /bin /opt /usr**
USER vespa

RUN chmod -R 755 /opt && \
chmod -R 755 /usr && \
chmod -R 755 /bin

ENTRYPOINT ["<entry script>"]
```
