### ISSUE TITLE
Grouped Distribution - Issue in deploying application

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#17903]
Hi Team,

I tried to convert my flat distribution cluster to grouped distribution and on deployment of application I got below error while preparing the application.

In my case I referenced https://docs.vespa.ai/en/performance/sizing-examples.html to create group distribution application.
There is one top-group and 2 leaf group0 and group1 with 3 content nodes respectively, redundancy is 2 and searchable copies is 2.

Request failed: http status code 400
Invalid application package: default.default: Error loading model: In indexed cluster music using hierarchic distribution: Expected redundancy per leaf group to be 1, but it is not according to distribution partitions '*|*'. Expected distribution partition should be '1|*'.
command terminated with exit code 1.

Based on above error I changed distribution partitions from '*|*' to '1|*' and created the application and deployed and activated it. The application got deployed and activated successfully with warning to restart searchnode services which has to be done manually assuming it is an external change of changing the distribution from flat to grouped.

What was the reason that my application with distributed partition '*|*' failed and '1|*' worked. I checked documentation https://docs.vespa.ai/en/reference/services-content.html#distribution but there is no mention of any pattern '1|*'.
Could you please clarify what distributed partition '1|*' means?

**Comment by kkraune** [comment]
Thanks for reporting! I don't think the reference guide is wrong, but https://docs.vespa.ai/en/performance/sizing-examples.html should have an example using 1|* as well (I am glad to see the error message was helpful). It helps me updating the doc if you can paste your working services.xml into this ticket

**Comment by abhimech001** [comment]
> Thanks for reporting! I don't think the reference guide is wrong, but https://docs.vespa.ai/en/performance/sizing-examples.html should have an example using 1|* as well (I am glad to see the error message was helpful). It helps me updating the doc if you can paste your working services.xml into this ticket

Thanks for reply!!!
In my case of on top group with 2 leaf groups with distribution partition '1|*' means distribute all indexed docs in both groups

Please find service xml below

  <content id="my-content" version="1.0">
    <documents>
      <document type="my-document" mode="index">
    </documents>
    <redundancy>2</redundancy>
     <engine>
      <proton>
        <searchable-copies>2</searchable-copies>
      </proton>
     </engine>
    <group name="top-group">
      <distribution partitions="1|*"/>
      <group name="group0" distribution-key="0">
        <node hostalias="searcher1" distribution-key="0"/>
        <node hostalias="searcher2" distribution-key="1"/>
        <node hostalias="searcher3" distribution-key="2"/>
      </group>
      <group name="group1" distribution-key="1">
        <node hostalias="searcher4" distribution-key="3"/>
        <node hostalias="searcher5" distribution-key="4"/>
        <node hostalias="searcher6" distribution-key="5"/>
      </group>
    </group>
  </content>
</services>

**Comment by abhimech001** [comment]
Also, I had 1 TB of data ingested with flat distribution 
Mem consumption of content node
content-0 - 9Gi, content-1 - 9Gi, content-2 - 10Gi, content-3 - 9Gi, content-4 - 9Gi, content-5 -  9Gi

Deployed grouped distribution application and restarted content node. The mem of content node changed to
after an hr mem status was
content-0 - 8Gi, content-1 - 8Gi, content-2 - 10Gi, content-3 - 29Gi, content-4 - 14Gi, content-5 -  29Gi
after 12+ hrs mem status is
content-0 - 8Gi, content-1 - 25Gi, content-2 - 28Gi, content-3 - 29Gi, content-4 - 25Gi, content-5 -  25Gi

Why content memory is inconsistent across nodes after flat distribution was changed to group distribution?
Will all content node sync and get to a state where content memory becomes nearly equal for all nodes?

**Comment by kkraune** [comment]
All nodes should have uniform usage after data migreation, yes. In the https://cloud.vespa.ai/en/index-bootstrap guide, you will see use of the _merge_bucket.pending_ metric to evaluate data migration status. This info is also found at the cluster controller status page, see https://docs.vespa.ai/en/operations/admin-procedures.html#cluster-state

It is hard to give more specific feedback without knowing your services.xml file

**Comment by abhimech001** [comment]
[](url)> All nodes should have uniform usage after data migreation, yes. In the https://cloud.vespa.ai/en/index-bootstrap guide, you will see use of the _merge_bucket.pending_ metric to evaluate data migration status. This info is also found at the cluster controller status page, see https://docs.vespa.ai/en/operations/admin-procedures.html#cluster-state
> 
> It is hard to give more specific feedback without knowing your services.xml file

Thank you for reply

merge_bucket.pending - checked this and it was useful. 

I do not see any option to attach services.xml here and when I paste it direct within Insert code section the content gets replaced as 2,2.
Please suggest how can I upload the services.xml
Also, I am still not sure how and why the memory footprint of content node went to 3X when changed from flat distribution to group distribution .

**Comment by kkraune** [comment]
when you write a comment here, just below it says "Attach files by dragging & dropping, selecting or pasting them." - did you try to drop the file here?

you can also dump a screenshot from the cluster controller status page here

**Comment by abhimech001** [comment]
> when you write a comment here, just below it says "Attach files by dragging & dropping, selecting or pasting them." - did you try to drop the file here?
> 
> you can also dump a screenshot from the cluster controller status page here
Thanks for help.
Please find service file attached. For now I have reverted the group distribution to flat distribution so will not be able to help with cluster controller snippet.

[service.txt](https://github.com/vespa-engine/vespa/files/6516936/service.txt)

**Comment by kkraune** [comment]
ok. my best bet is that content-0 never was part of the data migration, the cluster controller view would show this status

**Comment by abhimech001** [comment]
> ok. my best bet is that content-0 never was part of the data migration, the cluster controller view would show this status

I have reverted group distribution to flat and still see the same issue with content node memory
1) Memory distribution is not equal between 6 content nodes
2) Memory distribution in content node 1 is least in both type of distributions
content-0 - 9Gi, content-1 - 26.8Gi, content-2 - 25Gi, content-3 - 23Gi, content-4 - 19.3Gi, content-5 - 25.3Gi

Pasting the html content for ref.
`
<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252"><title>music Cluster Controller 0 Status Page</title></head><body>
<h1>music Cluster Controller 0 Status Page</h1>
<p><font size="-1"> [ <a href="http://vespa.default.ext.com/clustercontroller-status/v1/music#config">Current config</a> | <a href="http://vespa.default.ext.com/clustercontroller-status/v1/music#clusterstates">Cluster states</a> | <a href="http://vespa.default.ext.com/clustercontroller-status/v1/music#eventlog">Event log</a> ]</font></p>
<table><tbody><tr><td>UTC time when creating this page:</td><td align="right">2021-05-24 10:30:34</td></tr><tr><td>Cluster controller uptime:</td><td align="right">9.77 days</td></tr></tbody></table><h2>State of content cluster 'music'.</h2>
<p>Based on information retrieved from slobrok at generation 71.</p>
<table border="1" cellspacing="0">
<tbody><tr>
<td bgcolor="#ccccff" align="left" colspan="19">Group /</td>
</tr>
<tr>
<th bgcolor="#ffffff" align="center" rowspan="2">Storage</th>
<th bgcolor="#ffffff" align="center" colspan="3" rowspan="1">Node states</th>
<th bgcolor="#ffffff" align="center" rowspan="2">Build</th>
<th bgcolor="#ffffff" align="center" rowspan="2">FC<sup>1)</sup></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>OCT<sup>2)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>SPT<sup>3)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>SSV<sup>4)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>PC<sup>5)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>ELW<sup>6)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>default buckets</nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>global buckets</nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>Resource usage (%)</nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>Start Time</nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>RPC Address</nobr></th>
</tr>
<tr>
<th bgcolor="#ffffff" align="center">Reported</th>
<th bgcolor="#ffffff" align="center">Wanted</th>
<th bgcolor="#ffffff" align="center">System</th>
<th bgcolor="#ffffff" align="center">Pending</th>
<th bgcolor="#ffffff" align="center"><nobr>Total</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Pending</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Total</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Disk</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Memory</nobr></th>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.0">0</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>8.52 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>27</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174713</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">12.96</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:35:18</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-0.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.1">1</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>2.22 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>33</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174137</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">13.74</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:56:00</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-1.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.2">2</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>20.69 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>34</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>175065</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">14.66</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:54:59</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-2.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.3">3</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>10.34 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>28</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174961</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">15.11</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 12:34:14</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-3.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.4">4</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>7.51 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>24</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>175297</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">14.11</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 12:13:59</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-4.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=storage.5">5</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 19</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>21.42 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>25</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174413</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="right">13.54</td>
<td bgcolor="#c0ffc0" align="right">15.30</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 12:14:11</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-5.vespa-internal.default.svc.cluster.local:19101</td>
</tr>
<tr>
<td bgcolor="#ccccff" align="left" colspan="19">Group /</td>
</tr>
<tr>
<th bgcolor="#ffffff" align="center" rowspan="2">Distributor</th>
<th bgcolor="#ffffff" align="center" colspan="3" rowspan="1">Node states</th>
<th bgcolor="#ffffff" align="center" rowspan="2">Build</th>
<th bgcolor="#ffffff" align="center" rowspan="2">FC<sup>1)</sup></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>OCT<sup>2)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>SPT<sup>3)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>SSV<sup>4)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>PC<sup>5)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>ELW<sup>6)</sup></nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>default buckets</nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>global buckets</nobr></th>
<th bgcolor="#ffffff" align="center" colspan="2" rowspan="1"><nobr>Resource usage (%)</nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>Start Time</nobr></th>
<th bgcolor="#ffffff" align="center" rowspan="2"><nobr>RPC Address</nobr></th>
</tr>
<tr>
<th bgcolor="#ffffff" align="center">Reported</th>
<th bgcolor="#ffffff" align="center">Wanted</th>
<th bgcolor="#ffffff" align="center">System</th>
<th bgcolor="#ffffff" align="center">Pending</th>
<th bgcolor="#ffffff" align="center"><nobr>Total</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Pending</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Total</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Disk</nobr></th>
<th bgcolor="#ffffff" align="center"><nobr>Memory</nobr></th>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.0">0</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>45.13 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174976</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:25:15</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-0.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.1">1</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>15.43 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>175280</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:25:04</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-1.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.2">2</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>54.60 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174834</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:24:57</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-2.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.3">3</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>33.76 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174816</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:25:22</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-3.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.4">4</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>21.99 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174656</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:24:58</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-4.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
<tr>
<td bgcolor="#ffffff" align="center"><a href="http://vespa.default.ext.com/clustercontroller-status/v1/music/node=distributor.5">5</a></td>
<td bgcolor="#c0ffc0" align="left">U, b 58</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="left">U</td>
<td bgcolor="#c0ffc0" align="right"><nobr>7.398.17</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0 s</nobr></td>
<td bgcolor="#c0ffc0" align="left"><nobr>24.42 s</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>208</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#ffc0c0" align="right"><nobr>22</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>0</nobr></td>
<td bgcolor="#c0ffc0" align="right"><nobr>174024</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center"><nobr>-</nobr></td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="center">-</td>
<td bgcolor="#c0ffc0" align="right">2021-05-20 11:25:11</td>
<td bgcolor="#c0ffc0" align="right">tcp/vespa-content-5.vespa-internal.default.svc.cluster.local:19110</td>
</tr>
</tbody></table>
<p></p><p><font size="-1">
1) FC - Failed connections - We have tried to connect to the nodes this many times without being able to contact it.<br>
2) OCT - Out of contact time - Time in seconds we have failed to contact the node.<br>
3) SPT - State pending time - Time the current getNodeState request has been pending.<br>
4) SSV - System state version - The latest system state version the node has acknowledged (last <em>activated</em> state version in parentheses if this is not equal to SSV).<br>
5) PC - Premature crashes - Number of times node has crashed since last time it had been stable in up or down state for more than 120.00 minutes.<br>
6) ELW - Events last week - The number of events that has occured on this node the last week. (Or shorter period if a week haven't passed since restart or more than max events to keep in node event log have happened during last week.)<br>
`

**Comment by kkraune** [comment]
Revisiting this: Maybe you can describe the motivation for using a grouped distribution? https://docs.vespa.ai/en/performance/sizing-search.html is normally the driver, but most often one will do with https://docs.vespa.ai/en/schemas.html#querying-multiple-document-types in one content cluster with flat distribution.

I suggest you look into the https://cloud.vespa.ai/pricing#free-trial for better support, we can then help you more easily.

Please let me know next steps
