### ISSUE TITLE
vespa-visit - queries 

### ISSUE THREAD

**Issue by abhimech001** [vespa-engine/vespa#18008]
Hi Team,

Content type – music 

Schema definition
```schema music {
    document music {
        field artist type string {
            indexing: summary | index
        }
        field album type string {
            indexing: summary | index
        }
        field year type int {
            indexing: summary | attribute
        }
    }
}
```

**Used case 1:** 

1) Ingested 2000 doc in content type - music
2) Ran below vespa-visit operation to dump all data
             /opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> m2.json
3) Generated progress-file and all 2000 docs were available in m2.json.
4) Off 2000 ingested docs, updated the data for 1000 docs 
5) Ingested another 28000 recs (total docs = 30000)
6) Ran below vespa-visit operation again to dump updated/new data (progress-file available from step 3))
         /opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> m2.json
The above command did not dumped the updated and new ingested doc to m2.json file and count of m2.json continued to be 2000

log of above visit command

Resuming visitor already 100.0 % finished.
Completed visiting.
*** Visitor statistics
Nothing visited

checked docs in searchnode using /opt/vespa/bin/vespa-proton-cmd 19103 getState
"online", "true"
"onlineState", "online"
"onlineDocs", "30000"

**Why updated/new data did not get visited and dumped progressively on every consecutive run of vespa-visit?
How does above visit operation works for updated docs. Will it be treated as new docs?**

**Used case 2:**

1) Removed progress-file and m2.json generated in used case 1
2) Ran below vespa-visit operation to dump all data
         /opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> m2.json
3) Interupted the above visit operation with ctrl+Z after 7.8% of visit and killed the process.
4) progress-file and m2.json with partial data dump created.
5) Re-ran vespa-visit operation to dump data again (progress-file available from step 4))
      /opt/vespa/bin/vespa-visit -v --priority LOW_1 -p progress-file --fieldset 'music:[document]' >> m2.json

Resuming visitor already 7.8 % finished.
100 % finished..
Completed visiting.
*** Visitor statistics
Buckets visited: 236
Documents visited: 27710
Bytes visited: 5151806
Documents returned: 0
Bytes returned: 0
Documents returned (2nd pass): 27710
Bytes returned (2nd pass): 5151806

6) Observed duplicate docs were available.  used command to determine duplicate "sort m2.json | uniq -d"

**Is doc duplication an expected behavior?**

**Comment by bratseth** [comment]
Updated documents are not treated as new documents.

A visitor visits the entire bucket state once and then it's done forever. It does not subscribe to changes to documents or anything like that.

Yes a visitor can produce duplicates when there are disruptions causing retries etc.

**Comment by abhimech001** [comment]
> Updated documents are not treated as new documents.
> 
> A visitor visits the entire bucket state once and then it's done forever. It does not subscribe to changes to documents or anything like that.
> 
> Yes a visitor can produce duplicates when there are disruptions causing retries etc.

Thanks for reply

So does it mean, to get new ingested doc post visit operation, we will have to delete the progress-file and run visit operation again?

**Comment by bratseth** [comment]
Add a timestamp field to your documents and visit documents changed after the timestamp.
