### ISSUE TITLE
Mutual TLS for internode communication 

### ISSUE THREAD

**Issue by Sneha711** [vespa-engine/vespa#18066]
Can we have secure setup between containerised pods of vespa cluster? 
http pods connection works, but will https work?

**Comment by bratseth** [comment]
Yes, see https://docs.vespa.ai/en/securing-your-vespa-installation.html#securing-the-application-container

**Comment by Sneha711** [comment]
Can't find _jdisc_container_ folder in /path/to/vespa/home/conf/ even after adding -
```
<server id="server1" port="8080">
  <config name="jdisc.http.connector">
    <idleTimeout>90</idleTimeout>
  </config>
</server>
```

Will it work if I just add the certificates and the private key that I've generated?

**Comment by bratseth** [comment]
Yes, you can just create the path and add certs there.

**Comment by Sneha711** [comment]
Hi,
Wanted to check if mTLS is working between config(server-2) and container(server-1) after configuring TLS as follows. Tried to ping container through config, but it didn't work. How do I test it out? Is the below configuration correct?  Also will this configuration work for content nodes communication as well, from the looks of it, it seems as if it will work only for container given it's under container element.

Testing:
```
bash-4.2$ kubectl exec vespa-0 -- bash -c 'curl -iv https://vespa-container:8080'
* About to connect() to vespa-container port 8080 (#0)
*   Trying 11.33.101.35...
* Connection refused
* Failed connect to vespa-container:8080; Connection refused
* Closing connection 0
curl: (7) Failed connect to vespa-container:8080; Connection refused
```

TLS configuration:
```
<container id="default" version="1.0">
        <http>
            <server id="server-1" port="8080">
                <ssl>
                    <private-key-file>/opt/vespa/conf/jdisc_container/vespa-certs.key</private-key-file>
                    <certificate-file>/opt/vespa/conf/jdisc_container/vespa-certs.cer</certificate-file>
                    <ca-certificates-file>/opt/vespa/conf/jdisc_container/vespa-certs.p12</ca-certificates-file>
                    <client-authentication>want</client-authentication>
                    <cipher-suites>
                    TLS_AES_128_GCM_SHA256,
                    TLS_AES_256_GCM_SHA384,
                    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    </cipher-suites>
                    <protocols>TLSv1.2,TLSv1.3</protocols>
                </ssl>
            </server>
            <server id="server-2" port="19071">
                <ssl>
                    <private-key-file>/opt/vespa/conf/jdisc_container/vespa-certs.key</private-key-file>
                    <certificate-file>/opt/vespa/conf/jdisc_container/vespa-certs.cer</certificate-file>
                    <ca-certificates-file>/opt/vespa/conf/jdisc_container/vespa-certs.p12</ca-certificates-file>
                    <client-authentication>want</client-authentication>
                    <cipher-suites>
                    TLS_AES_128_GCM_SHA256,
                    TLS_AES_256_GCM_SHA384,
                    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    </cipher-suites>
                    <protocols>TLSv1.2,TLSv1.3</protocols>
                </ssl>
            </server>
        </http>
        <document-api/>
        <search/>
        <nodes>
            <node hostalias="node-1" />
        </nodes>
    </container>
```

**Comment by bratseth** [comment]
Above I answered how to configure mTLS for traffic to/from a Vespa instance.

mTLS for internal traffic between nodes is also possible, but more complicated, as there are multiple processes and protocols. We haven't yet gotten around to document this but i will happen in the not too far future.

I should also mention that this is provided for you by default when you deploy to the Vespa Cloud.

**Comment by vekterli** [comment]
Open source Vespa now officially supports mTLS across all internal services and endpoints. As mentioned, if you use [Vespa Cloud](https://cloud.vespa.ai/) this is—and always has been—enabled without any setup required.

See our [mTLS blogpost for an introduction](https://blog.vespa.ai/securing-vespa-with-mutually-authenticated-tls/) and our [mTLS reference documentation](https://docs.vespa.ai/en/mtls.html) for setup instructions.

Please let us know if you have any follow-up questions!
