### ISSUE TITLE
download-mind.sh demo fails as downloaded resource no longer is available

### ISSUE THREAD

**Issue by Komegaga** [vespa-engine/vespa#18611]
**Describe the bug**
The file download from ./bin/download-mind.sh demo is broken

**To Reproduce**
1. Execute ./bin/download-mind.sh demo
2. Error message
Archive:  ./mind/train.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./mind/train.zip or
        ./mind/train.zip.zip, and cannot find ./mind/train.zip.ZIP, period.

**Screenshots**
![Screenshot from 2021-07-15 10-21-25](https://user-images.githubusercontent.com/11317013/125718499-3a2cf24c-8664-4ee3-b81c-363c2d647462.png)

**Environment (please complete the following information):**
 - OS: CentOS
 - Infrastructure: self-hosted
 - Versions 7

**Comment by jobergum** [comment]
Looks like they have removed public access to the 'demo' dataset used in this sample application. The download script is light on the error checking and the downloaded file is a NoAccess message which fails with the mention unzip failure. 


```
curl -L -o train.zip https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_train.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   248  100   248    0     0    515      0 --:--:-- --:--:-- --:--:--   515
(base) Jos-MacBook-Pro:bigann bergum$ less train.zip 
(base) Jos-MacBook-Pro:bigann bergum$ cat train.zip 
<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:cceee300-f01e-008f-6177-7acf06000000
```

The small and large seem to be ok though.

**Comment by Komegaga** [comment]
Yes, I used the small dataset instead to go through the learning material.

**Comment by lesters** [comment]
Should now be fixed with the above PR.
