### ISSUE TITLE
Vespa-config-status gives connection errors after configuring HTTP/2

### ISSUE THREAD

**Issue by labriedion** [vespa-engine/vespa#18641]
I deployed a Vespa cluster in Azure Kubernetes with HTTP/2 enabled using the latest Vespa build. My setup is similar to this one: https://github.com/vespa-engine/sample-apps/tree/master/basic-search-on-gke, with the HTTP/2 server configured according to the instructions found here: https://blog.vespa.ai/http2/.

Here's the container part of my services.xml:

```

<container id="container" version="1.0">
       <http>
      <server id="tls" port="8443">
        <ssl>
          <private-key-file>/vespa-app/certificates/vespa-private-key.pem</private-key-file>
          <certificate-file>/vespa-app/certificates/vespa-public-cert.pem</certificate-file>
          <ca-certificates-file>/vespa-app/certificates/vespa-public-cert.pem</ca-certificates-file>
            <client-authentication>need</client-authentication>
        </ssl>
      </server>
      <server id="default" port="8080"/>
    </http>
    <document-api />
    <document-processing/>
    <search />
    <nodes jvmargs="-Xms512m -Xmx512m">
      <node hostalias='container'/>
        <node hostalias='container0'/>
        <node hostalias='container1'/>
        <node hostalias='container2'/>
    </nodes>
  </container>

```

Everything is working well, I'm able to load data and query Vespa using HTTP/2 using self-signed certificates. There's no errors or warnings in the logs, except for the following:

```
[2021-07-21 14:40:07.424] INFO    : slobrok          vespa-slobrok.slobrok.server.rpc_server_manager    managed server container/container.3/chain.indexing at tcp/vespa-container-2.vespa-internal.vespa.svc.clus
ter.local:19100 failed: (RPC) Connection error
[2021-07-21 14:41:19.882] INFO    : slobrok          vespa-slobrok.slobrok.server.rpc_server_manager    managed server container/container.2/chain.indexing at tcp/vespa-container-1.vespa-internal.vespa.svc.clus
ter.local:19100 failed: (RPC) Connection error
[2021-07-21 14:41:47.312] INFO    : slobrok          vespa-slobrok.slobrok.server.rpc_server_manager    managed server container/container.1/chain.indexing at tcp/vespa-container-0.vespa-internal.vespa.svc.clus
ter.local:19100 failed: disconnected

```
Also, when I run vespa-config-status, I get the following:

```
container/container.0: Failed to fetch json: could not parse HTTP status line: '§♥♥'
container/container.1: Failed to fetch json: Connection error: socket write error
container/container.2: Failed to fetch json: Connection error: socket write error
container/container.3: Failed to fetch json: Connection error: socket write error
command terminated with exit code 1
```

I'm surprised to see these errors since, like I said, Vespa is otherwise behaving fine.

**Comment by jobergum** [comment]
Just a short description on what is going on. 

The vespa-config-status tools uses http(s) of the containers to fetch configuration version, since it has been secured with mTLS it's not longer able to read the information.  I'll see what we can do about this, we do have a solution for this in the cloud. Your vespa installation health is not impacted by this error however.

**Comment by tokle** [comment]
As a workaround for this issue you can move the 8080 port first in the http block:

```
<container id="container" version="1.0">
    <http>
        <server id="default" port="8080"/>
        <server id="tls" port="8443">
        ...
    </http>
    ...
</container>
```

The config model will then tag port _8080_ to be used instead of _8443_. You can verify by checking the model, e.g:
```
# vespa-model-inspect service container
container @ vespa-container :
default/container.0
    tcp/vespa-container:8080 (STATE EXTERNAL QUERY HTTP)
    tcp/vespa-container:8443 (EXTERNAL HTTP)
```
The port tagged with _STATE_ will be used by the _vespa-config-status_ utility

**Comment by labriedion** [comment]
Thanks for your reply Morten. 

I changed the config as you said, and the vespa-model-inspect command shows it is indeed properly set:

`container @ vespa-0.vespa-internal.vespa.svc.cluster.local :
container/container.0
    tcp/vespa-0.vespa-internal.vespa.svc.cluster.local:8080 (STATE EXTERNAL QUERY HTTP)
    tcp/vespa-0.vespa-internal.vespa.svc.cluster.local:8443 (EXTERNAL HTTP)
    tcp/vespa-0.vespa-internal.vespa.svc.cluster.local:19100 (MESSAGING RPC)
    tcp/vespa-0.vespa-internal.vespa.svc.cluster.local:19101 (ADMIN RPC)
`

Unfortunately, I still get errors when running vespa-config-status:
`container/container.1: Failed to fetch json: Connection error: socket write error
container/container.2: Failed to fetch json: Connection error: socket write error
command terminated with exit code 1
`

**Comment by jobergum** [comment]
I'm not sure if you have secured ports? Are you able to curl -v to the vespa-0.vespa-internal.vespa.svc.cluster.local:8080/Applicationstatus from the node which you run vespa-config-status utility?

**Comment by labriedion** [comment]
I am able to access the admin cluster this way and get the ApplicationStatus. 

I also tried to reach the content and container nodes this way, not sure if that should work, and it fails with a connection refused error.

The vespa version I'm currently using is "7.438.16" not sure if you introduced any fixes since then.

**Comment by bjorncs** [comment]
@labriedion The next Vespa release will have HTTP/2 enabled by default without the need for TLS. Both HTTP/2 with prior knowledge and HTTP/2 through upgrade is supported. If you prefer TLS I highly recommend checking out our newly announced TLS functionality in Vespa: https://blog.vespa.ai/securing-vespa-with-mutually-authenticated-tls/.

**Comment by labriedion** [comment]
Thanks Bjørn!
