### ISSUE TITLE
Ability to load attribute data for re-ranking on-demand

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#18646]
There are use cases with relaxed throughput/latency requirements that loading attribute data for ranking could be feasible using on-demand with memory mapping. For example consider the ColBERT model described here https://blog.vespa.ai/pretrained-transformer-language-models-for-search-part-3/ there is a rather large tensor field:

```
field dt type tensor<bfloat16>(x{}, dt[32]) {
   indexing: summary |attribute
   attribute:fast-search
}
```

Which for a larger collection with high number of unique x values per document and potentially higher dimensionality for the dense order this could get really big so storing it in memory could become costly for many organizations that don't need 4K QPS and < 20 ms latency. In those cases the dt tensor is always used as a re-ranking step so max 500 to 1000 random reads are expected (based on re-ranking count). For such cases it could be worth having the ability to allow reading from disk and still enjoy the super fast computation. 

The alternative is to fetch from summary store and re-rank at the stateless container using e.g onnx to accelerate or the java tensor framework.

**Comment by baldersheim** [comment]
Then we have to agree on a syntax.
I suggest `attribute: swappable` indicating that it can be swapped out.

**Comment by baldersheim** [comment]
Agreement was reached with `attribute:paged`

**Comment by baldersheim** [comment]
@jobergum Then you can give it try and write some explanatory doc :)

**Comment by jobergum** [comment]
So the following would allow the dt (per document term embedding)  be saved on disk.  Doc values paged in on-demand (e.g from a second phase re-ranking). Frequently accessed docs from first-phase would be cached depending on memory pressure and the OS virt memory system. 

```
field dt type tensor<int8>(x[4096]) {
   indexing:attribute
   attribute:paged
}
```

**Comment by baldersheim** [comment]
Correct.

**Comment by baldersheim** [comment]
Present since 7.451
