### ISSUE TITLE
Bitwise hamming ranking feature for single order tensors with int8 cell type

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#18678]
We do support computing bitwise hamming distance as a distance metric in the nearest neighbor search operator for int8 tensor cell types but we don't have support for it as a ranking expression feature. 

Given 
```
q = tensor<int8>(x[1]):[-128]
d = tensor<int8>(x[1]):[127] ​
```
Bitwise hamming distance would be 8 as all bits differs 
```
bit_hamming_distance(q,d) = 8
```
Usually one want this is a similarity metric using 1/(1 + bit_hamming_distance(q,d))

**Comment by arnej27959** [comment]
the ranking feature you want is `closeness(field,d)`
you need to have a nearestNeighbor operator in the query that ties it to the "q" query feature, but that can be inside a RANK operator if you don't want it to impact which hits you get.

**Comment by jobergum** [comment]
It solves the case mentioned indeed @arnej27959 but I think we need more generic support for also multi order tensors 

```
dt = tensor<int8>(dt{}, x[16]) {}
qt = tensor<int8>(qt{}, x[16]) {}
```

Where one wants to compute hamming distance between all qt against all dt and retain the sum of the closest (inverted distance), something along the lines of (Similar to [MaxSim](https://github.com/vespa-engine/sample-apps/blob/master/msmarco-ranking/passage-ranking.md)))  
 
```        
sum(
          reduce(
              1/(1 + bit_hamming_distance(qt,dt))
            max, dt
          ),
          qt
        )
 ```

**Comment by arnej27959** [comment]
we would probably want something like
```
dt = tensor<int8>(dt{}, x[16]) {}
qt = tensor<int8>(qt{}, x[16]) {}
join(qt,dt,hamming_distance) = tensor<float>(dt{},qt{}, x[16]) {}
reduce(join(qt,dt,hamming_distance),sum,x) = tensor<float>(dt{},qt{}) {}  [optimized like dot-product]
reduce(reduce(join(qt,dt,hamming_distance),sum,x),min,dt) = tensor<float>(qt{}) {}
map(reduce(reduce(join(qt,dt,hamming_distance),sum,x),min,dt),f(x)(1/(1+x))) =  tensor<float>(qt{}) {}
reduce(map(reduce(reduce(join(qt,dt,hamming_distance),sum,x),min,dt),f(x)(1/(1+x))),sum,qt) = double
```
let us discuss with @havardpe next week if this makes sense to implement.

**Comment by jobergum** [comment]
Great @arnej27959, thanks for the excellent write up!

**Comment by jobergum** [comment]
This is know available https://docs.vespa.ai/en/reference/ranking-expressions.html#:~:text=can%20be%20scalars.-,hamming(t1%2Ct2),-join(t1%2C%20t2
