### ISSUE TITLE
Open source Vespa Docker image no longer built by Docker Hub

### ISSUE THREAD

**Issue by bjorncs** [vespa-engine/vespa#18699]
Docker Hub stopped recently stopped automatic building of Docker images for the free plan (https://www.docker.com/blog/changes-to-docker-hub-autobuilds/). Our open-source Vespa Docker image is no longer built and distributed. We need to either apply for the Docker Open Source program or build the image somewhere else (e.g Screwdriver).

**Comment by olgaakrekhovetska** [comment]
@johans1 Is there a plan to upload Vespa docker image to other public registries such as [Amazon ECR public gallery](https://gallery.ecr.aws/) or [Github container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)? There is an issue with hitting DockerHub rate limits, while the mentioned two don't have this problem.

**Comment by aressem** [comment]
@olgaakrekhovetska I will look into these alternatives.

**Comment by aressem** [comment]
@olgaakrekhovetska We are now publishing the Vespa container image to GitHub Container registry as well:
```
$ docker pull ghcr.io/vespa-engine/vespa:latest
```
Documented in https://docs.vespa.ai/en/build-install-vespa.html .

**Comment by olgaakrekhovetska** [comment]
Nice! Thanks a lot @aressem!

**Comment by houqp** [comment]
Thank you @aressem for the quick turnaround!
