### ISSUE TITLE
Vespa 8: Empty query handling

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#18838]
Today if the user query input parses to a NullItem due containing only unsearchable characters the other parts of the total query specification is still executed against the backend(s). 

All the following examples ends up searching for source:who 

```
/search/?query=,&yql=select..  where userQuery() and source contains "who";
```

```
/search/?yql=select..  where default contains "," and source contains "who";
```

```
/search/?query=,&filter=+source:who;
```

**Comment by bratseth** [comment]
Whether or not this is desirable is application dependent - could be that an empty user query just means "recommend all content matching filters" etc., so I don't think we should change it.

**Comment by jobergum** [comment]
Totally agree that there are valid use cases for both failing it and executing it as today, but there is no way to control the behaviour today except intercept and fail it in a custom searcher if query consist of only "filter" terms.

**Comment by johans1** [comment]
wontfix
