### ISSUE TITLE
how does vespa compress posting list?

### ISSUE THREAD

**Issue by ltang666** [vespa-engine/vespa#18846]
Read document https://docs.vespa.ai/documentation/proton.html#index found `compresssed posting lists with position information. File: posocc.dat.compressed`.

Has any document introduces how the posting list is compressed?

**Comment by kkraune** [comment]
Sorry, we do not have documentation for this, please refer to the source code. I'll check with core team and add a note if easy

**Comment by ltang666** [comment]
@kkraune could you tell me where the compressed posting list source code is. I searched "compress/decompress" keyword in the Vespa repo, but didn't find any related.
I will read the code and add some documents if possible.

https://github.com/vespa-engine/vespa/blob/HEAD/vespalib/src/vespa/vespalib/util/compress.h maybe not be used for compressed posting list.

**Comment by geirst** [comment]
The class for writing posting lists used in the disk index is here: https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/diskindex/zcposocc.h#L26. 
Similarly, the class for reading posting lists is here: https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/diskindex/zcposocc.h#L11.

**Comment by kkraune** [comment]
Thanks @geirst !

**Comment by ltang666** [comment]
@geirst What compressing method does Vespa use for docid or occ? pfordelta, newpfordelta, simple9 simple16 or binary packing.
