### ISSUE TITLE
/opt/vespa/bin/vespa-status-filedistribution failed to run

### ISSUE THREAD

**Issue by jamesbond7** [vespa-engine/vespa#19423]
I installed the Vespa version 7.476.1 and when I execute the "/opt/vespa/bin/vespa-status-filedistribution" tool in shell I get the error:

Error: Unable to initialize main class com.yahoo.vespa.filedistribution.status.FileDistributionStatusClient
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest

**Comment by hmusum** [comment]
Thanks for the report, fixed in 7.479.5
