### ISSUE TITLE
Query time adaptive parallelization for retrieval and ranking with multiple threads per search

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#19432]
Today we use whatever number of threads is configured in ranking profile/services.xml without doing any estimate if using more threads will help speed up the query.  Even the built in unranked ranking profile will use the upper bound number from services.xml setting. 

In [Predictive Parallelization: Taming Tail Latencies in Web
Search](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/paper-16.pdf) authors proposes a method to predict when to use more threads executing the query and not. 

Given that query setup and blue print setup is single threaded before executing the potential multithreaded matching and ranking phase(s) we could potentially guess the benefit from multi threaded by using the query plan with hit count estimates. 

Enabling how? We could expose a range in the ranking profile with min and max threads to use and where the actual number is adaptive determined by the predictor. 

```
rank-profile foo {
  num-threads-per-search:1-4 
}

**Comment by bratseth** [comment]
We're missing documentation of min-hits-per-thread.

**Comment by baldersheim** [comment]
min-hits-per-thread is documented at https://docs.vespa.ai/en/reference/schema-reference.html#min-hits-per-thread

Using different thread count between first and second phase is not possible.
That would be considered a major rewrite. And until a real-world use case emerges which proves that this would be beneficial this is moot.
