### ISSUE TITLE
query timeout after new index warmed up and switched in

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#19495]
Hi, 
All search requests are timeout after a new index being warmed and switched in, and it lasts 1-2 minutes. 
New indexed was switched in at 18:41:31 and 21:51:07.
`1633862485.937157	n245-113-041.byted.org	2675232/6607	searchnode	proton.searchcorespi.index.indexmaintainer	info	New index warmed up and switched in : selector : 0x1006a671d80(baseId=76, docidlimit=115753055, defaultsource=2)\n3 {0 : 0x1009e675c50(/opt/tiger/vespa/var/db/vespa/search/cluster.mt_video/n2/documents/mt_video_v2/0.ready/index/index.fusion.76), 1 : 0x1009e8a4ed0(/opt/tiger/vespa/var/db/vespa/search/cluster.mt_video/n2/documents/mt_video_v2/0.ready/index/index.flush.77), 2 : 0x1005d872c10(N6proton18MemoryIndexWrapperE)}`

`1633873840.229587	n245-113-041.byted.org	2675232/6607	searchnode	proton.searchcorespi.index.indexmaintainer	info	New index warmed up and switched in : selector : 0x10068ab4b80(baseId=77, docidlimit=115811088, defaultsource=1)\n2 {0 : 0x10004304090(/opt/tiger/vespa/var/db/vespa/search/cluster.mt_video/n2/documents/mt_video_v2/0.ready/index/index.fusion.77), 1 : 0x1005d872c10(N6proton18MemoryIndexWrapperE)}`

Here is the full log.
![image](https://user-images.githubusercontent.com/5534548/136731376-f1d60a81-7415-4268-ad1f-38f97b4c2133.png)
![image](https://user-images.githubusercontent.com/5534548/136731416-8c56b036-4ca9-414a-a4ee-58ba4c65febf.png)

The average search latency raised at the two timestamps. 
![image](https://user-images.githubusercontent.com/5534548/136730929-beb13538-6ca2-4c7c-88ac-65e1ca26a84d.png)

The search latency per node.
![image](https://user-images.githubusercontent.com/5534548/136769244-a1bfbef5-eef3-4479-8e36-06f98754e41c.png)

Configuration of the vespa cluster.
![image](https://user-images.githubusercontent.com/5534548/136731054-05a1d089-c285-4c62-b379-44c6d9883aa6.png)

Is it cost double cpu resources during warming up?

**Comment by dsisds** [comment]
@jobergum 
1.  Yes, it is from the content.proton.search_protocol.query.latency metric.
2. There are two indexes and each index contains more than 115M documents.
![image](https://user-images.githubusercontent.com/5534548/136882826-0caeed84-775d-445a-8b9e-604d17ec1410.png)
The index mt_video_v2 is serving.

10:37:48,  start flush
![image](https://user-images.githubusercontent.com/5534548/136884149-e1dc9ba9-0d88-4edf-839c-1c7642c5a614.png)

10:41:29, flush complete and the number of slow execution began rising.
![image](https://user-images.githubusercontent.com/5534548/136894649-6c6079d7-81ad-4985-8fd0-27ff81e41aed.png)

10:42:09, done warming up and new index switched in.
![image](https://user-images.githubusercontent.com/5534548/136895058-2d56dc26-606d-4522-9cb6-9c75e94375d3.png)

10:42:39, slow execution number reduced to normal
![image](https://user-images.githubusercontent.com/5534548/136895671-6b8fe05d-7da5-49f6-8852-560432d715e9.png)

**Comment by jobergum** [comment]
Ok, so all of the above was with warmup and populate? The suggestion from us is to remove warmup as you have already populate. This also removes one variable as these two features were not meant to be enabled at the same time.


Unrelated to the issue at hand but I suggest that you try to delete the slow query warnings strings from further communication and update the screenshots if possible.

**Comment by jobergum** [comment]
Hi @dsisds, were you able to verify using only the populate option?

**Comment by jobergum** [comment]
I'm resolving this, assuming removing both populate and warmup resolved this. Feel free to re-open if it did not, or you have further questions on this. Thanks!
