### ISSUE TITLE
Use default content-type in vespa-fbench for post queries

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#19840]
When using `vespa-fbench`, you need to specifically add the content-type header (`-H "Content-type:application/json"`) when using HTTP POST queries. 

When you specify post queries on the command line with the `-P` option, we should add the relevant content-type header as default unless another one is explicitly set with the `-H` option.

**Comment by frodelu** [comment]
Alternative to defaulting to json content-type is to at least require a content-type explicitly specified (using `-H` option) if you use post requests (with the `-P` option).

**Comment by baldersheim** [comment]
fixed in vespa-8.34.21
