### ISSUE TITLE
Explore ability to support global streaming search without user or group affinity 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20086]
[Streaming search](https://docs.vespa.ai/en/streaming-search.html) is a cost-efficient search solution for many use cases that do not require high query throughput and can accept latency measured in 3-4 digit ms instead of single digits. However, today, the developer needs to define group or user affinity to limit search scope to use streaming mode. 

It would be exciting to relax this requirement and allow a global streaming search without group or user affinity. 

Latency and summary store read throughput could be controlled by slicing, similar to [visit API slicing](https://blog.vespa.ai/sliced-visiting/).

**Comment by baldersheim** [comment]
Are you aware of `&streaming.selection=true`

**Comment by baldersheim** [comment]
@jobergum Is the above good enough for you ?
