### ISSUE TITLE
Feed overloading the container, even when throttling is employed

### ISSUE THREAD

**Issue by jonmv** [vespa-engine/vespa#20209]
**Describe the bug**
Feeding overloads the container due to slow regex matching in optimaize linguistics library, coupled with retries of problematic documents. 

**To Reproduce**
Feed any large string which matches the first part of optimaize's `private static final Pattern MAIL_REGEX = Pattern.compile("[-_.0-9A-Za-z]+@[-_0-9A-Za-z]+[-_.0-9A-Za-z]+");`, but has no `@` in it. This triggers quadratic complexity. A string of ~100k takes ~1 min to (not) match. 

When this is done with retries in the feed client, the container node may become overloaded for a long period of time, as the client retries the same document even while it is still being processed. 

**Expected behavior**
Feeding long strings should not cause the container to overload. 

**Vespa version**
7.503.19

**Comment by jonmv** [comment]
Several things we could do: 

1. Make PR to optimaize to limit the length of the email to 256 characters. [Longer ones aren't valid anyway.](https://www.rfc-editor.org/rfc/inline-errata/rfc3696.html)
2. Consider guarding against such behaviour. Really the job of the linguistics library, though.
3. Reconsider retry mechanisms for operations which time out.

**Comment by jonmv** [comment]
1. fixes this particular problem, as the other regex behaviour in this class is fine.

**Comment by jonmv** [comment]
Adding a negative lookbehind with one of the characters from the first part of the pattern also solves this, and is faster. It's also a pure optimisation, which doesn't alter the behaviour of the `replaceAll`. Will make a PR with this change, and see how that goes.

**Comment by jonmv** [comment]
Hmm I'm afraid the library isn't maintained anymore, though: https://github.com/optimaize/language-detector

**Comment by bratseth** [comment]
Looks like we should switch to https://github.com/pemistahl/lingua

**Comment by jonmv** [comment]
That one looks convincing. I'd be happy to work on this.

**Comment by bratseth** [comment]
Great!

**Comment by senecaso** [comment]
I've been using lingua for another part of my project, and it has been working well for that.  That said, I haven't done any performance testing, so I can't speak to what impact this replacement would have overall in Vespa.

**Comment by jonmv** [comment]
#20568 changes to the OpenNLP detector, with a patch for the mail regex, which is also present there. I also made https://github.com/apache/opennlp/pull/399 for a fix in the OpenNLP project, but I don't know how long we would have to wait for that to be released. 
Lingua was not a good option due to it using "all available cores" for each prediction; this is fine on "my machine", but not the type of code we want running in a server. It was also considerably slower than optimaize. With tuning, OpenNLP looks to be as fast as optimaize was, and more accurate.

**Comment by jonmv** [comment]
In the end, using OpenNLP for langdetect was a bit slower (~25% e2e), but we just had to accept this. I also patched some unnecessarily slow code used for ngram extraction in OpenNLP, but haven't made a PR for this. The newest Vespa releases should have these fixes.
