### ISSUE TITLE
Add support for hex format for int8 query tensors 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20232]
Currently, we don't support expressing query tensors with [hex feed format](https://docs.vespa.ai/en/reference/document-json-format.html#tensor-hex-dump ) (for int8 tensors).

It would be great if we could support this format on the query side as well:

```
/search/?ranking.features.query(binary_code)=FF00118022FE
```

**Comment by arnej27959** [comment]
done, doc in:
https://github.com/vespa-engine/documentation/pull/2468

**Comment by jobergum** [comment]
Thanks @arnej27959!
