### ISSUE TITLE
Ensure all documentation is in table of contents

### ISSUE THREAD

**Issue by jeisinge** [vespa-engine/vespa#20364]
**Is your feature request related to a problem? Please describe.**
As I have been reading through the documentation, page by page, I noticed that not all documentation is available on the sidebar's table of contents.  Some of it is listed in an overview page like https://docs.vespa.ai/en/performance/ .

Others are just available from links within other docs and the search like https://docs.vespa.ai/en/reference/document-v1-api-reference.html .

It is not clear to me why not all pages are available on the table of contents.  It is not clear to me why some high-level headings have summary pages and others do not.

**Describe the solution you'd like**
Have all pages have a reference in the table of contents.  All or no major headings should have a summary page like performance.

**Describe alternatives you've considered**
I have been just keeping open tabs for pages that aren't in the table of contents.

**Additional context**
The lowest priority!

**Comment by kkraune** [comment]
yes, very good points! I'll auto-generate/create a complete TOC. The sidebar might get too crowded with all the docs, but will consider. We are underway revamping all the docs these days, so this feedback is appreciated! Feel free to add more comments about minor and major issues, very useful.

**Comment by kkraune** [comment]
With https://github.com/vespa-engine/documentation/pull/1747, all docs are navigable from https://docs.vespa.ai/sitemap.html / the sidebar (same content). I'll work some more on improving the categorisation / merge a few related, small docs to make it more accessible, but everything is there now
