### ISSUE TITLE
Stemmed terms option in vespa semantic rules language

### ISSUE THREAD

**Issue by romanhwix** [vespa-engine/vespa#20388]
**Is your feature request related to a problem? Please describe.**
It is tedious and error prone to explicitly use synonyms to define all possible conjugations, declensions, and inflections of a word or of a compound word.

**Describe the solution you'd like**
I want to have option in vespa semantic rules language which inferences stemmed form of  compound words automatically. For instance: "criminal boys" becomes "crimin boy".

I want to use it in scope with this issue https://github.com/vespa-engine/vespa/issues/20386
It allows to implement synonym enrichment in the most short and clean way.

**Comment by bratseth** [comment]
Support proper stemmed matching in rule bases: https://github.com/vespa-engine/vespa/pull/20741

**Comment by bratseth** [comment]
Documentation: https://github.com/vespa-engine/documentation/pull/1748

**Comment by bratseth** [comment]
This will be available in the 7.526 release. Sorry for taking so long!

**Comment by bratseth** [comment]
This is on by default. Set @language(ISO 639-1 2-letter code) to match by stem in another language than english.
