### ISSUE TITLE
YQL parsing of large multi-valued query operators (weightedSet/dotProduct/wand/weakAnd) 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20481]
This is based on an observation from the wild where a Vespa user was using [weightedset query operator](https://docs.vespa.ai/en/performance/feature-tuning.html#multi-lookup-set-filtering) for large sets. With about 1000 keys the YQL parsing took around 10 ms which compared to backend execution was close to 3x. 

I think this is a problem with many of the [multi-valued query operators](https://docs.vespa.ai/en/multivalue-query-operators.html) like weightedSet, dotProduct where YQL parsing becomes a bottleneck with large inputs. 

I think we should have some native parameter/searcher implementation to accept large set filter inputs outside of YQL, maybe similar to [this PR](https://github.com/vespa-engine/sample-apps/pull/770)

**Comment by sternr** [comment]
Perhaps we need a more robust search API that allows separating the actual query from parameters so we could cache query parsing (similar to preparedStatements in traditional DBs)

**Comment by jonmv** [comment]
#20513 should reduce the time spent parsing that YQL by a factor ~2-2.5. It affects parsing of large wand, dotProduct, and weightedSet items. Using a custom encoding is still quite a bit faster, though.

**Comment by bratseth** [comment]
https://github.com/vespa-engine/vespa/pull/20665 adds support for supplying the term list in those operators externally to the YQL expression. That brings parse time for a weighted set with 1000 items down to about 0.5 ms. The remainder is number parsing cost.

**Comment by bratseth** [comment]
Documentation: https://github.com/vespa-engine/documentation/pull/1743
