### ISSUE TITLE
Missing documentation on fast-rank for tensors 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20561]
I don't think I have read anywhere about having to add fast-search to mixed tensors. I see that these are annotated with fast-search https://github.com/vespa-engine/system-test/blob/master/tests/performance/mixed_tensors/vec_256/test.sd. Is it needed or is "fast" operations default by now? 

Secondly, it could look like constant tensor part of the application package lacks this fast support?

**Comment by geirst** [comment]
First, summarise the performance differences between the default and 'fast-search' implementation for sparse/mixed tensors. Then we can decide whether we should document the flag (perhaps find a better name?) or collapse down to one implementation.

**Comment by kkraune** [comment]
I changed the title from "Missing documentation on fast-search for high order tensors" to "Missing documentation on fast-search for tensors" as this applies generally. I had a question yesterday on tensor memory usage and fast-search so lets add the missing details / conclude on naming.

By using fast-search, the tensor is only stored de-serialized (not in addition), so the behaviour is a little different than adding an index structure, but easily documented

**Comment by kkraune** [comment]
the name of the feature is blocking documentation - alternatives:
* _fast-search_. as-is, but at bit awkward name, is this really is _fast-ranking_
* _fast-ranking_
* _de-serialized_

please add suggestions to naming, so we can decide. another alternative is to always store de-serialized, and add an option like _memory-optimized_ instead

**Comment by kkraune** [comment]
work note for later documentation: A customer reported ``` Also, when I removed the fast-search attribute from the tensors, the memory usage dropped quite a bit (~59% to 25%) and our largest tensor field went from ~4.3GB to ~1GB.``` , so the memory different can be significant.

**Comment by kkraune** [comment]
Decision from architect meeting:
* call the setting for deserialised tensor `fast-rank`
* let Arne evaluate whether we _actually_ need it - if the speedup for given cases is worth the extra feature
** if so, rename to fast-rank and document it
** if not, let fast-search be a no-op for tensors, eventually fail it once no-one uses it

**Comment by jobergum** [comment]
I think we have demonstrated in many cases that fast-rank achieve a significant speedup and I would like to add fast-rank to the core album-recommendation sample apps which use sparse tensor dot product.

**Comment by geirst** [comment]
New reference doc: https://docs.vespa.ai/en/reference/schema-reference.html#attribute
Tensor performance considerations updated: https://docs.vespa.ai/en/tensor-user-guide.html#performance-considerations
