### ISSUE TITLE
Quick start docker requirements and default jvm min=max settings

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20788]
**Describe the bug**
Regarding https://docs.vespa.ai/en/vespa-quick-start.html

> do I really need 6GB of ram to index 3 small json files?
>I can not pass the guide for Vespa (I have 3GB for docker only. Maybe the reason)

![image](https://user-images.githubusercontent.com/20928528/149291281-0490cea2-2239-43ea-b6cd-72ebbc092dd7.png)

I agree with this, requiring 6!GB of RAM is a turn-off. The majority here is the default 1.5G where max=min for the stateless container.

**Comment by jobergum** [comment]
This is from just after starting and deploying the quick start app:

```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O       PIDS
a9080bfd4e65   vespa     44.38%    2.832GiB / 7.773GiB   36.43%    11.5kB / 13.8kB   480MB / 482MB   869
```

**Comment by jobergum** [comment]
Reducing stateless container jvm defaults by 

```
 <nodes>
            <jvm options="-Xms128M -Xmx512M"/>
            <node hostalias="node1">
            </node>
  </nodes>
```


```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT    MEM %     NET I/O        BLOCK I/O        PIDS
f7d1a12b98d0   vespa     41.83%    2.08GiB / 7.773GiB   26.76%    5.1kB / 811B   2.44MB / 483MB   871
```

**Comment by jobergum** [comment]
Per process

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                
  276 vespa     20   0 4560604 868580  29916 S   6.3 10.7   1:35.50 java -Xms128m -Xmx2048m -XX:+PreserveFramePointer -XX:+HeapDumpOnOutOfMemoryError -XX:+
  881 vespa     20   0 2487108 470240  28476 S   7.0  5.8   1:05.06 java -Dconfig.id=default/container.0 -XX:+PreserveFramePointer -XX:ActiveProcessorCoun+
  887 vespa     20   0  920088 196400  28616 S   0.7  2.4   0:22.51 java -Dconfig.id=admin/metrics/vespa-container -XX:+PreserveFramePointer -XX:ActivePro+
  885 vespa     20   0  811560 183436  27028 S   4.0  2.3   0:33.89 java -Dconfig.id=admin/cluster-controllers/0 -XX:+PreserveFramePointer -XX:ActiveProce+
  883 vespa     20   0  435872 137000  61444 S   8.6  1.7   0:28.31 /opt/vespa/sbin/vespa-proton-bin --identity music/search/cluster.music/0 --serviceiden+
  884 vespa     20   0  326336  96832  52868 S  10.0  1.2   0:31.78 /opt/vespa/sbin/vespa-distributord-bin -c music/distributor/0                          
  560 vespa     20   0  716324  92200  27284 S   2.7  1.1   0:24.53 java -Xms32M -Xmx128M -XX:CompressedClassSpaceSize=32m -XX:MaxDirectMemorySize=32m -XX+
  882 vespa     20   0  850004  69988  27000 S   0.7  0.9   0:03.85 java -server -Xms32m -Xmx256m -XX:CompressedClassSpaceSize=32m -XX:MaxDirectMemorySize+
  275 vespa     20   0   69596  29604   1784 S   0.0  0.4   0:00.43 vespa-runserver -s configserver -r 30 -p /opt/vespa/var/run/configserver.pid -- java -+
  888 vespa     20   0  122240  16400  13224 S   0.7  0.2   0:01.61 sbin/vespa-logd                                                                        
  886 vespa     20   0  112008  14536  12080 S   1.3  0.2   0:03.28 /opt/vespa/sbin/vespa-slobrok -N -p 19099 -c admin/slobrok.0                           
  853 vespa     20   0  119572  13948  11548 S   0.7  0.2   0:02.82 sbin/vespa-config-sentinel -c hosts/vespa-container     
```

**Comment by kkraune** [comment]
Most of the guides/sample apps have the same requirements, and this will potentially get more complicated in the future with more CPU architectures. It is easier if we can write this once, and include everywhere - options:
* link to a common place
* use a liquid macro (like we do for notes)

The latter can also be parametrized, say for memory, so can use the same macro for different requirements.

In the shared place for the requirements, we can also link to resources for how to shrink requirements, like https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA

I think most of the guides can do with 4G (not sure where the 6G came from, this used to be 4G) - once we have settled on how to link / include, I can change it per guide - taking this ticket myself

**Comment by kkraune** [comment]
The guides are updated, almost all can do with 4G. the Pre-req section now also links to the multinode-HA app for how to shrink container usage, for those that need to run on even smaller containers
