### ISSUE TITLE
vespa-cli: vespa log fails with invalid period 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20786]
```
$ vespa log
Error: Invalid period
parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

**To Reproduce**
Run through https://docs.vespa.ai/en/vespa-quick-start.html

**Environment (please complete the following information):**
 - MacOS/Darwin

**Vespa version**
```
vespa version
vespa version 7.508.20 compiled with go1.17.3 on darwin/amd64
```

**Comment by mpolden** [comment]
Looks like this is just a lack of argument validation. You have to provide at least one argument:
```Examples:
$ vespa log 1h
$ vespa log --nldequote=false 10m
$ vespa log --from 2021-08-25T15:00:00Z --to 2021-08-26T02:00:00Z
$ vespa log --follow
```

I suppose we could default to `1h` if nothing is given.

**Comment by jobergum** [comment]
Great @mpolden! Seems like it's not supported yet for local deployments which I'm using.

**Comment by mpolden** [comment]
Yes, unfortunately there is no way for Vespa CLI to access logs inside the Docker container because the logserver is not started by default i non-cloud deployments.
