### ISSUE TITLE
querybuilder UI thinks 'query' is an unknown request parameter

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20795]
The native query parameter is not included in the drop list. 

![Screenshot 2022-01-13 at 12 33 49](https://user-images.githubusercontent.com/20928528/149323095-763faebf-9f20-4cf2-89b0-4971615081a7.png)

**Comment by kkraune** [comment]
model.queryString is available at https://github.com/vespa-engine/vespa/tree/master/client/js/app

the query builder does not support aliases (as of today)
