### ISSUE TITLE
Add links from documentation to blog posts

### ISSUE THREAD

**Issue by jeisinge** [vespa-engine/vespa#20805]
**Is your feature request related to a problem? Please describe.**
The documentation describes the what great.  But, context and examples are sometimes missing.  The blog posts describe the why and examples great.  And, there are great links from the blog posts to the documentation.  However, there are missing links the other way --- from the reference documentation to the blog posts.

**Describe the solution you'd like**
For every link in the blog posts to the documentation, it would be great to have a link going the other way from the documentation to the blog post.

**Describe alternatives you've considered**
Read all of the documentation.  And, then read all of the blog posts.

**Additional context**
For example:
https://blog.vespa.ai/pretrained-transformer-language-models-for-search-part-2/ points to https://docs.vespa.ai/en/reference/query-language-reference.html#rank  But, there is no link the other way.

**Comment by kkraune** [comment]
great idea! I'll extract links, find docs and link back where appropriate

**Comment by kkraune** [comment]
This is ongoing, some links are added, more will be added as we go - thanks for submitting!
