### ISSUE TITLE
vespa document should print payload if operation fails with http != 200

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#20855]
Feedback on https://docs.vespa.ai/en/vespa-quick-start-java.html

When trying to feed documents on step #8
```
vespa document src/test/resources/A-Head-Full-of-Dreams.json 
```
If the system rejects due to resource limits:

```
Error: Container (document API) at 127.0.0.1:8080: 507 Insufficient Storage
```
Using the -v option and reproducing with curl the message is clearer:

```
{"pathId":"/document/v1/mynamespace/music/docid/a-head-full-of-dreams","id":"id:mynamespace:music::a-head-full-of-dreams","message":"[UNKNOWN(251009) @ tcp/vespa-container:19112/default]: ReturnCode(NO_SPACE, External feed is blocked due to resource exhaustion: disk on node 0 [vespa-container] (0.840 > 0.800)) "}%
```

**Comment by ean** [comment]
@jobergum could you try with the latest Vespa CLI version? This work as expected for me:

```
$ vespa document src//test/resources/A-Head-Full-of-Dreams.json
Error: Container (document API) at 127.0.0.1:8080: 507 Insufficient Storage

{
    "pathId": "/document/v1/mynamespace/music/docid/a-head-full-of-dreams",
    "id": "id:mynamespace:music::a-head-full-of-dreams",
    "message": "[UNKNOWN(251009) @ tcp/vespa-container:19112/default]: ReturnCode(NO_SPACE, External feed is blocked due to resource exhaustion: disk on node 0 [vespa-container] (0.824 > 0.750)) "
}
```

**Comment by jobergum** [comment]
Thanks

**Comment by diliprk-nference** [comment]
I just installed `vespa-cli` today using `brew` on a linux server machine and I still keep getting this same error, how to resolve this issue?
![vespa cli issues](https://user-images.githubusercontent.com/112689391/217445019-5ca4cb90-9c0d-4ff0-a62f-a4bf128a1301.png)

**Comment by jobergum** [comment]
This issue was about getting the rejection printed, which works fine in the above screenshot. 

The underlying issue is that your storage subsystem utilization is above 75%, and Vespa block feed operations. See [feed block documentation](https://docs.vespa.ai/en/operations/feed-block.html)
