### ISSUE TITLE
Bug when creating transformer pipeline in sample-apps/transformers

### ISSUE THREAD

**Issue by Brandhsu** [vespa-engine/vespa#20893]
**Describe the bug**

Not a vespa related bug, however, the transformer pipeline cannot be created in [sample-apps/transformers](https://github.com/vespa-engine/sample-apps/blob/master/transformers/). 

**To Reproduce**
Issue is here: https://github.com/vespa-engine/sample-apps/blob/master/transformers/src/python/setup-model.py#L16

**Fix**
```python
pipeline = transformers.pipeline("text-classification", model=model_name)
```

**Environment**
 - OS: macOS 10.15.7
 - Python: 3.9.7
     - PyTorch: 1.10.1
     - Transformers: 4.15.0

**Comment by kkraune** [comment]
CC @jobergum

**Comment by jobergum** [comment]
Thanks, fixed by https://github.com/vespa-engine/sample-apps/pull/817

**Comment by Brandhsu** [comment]
Yes, also saw some other tutorials following the same style of pipeline declaration that would also encounter the same error https://github.com/vespa-engine/sample-apps/search?q=transformers.Pipeline

**Comment by jobergum** [comment]
The DPR model is pinned to a given transformer version, as it does not work with recent updates to the transformer library.

**Comment by jobergum** [comment]
Thanks for reporting this @Brandhsu !

**Comment by Brandhsu** [comment]
Yes @jobergum, also there is a similar issue with the `pyvespa` package, I encountered it when doing the [stateless model serving](https://pyvespa.readthedocs.io/en/latest/use_cases/sequence-classification-task-with-vespa-cloud.html).

**Comment by kkraune** [comment]
@thigm85 please take a look at the pyvespa problem
