### ISSUE TITLE
Support boolean fields in GC expressions

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#21286]

**Comment by bratseth** [comment]
In addition, the Java parser does not support booleans.

**Comment by vekterli** [comment]
> Well that is something we can change, to implement boolean support properly.

Do we want to do this at the same time as adding fundamental bool field support, or should we consider these separately? The former likely takes rather more effort than the latter.

**Comment by vekterli** [comment]
It's not that I expect it to be "hard"™, but with how boolean constants are modelled and wired today it does require changing the C++ parser grammar and/or AST structure, so it's more work than just adding an extra type to the existing field value extraction logic. Hence the question on whether we should split this into two tasks (bool _field_ support vs. proper bool _expression_ support) 🎶🎷🦖
