### ISSUE TITLE
Bulk Query in Vespa

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#21330]
Hi, 

What is the recommendation for fetching a huge number documents from Vespa?
From our understanding there a two ways to request large number of documents from vespa which are - visit operation and by increasing the max hits from query-profile. 
What is the typical turnaround time of visit rest api as compared to query api with huge max hits example 50k hits? 
Could you also tell us which one is more suitable and what are the tradeoffs between using visit and max hits for fetching huge number or documents,

Thanks

**Comment by kkraune** [comment]
https://docs.vespa.ai/en/faq.html#how-to-extract-more-than-400-hits--query-and-get-all-documents

**Comment by kkraune** [comment]
A visit can take many minutes / hours, the query API is built for realtime operations in seconds

**Comment by 107dipan** [comment]
What does the minutes vs hours depend on?

**Comment by kkraune** [comment]
these are different interfaces built for different purposes

**Comment by 107dipan** [comment]
Hey @kkraune,
I wanted to understand more about the visit operation and I was thinking of checking the code for a better understanding of the visit operation. Could you tell me from which class/interface I can start if I want to do a deep dive. 

Thanks!

**Comment by 107dipan** [comment]
Hey @kkraune, 
Just wanted to know on what factors the visit operation time will depend upon. 
Is it a factor of the documents we have requested or something else.

**Comment by kkraune** [comment]
visit is a linear scan over all documents. if using a selection string, it will might return a smaller document set, but still need to iterate over the full corpus
