### ISSUE TITLE
Latency / Efficiency Results for the Open-Domain Question Answering Experiments

### ISSUE THREAD

**Issue by ccsasuke** [vespa-engine/vespa#21386]
**Is your feature request related to a problem? Please describe.**
Currently the Open-Domain Question Answering (ODQA) experiments (https://github.com/vespa-engine/sample-apps/blob/master/dense-passage-retrieval-with-ann/README.md) only provide the accuracy, but not latency.

**Describe the solution you'd like**
Could you add either the latency or processing speed to the dense, sparse, and hybrid models under the "Retriever Accuracy Summary" section, in addition to the accuracy numbers? Speed is another important consideration in addition to accuracies when comparing the three types of methods.

**Describe alternatives you've considered**
N/A

**Additional context**

This is the table I'm referring to in this doc: https://github.com/vespa-engine/sample-apps/blob/master/dense-passage-retrieval-with-ann/README.md#retriever-accuracy-summary

Retrieval Model | Recall@1 | Recall@5 | Recall@10 | Recall@20
-- | -- | -- | -- | --
sparse (WAND bm25) | 23.77 | 44.24 | 52.69 | 61.47
dense (nearest neighbor) | 46.37 | 68.53 | 75.07 | 80.36
hybrid (WAND + nearest neighbor) | 40.61 | 69.25 | 75.96 | 80.44

Could you provide how long it takes each model to produce the results on the same NQ-open.dev.jsonl data?

Thank you!

**Comment by jobergum** [comment]
Thank you for the detailed writeup @ccsasuke, 

We did not provide performance/efficiency numbers for this sample application. We did though for the [ms macro ranking](https://github.com/vespa-engine/sample-apps/blob/master/msmarco-ranking/passage-ranking.md) application, described in this [blog post](https://blog.vespa.ai/pretrained-transformer-language-models-for-search-part-4/). In that app, we compare end-to-end efficiency versus accuracy. 

For pure retrieval with 21M passages, sparse using WAND will be roughly 20 ms end to end, dense including query encoding and the nearest neighbor search will be roughly 30 ms (10 ms for ANN, 20 ms for query encoding with BERT). Hybrid will be approx the same. These are rough numbers. Re-training the dense embedded using e.g. a smaller model like MiniLM will reduce the cost of both the ANN search due to lower dimensionality and the query encoding.

**Comment by ccsasuke** [comment]
@jobergum Thanks for the prompt response! A couple of quick clarification questions regarding the MS MARCO latencies.

In the blog post, I see the following table regarding the latency:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/1481766/155760628-2185e40e-d078-49dd-bd6b-385ab79aa4d2.png">

It seems the average latency is comparable between sparse and dense, while sparse has a much higher P99.9. Which latencies were you referring to when you said sparse is roughly 20ms and dense being 30ms?

Also, you mentioned that the latency of the hybrid model will be similar to the dense one, though not depicted in the table. Is this because the hybrid model uses twice the CPU threads to run sparse and dense in parallel? Otherwise, if it's also using a single CPU thread as shown in the table, wouldn't the latency be roughly the sum of the sparse and dense model (e.g. ~50ms)?

**Comment by jobergum** [comment]
>It seems the average latency is comparable between sparse and dense, while sparse has a much higher P99.9. Which >latencies were you referring to when you said sparse is roughly 20ms and dense being 30ms?

Averages, notice that the dense retrieval method also includes query encoding with the transformer query tower model. It's known that WAND has limitations, and its effectiveness depends highly on the number of query terms, document terms, tf and IDF. Longer queries are generally slower. From the mentioned blog post:

>The dense single stage retriever using approximate nearest neighbor search has on average slightly worse latency than >sparse (wand) but wins in throughput and also less latency variation (e.g 99.9P). It is known that sparse retrieval using >WAND will have different latency or cost depending on the number of query terms in the query. Dense retrieval on the other >hand maps the query terms into a dense representation and is not sensitive to the number of query terms.

Notice also that both the MS Marco work and the DPR work uses CPU for the evaluation of the query transformer.

**Comment by ccsasuke** [comment]
Got it, thank you!

For my last question:

> Also, you mentioned that the latency of the hybrid model will be similar to the dense one, though not depicted in the table. Is this because the hybrid model uses twice the CPU threads to run sparse and dense in parallel? Otherwise, if it's also using a single CPU thread as shown in the table, wouldn't the latency be roughly the sum of the sparse and dense model (e.g. ~50ms)?

Is my assumption correct that if the hybrid model is also using the same number of CPU threads as the dense and sparse models (i.e. 1 CPU thread as shown in the table), the latency would be around 50ms?

**Comment by jobergum** [comment]
>EDIT: Reading your comment again, as you mentioned 21M passages which is the number of passages in Wikipedia rather >than MS MARCO, is your comment referring to what the latency would be for ODQA instead of on MS MARCO? If so, why is >the MS MARCO average latency of the dense model only 18ms if BERT encoding itself takes about 20ms?

The dense embedding model used for the MS Marco work is based on a 6 layer MiniLM model which has only 22M parameters, which is much more CPU friendly than the DPR query encoder which is based on BERT-base with 109M parameters. Also these are ballpark numbers, I don't have a running instance with this, but I'll consider re-running the experiments based on your interest :=) 

>Also, you mentioned that the latency of the hybrid model will be similar to the dense one, though not depicted in the table. >Is this because the hybrid model uses twice the CPU threads to run sparse and dense in parallel? 
If you built the hybrid retrieval based on two independent retrieval systems then this would be the case, same latency but 2x cost, or 2x latency with the same cost. 

Vespa can do an OR of NN and WAND in the same query (Similar to the Unicorn implementation). See also [this blog post](https://blog.vespa.ai/pretrained-transformer-language-models-for-search-part-2/#:~:text=Hybrid%20Dense%20Sparse%20Retrieval) so it's not necessarily 2x cost.

**Comment by jobergum** [comment]
>Is my assumption correct that if the hybrid model is also using the same number of CPU threads as the dense and sparse >models (i.e. 1 CPU thread as shown in the table), the latency would be around 50ms?

You can combine NN with WAND three ways, and it will be a single thread (or many threads if you have enabled that). 

NN OR WAND
RANK(NN,WAND)
RANK(WAND,NN) 

Where the RANK query operator, only does retrieval using the first operand, and second or third operands are only used to produce ranking features. NN OR WAND is more expensive than RANK(NN,WAND), the latter is then an approximation where you only retrieve using embedding representation but can calculate sparse ranking features, like BM25 for the top-k documents retrieved by the vector search. In practice, this work pretty well as NN is pretty good at recall@k so the recall@k does not improve that much from having the sparse signal separately.

**Comment by ccsasuke** [comment]
Thank you for the detailed explanation, @jobergum!

It would be great if you plan to re-run the experiments on ODQA with real latency numbers for the hybrid model! It would also be super nice if you can compare the accuracy and speed of the "NN OR WAND" and "RANK(NN, WAND)" variants.
I'm crossing my fingers that you'll find some time to run this experiment. 🤞

**Comment by jobergum** [comment]
You are only interested in the retriever stage of ODQA so recall@k and not the end-to-end EM metric? Yeah, it might be interesting to re-do this as there are some benchmarks coming out using 768 dims.

**Comment by ccsasuke** [comment]
Yes, I'm primarily interested in the the retrieval stage of ODQA.

**Comment by ccsasuke** [comment]
And since you mentioned the number of dimensions, I wonder if you have any insights in how the latency of ANN search scales with the number of dimensions? For instance, for a dense model with 2*768 dimensions, would its latency be roughly twice of a standard 768d model, or would it be less than that?

**Comment by jobergum** [comment]
>Yes, I'm primarily interested in the retrieval stage of ODQA.

Great, got it. 
>And since you mentioned the number of dimensions, I wonder if you have any insights in how the latency of ANN search >scales with the number of dimensions? For instance, for a dense model with 2*768 dimensions, would its latency be >roughly twice of a standard 768d model, or would it be less than that?

For brute force exact search, the complexity of each distance calculation would be 2x with 2x dimensions, for approximate it's more complicated since the search is strongly sub-linear and depending on the vector recall@k (exact versus approximate) target, but for the same recall@k with the same amount of distance calculations, it would also be 2x.

**Comment by baldersheim** [comment]
@jobergum Anything more todo here ? **soon** label has timed out.

**Comment by jobergum** [comment]
I think it doesn't make much sense at the moment, Vespa now supports GPU for query encoding and almost 3 years have passed since DPR was relevant.
