### ISSUE TITLE
Analytics vs. Big Data Serving

### ISSUE THREAD

**Issue by nehajatav** [vespa-engine/vespa#21543]
Hi Vespa team, I was going over [this page](https://vespa.ai/vespa-elastic-solr) to decide whether Elasticsearch or Vespa is the right choice for our use case. I came across the comparison that while elastic is good for massive datasets, vespa is not quite right for it. What is it about vespa which does NOT make it the right choice for huge data sets. Is 100m documents data set massive in that sense?

**Comment by bratseth** [comment]
100 millions of docs is not a massive data set, no.
Vespa applications regularly has billions of docs.
As is says on that page: "Massive data sets (**trillion of docs**)"

The point of that page is: If you can tolerate latencies in the seconds, have low qps, and only does append of new docs, never updates/removes to existing data, then you can do certain optimizations that Vespa don't do.

**Comment by jobergum** [comment]
Massive means trillions. As quoted on that page

>Massive data sets (trillion of docs) are cheap

Analytic data is written once, append-only, and documents are never updated, plus the query rate is very low and latency in the seconds is acceptable. Vespa system architecture is designed for single-digit ms response times with more data structures locked in memory for faster access and for fast true updates. 

> Is 100m documents data set massive in that sense?

No, it's not. [Here](https://blog.vespa.ai/billion-scale-knn-part-two/) is an example of 1B documents on a single Vespa content node.

**Comment by jobergum** [comment]
That said, we will soon add options for reducing memory usage by not requiring it to be "locked" in memory, but instead allowing touching disk.

**Comment by nehajatav** [comment]
> The point of that page is: If you can tolerate latencies in the seconds, have low qps, and only does append of new docs, never updates/removes to existing data, then you can do certain optimizations that Vespa don't do.

Thanks that's helpful!
