### ISSUE TITLE
New content group serving requests before data is completely replicated

### ISSUE THREAD

**Issue by canem-inops** [vespa-engine/vespa#21557]
**Describe the bug**

Extra context: https://vespatalk.slack.com/archives/C01QNBPPNT1/p1646403949536739

When scaling a cluster with a new [content group](https://docs.vespa.ai/en/performance/sizing-search.html#data-distribution) the new group starts serving requests before the data is completely replicated in its node. 

**To Reproduce**
1. Setup a cluster with 2 content groups as described in services_old.xml.txt: 4 content nodes per group
2. Index content in a schema (around 22M documents)
3. Start serving requests from this cluster
4. Scale up the cluster with a new group using a different number of nodes and hardware configuration (as described in services_new.xml.txt): 36 content nodes in the new group
5. Republish application with this new services.xml

**Expected behavior**
It was expected that the new content group would only process requests after the whole data is replicated in its nodes.

However, with only 500k documents available requests were being served from there.

**Environment (please complete the following information):**
 - OS: Linux
 - Infrastructure: GCP

**Vespa version**
Vespa version: 7.398.17

**Additional context**
[services_new.xml.txt](https://github.com/vespa-engine/vespa/files/8187128/services_new.xml.txt)
[services_old.xml.txt](https://github.com/vespa-engine/vespa/files/8187129/services_old.xml.txt)

Coverage results from the same query:

//When query hits old group
    "coverage": {
      "coverage": 100,
      "documents": 22770336,
      "full": true,
      "nodes": 4,
      "results": 1,
      "resultsFull": 1
    },

//When query hits new group
    "coverage": {
      "coverage": 100,
      "documents": 542232,
      "full": true,
      "nodes": 36,
      "results": 1,
      "resultsFull": 1
    }

**Comment by bratseth** [comment]
Thanks for the clear bug report.

The version you are running is very old and we have made significant changes to the dispatching algorithm since.
I've throughly reviewed the relevant code on head and I don't see any way this can possibly happen due to groups having different sizes or any other condition. I suggest you upgrade.

**Comment by canem-inops** [comment]
Thanks @bratseth !
