### ISSUE TITLE
struct-fields disappearing in 7.557.46

### ISSUE THREAD

**Issue by arnej27959** [vespa-engine/vespa#21682]
Some structs are returned as empty after upgrading Vespa to new version.
A schema with this:
        struct mystruct {
            field one type string {}
            field two type string {}
            field three type string {}
        }
        field some_stuff type map<string, mystruct> {
            indexing: summary
        }
    }
was suddenly not returning any data in summary.
Expected:
                "fields": {
                    "some_stuff": {
                        "foo": {
                            "three": "3 foo",
                            "one": "1 foo",
                            "two": "2 foo"
                        }
                    }
But got:
                "fields": {
                    "some_stuff": {
                        "foo": {
                        }

This is triggered by having another "struct mystruct" in a different schema.

**Comment by arnej27959** [comment]
Due to changes in internal processing of struct types, the config produced when multiple schemas had structs with the same name was very bogus in 7.557.  Config for one schema was good, but the other would be missing the struct fields:


 documenttype[].datatype[].sstruct.name "mystruct"
 documenttype[].datatype[].sstruct.version 0
 documenttype[].datatype[].sstruct.compression.type NONE
 documenttype[].datatype[].sstruct.compression.level 0
 documenttype[].datatype[].sstruct.compression.threshold 95
 documenttype[].datatype[].sstruct.compression.minsize 200
-documenttype[].datatype[].sstruct.field[].name "one"
-documenttype[].datatype[].sstruct.field[].id 997119011
-documenttype[].datatype[].sstruct.field[].datatype 2
-documenttype[].datatype[].sstruct.field[].detailedtype ""
-documenttype[].datatype[].sstruct.field[].name "two"
-documenttype[].datatype[].sstruct.field[].id 2054688289
-documenttype[].datatype[].sstruct.field[].datatype 2
-documenttype[].datatype[].sstruct.field[].detailedtype ""
-documenttype[].datatype[].sstruct.field[].name "three"
-documenttype[].datatype[].sstruct.field[].id 814368361
-documenttype[].datatype[].sstruct.field[].datatype 2
-documenttype[].datatype[].sstruct.field[].detailedtype ""

**Comment by arnej27959** [comment]
short-term, this is fixed by:
https://github.com/vespa-engine/vespa/pull/21683

**Comment by arnej27959** [comment]
medium-term, we should explicitly fail if same struct name appears in multiple schemas.

Unfortunately, this means users will have to change name of at least one struct, losing data in fields using that struct.  So they have to re-feed data.  The good news is that it doesn't impact JSON input or output format.

**Comment by kkraune** [comment]
I think we can close this with Vespa 8?

**Comment by arnej27959** [comment]
this issue was fixed properly in late 7 versions, definitively all 8 versions are OK for this.
