### ISSUE TITLE
Content nodes failing with the error message "Node not seen in slobrok" for some of the nodes

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#21765]
**Describe the bug**
I have a vespa deployment that is currently running the build 7.559.12. We had a cluster previously setup that had all the data stored in a NAS storage but we also wanted to bring up a cluster with data on emptyDir. To copy we used cp -ap command on static data.
After copy we tried to bring up the cluster but some of the content nodes are showing the error message "Node not seen in slobrok" on the cluster controller page. 
We checked the logs for the content nodes and found this error on the failing nodes
WARNING : searchnode       stderr     vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/searchcore/src/vespa/searchcore/proton/documentmetastore/documentmetastore.cpp:678: virtual void proton::DocumentMetaStore::removeBatch(const std::vector<unsigned int>&, uint32_t): Assertion `validLid(lid)' failed.

We also ran the utility to check proton status got this error
 /opt/vespa/bin/vespa-proton-cmd --local getState
[2022-03-22 07:45:33.321089] 12091/25341 (vespa-proton-cmd.slobrok.mirror) info: successfully connected to location broker tcp/vespa-dip-container-0.vespa-dip-internal.namespace.svc.cluster.local:19099 (mirror initialized with 77 service names)
looking for RTCs matching 'tcp/vespa-dip-content-1.vespa-dip-internal.namespace.svc.cluster.local:' (length 75)
found no local RTC, you must use --id=<name> (list follows):

**To Reproduce**

**Expected behavior**
Content node should come up successfully after application deployment

**Screenshots**

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions [7.559.12]

**Vespa version**
Include Vespa version(s) used.
7.559.12

**Additional context**

**Comment by jobergum** [comment]
Thanks, copying data this way is not something that we support.

**Comment by jobergum** [comment]
```
WARNING : searchnode stderr vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/searchcore/src/vespa/searchcore/proton/documentmetastore/documentmetastore.cpp:678: virtual void proton::DocumentMetaStore::removeBatch(const std::vector&, uint32_t): Assertion `validLid(lid)' failed.
```
Clearly indicates that this copy process did not work. You need immense knowledge of the internals of Vespa to do this in a safe way.
