### ISSUE TITLE
Use FQDN to connect to vespa services instead of localhost in mTLS setup

### ISSUE THREAD

**Issue by adarshaj** [vespa-engine/vespa#21887]
**Describe the bug**
On setting up mTLS, I noticed following warning messages obtained from `vespa-logfmt`
```log
WARNING : configserver     Container.com.yahoo.vespa.config.server.monitoring.ZKMetricUpdater Failure in retrieving monitoring data: (SSLHandshakeException) No subject alternative DNS name matching localhost found.
```
**To Reproduce**
1. Setup vespa with mTLS as described in docs: https://docs.vespa.ai/en/mtls.html
2. After vespa is up and running, run `vespa-logfmt | grep localhost`
3. See warning messages about failure to connect.

**Expected behavior**
When mTLS is setup, use the FQDN of the host to connect to various vespa services, that way the certificate would validate the hostname (or in cases where localhost must be used, disable the hostname checking on the client library used).

**Environment (please complete the following information):**
Any environment will produce same warnings.

**Vespa version**
Tested with vespa version 7.561.60

**Additional context**
The vespa seems to function despite the warning messages, so not sure how it impacts, guessing from log message, we might have some missing metrics?

The warning does go away when cert is issued with `localhost` in SAN, so its definitely a bug.

**Comment by hmusum** [comment]
Fixed in https://github.com/vespa-engine/vespa/pull/21897 (Vespa 7.568.13)
