### ISSUE TITLE
Unable to create threads while using Vespa feed client

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#21980]
**Describe the bug**
Unable to create threads while using feeder java client. We are using the vespa feed client to feed multiple jsons to the vespa cluster. 
After sometime we are getting the exception
pthread_create failed (eagain) for attributes stacksize 1024k

Can someone tell me how I can control the feeder threads so that we do not get this exception. 

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions [e.g. 22]: Feed client 7.561.60

**Vespa version**
Vespa version 7.559.12

**Comment by 107dipan** [comment]
Hey, 

I will check if I can configure it at the kubernetes level but Is there any setting at the container level that we can set in the services.xml to limit the number of threads that are created while feeding to vespa

**Comment by ean** [comment]
Good morning!

How are you running the feed client?

Vespa has some expectations from its runtime environment. If you look at "System Limits" in this document you should have equal or higher limits where you are running Vespa. This goes for the Vespa containers, backend and feeder CLI. The containers and backend will fail if it can't set these values when starting. But the feeder has no such functionality. 

Please ensure that limits for max processes and open files are adjusted before starting the feeder. If the system hard limits are high enough you might not need to do any changes on the Kubernetes infrastructure.

**Comment by 107dipan** [comment]
Hey Erik, 

Thanks a lot! We are using the feeder client and will take a heap dump to see why many threads are getting  created.

**Comment by ean** [comment]
Great. I'll close this for now, but don't hesitate to reopen it if you follow-up questions on this topic.
