### ISSUE TITLE
Option to skip hnsw indexing of a tensor which is unchanged from the current value

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#22025]
Some applications regularly reindex a corpus where much of the data is unchanged but there is not easy way to detect unchanged items from the outside.

It would be nice, and quite cheap, to do this detection inside Vespa by comparing the existing and to-be-written tensor values on the content node before reindexing.

**Comment by geirst** [comment]
Fixed in 8.8.4.
