### ISSUE TITLE
Vespa content nodes are throwing exceptions while bringing up a new cluster

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#22085]
**Describe the bug**
Vespa content nodes are throwing exceptions while bringing up a new cluster. WE are bringing up  a new cluster but we are getting the following exceptions at the content node level. 

bash-4.2$ /opt/vespa/bin/vespa-logfmt | grep stderr
[2022-04-11 12:33:53.597] WARNING : searchnode       stderr     vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/vespalib/src/vespa/vespalib/util/thread.cpp:42: vespalib::Thread::Thread(vespalib::Runnable&, vespalib::Thread::init_fun_t): Assertion `thread != nullptr' failed.
[2022-04-11 12:34:06.608] WARNING : searchnode       stderr     vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/vespalib/src/vespa/vespalib/util/thread.cpp:42: vespalib::Thread::Thread(vespalib::Runnable&, vespalib::Thread::init_fun_t): Assertion `thread != nullptr' failed.
[2022-04-11 12:34:36.719] WARNING : searchnode       stderr     vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/vespalib/src/vespa/vespalib/util/threadstackexecutorbase.cpp:183: void vespalib::ThreadStackExecutorBase::start(uint32_t): Assertion `thread != nullptr' failed.
[2022-04-11 12:36:43.115] WARNING : searchnode       stderr     vespa-proton-bin: /builddir/build/BUILD/vespa-7.559.12/vespalib/src/vespa/vespalib/util/threadstackexecutorbase.cpp:183: void vespalib::ThreadStackExecutorBase::start(uint32_t): Assertion `thread != nullptr' failed.

**Environment (please complete the following information):**
 - Infrastructure: RedShift K8s cluster
 - Versions :7.559.12

Can someone please help us understand what this issue is

**Comment by 107dipan** [comment]
If this issue is related to not able to create threads can u tell us how we can configure this

**Comment by jobergum** [comment]
Vespa content node process (proton-bin) uses [nproc ](https://www.flamingspork.com/blog/2020/11/25/why-you-should-use-nproc-and-not-grep-proc-cpuinfo/)to determine number of logical processors which should be cgroup limits aware.

**Comment by baldersheim** [comment]
How much memory does the nodes have ?
How many cores ?
There are other limits that "max user processes" matters. Could you give the whole output ?

**Comment by 107dipan** [comment]
content:
    requests:
      memory: 32G
      cpu: 4
    limits:
      memory: 64G
      cpu: 10

**Comment by baldersheim** [comment]
Hmm, none of those should kick in here. Then there might be some cgroups stuff.
What does 'cat /sys/fs/cgroup/pids/pids.max' produce ?

**Comment by 107dipan** [comment]
cat /sys/fs/cgroup/pids/pids.max
1024

**Comment by 107dipan** [comment]
Do u mean the total threads created in the content nodes will be (number of schema * configured persearch threads)?

**Comment by 107dipan** [comment]
Can someone help us understand the above query? 
Thanks!

**Comment by kkraune** [comment]
Hi @107dipan . I am working on improving documentation at https://docs.vespa.ai/en/performance/sizing-search.html and https://docs.vespa.ai/en/reference/services-content.html#requestthreads. In particular, @baldersheim details the values for search, persearch and summary exactly (I'll add this to docs) - in your case, given 4 cpu, it should be 8, not 128. @bratseth has also indicated above that is is too high, given your content node configuration.

So, please follow @baldersheim 's suggestion for the three parameters to get the content node started. Then your next step will be to evaluate the query performance, and fine-tune, possibly changing node configuration - the links above are good resources in that process

**Comment by baldersheim** [comment]
Prior to 7.574 it was by default num_schema * X where X depends on number of cores on the node and some other settings.
The summary threads and search threads are global and does not depend on number of schemas.
After 5.574 the number of schemas does not effect the amount of threads needed.

But independent of that 1024 is a too low number.

**Comment by 107dipan** [comment]
I followed @baldersheim suggestion and tuned the content node params such that the search thread is twice the cores and per search thread and summary is equal to the number of cores. Content nodes did not come up with 38 schemas but came up with 5 schemas. 
We are currently using 7.559.12 vespa version. 
Just wanted to confirm..  num_schema * X is the search thread count, right?

**Comment by jobergum** [comment]
>But independent of that 1024 is a too low number.

This is the main point. ^

X refers to threads related to background jobs, indexing, and so on. 

>The summary threads and search threads are global and does not depend on number of schemas.
