### ISSUE TITLE
The hit id when using YQL field selects could be confusing

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#22132]
The rendered `id` field is either the internal id, e.g `index:content-cluster/<node>/850c7a8a2668276578504488` or the reserved `documentid`. This might be confusing, especially for the case of using the default document summary with restrictive YQL field selections

[select id, title from doc where..](https://api.cord19.vespa.ai/search/?query=sars+coronavirus&ranking=bm25&model.defaultIndex=title&yql=select%20id,%20title%20from%20doc%20where%20userQuery()%3B&recall=%2Bid:98739&tracelevel=0) renders

```json
{
  "id": "index:content/3/850c7a8a2668276578504488",
  "relevance": 7.624612895408869,
  "source": "content",
  "fields": {
    "title": "[<hi>SARS</hi> <hi>coronavirus</hi>].",
    "id": 98739
  }
}
```

[select id, title, documentid from doc where..](https://api.cord19.vespa.ai/search/?query=sars+coronavirus&ranking=bm25&model.defaultIndex=title&yql=select%20id,%20documentid%20title%20from%20doc%20where%20userQuery()%3B&recall=%2Bid:98739&tracelevel=0) renders

```json
{
  "id": "id:covid-19:doc::98739",
  "relevance": 7.624612895408869,
  "source": "content",
  "fields": {
    "title": "[<hi>SARS</hi> <hi>coronavirus</hi>].",
    "id": 98739,
    "documentid": "id:covid-19:doc::98739"
  }
}
```

[select * where..](https://api.cord19.vespa.ai/search/?query=sars+coronavirus&ranking=bm25&model.defaultIndex=title&yql=select%20*%20from%20doc%20where%20userQuery()%3B&recall=%2Bid:98739&tracelevel=0) renders

```json
{
  "id": "id:covid-19:doc::98739",
  "relevance": 7.624612895408869,
  "source": "content",
  "fields": {
    "title": "[<hi>SARS</hi> <hi>coronavirus</hi>].",
    "id": 98739,
    "documentid": "id:covid-19:doc::98739"
  }
}
```

**Comment by jobergum** [comment]
Add a documentation note on this in the result template doc, cannot change the behavior in Vespa 7 and Vespa 8 is too soon.

**Comment by kkraune** [comment]
documentation updated in https://github.com/vespa-engine/documentation/pull/1989
