### ISSUE TITLE
Getting the following error while using attribute fields - Could not locate attribute for grouping number 0 : Failed locating attribute vector 'field_name_attr'. Ignoring this grouping

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#22204]
We are getting the above mentioned error message while querying our attribute fields. We have defined a schema where the indexed fields are serving as input for the attribute fields. We are getting this error message for all the attribute fields. 
We have currently defined 3 groups and getting response for our queries even when we get this exception. 

field field_name type array<string> {
            indexing: summary | index
        }

field field_name_attr type array<string> {
            indexing: input field_name | attribute
        }

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions: 7.559.12

**Vespa version**
7.559.12

**Comment by bratseth** [comment]
In the quote above you name it field_name _attr in the field while the error message says field_attr.

**Comment by 107dipan** [comment]
Actually this is not the actual name of the field. The field we are searching with and the query are same.
Sorry for the confusion

**Comment by bratseth** [comment]
Do you search multiple document types?

**Comment by 107dipan** [comment]
Yes, we are doing sources *

**Comment by bratseth** [comment]
And not all of them have these attributes?

**Comment by 107dipan** [comment]
We have defined the document types for all the groups but  different schemas have different fields. They have common fields but also fields that are exclusive to a particulat document type

**Comment by 107dipan** [comment]
Yes

**Comment by bratseth** [comment]
Then you'll get this message for the schemas where it is not present.
You can either ignore it or restrict the search to document types that have the attributes you use in grouping.

**Comment by jobergum** [comment]
Resolving this - this is expected behavior if you dispatch the query to multiple document types and the attribute is not present in all types.

**Comment by 107dipan** [comment]
Thanks a lot!!
