### ISSUE TITLE
Ingestion requests are timing out

### ISSUE THREAD

**Issue by sunil924** [vespa-engine/vespa#22264]
**Describe the bug**
While trying to ingest the data using Jmeter( Thread-1, Loop-10) getting timeout for some of the requests:
Response received: HTTP/1.1 504 Gateway Timeout

This is happening for ~2 request per 10 requests.

Could you please guide how to investigate the issue and fix it.

Infrastructure: RedShift K8s cluster
Versions :7.559.12

**Comment by jobergum** [comment]
This is not necessarily a bug. A timeout could happen. The performance will depend on many things. To name a few:

- The state of your cluster
- Your feed operation (size for example)
- Network connectivity
-  Hardware and Vespa configuration 

Here are a few relevant resources 
- https://docs.vespa.ai/en/performance/sizing-feeding.html
- https://docs.vespa.ai/en/performance/sizing-search.html
- https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA

**Comment by jobergum** [comment]
I'm resolving this, I also want to add https://docs.vespa.ai/en/reference/metrics.html - running Vespa without capturing metrics, both Vespa metrics, but also, system-level metrics like cpu usage, memory usage, disk io is critical.
