### ISSUE TITLE
Errors during conditional writes on a boolean field

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#22342]
**Describe the bug**
I am trying to perform conditional writes on a boolean field but I keep getting "Condition did not match document" message in my response payload. I am able to perform the request for  a string field but getting error for boolean fields. 

{
    "update": "id:namespace:docType::701753105",
    "condition": "docType.isNewWildCardFieldAdded==\"true\"",
    "fields": {
        "wildCardKeyz_s": ["wildCardFieldValuef"]
    }
}

{
    "pathId": "/document/v1/namespace/docType/docid/701753105",
    "id": "id:namespace:docType::701753105",
    "message": "[UNKNOWN(251013) @ tcp/vespa-content-4.vespa-service.namespace.svc.cluster.local:19109/default]: ReturnCode(TEST_AND_SET_CONDITION_FAILED, Condition did not match document nodeIndex=4 bucket=400000000000f627 ) "
}

**Comment by 107dipan** [comment]
Also, could u tell me how we can apply conditional for a array field

**Comment by vekterli** [comment]
Matching a boolean field can be done in two ways
* Comparing against the `true` or `false` literals, or
* Comparing against the integer values 1 or 0

It looks like you're comparing against a string literal, which is not implicitly converted to a bool. Bear in mind that support for comparing against `true` or `false` literals is a fairly recent addition (version 7.577.7 and beyond).

**Comment by 107dipan** [comment]
The field "isNewWildCardFieldAdded" is defined as a bool field and we are using vespa version 7.559.12. Does that mean condition on bool is not supported? 
Also, Can we perform conditional update on an array of struct field.

**Comment by 107dipan** [comment]
Thanks a lot!
This was very helpful.

**Comment by jobergum** [comment]
I'm resolving this support request.
