### ISSUE TITLE
Improve resource sampling for feed blocked

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#22444]
The content node will block feed when close to full, based on sampling of its environment.

This does not work in some environments, ref #22415

Suggestion from @geirst : 

We should improve the memory size sampling done in proton to also include the cgroup property for memory. Currently we use:

```
sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGESIZE)
```

We can probably take the minimum of the above and /sys/fs/cgroup/memory/memory.limit_in_bytes.

**Comment by kkraune** [comment]
These fixes are released in 7.586.113, thanks @toregge !

**Comment by geirst** [comment]
Details on total memory sampling is added to the reference doc: https://github.com/vespa-engine/documentation/pull/2054
