### ISSUE TITLE
Boolean value `true` is bolded in dynamic snippet when using some_field=true in query

### ISSUE THREAD

**Issue by codycollier** [vespa-engine/vespa#22627]
(opening issue per [discussion in the Vespa slack](https://vespatalk.slack.com/archives/C038YTM5SUQ/p1652735252127839))

**Describe the bug**

Imagine a document which contains the word `true`, the word `false`, and the word `baz`.  And imagine the following yql:

```
select * from sources foodoc 
where active=true 
and default contains "baz" limit 2;
```

With that query, my dynamic snippet field with bolding works great, but both `true` and `baz` are bolded from the snippet source text.  I would have expected only `baz` to be bolded.  As a workaround, I can use `!(active=false)` and it works as expected (no bolding of false for instance).

Is this expected, or possibly a bug?

**Expected behavior**

My expectation would be the word `true` is not bolded, since it's a boolean value (active=true).

**Screenshots**
none

**Environment (please complete the following information):**

docker, single node on mac os or linux (happens on both)

**Vespa version**

[7.585.20](https://hub.docker.com/layers/vespa/vespaengine/vespa/7.585.20/images/sha256-5d011af3e2851e03a16706b85c9ea9526b594d3ba120ca3e9941afc51a7e88b4?context=explore)

**Additional context**

Per the discussion in slack, I've applied a filter annotation as a work around.  See the example below, which works great.  However, the discussion indicated the above is still possibly a bug, so I went ahead and opened this issue.

```
select * from sources foodoc 
where ({filter:true}active=true) 
and default contains "baz" limit 2;
```

**Comment by geirst** [comment]
Thanks for reporting this issue. This uncovered a fundamental bug in summary fields using _dynamic_ or _bolding_, where query terms not searching the source field were still used during bolding calculation. This has been fixed in Vespa 8.117.40 (https://github.com/vespa-engine/vespa/pull/25768). More system tests added in https://github.com/vespa-engine/system-test/blob/master/tests/search/bolding/bolding_multiple_fields.rb.
