### ISSUE TITLE
Vespa tenants vs document types trade-offs

### ISSUE THREAD

**Issue by nehajatav** [vespa-engine/vespa#22631]
We manage search platform for 38+ document schemas. We would like to understand 

1. the trade-off between managing these in different doc types versus different tenants
2. how to perform feed and search for a given tenant?

**Comment by kkraune** [comment]
Open-source Vespa is primarily used in single-tenant mode. Refer to https://docs.vespa.ai/en/schemas.html#multiple-schemas and https://docs.vespa.ai/en/federation.html to understand multi-schema usage.

By default, Vespa queries all schemas.

If an application query is across all 38 schemas, Vespa works out of the box, a higher query timeout might be needed  Note that this translates to 38 queries inside Vespa, thread tuning might be needed to lower latency.

If an application query is within one or a few schemas use _restrict_ to query only the required schemas. https://docs.vespa.ai/en/reference/query-api-reference.html#model.restrict . It seems to me from your question that a tenant in your case maps to a schema.

In any case, use https://docs.vespa.ai/en/query-api.html#query-tracing to understand behavior and performance.

**Comment by nehajatav** [comment]
Thanks @kkraune , that's helpful!
