### ISSUE TITLE
Request dispatched to group even though ratio of nodes up is lesser than min-storage-up-ratio

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#22709]
**Describe the bug**
We have a cluster with grouped config where each group has 6 content nodes each. We have set the min-storage-up-ratio to 0.5 but still request is getting dispatched to the group which has only 2/6 content nodes UP. 

**To Reproduce**
1. Deploy the application with Grouped configuration and min-storage-up-ratio to 0.5
2. If using k8s, run the below command to change the number of content nodes
kubectl scale statefulsets vespa-andromeda-content --replicas=14
3. Wait for bucket distribution to complete and fire query with the traceLevel set to 5. 

**Expected behavior**
If ratio of storage node up in a group is less than 0.5 then request should not be dispatched to that group. 

**Screenshots**
From traceLevel logs we can see that the request is getting dispatched to that group "Dispatching to group 2"

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes

**Vespa version**
7.559.12

**Comment by jobergum** [comment]
If your content cluster name is `foo` you can get the group index mapping from 

```
vespa-get-config -n vespa.config.search.dispatch -i default/component/dispatcher.foo
```

Group 2 indicates that you have at least 3 groups as it is 0 indexed. And `min-storage-up-ratio` is not used to control query dispatch behavior.

**Comment by bratseth** [comment]
Dispatch behavior is controlled by this config: https://github.com/vespa-engine/vespa/blob/master/configdefinitions/src/vespa/dispatch.def

**Comment by bjormel** [comment]
Sounds good @107dipan, please reopen the issue if you need more assistance.
