### ISSUE TITLE
Correct metrics in sizing-feeding doc

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#23050]
https://docs.vespa.ai/en/performance/sizing-feeding.html
lists metrics that doesn't appear to exist any more.

At least
```
vds.filestor.alldisks.averagequeuewait.sum
vds.filestor.alldisks.queuesize
vds.filestor.alldisks.allthreads.update.sum.latency
```

**Comment by kkraune** [comment]
I'll take a stab at this once the 8 Docker image is out - there are some changes in https://docs.vespa.ai/en/vespa8-release-notes.html like

vds.filestor.alldisks.*	vds.filestor.*	alldisks has been removed from the metric name.

so the ticket is accurate
