### ISSUE TITLE
Not getting response in document summary using teaser

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#23119]
Hi @geirst, 

This issue is related to https://github.com/vespa-engine/vespa/issues/23099
It was closed and I was unable to reopen the issue. 

I tried using a different field name but I am still facing some issues. I am not getting the field in the response when I am trying to use the document summary with dynamic summary

Changed the document summary to -
document-summary summaryB {

    summary title_teaser type array<string> {
        source: title
        dynamic
    }
}
Document Ingested -
{
"fields": {
"title": ["The content of an indexed string field is language-agnostic. One must therefore apply a symmetric tokenization on the query terms in order to match the content of that field.The query parser subscribes to configuration that tells it what fields are indexed strings, and every query term that targets such a field are run through appropriate tokenization. The language query parameter is what controls the language state of these calls.Because an index may simultaneously contain terms in any number of languages, one can have stemmed variants of one language match the stemmed variants of another. To work around this, store the language of a document in a separate attribute, and apply a filter against that attribute at query-time.If no language parameter is given, the language detector is called to process the query string. The detector is likely to be confused by field names and query syntax, but it is a best-effort approach. This matches the language resolution of the index pipeline.By default, there is no knowledge anywhere that captures what languages are used to generate the content of an index. The language parameter only affects the transformation of query terms that hit tokenized indexes."]
}
}

Search Query -
{
"yql": "select * from sources * where title contains "tokenized";",
"timeout": "120s",
"presentation.summary": "summaryB"
}

Query Response -
{
"root": {
"id": "toplevel",
"relevance": 1.0,
"fields": {
"totalCount": 1
},
"coverage": {
"coverage": 100,
"documents": 1,
"full": true,
"nodes": 6,
"results": 1,
"resultsFull": 1
},
"children": [
{
"id": "index:ddoc/4/c4ca42386cd52a67065b91c5",
"relevance": 0.1620547555884915,
"source": "ddoc",
"fields": {
"sddocname": "testVespaDoc"
}
}
]
}
}

**Comment by geirst** [comment]
This is the feature request for supporting bolding and dynamic summary on array of string fields: https://github.com/vespa-engine/vespa/issues/14173.

**Comment by geirst** [comment]
@107dipan : The _summaryB_ document summary from your example should not pass deployment, as this is not supported. We will use this ticket to fix the schema validation, so this fails at deployment.

**Comment by 107dipan** [comment]
Thanks t @geirst & @jobergum. 
The deployment was successful but I got the warning message that this was not supported. 
"WARNING: For schema 'testVespaDoc', field 'title': Dynamic summaries are only supported for fields of type string, ignoring summary field 'title_teaser' for sd field 'title' of type Array<string>."

**Comment by geirst** [comment]
Thanks @107dipan. I think it is better to fail deployment to avoid confusion for the user.

**Comment by geirst** [comment]
The prioritization of https://github.com/vespa-engine/vespa/issues/14173 has been increased. No need to add more validation now.

**Comment by geirst** [comment]
@107dipan : Support for bolding and dynamic summary on array<string> index fields has been added in 8.53.21. See https://github.com/vespa-engine/vespa/issues/14173 for details.
