### ISSUE TITLE
Vespa content node crashing once in a while

### ISSUE THREAD

**Issue by ashutosh-hs** [vespa-engine/vespa#23215]
**Describe the bug**
we have a running vespa server/cluster (currently it’s single node), we are using pyvespa  to execute queries against it. Sometimes we get following error:
Max retries exceeded with url: /search/ (Caused by ResponseError('too many 503 error responses'))
There wasn’t too much load on vespa server at the time when this issue happened. We see (attached error log file) error messages related to storage in vespa logs, but the cluster recovers on it’s own and starts working fine in sometime.
I have also attached the services.xml where number of threads are defined. Currently there is not much load on the vespa server and number of requests at any moment is hardly in two digits.

**To Reproduce**
We have not been able to pin point yet the exact way to reproduce this issue.
This occurs once in 4-5 days. The content node crashes and recovers few times back to back and then again starts working fine.

**Expected behavior**
Search API shall be working fine.

**Environment (please complete the following information):**
Following are the details of physical machine on which our vespa container is running:
 - OS: Ubuntu (DISTRIB_ID=Ubuntu, DISTRIB_RELEASE=20.04, DISTRIB_CODENAME=focal, DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS") (Linux server-name 5.4.0-104-generic # 118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)
 - Infrastructure: self-hosted (Docker container)
 - Versions : 20.04

**Vespa version**
vespa version: 7.589.25 compiled with go1.17.7 on linux/amd64 
docker image for dockerhub: vespaengine/vespa (Linux vespa-server 5.4.0-104-generic # 118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

**Additional context**
We are running it in a docker container (created using vespa docker image) on a physical machine. The storage to this container comes from the physical machine it’s running on. 

Earlier the storage to this container was coming from nfs mount point from another physical machine. At that time also this issue used to happen and once it happened, the vespa storage cluster was taking much longer to recover. After getting the storage from the same physical machine on which this container is running, the storage cluster recovers in few minutes. 

[vespa_log.txt](https://github.com/vespa-engine/vespa/files/8966298/vespa_log.txt)
[vespa_services.xml.txt](https://github.com/vespa-engine/vespa/files/8966304/vespa_services.xml.txt)

**Comment by jobergum** [comment]
Do you have more logs prior to detection of the node crash?

```
config-sentinel	sentinel.sentinel.service	event	crash/1 name="searchnode" pid=906 signal="Segmentation fault"
```

**Comment by ashutosh-hs** [comment]
Please find attached complete log along with timestamp when we encountered this error.

[vespa_log_2.txt](https://github.com/vespa-engine/vespa/files/8967469/vespa_log_2.txt)

**Comment by ashutosh-hs** [comment]
@jobergum did you get chance to look at the detailed log?

**Comment by kkraune** [comment]
Hi, I am sorry the logs did not help that much. If you are able to provide a backtrace from a core file, we might be able to see where the segfault is.

We see that the searchnode fail just seconds after restart
````
1655304422.720139   searchnode  proton  event   started/1 name="proton"
1655304422.767215   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Node got back into slobrok with same address as before: tcp/vespa-server.weave.local:19104
1655304422.871041   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Altered min distribution bit count from 16 to 8
1655304422.873495   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Altered node state in cluster state from 'M: Connection error: Closed at other end. (Node or switch likely shut down)' to 'U, t 1655304422, b 8'
1655304422.873761   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304422872: Enough nodes available for system to become up
1655304422.874017   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304422872: New cluster state version 53. Change from last: version: 52 => 53, cluster: Down => Up, storage: 0: [Maintenance => Up, minUsedBits: 16 => 8, startTimestamp: 0 => 1655304422, description: Connection error: Closed at other end. (Node or switch likely shut down) => ]
1655304422.874337   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.database.ZooKeeperDatabase info    Cluster 'vespa_cluster_name': Storing new cluster state version in ZooKeeper: 53
1655304427.586179   searchnode  proton.metrics.manager  info    Metrics registration changes detected. Handling changes.
1655304430.997005   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.SystemStateBroadcaster info    Cluster 'vespa_cluster_name': Publishing cluster state version 53
1655304430.998832   searchnode  proton.state.manager    info    Transitioning from baseline state 'Down' to 'Up' (cluster state version 53)
1655304431.102068   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304431102: Reset 1 start timestamps as all available distributors have seen newest cluster state.
1655304431.105754   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Altered node state in cluster state from 'U, t 1655304422, b 8' to 'U, b 8'
1655304431.106065   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304431104: New cluster state version 54. Change from last: version: 53 => 54, storage: 0: startTimestamp: 1655304422 => 0
1655304431.106364   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.database.ZooKeeperDatabase info    Cluster 'vespa_cluster_name': Storing new cluster state version in ZooKeeper: 54
1655304431.309208   container   Container.com.yahoo.search.cluster.BaseNodeMonitor  info    Putting search node key = 0 hostname = vespa-server.weave.local path = 0 in group 0 field_6IsKnown = true working = false activeDocs = 2046 in service: Responds correctly
1655304432.289905   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Failed get node state request: Connection error: Closed at other end. (Node or switch likely shut down)
1655304432.290157   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Failed to get node state: D: Connection error: Closed at other end. (Node or switch likely shut down)
1655304432.291161   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Stopped or possibly crashed after 9420 ms, which is before stable state time period. Premature crash count is now 1.
1655304432.291459   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Altered min distribution bit count from 8 to 16
1655304432.291646   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Node is no longer in slobrok. No pending state request to node.
1655304432.292389   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Added node only event: Event: storage.0: Altered node state in cluster state from 'U, b 8' to 'M: Connection error: Closed at other end. (Node or switch likely shut down)'
1655304432.292509   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304432291: Too few storage nodes available in cluster. Setting cluster state down
1655304432.292613   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.EventLog   info    Cluster event type SYSTEMSTATE @1655304432291: New cluster state version 55. Change from last: version: 54 => 55, cluster: Up => Down, storage: 0: [Up => Maintenance, minUsedBits: 8 => 16, description:  => Connection error: Closed at other end. (Node or switch likely shut down)]
1655304432.292751   container-clustercontroller Container.com.yahoo.vespa.clustercontroller.core.database.ZooKeeperDatabase info    Cluster 'vespa_cluster_name': Storing new cluster state version in ZooKeeper: 55
1655304432.302333   config-sentinel sentinel.sentinel.service   event   crash/1 name="searchnode" pid=6130 signal="Segmentation fault"
````

**Comment by kkraune** [comment]
you can use https://docs.vespa.ai/en/reference/vespa-cmdline-tools.html#vespa-logfmt to increase log levels for more detailed debug or spam output from the searchnode

**Comment by ashutosh-hs** [comment]
@kkraune log file **vespa_log_2.txt** which I have shared above have log for all levels when we encountered this error. 
Also the vespa container didn't crash, only the vespa content node (service) crashed. So is there some vespa doc on how to setup up core dump when node crashes?
In the link which you have shared above, I found **vespa-jvm-dumper**, but that probably has to be run manually. Is there some way to configure this so that it dumps core when node crashes?

**Comment by vekterli** [comment]
@ashutosh-hs please check that your [core dump size limit](https://docs.vespa.ai/en/reference/files-processes-and-ports.html#vespa-system-limits) is set to `unlimited` and the [kernel core pattern](https://docs.vespa.ai/en/reference/files-processes-and-ports.html#core-dumps) is valid. The latter should also give some hint to where the core dumps are stored. If systemd is managing the coredumps, you might have to set [`LimitCORE=infinity`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties) and use `systemd-coredumpctl` to list any cores.

Once you have a core file, you can invoke gdb to get a full thread stack dump. Something like:
```sh
gdb -n -ex 'set print frame-arguments none' -ex 'thread apply all bt' -batch /opt/vespa/sbin/vespa-proton-bin /path/to/my/core/file.core
```

**Comment by jobergum** [comment]
I'm resolving this. Please feel free to re-open if you experience this again.
