### ISSUE TITLE
Ensure last Vespa 7 release RPMs are kept available

### ISSUE THREAD

**Issue by ean** [vespa-engine/vespa#23225]
**Is your feature request related to a problem? Please describe.**
COPR retains RPMs old builds for 14 days. Only the latest (greatest version) is kept.

> We keep one build for each package in one project indefinitely. All other builds (old packages, failed builds) are deleted after 14 days.
> 
> Note that we keep the build with the greatest EPOCH:NAME-VERSION-RELEASE, even though that build might not be the newest one. Also, if there are two builds of the same package version, it is undefined which one is going to be kept.

https://docs.pagure.org/copr.copr/user_documentation.html#how-long-do-you-keep-the-builds
 

**Describe the solution you'd like**
Ensure we keep last stable major releases around for at least the 3 months which is set as the expected migration time.

**Comment by aressem** [comment]
COPR will keep the last Vespa 7 release `7.594.36` indefinitely as described so this is not a problem. Old Vespa releases are kept up to one year in our archive at `https://artifactory.yahooinc.com/artifactory/vespa`.

This repository can be installed by using the config manager like this:
```
dnf config-manager --add-repo https://artifactory.yahooinc.com/artifactory/vespa/vespa.repo
```
