### ISSUE TITLE
Incorrect result degradation response in cases where dispatch fails to connect to a node in a group

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#23412]
Incorrect result degradation response when failing to connect to nodes that are retired or down in a group. 

If a node is retired from a group and all documents are migrated to the other nodes we have a corner case where the dispatcher will claim a degraded response with reduced coverage, even if the other nodes have taken ownership of the documents.

Here in this case with 1B documents indexed and 1B documents searched as shown in the `documents` response, this demonstrates that the search has in-fact coverage of all documents, but the response is still degraded with timeout flagged to true, this is because if fails to connect to the node and incorrectly flags this as a timeout. The issue is resolved when the nodes are removed from the application configuration and the dispatcher no longer sees the nodes. 

```
 "coverage": {
            "coverage": 71,
            "documents": 1000000000,
            "degraded": {
                "match-phase": false,
                "timeout": true,
                "adaptive-timeout": false,
                "non-ideal-state": false
            },
            "full": false,
            "nodes": 5,
            "results": 2,
            "resultsFull": 1
        },
```

With tracelevel=3 one can also see:

```
  "message": "Connection failure on nodes with distribution-keys: .."
```

**To Reproduce**
Related https://github.com/vespa-engine/vespa/issues/22632 (Shutting down a node with searchable-copies=2) - search is complete as shown in the trace, coverage docs before shutting down the node is equal to the number of docs after shutting down the node, still, coverage is claimed to be degraded. 

**Expected behavior**
Not degraded response.

**Comment by baldersheim** [comment]
This was fixed in September as a joint effort with @vekterli
Now coverage estimates are based on actual measured numbers directly from the backend.
This has been correct since 8.60 or so.
