### ISSUE TITLE
common-env.sh with CentOS stream image throws hostname: command not found

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#23469]
**Describe the bug**
```
vespa-get id:news:news::N3818
/opt/vespa/libexec/vespa/common-env.sh: line 332: hostname: command not found
```

**To Reproduce**
docker pull vespaengine/vespa:8.13.21 

cat /etc/redhat-release 
CentOS Stream release 8

**Comment by aressem** [comment]
Fix in https://github.com/vespa-engine/vespa/pull/23471
