### ISSUE TITLE
Add option for short tensor format for vespa-get and vespa-visit 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#23470]
Vespa 8 changes http document api to use short tensor format, 
but vespa-visit and vespa-get tooling still output in long format.

**Comment by geirst** [comment]
Flipping to short tensor format for these tools cannot happen before Vespa 9.

**Comment by vekterli** [comment]
Available through a new `--shorttensors` option for `vespa-visit` and `vespa-get` in 8.95.15 and beyond.
