### ISSUE TITLE
After updating vespa version, seeing an error msg related to config servers after deploying the application zip. 

### ISSUE THREAD

**Issue by shubh9194** [vespa-engine/vespa#23486]
**Describe the bug**
we have single node config server cluster with multiple container and content nodes.
After upgrading from 7.559.12 to 7.589.25 version, I deployed the application zip with the configs but seeing the following message at the end.
Session 2 for tenant 'default' prepared.
Activating session 2 using http://vespa-1016-pvc-new-0.vespa-1016-pvc-new-internal.d19029.svc.cluster.local:19071/application/v2/tenant/default/session/2/active
Request failed. HTTP status code: 500
Timed out waiting for peer config servers to complete operation (waited for barrier /conig/v2/tenants/default/sessions/2/activeBarrier).Got response from [], but need response rom at least 1 server(s). Timeout passed as argument was 119989 ms
command terminated with exit code 1

Cluster is up and running after this but not sure why we are seeing this error msg. It seems to be looking for peer config servers but we have only 1 config server running in our cluster.

**To Reproduce**
Upgrade Vespa version from 7.559.12 to 7.589.25

**Expected behavior**
should be getting msg like this
Session 2 for tenant 'default' activated.
Checksum:   369d99258fcf841ce869b982f165af1b
Timestamp:  1657622226930
Generation: 2

**Comment by jobergum** [comment]
I doubt this is related to the upgraded version. See https://docs.vespa.ai/en/operations/configuration-server.html and especially the operations section.

**Comment by bratseth** [comment]
Yes, it's also waiting for its own local ZooKeeper to complete. I don't know why ZooKeeper timed out in this case, but in any case it's harmless with just one config server.

**Comment by jobergum** [comment]
I'm closing this issue.

**Comment by jobergum** [comment]
So you probably have a large application package and, or very slow disk setup, remote NAS storage, or HDD. You can increase the barrier timeout, see https://docs.vespa.ai/en/operations/configuration-server.html

**Comment by nehajatav** [comment]
Issue is resolved with https://github.com/vespa-engine/vespa/issues/24245
