### ISSUE TITLE
Deploying vespa on aws multi-node localhost error

### ISSUE THREAD

**Issue by DBankx** [vespa-engine/vespa#23552]
Hi, im a new dev in a company i just joined and im not adept with vespa. our vespa service is currently down but the aws instance still says its health and everything is successful. when i ssh into the instance and try to run vespa again to restart it i get an error saying it cannot connect to localhost. Please can anyone help me with this. im currently in a rot. The image below shows the error i get. Any help is welcome. Thanks

<img width="835" alt="Screen Shot 2022-07-28 at 2 49 51 PM" src="https://user-images.githubusercontent.com/61208493/181615079-b4dfa894-7789-457f-a5c8-710fa304ab1f.png">

**Comment by kkraune** [comment]
It could be that the config server on that host is not running - please review https://docs.vespa.ai/en/operations/configuration-server.html

**Comment by DBankx** [comment]
> It could be that the config server on that host is not running - please review https://docs.vespa.ai/en/operations/configuration-server.html

Hi ive checked our hosts.xml file and everything seems to be ok. we have an admin0, stateless0, statless1, content0, content1 aliases there with the correct ip address to our instances

**Comment by kkraune** [comment]
But did you follow the procedure in the doc and validate that a config server is actually running on that host (like using state/v1/health in the start sequence)? deploy_vespa.sh is not a script from the Vespa distribution afaik, so hard to know what it does, unless you paste its content here.

https://docs.vespa.ai/en/overview.html is a great intro to the different kinds of Vespa services, and there is also a managed service at https://cloud.vespa.ai/

**Comment by DBankx** [comment]
hi yes i checked and the config servers are down. ill work on bringing it up

**Comment by DBankx** [comment]
Hi when i try to start the config server i get permission errors as well. im on the  centos user (main user for the ec2 instance). do you know what might be wrong?

<img width="876" alt="Screen Shot 2022-07-29 at 6 11 58 PM" src="https://user-images.githubusercontent.com/61208493/181852188-a5dd897c-0ce0-46db-8766-de76750071b4.png">

**Comment by kkraune** [comment]
It seems like the user starting Vespa does not have the privileges to change the directories? you can inspect the start scripts starting from https://docs.vespa.ai/en/reference/vespa-cmdline-tools.html#vespa-start-services for details. you can try to start Vespa with a user with more privileges?

**Comment by DBankx** [comment]
Hey we used the centos user to start vespa. any idea as to why the user suddenly does not have enough priviledges to start the vespa?. Thanks

**Comment by kkraune** [comment]
I am not sure what you mean by suddenly - what changed before this happened, and does it happen on all nodes?

I suggest you start with something that is known to be working, like https://docs.vespa.ai/en/vespa-quick-start-kubernetes.html (Based on https://app.slack.com/client/T01RFPFNAHX/C038YTM5SUQ/thread/C038YTM5SUQ-1658271844.299179 which I think is the same problem / this is run using kubernetes?)

Then you can run commands like
````
$ kubectl exec vespa-0 -- ls -la /opt/vespa/logs
total 28
drwxr-xr-x 1 vespa vespa 4096 Aug  2 19:19 .
drwxr-xr-x 1 root  root  4096 Aug  2 19:19 ..
drwxr-xr-x 2 vespa vespa 4096 Aug  2 19:09 telegraf
drwxr-xr-x 1 vespa vespa 4096 Aug  3 07:11 vespa
````

````
$ kubectl exec vespa-0 -- ps auxwww | grep vespa | head
vespa        275  0.0  0.3  70912 50364 ?        Ss   07:01   0:01 vespa-runserver -s configserver -r 30 -p /opt/vespa/var/run/configserver.pid -- java -Xms128m -Xmx2048m -XX:+UseTransparentHugePages -XX:+PreserveFramePointer -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/vespa/var/crash -XX:ErrorFile=/opt/vespa/var/crash/hs_err_pid%p.log -XX:+ExitOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:MaxJavaStackTraceDepth=1000000 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED -Djava.io.tmpdir=/opt/vespa/tmp -Djava.library.path=/opt/vespa/lib64 -Djava.security.properties=/opt/vespa/conf/vespa/java.security.override -Djava.awt.headless=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.net.client.defaultConnectTimeout=5000 -Dsun.net.client.defaultReadTimeout=60000 -Djavax.net.ssl.keyStoreType=JKS -Djdk.tls.rejectClientInitiatedRenegotiation=true -Djdisc.config.file=/opt/vespa/var/jdisc_container/configserver.properties -Djdisc.export.packages= -Djdisc.cache.path=/opt/vespa/var/vespa/bundlecache/configserver -Djdisc.bundle.path=/opt/vespa/lib/jars -Djdisc.logger.enabled=false -Djdisc.logger.level=WARNING -Djdisc.logger.tag=configserver -Dfile.encoding=UTF-8 -Dzookeeper_log_file_prefix=/opt/vespa/logs/vespa/zookeeper.configserver -cp /opt/vespa/lib/jars/jdisc_core-jar-with-dependencies.jar com.yahoo.jdisc.core.StandaloneMain standalone-container-jar-with-dependencies.jar
````

**Comment by DBankx** [comment]
Hi thanks for that. i ran the commands you put up and i got these.
![Screen Shot 2022-08-03 at 8 39 01 AM](https://user-images.githubusercontent.com/61208493/182609831-9cd239c7-c9e6-4b71-acc7-c936ea04b9da.png)

Also what i mean by suddenly is that vespa config server was run by the centos user before and now when i try to re run it using the same user it gives me permission errors. so i was asking do you know why im getting those permission errors now?

**Comment by kkraune** [comment]
https://docs.vespa.ai/en/operations/multinode-systems.html#aws is updated, closing
