### ISSUE TITLE
Documentation on internal file formats

### ISSUE THREAD

**Issue by ccleve** [vespa-engine/vespa#23657]
I'm looking for a reference that describes the Vespa internal file formats for dictionaries, postings, etc.. Does such a thing exist?

This doesn't turn up much: https://docs.vespa.ai/search.html?q=file+format

A link to the appropriate place(s) in the source code may do the trick, although a new page on it in the docs would be very helpful.

**Comment by bratseth** [comment]
Dictionaries: https://docs.vespa.ai/en/reference/files-processes-and-ports.html

Index and document store files: https://docs.vespa.ai/en/proton.html

**Comment by ccleve** [comment]
@bratseth Thanks. This is a start, but does not document the actual layouts. I'm interested in the format for the postings lists, compression schemes, etc..

**Comment by bratseth** [comment]
We don't have anything up to date between this and the code.
If you want to dive into that, see https://github.com/vespa-engine/vespa/tree/master/searchlib/src/vespa/searchlib
