### ISSUE TITLE
Onnx runtime in arm64 docker image

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#23673]
**Describe the bug**
When working with the arm64 image, I am having problems when trying to use onxxruntime to infer embeddings. In the screenshot section I show the error. This bug is originated in the onxxruntime library but it has been recently fixed in https://github.com/microsoft/onnxruntime/pull/12335

**To Reproduce**
1. Use BertBaseEmbedder in an arm64 environment

**Expected behavior**
It should load the onnxruntime correctly.

**Screenshots**

![Screenshot 2022-08-16 at 09 52 29](https://user-images.githubusercontent.com/28201311/184828089-58a6ae4f-f4e3-4f54-9a53-dcf36794f405.png)

**Environment:**
 - OS: macOS M1
 - Infrastructure: self-hosted
 - Version: 12.5

**Vespa version**
I am using the version 8.31.22

**Additional context**

**Comment by bratseth** [comment]
Thanks! https://github.com/vespa-engine/vespa/pull/23674

This will be available in 8.36, available Thursday if all goes normally.

**Comment by danitico** [comment]
@bratseth I have tried the new version of the docker image and I encountered the same error. I have been checking the directories and in /opt/vespa-deps/lib64 are located the onnxruntime libraries. I have copied those ones to /opt/vespa/lib64 and everything is working again!

I think the directory /opt/vespa-deps/lib64 should also be added to java.library.path

**Comment by bratseth** [comment]
This didn't fully make it into 8.36 after all, you'll need 8.38. Sorry for the delay.
