### ISSUE TITLE
Custom embedder with custom config definition

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#23675]
**Describe the bug**
I am trying to set up a custom embedder that is really similar to BertBaseEmbedder. When trying to get the path of the tokenizer file, it does not return the absolute path to it but the path to directory in which it is contained.

**To Reproduce**
In the BertBaseEmbedder class happens the same so one can try to set up an example using paths when referring to the vocabulary and the model

**Expected behavior**
It should get the correct absolute path to the file

**Screenshots**
The error I describe
![Screenshot 2022-08-16 at 10 19 12](https://user-images.githubusercontent.com/28201311/184832444-49cb7d6d-01c2-4ac7-91f2-a53c78540d22.png)

services.xml
![Screenshot 2022-08-16 at 10 19 24](https://user-images.githubusercontent.com/28201311/184832473-c9d51ff6-8aa0-4594-ad59-8cfe4f740029.png)

sentence-embedder.def
![Screenshot 2022-08-16 at 10 30 37](https://user-images.githubusercontent.com/28201311/184834697-1face471-dd10-4ba7-ab55-4e5763724b1d.png)

**Environment (please complete the following information):**
 - OS: macOS M1
 - Infrastructure: self-hosted
 - Version 12.5

**Vespa version**
8.31.22

**Additional context**

**Comment by bratseth** [comment]
Embedder configuration syntax allows models to be referenced by path, url or id, so you can say e.g `<model path='...' id='...'/>`. This is so it can be deployed both on self-hosted systems, using path (or url), and Vespa Cloud, using id.

However, it is only supported for certain well-known config definitions. For others you can use the regular config systems for setting a path, `<model>...</model>`. Doing that here solves this issue.

However, I guess this is a common expectation, so I've added support for using <model path='...'> syntax in all embedders in https://github.com/vespa-engine/vespa/pull/23710
