### ISSUE TITLE
Fields with matched-elements-only returns error in response if empty or yql lacks filter on it

### ISSUE THREAD

**Issue by lundin** [vespa-engine/vespa#23913]
Hi,
I am pretty sure this behavior can be classified as bug or at least differs from v7 iirc.

Having a field such as:
` field bodytree type array<bodylocale> {
indexing: summary
struct-field locale    { indexing: attribute }
summary: matched-elements-only
}
`

and documents that is indexed without such field (i.e empty). If i do a YQL query on it:

`'yql=select * from portfolio where sku contains ("4773545") and marketpricetree contains sameElement(marketcode contains ("21"),customergroup contains ("21SC"));`

i.e no bodytree filtering the json response will contain:

`"bodytree" : {
                  "error_message" : "input underflow",
                  "offending_offset" : 0,
                  "partial_result" : null
               },`

The expected results should be no bodytree element returned at all right ?

A document that do have data but an YQL wihout filter/sameElement do correctly results in:

`"bodytree" : [],`

and with a filter/query 

`select sku,bodytree from portfolio where sku contains ("12823312") and bodytree contains sameElement(locale contains ("sv")) and marketpricetree contains sameElement(marketcode contains ("21"), customergroup contains ("21SC"));`

the correct match is returned:

` "bodytree" : [
                  {
                     "name" : "<p><span>R▒ststyrda spr▒k ▒r: engelska, spanska, italienska, tyska, franska, holl▒ndska och portugisiska.</span></p>",
                     "locale" : "sv"
                  }`

**Vespa version**
Vespa v 8.46.19
Vespa Cloud

**Comment by geirst** [comment]
This is fixed by https://github.com/vespa-engine/vespa/pull/23918. Available in 8.48.20.
More system testing added in https://github.com/vespa-engine/system-test/pull/2515.
