### ISSUE TITLE
Support retries for DNS host name resolution on start

### ISSUE THREAD

**Issue by eric-millin** [vespa-engine/vespa#24023]
**Is your feature request related to a problem? Please describe.**
On start, if Vespa cannot resolve the host name, it will exit immediately. This makes it very frustrating to run Vespa in environments that use service discovery to list a custom host name of new containers.

The most notable example is AWS ECS. There is a race condition between when service discovery lists the host name for a new container container and when Vespa checks the name. Vespa will exit immediately despite the host name being resolvable a few seconds later.

E.g.,
1. Service discovery set to add a new DNS record `foo.bar` for a new container
2. New container starts with `VESPA_HOSTNAME=foo.bar`
3. Vespa starts trying to resolve the name.
4. Service discovery sees the new container and adds the record
5. Vespa can now resolve the host name and proceeds

**Describe the solution you'd like**
An option to have Vespa retry host name resolution for N seconds.

**Describe alternatives you've considered**
My current solution to this problem is building my own container that includes a sleep before starting Vespa. It feels hacky and adds unnecessary delay to the container start.

**Additional context**
This feature would make it much easier to scale Vespa on ECS, one of the largest container services in the world.

**Comment by eric-millin** [comment]
FWIW, I would consider PRing this change, but would need a little guidance.

**Comment by kkraune** [comment]
as for PR, if you are able to express to functionality in the pre-start script, it will be easy to transform into a native feature in a PR once validated, so grateful for any contribution here

**Comment by eric-millin** [comment]
That's waiting for the configserver to resolve. The issue I see is when the current host name doesn't resolve. In ECS there's a delay between when the container starts and when service discovery updates the DNS record.

**Comment by kkraune** [comment]
right, I just pasted code for a similar but not identical use case.

I am not sure what the failure is still - the pre-start script is supposed to just exit with 0 or non-zero, and its location put in `VESPA_VALIDATIONSCRIPT` - then `$VESPA_HOME/bin/vespa-start-services` will invoke it (i.e. your script shall not start vespa)

```
$ export VESPA_VALIDATIONSCRIPT=/tmp/my-prestart-check.sh
$ cat /tmp/my-prestart-check.sh
#!/bin/sh
echo detect some problem
exit 1
$ $VESPA_HOME/bin/vespa-start-services
```

**Comment by eric-millin** [comment]
There was a bug (it didn't sleep between iterations) in an earlier version of my script. I fixed it.

**Comment by eric-millin** [comment]
I'll reproduce it again. I suspect the problem is something like this: https://github.com/vespa-engine/vespa/blob/f4d3229d20f1c7ab617efd9ab7067c1d825fa792/vespalib/src/apps/vespa-validate-hostname/validate_hostname.cpp#L43

**Comment by kkraune** [comment]
yes, there are more places in the vespa code that checks for hostnames

**Comment by kkraune** [comment]
just checking in, did you make it work?

**Comment by kkraune** [comment]
Closing. We have made changes to hostname use in recent versions of Vespa
