### ISSUE TITLE
Document processors in system tests are not triggered

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#24068]
**Describe the bug**
When uploading document in system tests, document processors are not triggered correctly. However, if I do that document upload via vespa cli, document processors are triggered correctly.

**To Reproduce**
1. Write a system test that uploads a document of some type that is modified by a document processor and run that test
2. Check if the modified or new fields exists in the uploaded document
3. Delete that document
4. Upload the document via vespa cli
5. Check the document

**Expected behavior**
Document processors should be also triggered in system tests when uploading a document

**Environment (please complete the following information):**
 - OS: MacOS M1
 - Infrastructure: self-hosted

**Vespa version**
8.48.22

**Comment by jobergum** [comment]
Do you have an example of a system test? You mean this https://docs.vespa.ai/en/reference/testing.html ? It uses the exact same document rest api as the `vespa-cli` client. So maybe you have a way to reproduce?

**Comment by danitico** [comment]
I am closing this due to a misconfiguration.
