### ISSUE TITLE
cardinality estimation for filters and queries

### ISSUE THREAD

**Issue by patelprateek** [vespa-engine/vespa#24143]
new to vespa engine. I am trying to use this for some internal dataset
Wanted to get better understanding of some internal details to understand latency and compute resource usage.

When trying to use vector search with some constraints , how exactly we do cardinality estimation for the constraints : are there any documentation or pointers i can read more details , trying to understand how precise are these estimations , are they probabilistic with error bounds or accurate, whats the cost of cardinality estimation vs actually running the query.

**Comment by jobergum** [comment]
This [blog post](https://blog.vespa.ai/constrained-approximate-nearest-neighbor-search/) explains how Vespa performs filters and how we estimate filters. Vespa supports both pre-filtering and post-filtering. I suggest that you start with that and update this ticket with follow up questions.

**Comment by jobergum** [comment]
I'm closing this out @patelprateek. Feel free to re-open if you have questions on this - or join our slack - linked to from https://vespa.ai/support
