### ISSUE TITLE
grouping hits in hitslist is limited to 10 ?

### ISSUE THREAD

**Issue by lundinorio** [vespa-engine/vespa#24229]
**Describe the bug**
One of our YQL queries is no longer returning the same number of hits in hitslist when grouping even if it should be more as before upgrade to vespa 8. (hits and limits should be ok by default to return 12 items see below)

**To Reproduce**
It is hard to replicate without all the data but this YQL now only return 10 max grouped hits (used to return 12) (the same effect for other grouping queries that should return much more, always limited to 10) :

`yql=select grouphierid,cataloguehierid code,sectionnametree, path from saab where cataloguehierid matches ("98065166") and sectionnametree contains sameElement (locale contains ("sv")) | all(group(grouphierid) each(max(1)  each(output(summary()))));`

here is the last item in the hitslist:

`   "children" : [                                                                
   {                                                                          
      "continuation" : {                                                      
         "next" : "BKAAACBCABGBCBC"                                           
      },                                                                      
      "relevance" : 1,                                                        
      "children" : [                                                          
         {                                                                    
            "source" : "orioportalserver",                                    
            "fields" : {                                                      
               "sectionnametree" : [                                          
                  {                                                           
                     **"name" : "V▒rme och ventilation",**                        
                     "locale" : "sv"                                          
                  }                                                           
               ],                                                             
               **"grouphierid" : "98071438",**                                    
               "path" : "9-3 (9440)_8C_0140",                                 
               **"cataloguehierid" : "98065166",**                                
               "code" : "0140"                                                
            },                                                                
            "relevance" : 0.00174291938997821,                                
            "id" : "index:orioportalserver/0/00b4d5ea9fb8452f79f29a76"        
         }                                                                    
      ],                                                                      
      "label" : "hits",                                                       
      "id" : "hitlist:hits"                                                   `

However it misses for example this one (same cataloguehierid, different grouphierid):

`    "children" : [
               {
                  "relevance" : 1,
                  "children" : [
                     {
                        "value" : "98071694",
                        "relevance" : 0.00174291938997821,
                        "children" : [
                           {
                              "continuation" : {
                                 "next" : "BKAAAAABGBCBC"
                              },
                              "relevance" : 1,
                              "children" : [
                                 {
                                    "source" : "orioportalserver",
                                    "fields" : {
                                       "sectionnametree" : [
                                          {
                                             **"name" : "Tillbeh▒r",**
                                             "locale" : "sv"
                                          }
                                       ],
                                       **"grouphierid" : "98071694",**
                                       "path" : "9-3 (9440)_9_0055",
                                       **"cataloguehierid" : "98065166",**
                                       "code" : "0055"
                                    },
                                    "relevance" : 0.00174291938997821,
                                    "id" : "index:orioportalserver/0/d4ddbd67f8d728b791b7bc6c"
                                 }
                              ],
                              "label" : "hits",
                              "id" : "hitlist:hits"
                           }
                        ],
                        "id" : "group:string:98071694"
                     }
                  ],
                  "label" : "grouphierid",
                  "id" : "grouplist:grouphierid"
               }
            ],
            "id" : "group:root:0"`

**Expected behavior**
All 12 items should have been included in the hitlist

**Environment (please complete the following information):**
Vespa Cloud

**Vespa version**
v.8.57.18,

I can probably give some better replication data, but is this something you can do a quick sane check of if i am just plain wrong.
We have not added or removed documents or changed the YQL from before migrated hence i suspect that being the problem.

**Comment by bjorncs** [comment]
This is as expected on Vespa 8. The number of hits/groups returned are now limited to 10 by default per level. See changed defaults for [grouping.defaultMaxGroups](https://docs.vespa.ai/en/reference/query-api-reference.html#grouping.defaultMaxGroups), [grouping.defaultMaxHits](https://docs.vespa.ai/en/reference/query-api-reference.html#grouping.defaultMaxHits) and [grouping.globalMaxGroups](https://docs.vespa.ai/en/reference/query-api-reference.html#grouping.globalMaxGroups) in the [Vespa 8 release notes](https://docs.vespa.ai/en/vespa8-release-notes.html#changed-defaults). You can adjust the limit by having an explicit `max()` in your grouping query or by specifying the query parameters listed above.

**Comment by lundin** [comment]
Thanks! My bad, works indeed!
