### ISSUE TITLE
Not able to upgrade vespa 8 version in my current cluster because of permission issue.

### ISSUE THREAD

**Issue by sourabhmalhotra** [vespa-engine/vespa#24341]
**Describe the bug**
So basically we already have a vespa 7 setup and wanted to upgrade to vespa 8 and we have a constraint that our scripts can't be run by root user ergo the vespa commands can't be run by root user, so we are doing the below steps to run the same without root user on vespa 7.559.12.
1. In the docker file adding the below commands :
    _RUN chown -R nobody:nobody  /bin /opt /usr
    USER nobody
    RUN chmod -R 755 /opt && \
      chmod -R 755 /usr && \
      chmod -R 755 /bin_
2.  In the default environment text file adding below lines:
      _override VESPA_USER nobody
      override VESPA_UNPRIVILEGED yes_
3.  Adding runAsUser: 99(id for nobody user) in kubernetes yml files.

so using the above config we are able to smoothly run vespa 7.559.12 in our cluster without root user.

But on trying to update to vespa 8: latest version we are facing below issues : 
The id of nobody user which was 99 is changed to 65534 in vespa 8 maybe because of linux centos 8 version change and we have updated the same in our kubernetes yaml files, but on creating the container with vespa latest image version.
I am getting the below issue : 
_warning bad VESPA_USER '99' (ignored)
warning bad VESPA_USER '99' (ignored)
Executing /opt/vespa/libexec/vespa/stop-configserver
warning bad VESPA_USER '99' (ignored)
FATAL error: user '99' missing in passwd file_

Here VESPA_USER as mentioned above was kept nobody.

 So my issues is why the id of nobody user which is supposed to be 65534 for nobody is being printed as 99, as in the vespa 8:latest container 99 is not a defined user: 
_warning bad VESPA_USER '99' (ignored)
warning bad VESPA_USER '99' (ignored)
Executing /opt/vespa/libexec/vespa/stop-configserver
warning bad VESPA_USER '99' (ignored)
FATAL error: user '99' missing in passwd file_

**Vespa version**
vespa 8:latest

**Comment by nehajatav** [comment]
Anyone who can help with this? It is blocking vespa 8 upgrade for us while running as unprivileged user 
[cc: @bratseth ]

**Comment by jobergum** [comment]
The above indicates that you have VESPA_USER 99 instead of override VESPA_USER nobody. Check your settings, and also double check this, instead use the user name instead of the id. 

>Adding runAsUser: 99(id for nobody user) in kubernetes yml files.

**Comment by sourabhmalhotra** [comment]
@jobergum while deploying the image for latest vespa version, I have no where mentioned 99 for a user in any of my settings, for the command "override VESPA_USER nobody" not sure why VESPA_USER '99' is getting printed in the pod logs and deployment gets failed as 99 user does not exist in that container.
The config runAsUser: 99 was done with vespa image version `7.559.12` and that is running fine. However will update it with user name.

**Comment by jobergum** [comment]
You write already that
>The id of nobody user which was 99 is changed to 65534 in vespa 8 maybe because of linux centos 8 version change

So maybe 
> Adding runAsUser: 99(id for nobody user) in kubernetes yml files.

Is related?

**Comment by jobergum** [comment]
No, I don't think you are accurately describing the problem. 

> warning bad VESPA_USER '99' (ignored)
>warning bad VESPA_USER '99' (ignored)
It indicates simply that you have put 99 instead of nobody.

**Comment by sourabhmalhotra** [comment]
Looks like an issue at our end while trying out various values in default-env.txt where 99 was an older value; reverting this back to nobody did not reflect in our artifact repo at the time of image creation. Tried re publishing the artifact containing default-env.txt with the right value, and it worked.
Thanks for your observation.
