### ISSUE TITLE
Cross schema searching and ranking in vespa 8

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#24346]
In Vespa versions before 8 we were able to perform search and retrieve ranked result on documents belonging to different schema. I have added an example below  for  reference. 
Example  
select * from sources schemaA,schemaB where (address_s contains \"fieldValueA\") OR (migrated_s contains \"val3\")
The same could be achieved by  using "sources * in the query".

Here address_s is part of only the schemaA and migrated_s is part of schemaB

Can someone tell us how we can structure our yql to achieve the same functionality.

**Comment by jobergum** [comment]
Sorry, but what is the problem? What exactly is the difference you observe? I'm guessing you get a validation failure as the field does not exist in schema x.

**Comment by 107dipan** [comment]
Yes , In vespa 8 if  we do  a similar search it will throw  exception. Wanted to understand if we can achieve similar functionality i.e searching and raking over docs belonging to different schema.

**Comment by 107dipan** [comment]
We tried putting the sources statement in the OR clause too  for  multiple schema but that didnt work.

**Comment by bratseth** [comment]
To be clear this is supported in the same way on Vespa 8 as on 7, and we would never remove something like this.
What has changed though is that some validation has become stricter - some errors in queries that were ignored on Vespa 7 now produces an error response.

I guess what's hitting you here might be the validation that the query profile you request must be present in all the schemas you are querying? If so, add the profile to all the schemas you are going to query with it.

The cleanest way to do this is to let the schemas you are going to query together inherit a common schema, and put all the constructs that you will use in such queries in the common parent schema.

**Comment by bratseth** [comment]
(I'm guessing here, because you are saying "didn't work" instead of providing accurate information.)

**Comment by 107dipan** [comment]
We understand that after vespa 8 the validation became stricter due to  which we are getting the issue  only after upgrade. Our business use required searching and ranking across multiple schemas so we do need some way to achieve that. 

I dont think using a common schema is an ideal solution for us since we have a lot of tenants with few common fields and even vespa suggests us to use different schemas in those scenarios.

I didnt exactly get your query profile idea but  could you elaborate on that.

**Comment by jobergum** [comment]
Maybe you can provide the *exact* observation? The exact query and the observed exception?

**Comment by bratseth** [comment]
Searching and ranking across multiple schemas is supported, and extremely common, and no functionality related to this has been removed on Vespa 8.

When you search and rank over multiple schemas using a single query, you can of course only search and rank by things that are _common_ across these schemas, so the suggestion is to put these common things in a common parent schema.

I meant rank profile, not query profile, when guessing what actual problem you are observing. We're still missing precise information which can move this conversation beyond guesswork.

**Comment by 107dipan** [comment]
{
  "yql": "select * from (sources schemaA where migrated_s contains \"val3\") OR (sources schemaB where company_s contains \"val1\") ;",
  "timeout": "120s"
}

**Comment by 107dipan** [comment]
"message": "Could not create query from YQL: query:L1:15 missing 'select' at 'sources'",
                "stackTrace": "com.yahoo.processing.IllegalInputException: com.yahoo.search.yql.ProgramCompileException: query:L1:15 missing 'select' at 'sources'\n\tat com.yahoo.search.yql.YqlParser.parseYqlProgram(YqlParser.java:809)\n\tat com.yahoo.search.yql.YqlParser.parse(YqlParser.java:267)\n\tat com.yahoo.search.yql.MinimalQueryInserter.insertQuery(MinimalQueryInserter.java:95)\n\tat com.yahoo.search.yql.MinimalQueryInserter.search(MinimalQueryInserter.java:80)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat com.yahoo.processing.execution.Execution.process(Execution.java:112)\n\tat com.yahoo.search.searchchain.Execution.search(Execution.java:514)\n\tat com.yahoo.prelude.searcher.FieldCollapsingSearcher.search(FieldCollapsingSearcher.java:101)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat

**Comment by 107dipan** [comment]
In this query migrated_s is part of schemaA only  and company_s  os part of schemaB only.

**Comment by bratseth** [comment]
This syntax is not supported, and was not supported on Vespa 7 either.

**Comment by bratseth** [comment]
This syntax would produce the same exception on Vespa 8. 

Maybe you can share what you were doing on 7, which is now failing on Vespa 8.

**Comment by 107dipan** [comment]
Shared the same on the issue description too. 
select * from sources schemaA,schemaB where (address_s contains "fieldValueA") OR (migrated_s contains "val3")
The same could be achieved by using "sources * in the query".

Here address_s is part of only the schemaA and migrated_s is part of schemaB

**Comment by bratseth** [comment]
And what error is this causing?

**Comment by 107dipan** [comment]
Similar to  what we discussed here - https://github.com/vespa-engine/vespa/issues/24267

**Comment by 107dipan** [comment]
We are still setting up vespa 8 and we are getting some errors at k8s level due to which we are unable to try out the queries. But our understanding from the above issue is this query would fail. 


select * from sources schemaA,schemaB where (address_s contains "fieldValueA") OR (migrated_s contains "val3")
The same could be achieved by using "sources * in the query".

Here address_s is part of only the schemaA and migrated_s is part of schemaB

**Comment by bratseth** [comment]
Thanks, I understand your issue now.

**Comment by 107dipan** [comment]
Great! Let me know if I need to provide anymore details regarding our setup or anything

**Comment by bratseth** [comment]
There was no change in this particular validation on 7->8: We still only check if the field is present in _one_ of the referenced schemas.

I confirmed this by deploying an app with two schemas with different fields: Searching a field from either schema works fine, both with "from sources *" and "from sources schema1,schema2", and so does searching a field from each, combined by OR.

**Comment by 107dipan** [comment]
Thanks  a lot Jon! This is very helpful.
