### ISSUE TITLE
configserver not working after kubernetes pod was restarted

### ISSUE THREAD

**Issue by shubh9194** [vespa-engine/vespa#24376]
I have explained the issue in this ticket 
https://github.com/vespa-engine/vespa/issues/24333
The ticket is closed but I still have some doubts and questions

what is the expected behaviour of application deploy status in case all zookeeper nodes are shutdown and then restored without disk failure?
we are using NAS storage.
we are mounting /opt/vespa/var/db to NAS. Is there anything else we need to do and any other path where application related files are stored?
how do we make sure configserver comes up with application loaded whenever kubernetes pod is restarted.

**Comment by kkraune** [comment]
Hi again!

Please note that we generally are not able to document or support every kind of deployment variation, but let me try to point you in the right direction, and add to the documentation if something is missing

If Vespa config servers are shut down gracefully / without errors, with correct tools like https://docs.vespa.ai/en/operations/admin-procedures.html#vespa-start-stop-restart , they should start again with no error. 

https://docs.vespa.ai/en/operations/docker-containers.html for the disk mounts - it seems you are mounting the wrong path?:

> When running Vespa inside Docker containers in production, volume mappings to the parent host should be added to persist data and logs.
> /opt/vespa/var
> /opt/vespa/logs

Regardless of kubernetes, if the environment (directories, files, ports) is correct, config servers should start - see https://docs.vespa.ai/en/operations/configuration-server.html#start-sequence and let me know if something is missing. I am no kubernetes expert, you can maybe add some check on startup script/config to validate that the expected directories are there? Could be this is the mount problem above.
