### ISSUE TITLE
Make sorting by [docid] stable over multiple queries

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#24420]
We currently sort by lid but could sort by gid.

**Comment by baldersheim** [comment]
Using gid is probably the best. The sort blob will be 6 bytes longer and it will require using gid for all hits in the backend.
Alternatives could be to add [lid] and [gid], but I think it is not worth it.

**Comment by baldersheim** [comment]
Since 8.70 gid has been used giving globally stable sorting even with [docid].
