### ISSUE TITLE
Being able to add as a query parameter the keep-rank-count value

### ISSUE THREAD

**Issue by PeriLara** [vespa-engine/vespa#24899]
I would like to bench some rank profiles regarding their `keep-rank-count` value something like [10;100;10000 (which is the default value); 50k;100k]

Such a query parameter does not seem to exist.

It would be really nice to have this feature so that my search definition file would not grow exponentially with a multiplication of rank-profiles with slightly diverging behaviours :) 

Thanks a lot !

If it is not clear, let me know :)

**Comment by baldersheim** [comment]
Related: Query time control of rank-score-drop-limit in #27540
