### ISSUE TITLE
Add support for disallowing overriding query properties

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#24903]
Ability to lock query properties so they cannot be set in the query request. For example, an app might set different properties in queryProfiles, but end-users of the API can pass overrides. There should be support for disallowing overriding properties. For example `ranking.model` or `input(query)`.

**Comment by bjormel** [comment]
I believe that you can do this with 
```
<query-profile id="default">
    <field name="ranking.model" overridable="false">my-ranking-model</field>
</query-profile>
```
https://docs.vespa.ai/en/query-profiles.html#overrides
