### ISSUE TITLE
Latest docker vespa image startup fails on EC2 with --user vespa

### ISSUE THREAD

**Issue by tkaessmann** [vespa-engine/vespa#24983]
**Describe the bug**
On a experiment environment we're always pulling the `latest` vespa docker image on a EC2 Instance but since this week the startup fails by not getting healthy.
The log output is the following:
```
$ sudo docker logs vespa
...           
stderr  warning Wanted 262144 as limit for open files but cannot exceed current hard limit: 65536
mkdir conf/zookeeper: permission denied
```

The last line is new to us.
We've now rolled back to an older version and there everything runs fine.

**To Reproduce**
1. Run a EC2 Instance with the following AMI: amzn2-ami-kernel-5.10-hvm-*-arm64-gp2
2. `$ docker run -d  --name vespa --user vespa --hostname vespa-container  --publish 8080:8080 --publish 19071:19071 vespaengine/vespa`

4. `$ sudo docker logs vespa`

**Expected behavior**
Vespa docker image should become healthy.

**Environment (please complete the following information):**
 - OS: amzn2-ami-kernel-5.10-hvm-*-arm64-gp2
 - Infrastructure: AWS-EC2

**Vespa version**
Latest vespa docker image

**Comment by ean** [comment]
The user id of the `vespa` user inside the container was changed in Vespa version 8.73.7.  I am assuming that upgraded from a version earlier than that release. If that is wrong, please let me know.

See "Start Vespa container with Vespa user" in https://docs.vespa.ai/en/operations/docker-containers.html for details regarding starting the container with the `vespa` user. If you have any other questions after looking at the documentation, you can follow up on that here and we can get the documentation updated at the same time.

**Comment by aressem** [comment]
Thanks for bringing this to our attention. This is a real bug and regression on our side. A fix in Vespa `8.90.x` will be released early next week.

**Comment by tkaessmann** [comment]
Thank you so much for your quick response!
Will you comment here if the release is available?

**Comment by aressem** [comment]
Yes, we will leave this open until it is released to open source and notify you.

**Comment by aressem** [comment]
$ docker run -d --name vespa --user vespa --hostname vespa-container --publish 8080:8080 --publish 19071:19071 vespaengine/vespa:8.90.59
$ docker logs vespa
hostname: you must be root to change the host name
runserver(configserver) running with pid: 18
Running /opt/vespa/libexec/vespa/start-vespa-base.sh
Expected core file size to be unlimited, was 0
Starting config proxy using tcp/vespa-container:19070 as config source(s)
runserver(configproxy) running with pid: 337
Waiting for config proxy to start
config proxy started after 0s (runserver pid 337)
runserver(config-sentinel) running with pid: 398
```

**Comment by tkaessmann** [comment]
Thanks! Updated and everything is running in production with the newest version.
