### ISSUE TITLE
Perform phrase /fuzzy/ group/sorting searches on struct fields.

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#25207]
We have are using array of struct to store some fields in our document. I have added the schema below. But we are unable to find any example for the following types of searches on these fields - phrase/fuzzy/group/sorting.

Could you help us to perform these searches on array of struct fields.

```
struct arr_string {
  field xkey type string { }
  field xvalue type string { }
}
```

```
field field_s type array<arr_string> {
  indexing: summary
  struct-field xkey {
    indexing: attribute
  }
  struct-field xvalue {
     indexing: attribute
   }
 }
```

* Edit by @jobergum for readability.

**Comment by 107dipan** [comment]
For grouping and soring - We want to perform the group/sort operation on a particular  value of the field. 
We want to perform grouping on the value "docId" 
Example - 
{
xkey : "docId";
xvalue: "docValue"
}

**Comment by jobergum** [comment]
Generally, see [sameElement](https://docs.vespa.ai/en/reference/query-language-reference.html#sameelement) to search arrays or maps of struct fields. 

You cannot sort on multi-valued fields like an array or map. This is generally true for all multi-valued fields. You cannot sort on array<string> either. 

```
select * from sources * where field_s contains sameElement(xkey contains "dockey", xvalue contains "docvalue")
```

If you need `fuzzy` just use `xvalue contains fuzzy(..)`

To group you can use 

```
where field_s contains sameElement... | all(group(field_s.xkey) ..) 
```

Note that for grouping, *all* elements of the array or map are exposed, not just the one that matched.

**Comment by 107dipan** [comment]
Hey Joe, 
For the group query, can we filter the results for a particular struct key

**Comment by 107dipan** [comment]
Could you also show us how we can perform phrase search on this field

**Comment by 107dipan** [comment]
Can we use this field as an input to another field of indexing type index and then perform phrase search on that field

**Comment by jobergum** [comment]
Not with the functionality offered by map and array of struct types. See [searching and ranking multi-valued fields](https://docs.vespa.ai/en/searching-multi-valued-fields.html)which covers regular native types.
