### ISSUE TITLE
How can I create multiple applications on a single Vespa cluster?

### ISSUE THREAD

**Issue by Mahdi-Seeker** [vespa-engine/vespa#25211]
Hi there

I'm searching Vespa docs for days, and can't find the answer to my question.
I'd like to have a single Vespa cluster, perhaps a big one with e.g. 50 servers, and I'd want to have multiple applications on this single cluster (with different needs: num of documents, document types, query types, needed qps, and so on...). Is this possible?

Also I'm much confused with some concepts in Vespa and their relations, like:
- Application
- Container
- Content cluster
- Document type
- Schema
- Namespace

So I don't know what I want exactly! Maybe I can use a cluster with a single application, but multiple containers? or multiple content clusters? or multiple document types?! :woozy_face: 

Can u please guide me on these concepts?! Thanx! :pray:

**Comment by bratseth** [comment]
Hello Mahdi,
regarding those terms:

- Application: The unit of deployment and management. Can contain any number of clusters and schemas etc. but all deployed together.
- Cluster: A set of homogenous nodes which all perform the same task. Vespa has two types: _Container_ clusters are stateless, and _content_ clusters store and process the data.
- Schema: A description of a particular type of data and how to process/rank it etc.
- Document type: The data type portion of a schema - a collection of fields.
- Namespace: A segment of document ids which helps you generate unique ids also if you have multiple sources of unique values - not used for anything else.

So, with this in mind - as long as you are ok with managing it as a single unit you can create a single application with multiple schemas, and - perhaps - multiple clusters, to meet your needs.

If on the other hand you want different teams to manage their own applications independently, then you either need to let each of them create their own config servers as part of their application (basically each do have own Vespa installation), or deploy on Vespa Cloud, as config servers are not multi-application.

**Comment by Mahdi-Seeker** [comment]
Thank u so much! most of my confusion is gone now! :hibiscus: 

So, a single vespa cluster has a single config server cluster, and a single application installed on it, is that right?

I'd like to offer different services to different teams with their own needs, what's your suggestion for this situation? All of our data must be on our own servers, so using Vespa cloud is not an option for us.

**Comment by kkraune** [comment]
Work note: Add from above to the glossary in #20907

**Comment by Mahdi-Seeker** [comment]
> Managing multiple applications from a single control plane is an order of magnitude more complex - you need to safely manage the applications upgrading their Vespa version at different times etc. So, Vespa Cloud is the solution we provide for those cases. Perhaps you can challenge you data policy - all the data in Vespa Cloud is always encrypted both in transfer and at rest, see https://cloud.vespa.ai/en/security/whitepaper. Or, if by "our own servers" you mean instances in your own AWS account, we'll support that in Vespa Cloud in Q1.

That makes sense! Thanks for the support.

**Comment by kkraune** [comment]
Managed services like Vespa Cloud uses this: https://cloud.vespa.ai/en/tenant-apps-instances

**Comment by kkraune** [comment]
I hope you found what you looked for about tenants, closing
