### ISSUE TITLE
Consider bolding optional terms from rank query operator

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#25224]
Today, the optional "rank" terms are not bolded if you do query expansion using the `rank()` query operator. 

```
select id, abstract from doc where (rank(abstract contains "sars", abstract contains "cov")
```
Will not bold `cov`, even when found in the abstract.

1) [rank()](https://api.cord19.vespa.ai/search/?yql=select%20id,abstract%20from%20doc%20where%20rank(abstract%20contains%20%22sars%22,%20abstract%20contains%20%22cov%22)&recall=%2Bid:510856) where `cov` is not bolded. 

2) [or](https://api.cord19.vespa.ai/search/?yql=select%20id,abstract%20from%20doc%20where%20rank(abstract%20contains%20%22sars%22,%20abstract%20contains%20%22cov%22)&recall=%2Bid:510856) where `cov` is bolded. 

They do contribute to ranking (as expected), but not bolded. I think they should be bolded. It would also be nice to have annotations controlling the behavior (we have `filter` which is a way to turn off bolding, but we don't have an option to turn on bolding).

**Comment by mattweber** [comment]
+1, was wondering why my rank clause was not getting bolded and was pointed at this issue.

**Comment by kkraune** [comment]
we will do #28704 instead, closing - so we do not change behavior for the rank operator
