### ISSUE TITLE
minor typo on Vespa Cloud services documentation page

### ISSUE THREAD

**Issue by rorymc** [vespa-engine/vespa#25226]
https://cloud.vespa.ai/en/reference/services#deployment-variants

**Describe the bug**
In the documentation, there is a small spelling typo "Deplohyment variants".

It should likely be "Deployment variants", to line up with the anchor tag.

**Comment by kkraune** [comment]
Thanks! Fixed in https://github.com/vespa-engine/cloud/pull/627 - I'll do a full scan of the site for typos as well

**Comment by rorymc** [comment]
I think this might be another small documentation typo here:
https://docs.vespa.ai/en/reference/document-json-format.html#remove

"HitMe" on the left column should likely be "123"
