### ISSUE TITLE
publish Vespa Cloud availability/status changes via RSS

### ISSUE THREAD

**Issue by rorymc** [vespa-engine/vespa#25232]
**Is your feature request related to a problem? Please describe.**
As a small startup, we find it helpful to be warned when one of our dependencies has an issue.  The way we manage this has been to subscribe to status page RSS feeds for the different Cloud Platforms we are using (GCP, Firebase, Elastic.co, etc) and dump out the updates to a slack channel.

**Describe the solution you'd like**
When there is a status change in availability (or an incident) affecting Vespa Cloud, it would be very helpful if the incident (which may be manually or automatically published internally from the Vespa ops team) could be sent out via RSS feed.

I believe something like https://www.atlassian.com/software/statuspage can be used to power the solution.

**Describe alternatives you've considered**
We have not considered any other options, as I believe using RSS feeds for status updates is a standard.

Here are three examples:
* GCP:  https://status.cloud.google.com/en/feed.atom
* Firebase:  https://status.firebase.google.com/en/feed.atom
* Elastic.co:  https://status.elastic.co/history.rss

**Comment by oyving** [comment]
Hi @rorymc, 

For Vespa Cloud support questions it's better to file them through the Vespa Cloud support channel. The GitHub issues are mostly related to the open source development of Vespa. https://cloud.vespa.ai/support

We already have a support status page (it's not Atlassian's Status Page) that I think covers your use case, but we do not generate an RSS/Atom feed based on it. I'll file an internal ticket for us to follow up on that as it's an excellent idea.

I'll close this issue and we can follow up through Vespa Cloud support if you wish to do so.
