### ISSUE TITLE
ignore-undefined-fields does not work as expected

### ISSUE THREAD

**Issue by tkaessmann** [vespa-engine/vespa#25248]
**Describe the bug**
We found a random behaviour with the new config-property: [ignore-undefined-fields](https://docs.vespa.ai/en/reference/services-container.html#ignore-undefined-fields).
You can reproduce this issue with following repo: [here](https://github.com/tkaessmann/vespa-ignore-undefined-fields-bug).
The property is set [here](https://github.com/tkaessmann/vespa-ignore-undefined-fields-bug/blob/main/src/main/application/services.xml#L10).

**To Reproduce**
1. Checkout the [repo](https://github.com/tkaessmann/vespa-ignore-undefined-fields-bug). 
2. run the file: `./run.sh`
3. Download vespa-feed-client and place it into the repo.
4. Run the following failing line:

> $ ./vespa-feed-client-cli/vespa-feed-client --file feed_fail.jsonl --endpoint http://localhost:8080/ --show-errors

5. And then run the line where everything is fine:

> $ ./vespa-feed-client-cli/vespa-feed-client --file feed_fine.jsonl --endpoint http://localhost:8080/ --show-errors

The problem is that in the failing case we've only changed the order of attributes in the file.
The exception is: 
```
Status 400 executing 'POST /document/v1/foo/foo/docid/123': Error in document 'id:foo:foo::123' - could not parse field 't_field' of type 'tensor<float>(t{})': Expected '[' or '{'. Got 'END_OBJECT'.: Expected '[' or '{'. Got 'END_OBJECT'.
```

**Expected behavior**
It should ignore all attributes that are not defined in the schema and the import should not fail, because I set `ignore-undefined-fields`.

**Environment (please complete the following information):**
 - OS: on ec2 and local (mac + linux)
 - Versions: latest

**Vespa version**
Latest

**Comment by kkraune** [comment]
This is genuinely puzzling - I can reproduce the problem, and it is the same even if I represent the mapped tensor in another format as 
```
"t_field": {
      "cells": [
        {"address": {"t": "solr"}, "value": 1.0}
      ]
    }
```

The parse error does not occur if the tensor following the unknown field is also unknown.

It hence fails for _mapped_ tensors _in the schema_ (if t_field is an indexed tensor, there is no problem)

**Comment by tkaessmann** [comment]
Thanks for investing!
And yes, it took us a while to figure out that only the ordering is the problem... ;)

**Comment by bratseth** [comment]
Thanks for the very helpful report. 

Fixed by https://github.com/vespa-engine/vespa/pull/25453 which will be in 8.108, which will probably be released tomorrow, 2023-01-10.
