### ISSUE TITLE
Documents not returned when adding OR clause with fieldSet

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#25263]
**Describe the bug**
Documents not returned when adding OR clause with fieldSet. I am trying to perform a query with OR clause in the manner given below. 

_Query1_ : select * from sources * where (field_s.xvaule matches "blah") 
_Query2_ : select * from sources * where (field_s.xvaule matches "blah")  OR default contains "blah"

Documents returned in query1 are not part of the search results returned in Query2

**To Reproduce**

- _Step1_ : We need to add 2 schema to our cluster
- _Step2_ : Schema 1 with static fields and schema 2 with array fields mentioned below
- _Step3_ : Declare the static field to search as fieldSet

 ```
struct arr_string {
  field xkey type string { }
  field xvalue type string { }
}
field field_s type array<arr_string> {
  indexing: summary
  struct-field xkey {
    indexing: attribute
  }
  struct-field xvalue {
     indexing: attribute
   }
 }
```

_**Step4**_: Ingestion payload format

_**IngestionPayload1**_ : 

```
"fields": {
                     "documentid": "id:mynamespace:testDomainA::123",
                    "table": "anyTable",
                    "domain": "testingDomainA",
                    "text": [
                        "this is a blah text "
                    ],
                    "fileName": "Quries.txt",
                    "field_s": [
                        {
                            "xvaule": "Blah mla fla xyz clah slah abc def ghj efg",
                            "xkey": "phraseField_s"
                        }
                    ],
                    "user": "user",
                    "status": "active"
}
```

_**IngestionPayload2**_ : 

```
"fields": {
                     "documentid": "id:mynamespace:testDomainB::121",
                    "table": "anyTable",
                    "domain": "testingDomainB",
                    "text": [
                        "this is a blah text "
                    ],
                    "fileName": "Quries.txt",
                    "phraseField_s": ["Blah mla fla xyz clah slah abc def ghj efg"   ],
                    "user": "user",
                    "status": "active"
}

```

**Expected behavior**
The document matched from first part of the query should also be returned

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions : Vepsa 8.80.20

**Additional context**

**_Search Query 1_** : select * from sources * where (field_s.xvaule matches "blah") 

This is returning the following document

```
{
                "id": "id:mynamespace:testDomainA::123",
                "relevance": 0.0017429193899782135,
                "source": "lexdoc",
                "fields": {
                    "sddocname": "testDomainA",
                    "documentid": "id:mynamespace:testDomainA::123",
                    "table": "anyTable",
                    "domain": "testingDomainA",
                    "text": [
                        "this is a blah text "
                    ],
                    "fileName": "Quries.txt",
                    "field_s": [
                        {
                            "xvaule": "Blah mla fla xyz clah slah abc def ghj efg",
                            "xkey": "phraseField_s"
                        }
                    ],
                    "user": "user",
                    "status": "active"
                }
}
```

**_Search Query 2_** - select * from sources * where (field_s.xvaule matches "blah")  OR default contains "blah"
When adding the OR clause the document from the first search clause is not returned. Both the documents are part of different document types.

**Comment by jobergum** [comment]
Please take some time to format your issue summary. It's way too hard to read.

**Comment by 107dipan** [comment]
Hey Joe, 
Hope this helps. Let me know if I need to add anything.

**Comment by jobergum** [comment]
If you want to search across multiple document schemas in the same query, both must have the same fields with the same `match` settings.

**Comment by 107dipan** [comment]
We want to combine search on a struct array with search on fieldset. If my understanding is correct in this scenario, the ranking of the docs would have changed upon addition of the 2nd cluase but the documents returned from first part of the clause should also be present in the search result.

**Comment by 107dipan** [comment]
Hey Joe, 
We are still unable to understand the issue why the docs returned by the first search clause is not returned in the query. 
We have seen that if we query with fields belonging to different schemas the docs matching all are returned and from multiple schema.

**Comment by jobergum** [comment]
Then you need to provide a minimal sample application where you have two document types, and both schemas have a `default` fieldset and your array of struct fields. Any other combination gives undefined behavior. If you want to search both schemas, they must have the same fields.
