### ISSUE TITLE
Increasing weight is not affecting the order of docs returned

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#25286]
**Describe the bug**
We are trying to perform a search by adding a weight to one of the search clause

`select * from sources * where (boost_s contains ({weight:500} "BoostTerm") OR table contains  "newTableName" )`

**To Reproduce**
1. Perform search query by adding weight to a term. 
2. We are using the default ranking i.e. nativeRanking

YQL Query from traceLevel logs 

`select * from sources * where (boost_s contains ({stem: false, normalizeCase: false, id: 1, weight: 500}\"boostterm\") OR table contains ({origin: {original: \"gsam_clientdoc\", offset: 0, length: 14}, id: 2}phrase(\"gsam\", \"clientdoc\"))) timeout 499"`

**Expected behavior**
Upon adding weight criteria we would expect the document matching the clause with weight to be ranked higher but that is not the case. 

**Environment (please complete the following information):

Infrastructure: Kubernetes
Versions : Vepsa 8.80.20

**Comment by jobergum** [comment]
It depends on the rank expression used in the rank profile, and order does not necessarily change, but the score will change.

**Comment by 107dipan** [comment]
We have not added any rank expression or rank profile to our cluster currently.

**Comment by jobergum** [comment]
Then you will be using `nativeRank`, and as I said, a weight boost does not necessarily change the order.

**Comment by 107dipan** [comment]
If I understand correctly, even if the order does not change there should be a change in the relevance of the doc. I tried to increase/decrease the weight but even with that the relevance of the doc for the particular search query does not change.

**Comment by jobergum** [comment]
This is standard functionality here,  is an example of the functionality. 

```
select id,title,abstract from sources * where title contains ({weight:100} "covid-19") OR title contains "sars-cov-2" 
```
I'm limiting the retrieval to a specific id using the `recall` parameter and where id is a field in the schema which uniquely identifies the hit. 

- with a default weight 100, the relevance score is `relevance: 0.31916905670757983`
[Query link with weight 100](https://api.cord19.vespa.ai/search/?yql=select%20id,title,abstract%20from%20sources%20*%20where%20(title%20contains%20(%7Bweight%3A100%7D%20%22covid-19%22)%20OR%20title%20contains%20%22sars-cov-2%22%20)&recall=%2Bid:574360)

- With a weight of 1000, the relevance score is `relevance: 0.4133138198893686`
[Query link with weight 1000](https://api.cord19.vespa.ai/search/?yql=select%20id,title,abstract%20from%20sources%20*%20where%20(title%20contains%20(%7Bweight%3A1000%7D%20%22covid-19%22)%20OR%20title%20contains%20%22sars-cov-2%22%20)&recall=%2Bid:574360)
