### ISSUE TITLE
Segmentation fault when executing vespa

### ISSUE THREAD

**Issue by jprantza** [vespa-engine/vespa#25307]
I'm running a VMware image on WIndows 11. The image has 8GB ram, 4 cores, and 300GB allocated to it. It's running CentOS Stream release 8, and I have installed the community edition of Docker version 20.10.22, OpenJDK 17.0.5, Maven 3.5.4, and Homebrew 3.6.15 on it. When I try to execute 'vespa' from the command line, it generates a segmentation fault and exits, like so:

```
[jprantza@localhost x]$ strace -ff -o strace-vespa.log vespa
Segmentation fault (core dumped)

[jprantza@localhost x]$ ls -la
total 8
drwxrwxr-x.  2 jprantza jprantza   35 Dec 20 06:46 .
drwx------. 17 jprantza jprantza 4096 Dec 20 06:45 ..
-rw-rw-r--.  1 jprantza jprantza  140 Dec 20 06:46 strace-vespa.log.5956

[jprantza@localhost x]$ cat strace-vespa.log.5956 
execve("/home/linuxbrew/.linuxbrew/bin/vespa", ["vespa"], 0x7ffd1bc7d248 /* 54 vars */) = -1 EEXIST (File exists)
+++ killed by SIGSEGV +++

```

If I install vespa from homebrew within WSL on my host machine, then everything works fine. Also, if I download the [latest version](https://github.com/vespa-engine/vespa/releases/download/v8.101.28/vespa-cli_8.101.28_linux_amd64.tar.gz) of the CLI from Github and extract that into my VMware image and run 'vespa', then that works fine as well.

@aressem had helped me through this in the following [slack thread](https://vespatalk.slack.com/archives/C01QNBPPNT1/p1671493711375879).

**Comment by jprantza** [comment]
Another observation, when I download the [8.98.34](https://github.com/vespa-engine/vespa/releases/tag/v8.98.34) version of the vespa-cli and extract/try to run the vespa executable, I get a segmentation fault as well. The 8.98.34 version is the same version that was installed on my VM using brew. This segmentation fault does not occur with the 8.101.28 version of the cli. Looks like simply updating the version of the cli for brew will address this issue.

**Comment by jprantza** [comment]
The issue appears to be related to homebrew. I noticed that the version of vespa installed by homebrew was 8.98.34, so I re-installed and got the 8.101.28 version this time. Both versions give a segmentation fault when installed using homebrew, but if I download the cli from https://github.com/vespa-engine/vespa/releases then both versions work fine.

I noticed that there is a file size difference between the homebrew version of vespa and the tarred up version.


From [vespa-cli_8.101.28_linux_amd64.tar.gz](https://github.com/vespa-engine/vespa/releases/download/v8.101.28/vespa-cli_8.101.28_linux_amd64.tar.gz):
```
[jprantza@localhost bin]$ ./vespa version
Vespa CLI version 8.101.28 compiled with go1.19.4 on linux/amd64

[jprantza@localhost bin]$ ls -la
total 20752
drwxr-xr-x. 2 jprantza jprantza       39 Dec 20 03:02 .
drwxr-xr-x. 4 jprantza jprantza       45 Dec 20 03:02 ..
-rwxr-xr-x. 1 jprantza jprantza  8512509 Dec 20 03:02 script-utils
-rwxr-xr-x. 1 jprantza jprantza 12732815 Dec 20 03:02 vespa
```

From homebrew installation:
```
[jprantza@localhost bin]$ pwd
/home/linuxbrew/.linuxbrew/Cellar/vespa-cli/8.101.28/bin

[jprantza@localhost bin]$ ./vespa version
Segmentation fault

[jprantza@localhost bin]$ ls -la
total 12504
drwxr-xr-x. 2 jprantza jprantza       19 Dec 18 10:03 .
drwxr-xr-x. 6 jprantza jprantza      129 Dec 20 14:12 ..
-r-xr-xr-x. 1 jprantza jprantza 12800334 Dec 20 14:12 vespa
```

Note that the file size in the tarball version is 12732815, but the file size in the homebrew version is 12800334.

**Comment by jprantza** [comment]
A little more info in case it helps.

Tarball version:
```
[jprantza@localhost bin]$ file vespa
vespa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped

[jprantza@localhost bin]$ readelf -h vespa
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x467560
  Start of program headers:          64 (bytes into file)
  Start of section headers:          456 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         23
  Section header string table index: 3
```

Homebrew version:
```
[jprantza@localhost bin]$ file vespa 
vespa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, with debug_info, not stripped

[jprantza@localhost bin]$ readelf -h vespa
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x4691e0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          12797406 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         11
  Size of section headers:           64 (bytes)
  Number of section headers:         36
  Section header string table index: 12
```
 
It appears the tarball version is statically linked vs the homebrew version which is dynamically linked.

**Comment by jprantza** [comment]
Not sure if this is relevant, but I uninstalled brew and did a fresh install of vespa-cli again and noticed the following:
```
==> Pouring gcc--12.2.0.x86_64_linux.bottle.2.tar.gz
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall gcc

```

**Comment by jprantza** [comment]
As an FYI, I can confirm that this issue does not occur with CentOS Stream 9, and that the homebrew version of vespa executable works fine with that version of CentOS.

**Comment by mpolden** [comment]
Thanks for reporting this issue!

The difference between Homebrew binaries and tarball releases is that Homebrew builds their own binaries from source, while we build the binaries published on https://github.com/vespa-engine/vespa/releases ourselves. As you've discovered, binaries built by Homebrew infra are dynamically linked while ours are statically linked.

> If I install vespa from homebrew within WSL on my host machine, then everything works fine

> I can confirm that this issue does not occur with CentOS Stream 9

I assume this is because the binaries by built by Homebrew are compatible with both the Linux distribution used within WSL (Ubuntu I believe?) and CentOS Stream 9.

This should probably be reported as an issue to Homebrew as it sounds like they're building a faulty binary for CentOS Stream 8. What happens if you install `vespa` from source on CentOS Stream 8, with `brew install --build-from-source vespa`?

In general I would recommend using our tarball releases on Linux.

**Comment by jprantza** [comment]
```
[jprantza@localhost local]$ brew reinstall --build-from-source vespa-cli

==> Fetching dependencies for vespa-cli: linux-headers@5.15, mpfr and xz
==> Fetching linux-headers@5.15
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/manifests/5.15.86
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/blobs/sha256:65ac34deace6ddf03c403acd31f5ae72736450c67abfb77e9bbe2941e3785428
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:65ac34deace6ddf03c403acd31f5ae72736450c67abfb77e9bbe2941e3785428?se=2023-0
######################################################################## 100.0%
==> Fetching mpfr
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:3e62ca94c057c73dfb08c6b7be42b3aaf0e338c9a422dbdd74695e1106c302a5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:3e62ca94c057c73dfb08c6b7be42b3aaf0e338c9a422dbdd74695e1106c302a5?se=2023-0
######################################################################## 100.0%
==> Fetching xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.4.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:ce4daa84cc24f38a0e1c76646b83374ac210f094aefbf4db4d627c4c324e9c60
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ce4daa84cc24f38a0e1c76646b83374ac210f094aefbf4db4d627c4c324e9c60?se=2023-0
######################################################################## 100.0%
==> Fetching vespa-cli
==> Downloading https://github.com/vespa-engine/vespa/archive/v8.101.28.tar.gz
==> Downloading from https://codeload.github.com/vespa-engine/vespa/tar.gz/refs/tags/v8.101.28
                                            -=O=-                     #  # # #
==> Reinstalling vespa-cli 
==> Installing dependencies for vespa-cli: linux-headers@5.15, mpfr and xz
==> Installing vespa-cli dependency: linux-headers@5.15
==> Pouring linux-headers@5.15--5.15.86.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/linux-headers@5.15/5.15.86: 963 files, 5.6MB
==> Installing vespa-cli dependency: mpfr
==> Pouring mpfr--4.2.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/mpfr/4.2.0: 31 files, 3.9MB
==> Installing vespa-cli dependency: xz
==> Pouring xz--5.4.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.4.0: 179 files, 2.5MB
==> Installing vespa-cli
==> make all manpages
Last 15 lines from /home/jprantza/.cache/Homebrew/Logs/vespa-cli/01.make:
2023-01-07 20:07:00 +0000

make
all
manpages

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
mkdir -p mytmp
env GOBIN=/tmp/vespa-cli-20230107-145047-1hjqoac/vespa-8.101.28/client/go/bin go install -ldflags "-X github.com/vespa-engine/vespa/client/go/build.Version=8.101.28" ./...
TMPDIR=`/bin/pwd`/mytmp go test ./...
make: *** [Makefile:122: install] Segmentation fault
make: *** Waiting for unfinished jobs....
make: *** [Makefile:135: test] Segmentation fault

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by jprantza** [comment]
Hi Martin,

Thanks for looking into this. I've been able to move past this issue by using the statically linked binaries or using CentOS 9 instead. I have a solution, so technically, I guess you can close this issue, however, if you allow me, I'd like to explain why I don't necessarily think you should yet.

I'm new to Vespa. I, like most others, started by going to your product documentation for the install procedure. I recall reading somewhere that CentOS 8 is the only platform supported for doing vespa builds, so I figured I'd stick to the same even though CentOS 9 was available. I then proceeded to install everything using HomeBrew, as outlined in the documentation and immediately encountered this issue.

I think you have a great product, great documentation, and great support, but if I ran into this issue then it's likely that others will too. Maybe if they search they will find this bug and figure out a way to resolve it, or maybe someone will help them in the Slack community as they did for me, but why not just make a simple documentation modification to help others who might run into a similar issue. Just add a simple comment to use the statically linked binaries if you run into any issues when using HomeBrew. That way they know what to do if they run into an issue. That would be my recommendation.

I will also try to file an issue with HomeBrew as well, because I agree with you that this is probably more of an issue with their product than yours.

Thank you again for looking into this.

**Comment by jprantza** [comment]
FYI, I started a thread on this topic under HomeBrew discussions [here](https://github.com/orgs/Homebrew/discussions/4092). If they agree that it's a bug I'll create a ticket for it.

**Comment by mpolden** [comment]
This is a Homebrew/Linuxbrew issue, and not specific to Vespa CLI. Even GCC segfaults for me when installed through Homebrew on CentOS Stream 8.

See https://github.com/Homebrew/homebrew-core/issues/116841 for more details.
