### ISSUE TITLE
Executing vespa cli commands inside the pod without using kubectl command

### ISSUE THREAD

**Issue by akhilambati** [vespa-engine/vespa#25345]
Hi,
Just wanted to know if there is a way to trigger/use vespa cli outside the Kubernetes cluster without using kubectl command.

Thanks,
Akhil

**Comment by bratseth** [comment]
vespa-cli can run anywhere, see https://docs.vespa.ai/en/vespa-cli.html

**Comment by akhilambati** [comment]
thanks for your response.. @bratseth 
is it possible to run vespa-visit with above cli tool?
basically i want to run vespa-visit on the pod in kubernetes cluster which doesn't have exec access, is there a way to trigger it from rpc?

**Comment by bratseth** [comment]
Not yet, but you can visit over HTTP: https://docs.vespa.ai/en/document-v1-api-guide.html#request-examples

**Comment by akhilambati** [comment]
yes , but there are some limitations with visit http api, we can't use some cli provided features like fromTimeStamp, toTimeStamp and flag visit-removes

**Comment by jobergum** [comment]
`vespa-visit != vespa-cli` 

If you need specific features that `vespa-visit` exposes, exposed on the HTTP /document/v1 API then please create a feature request.

**Comment by akhilambati** [comment]
sure, thanks @jobergum @bratseth , closing this ticket and raising a feature request for visit http api
