### ISSUE TITLE
Unable to sort string fields of attribute indexing type

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#25468]
**Describe the bug**
Unable to sort based on single valued string fields

**To Reproduce**
1. Deploy application with schema containing a single valued string field
2. Yql query - select * from sources * where user contains "random" order by singleStringField ASC

**Expected behavior**
Results should be sorted based on the field given

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes
 - Versions : 8.80.20

**Vespa version**
8.80.20

**Additional context**
I have a document that matches the below criteria but when I an using the above yql query mentioned I am not getting documents
with the field singleStringField

- select * from sources * where user contains "rodipa" AND singleStringField contains "random"

**Comment by kkraune** [comment]
Hi, please add the schema as well so this can be reproduced - thanks :-)

**Comment by 107dipan** [comment]
# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

# A description of a type of data, how to store and index it, and what to compute over the data elements
#
# See:
#  - https://docs.vespa.ai/en/schemas.html
schema testingDomainBlexDocument  {

    document testingDomainBlexDocument {



            field singleStringField type string {
                indexing: summary | attribute

            }

        }

        

}

**Comment by jobergum** [comment]
We have tests for this, also see https://api.cord19.vespa.ai/search/?query=sars&yql=select%20title,%20id,source%20from%20doc%20where%20userQuery()%20order%20by%20source+asc and https://api.cord19.vespa.ai/search/?query=sars&yql=select%20title,%20id,source%20from%20doc%20where%20userQuery()%20order%20by%20source+desc
