### ISSUE TITLE
Run query builder without CORS config

### ISSUE THREAD

**Issue by JeanExtreme002-Escavador** [vespa-engine/vespa#25522]
**The problem:**

I'm trying to search using query-builder and I always receive the following red message: "Failed to fetch". It also happens to the `/ApplicationStatus` endpoint. Opening the dev tools of the browser, I can see 2 requests. The first one generates a CORS Error and the second one (OPTIONS request) receives a 400 status code, with no message.

My vespa application is initialized and running, working on pyvespa. I can even do a GET request on browser seach box and it will return all results correctly.

**To reproduce:**

Run a vespa application with a simple schema and start the QueryBuilder with `yarn dev`, such as its tutorial. After that, on Chrome or Edge, open its web page and query, using GET or POST method, by URL `http://localhost:8080/search/`. At least to me, it'll show a error message.

**Environment:**
 - OS: Windows 11 64 bits
 - Node: 18.12.1
 - Yarn 1.22.19

**Vespa version:** latest

![Sem título](https://user-images.githubusercontent.com/119371214/211890886-fe1015ab-37c5-42b0-a777-fe1478c79498.png)

**Comment by kkraune** [comment]
Thanks for reporting! I can reproduce the issue and is looking into

**Comment by kkraune** [comment]
OK! Yes, the CORS config is really a pain, I we hope to have something to replace this soon. I will take the liberty to rename the title of this ticket to a feature request to eliminate the CORS requirement, and you can track progress here. Thanks!

**Comment by JeanExtreme002-Escavador** [comment]
@kkraune I configured CORS by adding that `<html>` to my container on services.xml, such as at [documentation](https://github.com/vespa-engine/vespa/tree/master/client/js/app#query-builder) and that error is still being raised to me.

**Comment by jobergum** [comment]
I just tried the instructions and they clearly don't add any cors header:

```
curl -v localhost:8080/search/
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /search/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.84.0
> Accept: */*
> 
```

There is no cors header set, 

Expected would be to see ```Access-Control-Allow-Origin: *```

**Comment by jobergum** [comment]
Scratch that, it does work:

```
curl -v -H "Origin: https://foo.example" localhost:8080/search/
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /search/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.84.0
> Accept: */*
> Origin: https://foo.example
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 09 Mar 2023 19:49:40 GMT
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Origin,Content-Type,Accept,Yahoo-Principal-Auth,Okta-Identity-Token,Okta-Access-Token,Okta-Refresh-Token,Vespa-Csrf-Token
< Access-Control-Allow-Methods: OPTIONS,GET,PUT,DELETE,POST,PATCH
< Access-Control-Allow-Origin: https://foo.example
< Access-Control-Max-Age: 604800
< Content-Type: application/json;charset=utf-8
< Vary: *, Accept-Encoding
< Content-Length: 240
```

**Comment by JeanExtreme002-Escavador** [comment]
Ignore my message above. It's working. The problem was I didn't set the same container ID to the server tag.  I'm closing this issue now. Thank you guys!
