### ISSUE TITLE
Default resource limit memory  is getting detected as 0.9 when no value is set

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#25674]
**Describe the bug**
We are not setting any value for the property resource-limits memory but the value is getting detected as 0.9 when though the value as per the documentation is 0.8. -https://docs.vespa.ai/en/reference/services-content.html#memory

We are deploying our services xml with the following configuration

```
                <resource-limits>
                    <disk>0.90</disk>
                </resource-limits>
```

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes, Azure, AWS, self-hosted

**Vespa version**
Vespa version - 8.80.20

**Comment by bjormel** [comment]
There are two limits:
* For the cluster as a whole entity, default 0.8: https://docs.vespa.ai/en/reference/services-content.html#memory
* For individual content nodes, default 0.9: https://docs.vespa.ai/en/reference/services-content.html#resource-limits-proton

To verify configuration, e.g. :
* `$ vespa-get-config -n vespa.config.content.fleetcontroller -i admin/standalone/cluster-controllers/0/components/clustercontroller-mycontent-configurer|grep cluster_feed_block_limit.memory`
* `$ vespa-get-config -n vespa.config.search.core.proton -i mycontent/search/cluster.mycontent/0|grep writefilter.memorylimit`
