### ISSUE TITLE
Indexing in Vespa is slow

### ISSUE THREAD

**Issue by danielbicaSP** [vespa-engine/vespa#25715]
When indexing in local Vespa, the indexing is slow.

My configuration:

```
<container id="default" version="1.0">
    <search />
    <document-api />
    <nodes>
        <node hostalias="node1" />
    </nodes>
</container>

<content id="bo" version="1.0">
    <redundancy>1</redundancy>
    <documents>
        <document type="psearch" mode="index" />
    </documents>
    <nodes>
        <node hostalias="node1" distribution-key="0" />
    </nodes>
</content>
```

and schema:

```
schema psearch {
    document psearch {
        field Id type int {
            indexing: summary | attribute
            attribute: fast-search
        }
        field Name type string {
            indexing: summary | index | attribute
            index: enable-bm25
    }
    field AdId type string {
            indexing: summary | index | attribute
            index: enable-bm25
    }
    field Country type string {
            indexing: summary | index | attribute
            index: enable-bm25
    }
    field Avatar type string {
            indexing: summary | index | attribute
            index: enable-bm25
    }
    field Value type long {
            indexing: summary | attribute
            attribute: fast-search
        }
        field Numbers type int {
            indexing: summary | attribute
            attribute: fast-search
        }
    field BotLastTime type long {
            indexing: summary | attribute
            attribute: fast-search
        }
    field BotDailyCount type int {
            indexing: summary | attribute
            attribute: fast-search
        }
    field Platform type string {
            indexing: summary | index | attribute
            index: enable-bm25
      }
   }

    fieldset default {
        fields: Id, Name, AdId, Country, Avatar, Numbers, BotLastTime, BotDailyCount, Platform
    }

    rank-profile default {
        first-phase {
            expression: nativeRank(Id, Name, AdId, Country, Avatar, Numbers, BotLastTime, BotDailyCount, Platform)
        }
    }
}
```

I use /document/v1 API to push documents into Vespa (POST to put a given document, by ID) https://docs.vespa.ai/en/reference/document-v1-api-reference.html

On my tests on local Vespa it takes arount 2.3 milliseconds to push one document, in a test where i push 100k documents.

I did the same test wit Elastic search and the average time is around 1.7 milliseconds. I am trying to find a way of getting at least the same performance as in ElasticSearch.

Any idea how can i improve my time on each document push?

**Comment by jobergum** [comment]
The difference between Elasticsearch and Vespa concerning indexing is that Elasticsearch replies when the operation is persistent but not searchable/applied. Vespa, on the other hand, when you get the reply, the operation is persisted, visible, and indexed.

**Comment by danielbicaSP** [comment]
Hi @baldersheim i am doing the feeding from multiple 

this is my code for my client for indexing :
for (int i = 0; i < nrSteps; i++)
{
	for (int j = 0; j < _nrIterations; j++)
	{
		var index = i * _nrIterations + j;
		var doc = datas[index];
		
		tasks.Add(Task.Run(async () => await _vespaSearchService.IndexDocumentAsync(doc.Id.ToString(), doc)));
	}

	await Task.WhenAll(tasks);
}

basically I will start _nrIterations tasks that will run in parallel to push the documents.
_nrIterations = 100


What do you think about this?

Also there is a possibility to push multiple documents at the same time  like BulkInsert?

**Comment by danielbicaSP** [comment]
> The difference between Elasticsearch and Vespa concerning indexing is that Elasticsearch replies when the operation is persistent but not searchable/applied. Vespa, on the other hand, when you get the reply, the operation is persisted, visible, and indexed.

Is there a way in Vespa to get the answer as in ElasticSearch,  faster, not waiting for the data to be ready and visible to search?

**Comment by baldersheim** [comment]
No. Feed is optimized for throughput, not latency.

I assume that each document has a unique id. Operations against same document id are serialized.

The code above will send 100 documents and then wait for the reply from all. That is not very efficient.
You need to keep the pressure up. 
As soon as you get one reply back you must post the next one so that you always have 100(or more) inflight.

**Comment by danielbicaSP** [comment]
Hi @baldersheim,
Thanks for your observation, that was a good observation :) .

It seams that to wait for all 100 docs to finish indexing indeed was not very good idea ...

I fix this with something like here:
https://stackoverflow.com/questions/14075029/have-a-set-of-tasks-with-only-x-running-at-a-time

And now my indexing performance increase.
So to index the 100k docs with 100 parallel tasks i will get around 1.2 ms per doc indexed.
if I will index using 200 parallel tasks I will get 0.8 ms per doc indexed.

**Comment by baldersheim** [comment]
I recommend measuring feed performance with number of operations per second. That is a better measure.
Latency of a feed operation will vary depending of what else is happening in the pipeline. Even if we do not have a bulk concept, the backend will group multiple feed operations if there are more in the internal Q in the backend. So the more you have inflight the cheaper it will be per operation.
The ideal number of operations to have inflight is hard to tell. The feed client we provide, https://docs.vespa.ai/en/vespa-feed-client.html, uses a dynamic throttling algorithm that is very good at finding the sweet spot.
I would recommend that for efficient feeding.
