### ISSUE TITLE
Backup and Sync

### ISSUE THREAD

**Issue by sunil924** [vespa-engine/vespa#25737]
**Is your feature request related to a problem? Please describe.**
As the documents grow, taking the complete data backup and sync in the secondary cluster will become a long process. In case of disaster scenario, it may take more than a day to bring up the secondary cluster.

**Describe the solution you'd like**
Direct backup of index data and sync using rsync will be faster instead of dumping the documents and feeding in the secondary cluster.
Attivio supports the above approach.

**Comment by kkraune** [comment]
This ticket is related to #25736. I will post short responses with some questions to validate my assumptions, before making any recommendations.

I assume the cluster you will create a backup from has writes at any time - or is it static?

Please provide the environment this is running in, like AWS, using EC2/ECS/Kubernetes or something else.

https://cloud.vespa.ai/en/cloning-applications-and-data is a good read to understand some of the tools needed for later steps.

**Comment by kkraune** [comment]
https://github.com/vespa-engine/sample-apps/blob/master/examples/google-cloud/cloud-functions/go/visit.go has a "backup" function that exports all documents to storage.

Another alternative is doing something like

```
$ vespa visit --zone prod.aws-us-east-1c --cluster default --selection doc | wc -l
     450

$ vespa visit --zone prod.aws-us-east-1c --cluster default --selection doc | split -l 100

$ ls -1
xaa
xab
xac
xad
xae
```

see https://github.com/vespa-engine/vespa/issues/26134 for details. I hope this helps, please reopen with more details as needed
