### ISSUE TITLE
Missing warning when attempting to use `indexing: attribute` in nested complex types

### ISSUE THREAD

**Issue by codycollier** [vespa-engine/vespa#25739]
**Describe the bug**
Recently, when experimenting with some fairly complex and nested schema types, I was trying to set `indexing: attribute` on some of the inner fields.  After discussion with JKB, I now understand this was an invalid configuration.  However, when applying such schema in an application, there were no warnings alerting to this misconfiguration.

**To Reproduce**

Here's an example subset of the schema that was being used:
```
  1 struct toy {
  2     field name  type string {}
  3     field color type string {}
  4 }
  5
  6 struct toybox {
  7     field myid     type string {}
  8     field myowner  type string {}
  9     field mytoys   type array<toy> {}
 10 }
 11
 12 field playroom type map<string, toybox> {
 13     struct-field key           { indexing: attribute }
 14     struct-field value.myid    { indexing: attribute }
 15     struct-field value.myowner { indexing: attribute }
 16     struct-field value.mytoys  {
 17         struct-field name  { indexing: attribute } # attr accepted, but not allowed?
 18         struct-field color { indexing: attribute } # attr accepted, but not allowed?
 19     }
 20 }
```

Note lines 17-18, which have `indexing: attribute`, but where attribute is not allowed.

**Expected behavior**

The expectation was that applying an application package with such a schema would generate a warning or error from the deploy api.

**Screenshots**

N/A

**Environment (please complete the following information):**

Mac OS X 12.6 (Intel chip)

**Vespa version**

8.54.61

**Additional context**

Additional details in this slack thread:
https://vespatalk.slack.com/archives/C038YTM5SUQ/p1674613344915269

There were also no errors when trying to query this field.

**Comment by geirst** [comment]
In Vespa 8.189.12 this will generate a warning during deploy (https://github.com/vespa-engine/vespa/pull/27618).

**Comment by geirst** [comment]
In Vespa 8.208.17 this will fail deployment (https://github.com/vespa-engine/vespa/pull/27984).
