### ISSUE TITLE
Consider not YQL filtering matchfeatures, rankfeatures, summaryfeatures

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#25741]
The YQL field filter searcher removes all fields that are not explicit mention in the select statement. On many occasions, this needs to be clarified for the special ranking-related field features. They should be returned regardless of the YQL select field scoping.

**Comment by bratseth** [comment]
Done in 8.118 - https://github.com/vespa-engine/vespa/pull/25774

**Comment by jobergum** [comment]
Thanks!
