### ISSUE TITLE
Support physical fieldsets / composite fields

### ISSUE THREAD

**Issue by mattweber** [vespa-engine/vespa#25971]
**Is your feature request related to a problem? Please describe.**
I am unable to create physical composite fields, only a virtual query-time `fieldset`.

**Describe the solution you'd like**
Add support for creating a `fieldset` that is actually a physical index field with all the necessary data structures in memory / on disk.  This is useful for unified term statistics in scoring or for more efficient term expansions if #25970 is ever supported.  Might even help with #25618.

**Describe alternatives you've considered**
Creating the composite field outside of the engine or in an indexing component.  These are possible but it would be much nicer to have this supported natively inside the schema.

**Additional context**
None

**Comment by mattweber** [comment]
Looking for something similar to `copy_to` or `fields` inside of elasticsearch mappings.

**Comment by jobergum** [comment]
You can stuff multiple fields into the same index:

```
field bloat type string {
  indexing: input title . " " . (input description || "")  |index
}```

**Comment by mattweber** [comment]
Thanks @jobergum! A bit hacky but would do the trick.  Thank you.

**Comment by jobergum** [comment]
I'm resolving this, and I don't think this is hackier than `copy_to` :)

**Comment by baldersheim** [comment]
A long time ago, like up to 12-15 years ago there was only a single index with many virtual fields. Reason was performance and reduction of disk seeks.
However with the arrival of 64 bit cpus, larger memory, and also the end of spinning disks era, performance was less of reason for single physical index.
The greater flexibility of having independent fields was much more valuable, both from a user perspective and from the development of the vespa core.
The experience was that most of the time the dictionary of a field was tied very much to the field. So sharing a dictionary with other fields made ranking a lot more complicated.
So we have never really looked back after we split out.

**Comment by mattweber** [comment]
Thank you @jobergum!  I never said `copy_to` wasn't a hack itself 🤣 

Thanks for the info @baldersheim , I remember those days with FAST ESP 😄  and probably why I still look for this functionality.
