### ISSUE TITLE
When running a vespa instance, I get the error

### ISSUE THREAD

**Issue by wjy3326** [vespa-engine/vespa#25974]
Waiting for application status, 210/300 seconds...
Waiting for application status, 215/300 seconds...
Waiting for application status, 220/300 seconds...
Waiting for application status, 225/300 seconds...
Waiting for application status, 230/300 seconds...
Waiting for application status, 235/300 seconds...
Waiting for application status, 240/300 seconds...
Waiting for application status, 245/300 seconds...
Waiting for application status, 250/300 seconds...
Waiting for application status, 255/300 seconds...
Waiting for application status, 260/300 seconds...
Waiting for application status, 265/300 seconds...
Waiting for application status, 270/300 seconds...
Waiting for application status, 275/300 seconds...
Waiting for application status, 280/300 seconds...
Waiting for application status, 285/300 seconds...
Waiting for application status, 290/300 seconds...
Waiting for application status, 295/300 seconds...
Traceback (most recent call last):
  File "faiss_vespa_test.py", line 196, in <module>
    app = vespa_docker.deploy(application_package=app_package)
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/vespa/deployment.py", line 194, in deploy
    return self._deploy_data(application_package, application_package.to_zip())
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/vespa/deployment.py", line 250, in _deploy_data
    app.wait_for_application_up(max_wait=APP_INIT_TIMEOUT)
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/vespa/application.py", line 185, in wait_for_application_up
    "Application did not start, waited for {0} seconds.".format(max_wait)
RuntimeError: Application did not start, waited for 300 seconds.

**Comment by kkraune** [comment]
It seems like the Vespa Container does not start - see https://docs.vespa.ai/en/components/bundles.html#troubleshooting for how to troubleshoot and let me know. /opt/vespa/logs/vespa.log (in the Docker container) usually has a descriptive error message

**Comment by wjy3326** [comment]
I run the app_package = QuestionAnswering() in https://pyvespa.readthedocs.io/en/latest/getting-started-pyvespa.html  I got the above error.  
When I use the default package like:  app_package = ApplicationPackage(name="vespa"), I get another error:

Waiting for configuration server, 0/300 seconds...
Waiting for configuration server, 5/300 seconds...
Traceback (most recent call last):
  File "faiss_vespa_test.py", line 196, in <module>
    app = vespa_docker.deploy(application_package=app_package)
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/vespa/deployment.py", line 194, in deploy
    return self._deploy_data(application_package, application_package.to_zip())
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/vespa/deployment.py", line 245, in _deploy_data
    r.status_code, json.loads(r.content.decode("utf8"))
RuntimeError: Deployment failed, code: 400, message: {'error-code': 'INVALID_APPLICATION_PACKAGE', 'message': "Invalid application: schema-removal: Schema 'context' is removed in content cluster 'vespa_content'. This will cause loss of all data in this schema. To allow this add <allow until='yyyy-mm-dd'>schema-removal</allow> to validation-overrides.xml, see https://docs.vespa.ai/en/reference/validation-overrides.html"}

I change the validation-overrides.xml to this:
<validation-overrides>
    {% if validations %}
    {% for validation in validations %}
    <allow until='2023-02-10'>content-cluster-removal</allow>
    {% endfor %}
    {% endif %}
</validation-overrides> 
the error is not solved.

**Comment by wjy3326** [comment]
I run the container use:  docker run --detach --name vespa --hostname vespa-container \
  --publish 8080:8080 --publish 19071:19071 \
  vespaengine/vespa

**Comment by kkraune** [comment]
It is a good idea to list and kill all Docker containers to make sure the start state is clean - do `docker ps` to make sure there are none in the list - you can also do `docker rm -v $(docker ps -a -q -f status=exited)`

"Schema 'context' is removed in content cluster" indicates you are deploying to an existing container with a different config

**Comment by kkraune** [comment]
I have added 
````
vespa_docker.container.stop()
vespa_docker.container.remove()
````
to many guides / documentation - I think this will help cleaning up from previous experiments. I hope this solved your problem, thanks for reporting!
