### ISSUE TITLE
Vespa Visit for entire cluster is running slow

### ISSUE THREAD

**Issue by akhilambati** [vespa-engine/vespa#26020]
Problem statement:
I have a Vespa Cluster of 41Million docs, having 39 schemas, when performing complete visit on the cluster after 12hrs it was able to complete only 20%(which progress shown in verbose output), can you suggest how can i make this process faster?
command --> vespa-visit -v --progess progressFile.txt --visitremove remove-entries 

Cluster Resources:
3 Config Nodes - 2 cpu, 8gb ram each
5 Container Nodes - 3 cpu,64gb ram each
12 Content Nodes - 3 cpu, 82gb ram each

while performing entire visit,
1.one of the config node where i was running visit, cpu and memory was 50% and on other config nodes cpu usage is less than 3% and memory usage is less than 50%
2. on container nodes, cpu  usage is less than 3% and memory usage is more than 50%
3. on all content nodes, cpu usage is more or less 20% and memory usage is more than 80%

**Comment by akhilambati** [comment]
Visiting operation got stuck after 20%, the log says something like this
Visitor Error : TIMEOUT : ReturnCode(TIMEOUT, [ from content node n] A timeout occured while waiting for 'tcp/dns.local:41235/visitor-1-167xxxx' (180 seconds expired); (RPC) Invocation timed out)

**Comment by akhilambati** [comment]
I have killed the visit process and started again using the same process file, there is no progress after 20%, seeing same Visitor error as mentioned below 
Visitor Error : TIMEOUT : ReturnCode(TIMEOUT, [ from content node n] A timeout occured while waiting for 'tcp/dns.local:41235/visitor-1-167xxxx' (180 seconds expired); (RPC) Invocation timed out)

**Comment by akhilambati** [comment]
Hi, I got the inputs from slack channel https://vespatalk.slack.com/archives/C01QNBPPNT1/p1676381397413969, thanks for your time, please add if you have any suggestions
Thanks

**Comment by bratseth** [comment]
So, the description sounds like you are buffering everything that the visit operation returns in memory on the client side, which will eventually fail.

- Did specifying --unbuffered and/or --stream to jq help?
- Did you try to output the visit result to /dev/null to verify thius is a client problem?

**Comment by akhilambati** [comment]
hi @bratseth sorry for getting back late
* specifying --unbuffered didn't help.
* yes tried output of visit redirecting to null device, it worked

**Comment by bratseth** [comment]
That indicates that the issue is in _receiving_ the data, using jq (and using unbuffered with jq doesn't resolve it).

I'm not sure what the end goal here is, but maybe you can write chunks to disk, and then use jq to process those chunks, or else write a small programmatic client to process the data you receive, where you can control the memory usage better than with jq.

**Comment by Shiridisai111** [comment]
okay thanks for your inputs @bratseth
