### ISSUE TITLE
Pattern field types for E-Commerce

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26104]
**Is your feature request related to a problem? Please describe.**
I considered integrating Vespa to my WooCommerce plugin. 
But for this use case the schema is not fixed, as the site owner may add fields, change field types, and re-index on-the-fly. By settings or code. 
For instance, WooCommerce provides several pricing fields, that a WooCommerce site can choose to use as a numerical facet or not.
A manual update of the schema file with the use of a CLI command to apply is not a realistic option here.

**Describe the solution you'd like**
A solution would be defining dynamic types based on the field name pattern. 
This is the solution I use with [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-unmatch) and [Apache Solr](https://solr.apache.org/guide/solr/latest/indexing-guide/dynamic-fields.html).
Great solution, as it does not require to restart/reapply anything.

**Describe alternatives you've considered**
Another solution would be a schema field API to update field and field type definitions. I use this solution with Weaviate or Google Retail Search API.

**Additional context**
Controlling the schema files by hand is certainly the way to go for big projects.
For smaller projects, or ready-to-use OEM integrations, an API can efficiently hide technical layers to the untrained eyes.

**Comment by bratseth** [comment]
The CLI just uses a REST API to deploy.

Use https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#prepareandactivate
to just deploy an application package.

Or if you want to do it as a 2-phase commit use
https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#prepare-session
then
https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#activate-session

**Comment by eostis** [comment]
Thanks @bratseth. 

What do you think of dynamic fields? 
You define them once at the creation of your schema, and then never have to reactivate your application.

**Comment by bratseth** [comment]
Re dynamic fields, I think it would be useful to support indexes on maps of text strings, which I think is what you really need here?

Map attributes are already supported, which I think solves this need for structured data.

**Comment by eostis** [comment]
Dynamic fields are for environments with highly unpredictable evolving schema definitions.

In a ideal use case, the schema and all its field definitions are know in advance. We can provide a default schema that will not change at all, or infrequently.

In my use case, I'm integrating Vespa APIs in a WooCommerce plugin. 

Users will download the plugin, install it on their site, and configure it. 

More specifically, they will need to update the schema to their own instance specification. 

For instance, they will add product attributes like colour, size, price. 

For each of those attributes, they will set the type: a string, a text, an integer, a floating point.

In the ideal situation, the schema will contain dynamic field types, based on field names patterns: *_str, *_txt, *_i, *_f, *,blob ...

If the user select the type string to the attribute colour, the field name colour_str will be indexed, which will be mapped to the pattern *_str.

Hence, I can provide a default schema will all the patterns, and users do not have to adapt it and reactivate their application for every new field.

**Comment by jobergum** [comment]
Vespa should never support dynamic field types, anyone that used that in production will agree. Guessing the type is one thing. How it should be matched, ranked, or sorted is undefined. And if you have 30 unknown fields, you can solve that in a single deployment.

**Comment by eostis** [comment]
@jobergum I suspect you think of shemaless dynamic fields: when field types are inferred dynamically from field's indexed data.

What I'm referring to are field types, written in the schema files, but attached to a field name pattern rather than a field name.

Something like:
```
field *_txt type string {
            indexing: summary | attribute
            match: word
            rank: filter
        }

```

**Comment by jobergum** [comment]
Yes, schemaless dynamic fields. Your particular example is supported using `map<string,string>` but it does not generalize beyond that.

**Comment by eostis** [comment]
I considered that indeed. But can I prepare/activate an application package with just the schema modifications required?

=> A owner could modify and activate the application package files delivered by my plugin: I do not want the plugin to erase them during its prepare/activate operation. All files but the schema files shoud remain untouched.

**Comment by bratseth** [comment]
> But can I prepare/activate an application package with just the schema modifications required?

Yes, that is safe and the advantage is that these changes will be validated against the rest of the application package which references the fields.

> All files but the schema files shoud remain untouched.

Sounds like you can achieve this just by controlling how the application package is generated?

**Comment by eostis** [comment]
> Sounds like you can achieve this just by controlling how the application package is generated?
This is the point, I cannot because both the plugin and the site owner can work on the application files: 
1. The plugin provides some default application files
2. The site owner can modify the application files, outside of the plugin
3. The plugin should be able to add fields to the schema without overriding the site owner configuration

Something like with a decentralised git:  the plugin and the owner should "clone"/"fetch" the server application files to synchronize them locally, modify/add files locally, then "push" the changes.

With other engines, this problem does not occur, because:
1. The schema is provided by the plugin with pattern field types, and therefore is never required to be updated by the plugin. No conflict here.
2. Or the engine provides APIs to create the fields on the server directly, without the need to fetch/push all the configuration files

**Comment by bratseth** [comment]
You can change just some files of the application package when redeploying, using the application/v2 API (create a session from the current one, put new/changed files, deploy).

You can also use document type inheritance to provide a set of base fields and let applications add more without modifying the same files.

**Comment by eostis** [comment]
But can I redeploy only one file? (the schema type)

**Comment by bratseth** [comment]
Yes.

**Comment by eostis** [comment]
Thanks. That could be a good workaround indeed. Will try that.

I'll keep this issue open, because I think pattern field types would be a nice addition to Vespa's features. No need to redeploy when new fields need to be indexed and searched during the lifetime of an application.

**Comment by bratseth** [comment]
You need to modify an existing full application. by creating a new edit session from the current one, as in this example: https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#use-case-modify

**Comment by eostis** [comment]
Thanks 🙏

**Comment by eostis** [comment]
Feedback after a few more tests: I could not deploy schemas incrementally without deploying the whole application files.

Is there a way to get all files from an active application with the APIs? 

(I noticed `vespa-deploy fetch`, but could not find the same fetch in the APIs)

**Comment by kkraune** [comment]
Good question! There is no easy way to get the full package in one operation - https://cloud.vespa.ai/en/cloning-applications-and-data#cloning---self-hosted-to-vespa-cloud :
```
$ docker exec vespa1 sh -c "mkdir -p /tmp/d && cd /tmp/d && /opt/vespa/bin/vespa-deploy fetch"

$ docker exec -w /tmp/d vespa1 tar cvf - . | tar xvf -

$ docker exec vespa1 rm -rf /tmp/d
```
which is clunky. Maybe to can create a feature request for this?

**Comment by eostis** [comment]
New fetch API issue: #26487

**Comment by bratseth** [comment]
> Feedback after a few more tests: I could not deploy schemas incrementally without deploying the whole application files.

Did you follow the example I pointed to? If so, which part of it didn't work for you?

**Comment by eostis** [comment]
I did. But I discovered that to add new schemas to an active application, I needed to redeploy the whole /schema/ folder content also. Hence my request for a cleaner fetch API.

**Comment by bratseth** [comment]
How did you discover that? That example shows how to create a new session from a currently active application, which means you don't need to do that.

**Comment by bratseth** [comment]
From that example (step 2):

Session 1 is activated and cannot be changed - create a new session based on the active session:

`$ curl -s -X POST "http://host:19071/application/v2/tenant/mytenant/session?from=http://host:19071/application/v2/tenant/mytenant/application/fooapp/environment/default/region/default/instance/default"`

Notice the **from** argument.

**Comment by eostis** [comment]
# Error
`{"error-code":"BAD_REQUEST","message":"Error preprocessing application package for default.default, session 3: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.: Content is not allowed in prolog."}
`

Below are the steps I followed. Notice that after the error, I ran a "vespa deploy" with success to check that no syntax error occured.  

# get session
`curl -X POST "http://localhost:19071/application/v2/tenant/default/session?from=http://localhost:19071/application/v2/tenant/default/application/default/environment/default/region/default/instance/default"
`
# set session
`VESPA_SESSION=3
`
# Redeploy with a new schema in /schemas/ and also declared in services.xml
```
curl -X PUT --data-binary services.xml "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/services.xml" && \
  curl -X PUT --data-binary services.xml "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/schemas/music9.sd" && \
  curl -X PUT "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/prepared?applicationName=default"


```

**Comment by eostis** [comment]
🙏 It worked.

```
# Create session
curl -X POST "http://localhost:19071/application/v2/tenant/default/session?from=http://localhost:19071/application/v2/tenant/default/application/default/environment/default/region/default/instance/default"

# Use session
VESPA_SESSION=3

# Deploy new schema with updated services.xml
curl -X PUT --data-binary @services.xml "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/services.xml" && \
  curl -X PUT --data-binary @schemas/music9.sd "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/schemas/music9.sd" && \
  curl -X PUT "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/prepared?applicationName=default"

```

**Comment by eostis** [comment]
We also remove a schema incrementally:

```
# Create session
curl -X POST "http://localhost:19071/application/v2/tenant/default/session?from=http://localhost:19071/application/v2/tenant/default/application/default/environment/default/region/default/instance/default"

# Use session
VESPA_SESSION=4

# Deploy deleted schema with updated services.xml
curl -X PUT --data-binary @services.xml "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/services.xml" && \
  curl -X DELETE "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/content/schemas/music9.sd" && \
  curl -X PUT "http://localhost:19071/application/v2/tenant/default/session/${VESPA_SESSION}/prepared?applicationName=default"

```

**Comment by eostis** [comment]
Closing inactive issue.
