### ISSUE TITLE
Exception while bringing up  container using vespa docker image with Podman

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#26123]
**Describe the bug**
We are trying to bring up vespa cluster using podman. We are trying to run vespa application as vespa user. 
We are using this documentation to understand how to setup vespa in docker as reference - https://docs.vespa.ai/en/operations/docker-containers.html.

We were able to bring up the config node but facing some issues while bringing up the container and content node. 

> hostname: you must be root to change the host name
> Wrong owner for /opt/vespa/logs, expected vespa, was root

```
Podman command - 
podman --log-level debug run --privileged --pids-limit=0 --ulimit nofile=x:x --detach --name content-0 --user vespa:vespa --hostname <current-host-name>  -e VESPA_CONFIGSERVERS=<host-name>  --publish 8080:8080 --publish 19000-19110:19000-19110 --volume $VESPA_VAR_STORAGE:/opt/vespa/var --volume $VESPA_LOG_STORAGE:/opt/vespa/logs   <image-registry? services   

```

The volume path have all the permissions and I can even see files on the host for the volumes mapped
 

> echo $VESPA_VAR_STORAGE
> /tmp/vespa/var
>  echo $VESPA_LOG_STORAGE
> /tmp/vespa/logs
> 
> -bash-4.4$ ls -ltr /tmp/vespa/
> total 8
> drwxrwxrwx. 8 systemUser systemUser 4096 Feb 21 04:14 var
> drwxrwxrwx. 3 systemUser systemUser 4096 Feb 21 04:14 logs

**Vespa version**
(vespa:8.82.24)

**Additional context**
We checked the owners of the file  to confirm that vespa is owner of logs and var directory. 

> INFO[0018] Running: [/bin/sh -c ls -ltr /opt/vespa/]    
> total 12
> drwxr-xr-x. 2 root  root  4096 Feb 21 09:23 bin
> drwxr-xr-x. 8 root  root   116 Feb 21 09:23 conf
> drwxr-xr-x. 3 root  root    19 Feb 21 09:23 include
> drwxr-xr-x. 4 root  root    58 Feb 21 09:23 etc
> lrwxrwxrwx. 1 root  root    27 Feb 21 09:23 jdk -> /usr/lib/jvm/jre-17-openjdk
> drwxr-xr-x. 4 root  root    31 Feb 21 09:23 lib
> drwxr-xr-x. 3 root  root  4096 Feb 21 09:23 lib64
> drwxr-xr-x. 3 root  root    19 Feb 21 09:23 libexec
> drwxr-xr-x. 4 vespa vespa   35 Feb 21 09:23 logs
> drwxr-xr-x. 3 root  root    18 Feb 21 09:23 man
> drwxr-xr-x. 2 root  root   254 Feb 21 09:23 sbin
> drwxr-xr-x. 3 root  root    19 Feb 21 09:23 share
> lrwxrwxrwx. 1 root  root    18 Feb 21 09:23 tmp -> /opt/vespa/var/tmp
> drwxr-xr-x. 9 vespa vespa  104 Feb 21 09:23 var

We also tried to create another image with the base vespa image so that we can run chown on these directories

> INFO[0052] Running: [/bin/sh -c ls -ltr /opt/vespa/]    
> total 12
> drwxr-xr-x. 2 vespa vespa 4096 Feb 21 09:41 bin
> drwxr-xr-x. 8 vespa vespa  116 Feb 21 09:41 conf
> drwxr-xr-x. 3 vespa vespa   19 Feb 21 09:41 include	
> drwxr-xr-x. 4 vespa vespa   58 Feb 21 09:41 etc
> lrwxrwxrwx. 1 vespa vespa   27 Feb 21 09:41 jdk -> /usr/lib/jvm/jre-17-openjdk
> drwxr-xr-x. 4 vespa vespa   31 Feb 21 09:41 lib
> drwxr-xr-x. 3 vespa vespa 4096 Feb 21 09:41 lib64
> drwxr-xr-x. 3 vespa vespa   19 Feb 21 09:41 libexec
> drwxr-xr-x. 4 vespa vespa   35 Feb 21 09:41 logs
> drwxr-xr-x. 3 vespa vespa   18 Feb 21 09:41 man
> drwxr-xr-x. 2 vespa vespa  254 Feb 21 09:41 sbin
> drwxr-xr-x. 3 vespa vespa   19 Feb 21 09:41 share
> lrwxrwxrwx. 1 vespa vespa   18 Feb 21 09:41 tmp -> /opt/vespa/var/tmp
> drwxr-xr-x. 9 vespa vespa  104 Feb 21 09:41 var
> 

Can someone help  us understand what the issue might be

**Comment by kkraune** [comment]
Hi!

Please see a related discussion in https://app.slack.com/client/T01RFPFNAHX/C01QNBPPNT1/thread/C01QNBPPNT1-1676528386.142449

https://docs.vespa.ai/en/operations/multinode-systems.html documents how to configure and run multinode systems. Other than that, we can provide little or no support, as there are so many different environments. We know it can be done with podman, but there are many things to consider, like how to map file systems for good performance and so on. To start with, I would not map anything, just to get things going. User ids are also different outside/inside containers.

Note that recent Vespa versions have changes to start scripts; please upgrade from 8.82.24. The newer versions have better safeguards and refuse to start when permissions are wrong, with good error messages.

**Comment by 107dipan** [comment]
We were able to bring up the vespa cluster on podman wby creating podman volumes and creating another image on top of the vespa docker file that runs with user vespa.

Thanks for the response!

**Comment by kkraune** [comment]
Great! closing.
