### ISSUE TITLE
docker-compose.yml examples and generator 

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26149]
All examples use docker run with command arguments.

Would it be possible to get the examples with docker-compose.yml also? (At least for example "album-recommendation")

**Comment by kkraune** [comment]
Hi! that would be possible yes, we opted not to do it in order to be explicit on all the steps in the guides. As we auto-test the examples and documentation it gets more complicated to support multiple ways to do it. What would be your benefit with the compose-file? (I might be overlooking things)

**Comment by eostis** [comment]
For me, the point of docker-compose is to make explicit some implicit features, hence to learn about the architecture of Vespa.

This would be a great way to explain Vespa to newbies. More or less everyone is able to read a docker compose file.

We could have several files with increasing complexity of architecture.

I found https://github.com/yahoojapan/vespa-tutorial/blob/master/docker-compose.yml, which is pretty interesting as it exposes the configserver and 2 services containers. But I could not make it work yet (ports 8080, 8081, and 8082 are not accessible).

**Comment by jobergum** [comment]
Yeah, that is outdated. We should create docker compose examples, maybe for the high availability sample app @kkraune ?

**Comment by eostis** [comment]
Or even a docker compose generator like https://weaviate.io/developers/weaviate/installation/docker-compose ?

**Comment by kkraune** [comment]
https://github.com/vespa-engine/sample-apps/pull/1149

**Comment by kkraune** [comment]
Please take a look at https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA#docker-compose and let me know if this is better - feedback welcome, and thanks for reporting!
