### ISSUE TITLE
Docker image disk size is too small

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26141]
Just after launching a clean docker, the disk is 90% full:
`docker run --detach --name vespa --hostname vespa-container   --publish 8080:8080 --publish 19071:19071   vespaengine/vespa
`
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1785759/220633352-7f0cbe2f-6ba2-49d0-b2c8-b53d2fc91f36.png">

Error at first indexing from demo:
```
vespa clone album-recommendation myapp && cd myapp
vespa deploy --wait 300
vespa document ext/Love-Is-Here-To-Stay.json
```
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/1785759/220634314-7918f75a-4c99-479f-8e30-559dd0322d0c.png">

**Comment by kkraune** [comment]
This depends on how much disk you have allocated in Docker preferences - I suggest you increase this; I am using Docker Desktop, Preferences -> Resources

**Comment by eostis** [comment]
It worked. 🙏 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1785759/220641597-8eaeaee7-9c44-4693-bde7-606706169ffb.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1785759/220641765-1efa1856-300d-4bf7-8405-cf309ab73e0d.png">

**Comment by eostis** [comment]
Could be worth mentioning that in the documentation !!

**Comment by kkraune** [comment]
True - I'll make sure it gets there soon - thanks for reporting!

**Comment by kkraune** [comment]
Update doc: https://github.com/vespa-engine/documentation/pull/2537
