### ISSUE TITLE
GKE Helm Charts and scripts for small/medium projects

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26186]
The guide https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/basic-search-on-gke is a good starting point.

My goal is to get a production ready environment for WooCommerce sites that cannot afford a managed Vespa Cloud (that I would recommend first !), but still require better scalability than a single docker container.

**Comment by kkraune** [comment]
I have created https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA/gke - it is a step on the way

**Comment by eostis** [comment]
Nice !! 👌 

Can't wait to play with it. Still working on the local docker instance...

**Comment by kkraune** [comment]
I am not sure whether  https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA/gke will suffice for most people - If we are to support https://helm.sh/ , we should also consider Terraform and so on... To be discussed
