### ISSUE TITLE
Boolean field in the schema is added to document with default value even when it is not present in actual payload.

### ISSUE THREAD

**Issue by shubh9194** [vespa-engine/vespa#26217]
**Describe the bug**
I have a cluster in which I have deployed couple of schemas. I have added few boolean fields.
I have noticed whenever i ingest a document for schema that has boolean field. After Ingestion, bool field is present in the doc even though it was not present in the actual payload with default value of false.
Is this usual behavior in vespa? 
Is there a way to avoid this?

example of field in schema 
field isHandled_b type bool {
      indexing: summary | attribute
}
summary isHandled_b type bool {
     source: isHandled_b        
}

**Screenshots**

**Environment (please complete the following information):** - OS: [e.g. iOS]
 - Infrastructure: Kubernetes

**Vespa version**
8.82.24

**Additional context**

**Comment by bratseth** [comment]
Yes, boolean fields aren't tri-state, just `true` or `false`.

The only way to avoid it is to use a string field with some fixed values (e.g "true" and "false") instead.
