### ISSUE TITLE
Add support for using attribute with type raw 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#26242]
Several Vespa users use Vespa as a key-value store because of the high availability and elasticity plus the ability to perform ranking for the values retrieved. For low latency serving and with binary payloads, Vespa should support `attribute` for [type raw](https://docs.vespa.ai/en/reference/schema-reference.html#type:raw).

**Comment by geirst** [comment]
This is now supported in Vespa 8.141.24.

See the system test for examples of use: https://github.com/vespa-engine/system-test/tree/master/tests/search/raw_attributes

**Comment by geirst** [comment]
Reference doc: https://docs.vespa.ai/en/reference/schema-reference.html#type:raw
