### ISSUE TITLE
Improve Vespa Cloud Status and incident updates published via RSS

### ISSUE THREAD

**Issue by rorymc** [vespa-engine/vespa#26292]
**Is your feature request related to a problem? Please describe.**

Here is an example of a status update published out via RSS:

> Vespa Cloud Status Updates
> WARNING: We have confirmed that we are impacted by an issue with our certificate provider that are working to address this. Note that running instances will not be impacted - only new deployments. ()

As compared to other systems which publish out status via RSS, Vespa's updates have a few things which could be improved:

1. (optional) include a sub-page for every incident.  this is useful because updates for the given incident can be easily seen in a deep-link, instead of from the main status page.
2. include a link to either the specific incident sub-page, or to the main https://cloud.vespa.ai/status page, in the text
3. fix whatever is appending the empty `()` at the end of each status update from Vespa

**Describe the solution you'd like**

Here are 2 examples from GCP Status updates published via RSS, which has the features i mentioned above:

An update to an existing incident:

> Google Cloud Service Health Updates
> [UPDATE: Cloud SQL Create Operations Failing Globally](https://status.cloud.google.com/incidents/y7wwfrMbL3UNpsrfCYxN)
> Incident began at 2023-03-03 12:20 (all times are US/Pacific).Summary: Cloud SQL Create Operations Failing Globally
> Description: We've received a report of an issue with Google Cloud SQL as of Friday, 2023-03-03 12:20 US/Pacific.
> We will provide more information by Friday, 2023-03-03 13:20 US/Pacific.
> Diagnosis: Cloud SQL Create Operations Failing Globally
> Workaround: None at this time.
> Affected products: Google Cloud SQL

when an existing incident is resolved:

> Google Cloud Service Health Updates
> [RESOLVED: Cloud SQL Create Operations Failing Globally](https://status.cloud.google.com/incidents/y7wwfrMbL3UNpsrfCYxN)
> Incident began at 2023-03-03 12:20 and ended at 2023-03-03 13:13 (all times are US/Pacific).The issue with Google Cloud SQL has been resolved for all affected projects as of Friday, 2023-03-03 13:07 US/Pacific.
> We thank you for your patience while we worked on resolving the issue.
> Affected products: Google Cloud SQL

and here is an example of an update from GitHub Status:

> GitHub Status - Incident History
> [Incident with Actions and Codespaces](https://www.githubstatus.com/incidents/d6f6kjk81v33)
> Feb 28, 17:31 UTC
> Resolved - This incident has been resolved.Feb 28, 17:26 UTC
> Update - Codespaces is operating normally.Feb 28, 17:00 UTC
> Update - Actions is now experiencing degraded performance. We are still investigating and will provide an update when we have one.Feb 28, 17:00 UTC
> Update - Actions is now experiencing degraded availability. We are continuing to investigate.Feb 28, 16:58 UTC
> Update - The Actions Larger Runner beta is experiencing issues with VM scale up which will lead to...

For ref:
* Vespa Status RSS feed:  https://cloud.vespa.ai/status.xml
* GCP Status RSS feed:  https://status.cloud.google.com/feed.atom
* GitHub Status RSS feed:  https://www.githubstatus.com/history.rss

**Comment by frodelu** [comment]
Hi Rory,

Thank you for your input. As you may know, our current status update mechanism is of the simpler sort using GitHub Pages (for now), so the more advanced features you mention are likely not something we will add in the short term. That being said; I made some minor changes to address some of your comments in [vespa-engine/cloud#677](https://github.com/vespa-engine/cloud/pull/677):
* Included a link to the status page (https://cloud.vespa.ai/status) as a link to every entry. This should work for most RSS readers, I would assume.
* Somewhat improved wording in the prefix to the title based on the status.

With regards to the empty parenthesis you mention; this is not something I see in the feed. Is it added by your RSS reader? Is it a field we are missing that is causing this to be empty? Here is what I see in the raw output:
```xml
<entry>
    <id>id:cloud.vespa.ai-2023:feed:321677876900</id>
    <link href="https://cloud.vespa.ai/status.html" />
    <title>PROBLEM: We have confirmed that we are impacted by an issue with our certificate provider that are working to address this. Note that running instances will not be impacted - only new deployments.</title>
    <updated>2023-03-03T20:55:00+00:00</updated>
</entry>
```

This is _after_ my recent update, but I didn't see the empty brackets there prior to the update either.
