### ISSUE TITLE
Enable cluster selection in local environments

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#26388]
**Is your feature request related to a problem? Please describe.**
Imagine that you have a vespa application where one container is dedicated to doc processing and another to search, that means having two <container>...</container> tags at your services.xml. This means having a docker container for each one or more (see the multinode-HA example in the sample-apps of vespa-engine organization).

If we want to run system tests in a local environment, the vespa cli does not recognize the containers (cluster flag) that the application and will put as base url the value http://127.0.0.1:8080 in every case. However, if we run the same tests in a hosted environment like Vespa Cloud, it will get the appropriate base url.

**Describe the solution you'd like**
Vespa cli should support the selection of the cluster when the target flag is set to local.

**Describe alternatives you've considered**
The local target could use the environment variable called "VESPA_CLI_ENDPOINTS" to enable this feature request

**Additional context**
Nothing.

**Comment by mpolden** [comment]
There is no way for Vespa CLI to discover clusters by name when running Vespa locally. However, you can pass the URL to your other cluster as the target:
```
$ vespa query --target http://localhost:8081 'select * from music where year = 2015'
```

**Comment by danitico** [comment]
Hi @mpolden ! It seems that now cluster selection is enabled for system tests in local environments. We have run a system test and we have seen the following error:

```
Error: error in Step 8: finds results by category (non matching): no such service: "query": known services: feed
```

Did you release this feature?

**Comment by danitico** [comment]
oh ok! What I am checking is that if we want to maintain the same system tests for local and for vespa cloud, we will need to change somehow the cluster selected request. Let me explain:

We now have this services.xml:

```xml
<?xml version='1.0' encoding='UTF-8'?>

<services version="1.0" xmlns:deploy="vespa" xmlns:preprocess="properties">
  <preprocess:properties>
    <feeder.container.name>feed</feeder.container.name>
    <searcher.container.name>query</searcher.container.name>
    <content.name>vlex</content.name>
  </preprocess:properties>

  <container id="${feeder.container.name}" version="1.0">
    <preprocess:include file="xml/handlers/feeder-handlers.xml" />
    <preprocess:include file="xml/handlers/searcher-handlers.xml" />

    <preprocess:include file="xml/docproc/chain.xml" />
    <preprocess:include file="xml/searchers/chain.xml" />
    <document-api />

    <preprocess:include file="xml/document-bindings.xml" />

    <preprocess:include file="xml/injections/common-injections-components.xml" />
    <preprocess:include file="xml/injections/feeder-injections-components.xml" required="false"/>
    <preprocess:include file="xml/injections/searcher-injections-components.xml" required="false"/>

    <preprocess:include file="xml/deployment/local/container.xml"/>
  </container>

  <content id="${content.name}" version="1.0">
    <redundancy>1</redundancy>
    <preprocess:include file="xml/configs/content-cluster-configs.xml"/>
    <preprocess:include file="xml/content/content-documents.xml"/>
    <preprocess:include file="xml/deployment/local/content.xml"/>
  </content>
</services>
```

As you can see here, we only define a cluster, but our system tests we have the following:

```json
{
    ...
    {
      "name": "feed stack",
      "request": {
        "method": "POST",
        "cluster": "feed",
        "body": "../data/administrativeDecision/stack.json",
        "uri": "/document/v1/test/administrativeDecision/docid/stack"
      }
    },
    {
      "name": "finds results by category (non matching)",
      "request": {
        "uri": "/rest/search/administrative_decision",
        "cluster": "query",
        "parameters": {
          "category": "threehundred"
        }
      },
      "response": {
        "body": {
          "root": {
            "fields": {
              "totalCount": 0
            }
          }
        }
      }
    },
    ...
}
```

So the behaviour we are observing is that we don't have the "query" in local environment, but this will drive us to have different system tests for local and vespa cloud.

**Comment by mpolden** [comment]
Do you use a different services.xml on local vs. Vespa Cloud? If you want to run the exact same tests in both environments, they need to have the same clusters. You could simply add a "query" cluster to the local environment.
