### ISSUE TITLE
YQL does not recognize special sorting "fields" [relevance], [docid]

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#26397]
The special sorting attributes cannot be used in YQL it seems:

https://docs.vespa.ai/en/reference/sorting.html#special-sorting-attributes

https://api.cord19.vespa.ai/search/?yql=select%20id,title%20from%20doc%20where%20userQuery()%20order%20by%20[relevance]&query=sars

```
Could not create query from YQL: query:L1:53 no viable alternative at input '[relevance'
```

**Comment by bjormel** [comment]
You have to encapsulate the special sorting attributes with `'`:
https://api.cord19.vespa.ai/search/?yql=select%20id,title%20from%20doc%20where%20userQuery()%20order%20by%20%27%5Brelevance%5D%27&query=sars

**Comment by jobergum** [comment]
Ok, this works https://api.cord19.vespa.ai/search/?yql=select%20id,title%20from%20doc%20where%20userQuery()%20order%20by%20%27%5Brelevance%5D%27%20desc,%27%5Bdocid%5D%27%20desc&query=sars&tracelevel=3

Should I update the documentation with this example @bratseth, or we will soon address it?

**Comment by bratseth** [comment]
Please update the doc, attempting to parse this without quotes becomes a mess.
