### ISSUE TITLE
List tenant applications?

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26481]
I carefully browsed the API documentation, but could not find how to list applications (of a tenant)

**Comment by kkraune** [comment]
The open source code/doc is made for single tenant / single application use - I know this can be a bit confusing in the documentation, sorry about that

**Comment by eostis** [comment]
I can list and create tenants. Not applications?

**Comment by kkraune** [comment]
I suppose you can, I dont know the API that well ...

But as I said, the open source doc is built for the single app case, so you might need to read the code to find out

**Comment by bratseth** [comment]
The open source product does not support having multiple tenants and applications on the same config server so they are always "default" and "default". I know this API suggest it should be possible, but we have since realized this is too hard for self-hosting - especially when upgrading one of those applications as you need the config model of that application to be on the version you're upgrading to, so they are better off by using separate config clusters per application.

**Comment by eostis** [comment]
Thanks for this precision.

And what about the hosted API? Can I list the applications of a tenant too?

**Comment by bratseth** [comment]
Yes, if you have admin rights on that tenant.

**Comment by eostis** [comment]
Great. Where can I find it?

**Comment by bratseth** [comment]
Not explicitly documented, but use this API in the obvious way as a REST API: https://cloud.vespa.ai/en/reference/vespa-cloud-api.html#http-deploy

**Comment by bratseth** [comment]
... however, in this API (application/V4) we do not have support for incremental application package changes yet. It's something we want to do, but haven't gotten around to yet. Github issues isn't for Vespa Cloud support though, maybe it is better if you write up what you want to do and send it to us over the Vespa Cloud support channel so we can follow up there.

**Comment by eostis** [comment]
Thanks. I will contact the Vespa Cloud support indeed.

(I thought self hosted and hosted applications behave in the same way)

For now, I will concentrate on the self hosted API, knowing that tenant and application are both "default". 

To answer your question, my goal is to integrate Vespa to my WordPress/WooCommerce search plugin. Reading the documentation, I imagined that I would build the UI with dropdown lists,  so that a user could choose among his Vespa cluster's tenants and tenant applications.
