### ISSUE TITLE
New API to download application packages

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26487]
From #26104

Build an API to get all files from an active application to redeply it incrementally

(I noticed vespa-deploy fetch, but could not find the same fetch in the APIs)

Use case:  an application package is already deployed with some schemas on a remote server or in the cloud. You want to add/remove/update a schema from it, without erasing other schemas. But you do not have access to the source of the last deployed files, nor to the server filesystem.

**Comment by johans1** [comment]
Add to application v4 and v2 and CLI, use it in the console

**Comment by eostis** [comment]
Closing inactive issue.

**Comment by bratseth** [comment]
On our backlog.

**Comment by baldersheim** [comment]
backlog or **soon** ....

**Comment by mpolden** [comment]
`vespa fetch` is available in 8.265.12.
