### ISSUE TITLE
Add tensor rank expression support and nearestNeighbor for streaming search

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#26483]
[Streaming search](https://docs.vespa.ai/en/streaming-search.html) does currently not support using tensors in ranking expressions. There is no warning about this when deploying a rank profile with tensor expressions.

The current workaround for vector search is to use legacy dot products over an array of floats: 

```field embedding_vector type array<float> { indexing: summary | attribute}```

Query example limited to personal data for userid=1 and for document text containing april. 

```
/search/?yql=select%20*%20from%20sources%20*%20where%20text%20contains%20"april"&streaming.userid=1&tracelevel=0&ranking.properties.dotProduct.query=[1%202%203%204]&ranking=embedding
```

```
rank-profile embedding {
      first-phase {
        expression: dotProduct(embedding_vector, query)
      }
}
```

**Comment by geirst** [comment]
Vector streaming search is available in Vespa 8.181.15. This supports using tensors and the nearestNeighbor query operator in streaming mode. 

See the blog post where the feature is announced: https://blog.vespa.ai/announcing-vector-streaming-search/
See the reference documentation for more details: https://docs.vespa.ai/en/streaming-search.html
