### ISSUE TITLE
Sitemaps for APIs

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26482]
It would be very time-efficient for developers to enhance the current APIs with some kind of sitemaps.

**Comment by kkraune** [comment]
Hi! Thanks for the request! I think it is a good idea to enhance API/documentation. By sitemap do you mean something like improving https://docs.vespa.ai/en/api.html or auto-generate from annotations in code? An example will help, and thanks!

**Comment by eostis** [comment]
Something like a recursive map of APIs and documentation is very helpful: 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1785759/226314158-1fba19ed-f88e-43c3-8aaa-570315e408e5.png">

**Comment by eostis** [comment]
Closing inactive issue.
