### ISSUE TITLE
Cleaner local vs cloud APIs and documentation

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26493]
I recently played a lot with the APIs to integrate them into a WordPress plugin.

It appears that the documentation and APIs are very targeted to cloud users. Which is normal as it is the historical project I believe.

But some API parameters like "tenant" do not exist at all on local envs ("default"). 

There are also no local application parameter neither, but docker containers (as I understand, the pyvespa client runs a new container per application).

This is very confusing for newbies!

**Comment by jobergum** [comment]
>It appears that the documentation and APIs are very targeted to cloud users.

Is that true? All the sample apps and all the documentation at docs.vespa.ai is targeted for self-served usage. Could you point to examples in the docs.vespa.ai that describes API's and functions or whatever that is exclusive to Vespa cloud? 

> There are also no local application parameter neither,
What do you mean by that?
