### ISSUE TITLE
Increase the hostname limit to 253

### ISSUE THREAD

**Issue by pehrs** [vespa-engine/vespa#26551]
**Is your feature request related to a problem? Please describe.**

Vespa limits the full FQDN to [64 characters](https://github.com/vespa-engine/vespa/blob/master/config-provisioning/src/main/java/com/yahoo/config/provision/HostName.java#L19)

It also looks like this check is only done when the config nodes restart as we were able to create a cluster with content nodes that had longer names by first starting the config nodes and then later the content nodes.
Later when the application was deployed and we needed to restart the config nodes they would just get stuck in an loop failing to start.

**Describe the solution you'd like**

Please change the 64 limit to 253 which is what [Linux support](https://man7.org/linux/man-pages/man7/hostname.7.html) (we are running your docker image with CentOS)
Also allow for trailing dots as that is [allowed in DNS](http://www.dns-sd.org/trailingdotsindomainnames.html)

**Describe alternatives you've considered**

We currently have to limit our node FQDN names to 64 characters not to run into this problem.

**Additional context**

**Comment by andreer** [comment]
Internally we set the hostname to the FQDN, which is probably why we have this limit. But recommendations seem to vary, e.g. https://serverfault.com/questions/331936/setting-the-hostname-fqdn-or-short-name - I don't think Vespa should enforce one choice over the other here.

**Comment by jonmv** [comment]
https://github.com/vespa-engine/vespa/pull/26643 changes some configserver code to use the more relaxed `DomainName` class. I believe this is enough to run with longer names in a self-hosted environment. Due to Easter vacation, we won't be releasing a new version before April 11.

**Comment by andreer** [comment]
@pehrs can you confirm whether this change improves things for you?
