### ISSUE TITLE
Upsert, update, partial update, non-existent

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26562]
The documentation for Upserts is confusing. 

What is the API for upserts, among:

**Update**
https://docs.vespa.ai/en/reads-and-writes.html#operations

**Partial update**
https://docs.vespa.ai/en/partial-updates.html

**Non-existent**
https://docs.vespa.ai/en/document-v1-api-guide.html#create-if-nonexistent

**Comment by kkraune** [comment]
Yes, it can be a bit confusing, but there are more clients and APIs, there are more ways of doing it. I think https://docs.vespa.ai/en/document-v1-api-guide.html#create-if-nonexistent is an upsert, right?

**Comment by eostis** [comment]
**I get an error with the documented command https://docs.vespa.ai/en/document-v1-api-guide.html#create-if-nonexistent **

```
curl -X PUT -H "Content-Type:application/json" --data '
  {
      "fields": {
          "artist": {
              "assign": "Coldplay"
          }
      }
  }' \
  http://localhost:8080/document/v1/mynamespace/music/docid/a-head-full-of-thoughts?create=true
```

👎 Returns
`{"pathId":"/document/v1/wpsolr1/wpsolr1/docid/47","message":"Expected start of JSON object, got VALUE_STRING"}`

It works if I just change PUT to POST:
```
curl -X POST -H "Content-Type:application/json" --data '
  {
      "fields": {
          "artist": {
              "assign": "Coldplay"
          }
      }
  }' \
  http://localhost:8080/document/v1/mynamespace/music/docid/a-head-full-of-thoughts?create=true
```

👍 Returns 
`
{"pathId":"/document/v1/wpsolr1/wpsolr1/docid/47","id":"id:wpsolr1:wpsolr1::47"}
`

**Comment by kkraune** [comment]
oh - thanks for reporting - will get to it next week :-)

**Comment by kkraune** [comment]
Re your last comment, here is what I did (after running https://github.com/vespa-engine/sample-apps/tree/master/album-recommendation):
```
$ vespa visit --field-set "[id]"
{"id":"id:mynamespace:music::love-is-here-to-stay","fields":{}}
{"id":"id:mynamespace:music::a-head-full-of-dreams","fields":{}}
{"id":"id:mynamespace:music::hardwired-to-self-destruct","fields":{}}

$ curl -X PUT -H "Content-Type:application/json" --data '
>   {
>       "fields": {
>           "artist": {
>               "assign": "Coldplay"
>           }
>       }
>   }' \
>   http://localhost:8080/document/v1/mynamespace/music/docid/a-head-full-of-thoughts?create=true
{"pathId":"/document/v1/mynamespace/music/docid/a-head-full-of-thoughts","id":"id:mynamespace:music::a-head-full-of-thoughts"}

$ curl -X PUT -H "Content-Type:application/json" --vespa visit --field-set "[id]"
{"id":"id:mynamespace:music::love-is-here-to-stay","fields":{}}
{"id":"id:mynamespace:music::a-head-full-of-dreams","fields":{}}
{"id":"id:mynamespace:music::a-head-full-of-thoughts","fields":{}}
{"id":"id:mynamespace:music::hardwired-to-self-destruct","fields":{}}
```

This looks right. I just copied the command from the documentation. Your error message indicates a json format error, so something with what you pasted, maybe?

**Comment by kkraune** [comment]
Improved doc in https://github.com/vespa-engine/documentation/pull/2580

**Comment by eostis** [comment]
> Your error message indicates a json format error, so something with what you pasted, maybe?
I just replaced 'PUT' with 'POST' to make it work. Strange.
