### ISSUE TITLE
Batch mode for document APIs

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26579]
Related to #16713, closed a long time ago.

 @jobergum I agree, the batch mode to index data is more than useful. Calling tens of thousands times the API is really not good.

@frodelu Personally, I would very much accept a single error code for the whole batch. For instance the first document with an error. In my client code, I just do not commit if any error is detected in a whole batch call, to prevent any issues.

**Comment by bratseth** [comment]
That ticket was "while we wait for http/2". Now we have http/2 and there is no reason to add batch.

**Comment by eostis** [comment]
We send documents one by one, and let http/2 optimize the transfer. Cool.


> Now we have http/2
I guess this means for Cloud and all self hosted?

**Comment by eostis** [comment]
Are there examples of sending a "batch" of document updates with HTTP/2?

Does it depend on the client language?

How do we manage error catching?

**Comment by bratseth** [comment]
You don't need batch with HTTP/2 since it is fully asynchronous.

The client language needs to have a HTTP client that supports HTTP/2 but most do by now I think.

Each request may fail with an error even though it is asynchronous.

**Comment by eostis** [comment]
I found https://github.com/vespa-engine/pyvespa/blob/master/vespa/application.py#L1082, which uses async, semaphores and coroutines to loop on a document for async batch updates.

It looks to me that batch with Vespa is currently the responsibility of clients: depending on the programming language, one has  to build the asynchronous loop calls. And we know this is a difficult problem.

Would not it be better to implement the batch in the backend, rather than in the front-end?

**Comment by eostis** [comment]
Thanks for the detailed answer. I'll manage the chunks!
