### ISSUE TITLE
Allow negative vector distances in HNSW graphs

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#26587]
If vectors are not of unit length but `innerproduct` is used as [distance metric](https://docs.vespa.ai/en/reference/schema-reference.html#distance-metric), we get many negative distance values, which are capped as distance 0, which leads to a graph with many vectors in the same point, which causes a performance breakdown.

We should instead tolerate negative distances in the graph and instead just cap closeness (but not distance) at zero.

**Comment by geirst** [comment]
Experimentation shows that allowing negative distances (as described above) results in a bad hnsw graph with many unreachable nodes. With the improvement in https://github.com/vespa-engine/vespa/issues/26588, we no longer require that vectors are of unit length when using _**prenormalized-angular**_ (previously _**innerproduct**_). They only need to have the same length. The problem described above is less likely now.
