### ISSUE TITLE
Reduce number of size classes (buffer types) for multivalue attributes

### ISSUE THREAD

**Issue by baldersheim** [vespa-engine/vespa#26640]
Too many size classes used for storage of attribute data. The static cost for adding fields of type **array** and **weighted-set** is too high. Currently defining an array field has a fixed cost just below 1M. Too some extend it also holds for fields requiring a dictionary like string fields or fields with fast-search, but to a lesser extent.

Suggested solution is to reduce granularity of the size classes, and allow a small (handfull) percentage of waste.

This is the last known improvement for #26350

Here is output after starting the performance test [lookup](https://github.com/vespa-engine/system-test/tree/master/tests/performance/lookup) and stopping the test before feeding any data, and then inspecting the attribute memory usage with 
`vespa-curl-wrapper 'https://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute'|jq .`

`{
  "id": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 339036,
    "usedMemory": 102016,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/id"
  },
  "f1": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 868804,
    "usedMemory": 606276,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/f1"
  },
  "s1": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 875432,
    "usedMemory": 609632,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/s1"
  },
  "payload_array_byte": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 512056,
    "usedMemory": 504396,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/payload_array_byte"
  },
  "payload_array_long": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 512056,
    "usedMemory": 504396,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/payload_array_long"
  },
  "payload_raw": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 357184,
    "usedMemory": 347176,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/payload_raw"
  },
  "f1_hash": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 774772,
    "usedMemory": 581244,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/f1_hash"
  },
  "s1_cased": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 875432,
    "usedMemory": 609632,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/s1_cased"
  },
  "s1_hash": {
    "numDocs": 1,
    "lastSerialNum": 2,
    "allocatedMemory": 781400,
    "usedMemory": 584600,
    "onHoldMemory": 0,
    "committedDocIdLimit": 1,
    "url": "http://localhost:19110/state/v1/custom/component/documentdb/test/subdb/ready/attribute/s1_hash"
  }
}`

**Comment by geirst** [comment]
In Vespa 8.181.15 the number of size classes (buffer types) for multivalue attributes are reduced from 1023 to 300. Previously we used 1023 buffer types that map directly to how many elements that buffer stores per entry, e.g. buffer type 27 stores entries with 27 elements. With this change buffers map directly up to a certain point, then we start using dynamic buffers that can store entries with a range of elements. The final switch was done in this PR: https://github.com/vespa-engine/vespa/pull/27478. 

This results in up to 40% reduction of static memory usage for multivalue attributes (array and weightedset). Examples:
- array<int>: From 495k to 298k
- array<string> From 608k to 410k
