### ISSUE TITLE
Approx nearest neighbour searches are not subject to query timeouts

### ISSUE THREAD

**Issue by akateiva** [vespa-engine/vespa#26663]
**Describe the bug**
HNSW searches are not subject to user specified query timeouts. When searching a HNSW index with filters that select for lowest scoring documents in the index, `HnswIndex<type>::search_layer` may take a long time. In our case we observe that `content_proton_documentdb_matching_rank_profile_query_setup_time_max` metric exceeds 30 seconds even though all of our queries specify a timeout of 150ms. 

Many of such queries can effectively cause a denial of service.

https://github.com/vespa-engine/vespa/blob/b67d98e3d299c687967dbf6fe84fb749c7fcacf4/searchlib/src/vespa/searchlib/tensor/hnsw_index.cpp#L900

**To Reproduce**
1. Set up an index with i.e. 1 mil vectors
2. Query vespa with nearestNeighbor operator, set approximate:true and hnsw.exploreAdditionalHits to some large value (i.e. 400_000), timeout to 0.05s 
3. Observe content_proton_documentdb_matching_rank_profile_query_setup_time_max / avg vastly exceed specified query timeouts

note that we set `hnsw.exploreAdditionalHits` to an arbitrarily large value to simulate what happens when the hnsw algorithm is forced to explore many nodes in layer0 due to global filter

**Expected behavior**
Vespa should terminate a HNSW graph traversal prematurely if time taken exceeds user specified timeout.

**Vespa version**
8.113.20

reference slack thread: https://vespatalk.slack.com/archives/C01QNBPPNT1/p1679399201834239

**Comment by andreer** [comment]
Thank you for reporting this! A lot of the team is out on easter vacation this week, so it will likely take longer than normal for us to get back to you.

**Comment by bratseth** [comment]
> note that we set hnsw.exploreAdditionalHits to an arbitrarily large value to simulate what happens when the hnsw algorithm is forced to explore many nodes in layer0 due to global filter

Note that with default parameters a strong global filter will not lead to exploring an excessively large number of nodes as Vespa will switch to exact evaluation if it estimates that more than 95% will be filtered out. See 
https://blog.vespa.ai/constrained-approximate-nearest-neighbor-search/

**Comment by akateiva** [comment]
> with default parameters a strong global filter will not lead to exploring an excessively large number of nodes as Vespa will switch to exact evaluation if it estimates that more than 95% will be filtered out

for some embedding+filter combinations we see high query setup times even if the filter hitrate is i.e. 50%

**Comment by jobergum** [comment]
Yeah, the traversal should be subject to query timeout

**Comment by geirst** [comment]
This is fixed by https://github.com/vespa-engine/vespa/pull/27240. Part of Vespa 8.170.13.
