### ISSUE TITLE
Add sort on multivalued attributes

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26681]
#26680 

For E-Commerce, sorting  multivalued attributes is common. Products tags and product variations attributes for instance.

**Comment by bratseth** [comment]
What is the correct sort order for a multivalued attribute?

**Comment by eostis** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#_sort_mode_option

Lower and higher value are the default for asc and desc order.

**Comment by geirst** [comment]
This fixed by https://github.com/vespa-engine/vespa/pull/27628 (in Vespa 8.190.5)
System test: https://github.com/vespa-engine/system-test/pull/2929
Reference doc: https://docs.vespa.ai/en/reference/sorting.html#multivalue-sort-attribute

**Comment by eostis** [comment]
Thanks to the team. 
@geirst, an idea when Vespa 8.190.5 will be released?
I'm eager to try it with WooCommerce #26694

**Comment by eostis** [comment]
Tested with Vespa 8.198.18 :)
