### ISSUE TITLE
Demos with better fault-tolerant spelling

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26691]
I noticed that spelling fault-tolerance is not great with 2 Vespa demos I tried today.

Can it be improved, and how?

 **COVID-19 Vespa demo with "jakett"**

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/1785759/230132924-cc8f9ab2-837d-41d4-a1e9-0bf5c38a67a3.png">

 **Local user shopping Vespa demo with "jakett":**
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/1785759/230133042-e317300a-e2d6-48dc-8174-2abfa9175d62.png">

👍 **My WooCommerce demo with "jakett" (not Vespa,  but vector search):**
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1785759/230133153-fb2e09f5-78ea-4df2-a541-4ebe95996471.png">

**Comment by jobergum** [comment]
The cord19 app does not use vector search for retrieval or have any typo-relaxed matching. 

The commerce demo has relaxed auto-complete:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/20928528/230200908-b5eef100-a10e-479f-a5c6-ad7e58f85606.png">

In addition, it uses hybrid retrieval but will not throw out hits with cosine similarity below 0.45 https://github.com/vespa-engine/sample-apps/blob/master/use-case-shopping/src/main/application/schemas/item.sd#L138

**Comment by eostis** [comment]
It would be great to have a centralised repo of all demos, live.

Everybody has some specific features in mind that he'd like to try before digging deeper in technical details with the downloadable version.

For instance, I had to fight with MacOS java and python to install the user shopping demo, but failed the python step: I did not see the autocomplete feature.

**Comment by jobergum** [comment]
I'm closing this; Vespa is a very feature-rich platform, and we are unable to host demos of all our vespa sample applications.
