### ISSUE TITLE
Adding TRUE as an additional condition prevents dynamic summary generation

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26693]
Source: https://stackoverflow.com/questions/75923027/

The content:
```{"wpsolr_title": "Hamster one"}```

The schema:
```
field wpsolr_title type string {
  indexing: index | summary
  summary: dynamic
}

fieldset default {
  fields: wpsolr_title
}

```
userInput() alone:
```
vespa query \
  'yql=select wpsolr_title from wpsolr30 where (userInput(@query))' \
  'query=hamster'

 "fields": {
                "wpsolr_title": "<hi>Hamster</hi> one"
            }
```

userInput() with another condition:
```
vespa query \
  'yql=select wpsolr_title from wpsolr30 where (userInput(@query)) and true' \
  'query=hamster'

 "fields": {
                "wpsolr_title": "Hamster one"
            }
```

**Comment by bratseth** [comment]
Yes, but only when the additional filter is _true_.

**Comment by eostis** [comment]
In fact, for any filter. I wrote true for simplification.

**Comment by bratseth** [comment]
No. What other condition did you try?

**Comment by eostis** [comment]
I started from a real query:
`{"offset":0,"limit":20,"query":"product","yql":"select wpsolr_id, wpsolr_PID, wpsolr_type, wpsolr_meta_type_s, wpsolr_title, wpsolr_numcomments, wpsolr_comments, wpsolr_displaydate, wpsolr_displaymodified, wpsolr_author, wpsolr_snippet_s from wpsolr56 where (((wpsolr_type contains ({stem: false}\"post\")) or (wpsolr_type contains ({stem: false}\"product\"))) and !(((wpsolr_post_status_s contains ({stem: false}\"draft\")) or (wpsolr_post_status_s contains ({stem: false}\"pending\")) or (wpsolr_post_status_s contains ({stem: false}\"trash\")) or (wpsolr_post_status_s contains ({stem: false}\"future\")) or (wpsolr_post_status_s contains ({stem: false}\"private\")) or (wpsolr_post_status_s contains ({stem: false}\"auto-draft\")))) and (!((wpsolr_type contains ({stem: false}\"product\"))) or (!(!((wpsolr_product_visibility_str contains ({stem: false}\"_wpsolr_undefined\")))) or !((wpsolr_product_visibility_str contains ({stem: false}\"exclude-from-search\"))))) and (!(!((wpsolr_is_excluded_s contains ({stem: false}\"_wpsolr_undefined\")))) or (wpsolr_is_excluded_s contains ({stem: false}\"n\"))) and ([{\"defaultIndex\":\"wpsolr_fieldset\"}]userInput(@query))) | all(all(group(wpsolr_type) order(-count()) max(20) each(output(count()))) all(group(wpsolr_product_tag_str) order(-count()) max(20) each(output(count()))) all(group(wpsolr_product_visibility_str) order(-count()) max(20) each(output(count()))) all(group(wpsolr_flat_hierarchy_product_cat_str) order(-count()) max(20) each(output(count()))) all(group(predefined(wpsolr__price_f, bucket(-inf, 0), bucket(0, 100), bucket(100, 200), bucket(200, 300), bucket(300, 400), bucket(400, 500), bucket(500, 600), bucket(600, 700), bucket(700, 800), bucket(800, 900), bucket(900, 1000), bucket(1000, inf))) each(output(count()))) all(group(\"wpsolr_displaymodified_dt\") each(output(min(wpsolr_displaymodified_dt)) output(max(wpsolr_displaymodified_dt))) ))"}`

I add to remove all the filters one by one to finally get the summary.

**Comment by bratseth** [comment]
Well, then surely you can share a much simpler query that doesn't cause dynamic summary generation?

**Comment by eostis** [comment]
It looks like it is a condition with "!" and "or" that causes the issue:

```
curl -X POST -H "Content-Type: application/json" --data '
    {"offset":0,"limit":20,"query":"product","yql":"select wpsolr_title, wpsolr_product_visibility_str from wpsolr56 where (!(wpsolr_type contains ({stem: false}\"product\")) or (wpsolr_product_visibility_str contains ({stem: false}\"_wpsolr_undefined\")) )  and ([{\"defaultIndex\":\"wpsolr_fieldset\"}]userInput(@query)) "}
    ' \
     http://localhost:8080/search/
"fields":{"wpsolr_title":"product red medium","wpsolr_product_visibility_str":["_wpsolr_undefined"]}
```

Same without the "!":
```
curl -X POST -H "Content-Type: application/json" --data '
    {"offset":0,"limit":20,"query":"product","yql":"select wpsolr_title, wpsolr_product_visibility_str from wpsolr56 where ((wpsolr_type contains ({stem: false}\"product\")) or (wpsolr_product_visibility_str contains ({stem: false}\"_wpsolr_undefined\")) )  and ([{\"defaultIndex\":\"wpsolr_fieldset\"}]userInput(@query)) "}
    ' \
     http://localhost:8080/search/
"fields":{"wpsolr_title":"<hi>product</hi> red medium","wpsolr_product_visibility_str":["_wpsolr_undefined"]}

```

Same without the "or":
```
curl -X POST -H "Content-Type: application/json" --data '
    {"offset":0,"limit":20,"query":"product","yql":"select wpsolr_title, wpsolr_product_visibility_str from wpsolr56 where (!(wpsolr_type contains ({stem: false}\"XXXX\")) )  and ([{\"defaultIndex\":\"wpsolr_fieldset\"}]userInput(@query)) "}
    ' \
     http://localhost:8080/search/
"fields":{"wpsolr_title":"<hi>product</hi> red medium","wpsolr_product_visibility_str":["_wpsolr_undefined"]}

```

**Comment by geirst** [comment]
Fixed in https://github.com/vespa-engine/vespa/pull/27257.
System test added in https://github.com/vespa-engine/system-test/pull/2879.
Part of Vespa 8.171.14.
