### ISSUE TITLE
API to deploy PROD applications on Vespa Cloud

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#26709]
(I know this repository is about Vespa engine.  But without a Vespa cloud repository, it seems to be the best place, and it is a FR that could interest others).

As [mentioned](https://cloud.vespa.ai/en/reference/vespa-cloud-api#http-deploy) in the documentation, the current APIs can deploy on dev and test environments, but not on production.

My feature request is therefore to extend the API to PROD.

My use case is to deploy an application in production from a WooCommerce plugin.

**Comment by oyving** [comment]
We are planning to build out a public facing control plane API for Vespa Cloud, so this will be possible in the future. I've created a ticket for this in the Vespa Cloud system and will close this one.

**Comment by eostis** [comment]
Hey @oyving, is the plane API for Vespa Cloud on its way?

**Comment by oyving** [comment]
Hi @eostis - sorry for the overdue response. This is still a backlog item for us. Work on implementing it has not been started yet.
