### ISSUE TITLE
Application Generation not returned from config node.

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#26735]
**Describe the bug**
Application generation returned from config node is always 0.

 curl -s http://localhost:19071/state/v1/config
{
  "config" : {
    "generation" : 0,
    "container" : {
      "generation" : 0
    }
  }
}-bash-4.4$ curl -s http://localhost:8080/state/v1/config
{
  "config" : {
    "generation" : 2,
    "container" : {
      "generation" : 2
    }
  }

**To Reproduce**
1. Application Deployment 
2. Check  curl -s http://localhost:19071/state/v1/config endpoint after application deployment 

**Expected behavior**
The config node endpoint should return the current application generation. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: RHEL8
 - Infrastructure: Podman
 - Versions 8.137.25

**Vespa version**
 8.137.25

**Comment by kkraune** [comment]
Correct - the config server has its own config regardless of the config of the container and content nodes - these report the _application_ config generation. This is a little confusing, I will look into documentation

**Comment by 107dipan** [comment]
Do we have a separate endpoint for checking config server config generation?

**Comment by kkraune** [comment]
http://localhost:19071/state/v1/config _is_ the _config server's_ config generation - the point is, the config servers make a service that serves configuration (i.e. application packages) to _other_ nodes. Think of config servers as a different services. 

The config server's config is file-based and in practise always 0. As I said, I will try to update the documentation on this

**Comment by kkraune** [comment]
Clarified in https://docs.vespa.ai/en/operations/configuration-server.html#status-and-config-generation - thanks for reporting!
