### ISSUE TITLE
How to replace nodes in cluster?

### ISSUE THREAD

**Issue by Mahdi-Seeker** [vespa-engine/vespa#26759]
Hi!

I'm using Vespa docker image v8.89.6.

I have a Vespa cluster with 4 servers, a container cluster, and a content cluster equally placed on all 4 servers. The config cluster is put on the first server.
Now I'd want to replace these servers with new servers because of hardware issues in that old servers.

I have some problems here:
1. First of all, I've added the new servers to both container & content clusters, and increased redundancy from 1 to 2 to be able to remove 1 server at a time (as mentioned in docs). When I deployed the new app, Vespa warns me that ports have changed and I have to restart the cluster. Now the question is: what's the recommended procedure for rolling restart of all servers? The Vespa cluster is under production load and I don't want to have any downtime.
2. What about changing the config server to another server? Is is possible to do that without downtime?
3. After restarting all servers, another issue is that all of the old servers start to replay the wal and that takes toooooo much time. What's the appropriate way of restarting a Vespa docker container? I just do `docker stop` and then `docker start`, but it seems that's not much graceful and the container takes about an hour to be ready and start serving requests.
4. Now that all servers are up, the cluster starts to rebalance the data on new servers. After that, I have 8 servers up and running. Now is the time to bring the old servers down, one by one. I have to bring first server down (with `docker stop`?), check the status of cluster and wait for data to be re-balanced, and then go to the next server? Isn't there a faster way of doing this?
5. Another related question: When I change some fields' indexing and I have to re-index the whole data, the only way I've found for that is restarting the whole cluster. After restart, the re-index procedure starts. Isn't there another way for re-indexing? Specially a way without downtime?

**Comment by kkraune** [comment]
Hi and thanks for using Vespa! That is a lot of questions, so will drop a list of resources here that are hopefully helpful:

3: https://docs.vespa.ai/en/operations/docker-containers.html#graceful-stop is useful to let Vespa flush data structures, for a quicker restart. Not sure what your timeout should be, so set it high to let Vespa gracefully stop

**Comment by kkraune** [comment]
2: See https://docs.vespa.ai/en/operations/configuration-server.html#scaling-up or "replacing nodes" in the same doc

**Comment by kkraune** [comment]
For a rolling restart, do one node at a time per cluster. Normally this trivial for container nodes, as they don't have documents. Content nodes need time to sync if you have writes to the cluster while restarting - see my first comment on stopping

**Comment by Mahdi-Seeker** [comment]
> Hi and thanks for using Vespa! That is a lot of questions, so will drop a list of resources here that are hopefully helpful:
> 
> 3: https://docs.vespa.ai/en/operations/docker-containers.html#graceful-stop is useful to let Vespa flush data structures, for a quicker restart. Not sure what your timeout should be, so set it high to let Vespa gracefully stop

Thanks for responses!

As I remember, I've already done that, no difference.
Let me try it again.

**Comment by Mahdi-Seeker** [comment]
> 5: https://docs.vespa.ai/en/operations/reindexing.html

I've already read that, the problem is when I deploy the new app, the corresponding content cluster's reindexing state (from /reindexing api call) changes to ready, but doesn't start re-indexing until I restart the node. Is this the expected behaviour?

**Comment by Mahdi-Seeker** [comment]
I've found this:
https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#reindex
> ### POST /application/v2/tenant/default/application/default/environment/default/region/default/instance/default/reindex
> Triggers [reindexing](https://docs.vespa.ai/en/operations/reindexing.html) of specified document types in specified clusters of an application. **Reindexing starts with the next redeployment of the application.**

I don't get it. When it says "with the **next** redeployment of the application", does it mean that when I change my app and deploy it, nothing happens, and when I redeploy it then reindexing starts?

What I observed so far is that when I deploy the new app that has change needing reindex, calling /reindexing api says its ready for reindex, but doesn't start. And when I restart the node after that, it starts reindexing. I'd want to be able to do it without restarting.

**Comment by jonmv** [comment]
After calling the API, do a new `vespa deploy` with your application package, and the reindexing will start without any node restarts. (The reindexing config is kept by the configserver, and won't be propagated without a new deploy call, or, as you saw, a node restart. This is not ideal, and something we _may_ change at a later time, but it doesn't have high priority as of now.)

**Comment by vigi99vs** [comment]
> 4: https://docs.vespa.ai/en/operations/admin-procedures.html#add-or-remove-a-content-node - use the retired state on all nodes you want to replace - this will migrate the replicas to the new nodes.

Can we retire more than 1 content node at a time if the redundancy factor is 2 ?

**Comment by bratseth** [comment]
Yes, you can safely retire as many as you like at the same time (regardless of redundancy); retiring nodes just tells the system to ensure there is sufficient redundancy _without_ the retired nodes. Once the resulting redistribution is completed they can be safely removed.

**Comment by bjormel** [comment]
@vigi99vs please reopen if you need more assistance on this, thanks!
