### ISSUE TITLE
Warn/bail out if vm.max_map_count is low

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#27229]
Vespa will refuse to start if certain system limits like nofile are too low as documented in [system limits](https://docs.vespa.ai/en/operations/docker-containers.html#system-limits). 

This does not cover all possible ways to end up in a bad state due to various limits being from the 90s. Another common issue is low defaults for `vm.max_map_count` which makes apps run into memory mapping assertions,  especially if the `paged` option has been enabled for a lot of attribute fields. 

A few symptoms reported 

```
vespalib::alloc::MemoryAllocator::PtrAndSize vespalib::alloc::MmapFileAllocator::alloc(size_t) const: Assertion buf!=MAP_FAILED
```

```
'terminate called after throwing an instance of 'std::runtime_error' 'what(): mmap of file '/opt/vespa/var/db/vespa/search/cluster.abc/n12/documents/xyz/0.ready/index/index.fusion.43/field123/boolocc.bdat' with flags '1' failed with error: 'Cannot allocate memory'
```

**Comment by arnej27959** [comment]
https://github.com/vespa-engine/vespa/pull/27254
