### ISSUE TITLE
Need support for Distinct query

### ISSUE THREAD

**Issue by madhukesha94** [vespa-engine/vespa#27280]
**Is your feature request related to a problem? Please describe.**
I am working on an e-commerce platform. In e-commerce domain, we have products of multiple verticals like Grocery, Fashion. In Fashion, we have a concept called as variants which are basically multiple variations of a single product like different sizes/different colors. I understand that we can dedupe the variants being shown to the customer with the use of group by. How can we get facets/filters based on this list of de-duped products

**Describe the solution you'd like**
One probable solution that I have in mind is to introduce the functionality for DISTINCT, similar to what we have in MySQL. This would help us in performing a top-level de-dupe first and then implement the grouping over it

**Describe alternatives you've considered**
Other solution might be to use the pipe operator like that of Linux, where we may be able to introduce stages. The first stage would be used to de-dupe the results with the existing grouping query and the next stage would be used to get the facets/filters based on the output of that grouping.

**Additional context**
Sample input Documents:
```
{
"id": "1",
"color": "red",
"size": "M",
"groupingCode":"1",
"brand":"Nike"
}

{
"id": "2",
"color": "red",
"size": "XL",
"groupingCode":"1",
"brand":"Nike"
}
```

Expected Query: `select *, distinct(groupingCode) from grouping where true | all(group(brand) order(-count()) each(output(count())))`

Expected Output
```
{
  "root": {
    "children": [
      {
        "id": "group:root:0",
        "children": [
          {
            "id": "grouplist:brand",
            "relevance": 1,
            "label": "color",
            "children": [
              {
                "id": "group:string:nike",
                "relevance": 1,
                "value": "nike",
                "fields": {
                  "count()": 1
                }
              }
            ]
          }
        ]
      },
      {
        "id": "id:test:grouping::1",
        "relevance": 0,
        "source": "mind",
        "fields": {
          "sddocname": "grouping",
          "documentid": "id:test:grouping::1",
          "id": "1",
          "color": "red",
          "size": "M"
        }
      }
    ]
  }
}
```

**Comment by bratseth** [comment]
Did you consider nested grouping? If so, could you explain the difference?
