### ISSUE TITLE
semantic rules are not validated

### ISSUE THREAD

**Issue by arnej27959** [vespa-engine/vespa#27326]
Syntax errors in rules/foo.sr will not be found in deploy, but fail when container tries to apply the generated config.
It looks like parsing/validation used to happen in RuleConfigDeriver which was removed in
https://github.com/vespa-engine/vespa/pull/5043

**Comment by hmusum** [comment]
Fixed in https://github.com/vespa-engine/vespa/pull/27368, released in 8.175.37
