### ISSUE TITLE
 Logging of Embedding Creation Time

### ISSUE THREAD

**Issue by rharige** [vespa-engine/vespa#27397]
**Is your feature request related to a problem? Please describe.**
When using the `embed` functionality in Vespa to calculate embeddings at index time and query time, there is no information logged on how long the embedding creation process takes for each embedding field/document. This information is critical to benchmark the performance at ingest time and query time and to identify the parameters that influence the performance.

**Describe the solution you'd like**
I would like Vespa to log this information about the time taken by Vespa to calculate embeddings per field and query and make it accessible to the user. Additionally, Vespa could define a metric that best captures this information and expose it via Vespa metrics API.

**Describe alternatives you've considered**
The alternative is to manually measure the performance times at ingest time: with and without HSNW indexing and at query time.

**Additional context**
This feature is requested on the Vespa repo, with the understanding that it will also be released for Vespa Cloud when it is ready.

**Comment by jobergum** [comment]
Yes, we should add inference time per configured embedder and with an extra dimension if it's used during a query or document serving. Also, the sequence length could also be interesting.

**Comment by bjorncs** [comment]
Introduced `embedder.latency` and `embedder.sequence_length` in https://github.com/vespa-engine/vespa/pull/27969. They will soon arrive at [Container Metrics documentation](https://docs.vespa.ai/en/reference/container-metrics-reference.html).
