### ISSUE TITLE
Support verbose flag to all commands in Vespa CLI

### ISSUE THREAD

**Issue by rharige** [vespa-engine/vespa#27419]
**Is your feature request related to a problem? Please describe.**
Sometimes it is not clear how to use the Vespa APIs, particularly, what parameters to supply and what format the values  should be, specific to your environment, to get a task done. On such occasions, Vespa CLI's `verbose flag (-v)` is quite handy to get the cURL equivalent of the CLI command, provided that the task and flag is supported in CLI. However, the verbose flag is not exposed to all the commands of Vespa. For example, Vespa Visit (with `--selection` and other possible parameters). 

**Describe the solution you'd like**
I would like this verbose flag to be exposed for all the commands of Vespa CLI.

**Describe alternatives you've considered**

**Additional context**

**Comment by mpolden** [comment]
Some CLI commands are too complicated to meaningfully be translated to a curl equivalent. I'll look into adding this for commands where it makes sense, such as `vespa visit`.

**Comment by mpolden** [comment]
`vespa visit --verbose` is available in 8.265.12.
