### ISSUE TITLE
"NO_SPACE" error when  feeding data into vespa

### ISSUE THREAD

**Issue by NasonZ** [vespa-engine/vespa#27609]
**Describe the bug**
I'm attempting to follow [tutorial 2](https://github.com/vespa-engine/documentation/blob/master/en/tutorials/news-2-basic-feeding-and-query.md#:~:text=vespa%20feed%20mind/vespa.json%20%2D%2Dtarget%20http%3A//localhost%3A8080). I get to the section where I need to feed news articles into Vespa, however, I am encountering a "NO_SPACE" error message that is blocking the external feed due to resource exhaustion.

**To Reproduce**

Follow tutorial 2 up to the part where we attempt to feed the data to Vespa using the command `$ vespa feed mind/vespa.json --target http://localhost:8080`

See error messages regarding resource exhaustion and blocked external feed. Examples of the error message are:

```
"[UNKNOWN(251009) @ tcp/vespa-tutorial:19112/default]: ReturnCode(NO_SPACE, External feed is blocked due to resource exhaustion: disk on node 0 [vespa-tutorial] (0.781 > 0.750)) "}) for put id:news:news::N3112: retrying
"[UNKNOWN(251009) @ tcp/vespa-tutorial:19112/default]: ReturnCode(NO_SPACE, External feed is blocked due to resource exhaustion: disk on node 0 [vespa-tutorial] (0.781 > 0.750)) "}) for put id:news:news::N5409: retrying
```

**Expected behavior**
The data feed should have successfully been processed by Vespa without resource exhaustion or blocking of the external feed.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Infrastructure: Self-hosted
 - Versions: N/A

**Vespa version**
Vespa CLI version 8.184.20 compiled with go1.20.5 on linux/amd6

**Additional context**
I have 30GB free on my /home drive so I'm sure I have plenty of memory, I have also tried running `vespa feed mind/vespa.json --target http://localhost:8080` with only 5 articles in vespa.json but I get the same error.

**Comment by geirst** [comment]
Please try to increase the allocated storage for the Docker daemon as specified here: https://docs.vespa.ai/en/operations/feed-block.html.

**Comment by NasonZ** [comment]
Thanks, this resolved the issue for me.
