### ISSUE TITLE
Extract the text around the word being searched

### ISSUE THREAD

**Issue by kumarsatish29** [vespa-engine/vespa#27610]
Like if searched for the word 'hospital' within a very long paragraph and need to extract the sentences around the sentence that contains the word 'hospital'.

ex: Another index is the average bed-occupancy rate—that is, the percentage of available beds actually occupied per day or per month. Bed-occupancy rates may be higher in the cold winter months, which bring more [respiratory disease](https://www.britannica.com/science/respiratory-disease). In developing countries the bed-occupancy rate is often more than 100 percent—there are more patients in the hospital than there are beds for them. This situation has also emerged in some developed countries where demand for services has outstripped supply.
result would be  'In developing countries the bed-occupancy rate is often more than 100 percent—there are more patients in the hospital than there are beds for them. '
Not the entire paragraph

**Comment by hmusum** [comment]
Have a look at the doc for dynamic snippets: https://docs.vespa.ai/en/document-summaries.html#dynamic-snippets
