### ISSUE TITLE
Approximate nearestNeighbor without adjusting targetHits

### ISSUE THREAD

**Issue by vsolovyov** [vespa-engine/vespa#27672]
**Is your feature request related to a problem? Please describe.**
As discussed in [slack](https://vespatalk.slack.com/archives/C038YTM5SUQ/p1688655588022189), I have a query that goes like this:

```
SELECT * FROM article WHERE concepts_title_abstract contains \"114000\" AND ({targetHits: 500, distanceThreshold: 0.2, label: \"query_embedding_1\"}nearestNeighbor(article_vec_1, query_embedding_1));
```

And it takes 6 seconds to execute. If I drop left or right part of that AND query, query is executed in single-digit milliseconds (5-8 ms). tracelevel=3 and explainlevel=1 give [this trace](https://paste.in.ua/1jti/), which indicates that targetHits gets adjusted up to **4963058**. Total collection size is 157M in this schema.

**Describe the solution you'd like**
I would like to tell `nearestNeighbor` to not adjust `targetHits` up too much, I really need only top 500 here. I'm okay with it being top 400 or top 2000. I am also okay if this complete query with AND will return only a couple of hits, or even zero, this is a desired result.

**Describe alternatives you've considered**
I consider executing a separate query with `nearestNeighbor` only, and then somehow supplying these 500 ids as a part of query. Maybe something like `id = 123 OR id = 234 OR ...`, or maybe I would try if `equiv` could work here. Maybe an `IN <list-of-values>`, but I couldn't find such an operator in YQL.

**Additional context**
@jobergum said "We should have an option to not adjust target" and asked me to create this issue :)

**Comment by vsolovyov** [comment]
How soon can we expect this feature? Should we wait for it, or should we implement our alternative route?

I also grepped vespa sources a bit, and it doesn't look too hard to implement the thing myself and to send a PR.

**Comment by jobergum** [comment]
Hey @vsolovyov, the issue has a soon milestone, which usually means about 2 months. I don't think this is a big change and might arrive earlier, but need a way to specify that this is the behavior you want. Ideas around that?

**Comment by vsolovyov** [comment]
@jobergum well, as I explained in slack thread https://vespatalk.slack.com/archives/C038YTM5SUQ/p1688655588022189, my query is getting three orders of magnitude slower. It's getting adjusted from 2500 hits to almost 5 million (out of 158M total). And that's even with `distanceThreshold=0.2` (is it getting ignored when adjusted? No way there's 5 millions of so similar docs).

I'm totally fine with getting 0-5-20 hits on such queries, when `nearestNeighbor` is getting `AND`ed with some regular filter.

Is this what you expected to hear, or did I not understand your question?

**Comment by jobergum** [comment]
>Is this what you expected to hear, or did I not understand your question?

No, sorry for being unclear. I'm not questioning the use case for not adjusting targetHits based on the filter. The question was more about exposing this knob, as we cannot change the default behavior. 

Post filtering is today by either schema or `ranking.matching.postFilterThreshold` where `ranking.matching.postFilterThreshold=0` would always trigger post filtering, but with targetHits adjustment. The hackiest solution is to not adjust targetHits if postFilterThreshold is negative. Or we have to introduce another parameter to control this aspect.

**Comment by vsolovyov** [comment]
Ah, sorry for being a bit dense. I suspected that I understood you incorrectly :)

Well, I had only one idea before and that was to introduce an additional parameter. But now as I think about it, it probably would benefit from an additional validation, to catch when someone sets both new parameter, let's say `noTargetHitsAdjust` and existing `postFilterThreshold`.

Adding a negative for `postFilterThreshold` as a no-adjust indicator indeed looks a bit hacky at first, but on the other hand — it avoids the situation with specifying conflicting parameters.

For me personally it doesn't matter much, because in any case it goes into a code/schema with a 4-line comment, that explains the thing for my coworkers and my future self. And with any solution, it needs to be explained in docs.

So what are the downsides of the negative value for `postFilterThreshold`, because as I think more and more about it, it looks like a pretty cool solution? I suspect that the first "hacky" impression is made by a thought that it's reused for "other thing" in order to not introduce more parameters. Easy change for developer instead of thinking deeply about the problem. But it's not some "other thing".

Is it a future-proof solution? Are there any other possible future options here? I can't think of any right now. Doesn't mean there is none, of course.

**Comment by jobergum** [comment]
Thank you for your insight and feedback on this @vsolovyov, will discuss this with @geirst and the team once we have more people back from vacation.

**Comment by geirst** [comment]
A new parameter (_target-hits-max-adjustment-factor_) to control the auto-adjustment of _targetHits_ will be available in Vespa 8.214.6 (https://github.com/vespa-engine/vespa/pull/28054). This should be available open source next week.

Setting this to 1.0 will disable auto-adjustment. See the reference documentation for more details: https://github.com/vespa-engine/documentation/pull/2809

**Comment by geirst** [comment]
@vsolovyov Vespa 8.215.17 is now available.

**Comment by geirst** [comment]
Reference documentation: https://docs.vespa.ai/en/reference/schema-reference.html#target-hits-max-adjustment-factor

**Comment by vsolovyov** [comment]
@geirst fantastic, thank you very much!
