### ISSUE TITLE
Emit logs on availability of embedding model on GPU 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#27815]
If you configure embedders with a GPU device  

```
<component id="e5" type="hugging-face-embedder">
            <transformer-model path="model/multilingual-e5-small.onnx"/>
            <tokenizer-model path="model/tokenizer.json"/>
            <onnx-gpu-device>0</onnx-gpu-device>
        </component>
```
There is no warning or error if the device does not exist or the correct libraries are not present. It falls back to the CPU, which is fine, but there should be some noise in the vespa log. Plus, there should also be something in the log if device configuration and map is successful.

**Comment by jobergum** [comment]
Thanks @mpolden

**Comment by stauntonjr** [comment]
Thanks!!!
