### ISSUE TITLE
Expose the length of index fields as rankFeature

### ISSUE THREAD

**Issue by jgarciarp** [vespa-engine/vespa#27825]
We would like to use the length of an indexed field of type String in a ranking expression. But we run into the problem that  we cannot make use of this feature.

We would like to have a way to access such information in the same way as can be done when a field is indexed as an attribute (`attribute(name).count`).

We evaluated pre-computing the indexed field length and indexing it as an attribute field that we can use in the ranking expression. Although this would work, it will have an impact on cost when indexing at scale (multi-billion document set). We do hope that exposing the field length, already present in the index, as a rank feature could be a simple change that will give us great value.

**Comment by geirst** [comment]
@jgarciarp We already have the rank feature _fieldLength(my_index_field)_ for this. As the field length information is stored in the field index structure, the value can only be returned when at least one query term matches the field. See https://docs.vespa.ai/en/reference/rank-features.html#document-features for details. Will this work for you?

**Comment by Johannagp9** [comment]
@geirst. Thank you for the answer. With this I understand that in the case of semantic search or search by other elements as in our case is the entities that are represented by an ID but may not share text, taking into account that the length I need is the` text` field would not be possible. Am I right?

**Comment by jgarciarp** [comment]
@geirst. Thank you for the answer. With this I understand that in the case of semantic search or search by other elements as in our case is the entities that are represented by an ID but may not share text, taking into account that the length I need is the text field would not be possible. Am I right?

**Comment by geirst** [comment]
@jgarciarp I am sorry, but I don't understand your question. Can you please reformulate to make it clearer?

**Comment by jgarciarp** [comment]
Sorry. To give you more context, I want to use the length of the text field in a ranker. What I understand from that documentation is that it returns the length only if any terms in the field match the query terms. However, we have several types of queries where we don't search by the text field but we use for example in the case of semantic search a vector that represents that text so in this case no query term matches the values of the text field.SIf If I have understood correctly, in this case this function cannot be used and the same would happen in cases where my query does not contain anything related to the text field.

**Comment by geirst** [comment]
Yes, you are right. If you always need access to the field length (regardless of whether some query terms match that field or not), you must add an extra attribute field to your schema and populate it with the field length in a document processor (https://docs.vespa.ai/en/document-processing.html). 

There is unfortunately no trivial way of extracting the field length information for a given document from the field index structure when being independent of the query.
