### ISSUE TITLE
Feature request: source property on field definition to clone fields

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#27880]
Being able to index a field with different schemes is usual with e-commerce search.

For instance, a field "color" could be used for filtering and for matching.

Which means "color" would need a definition with the "attribute" property, and another one with the  "index" property.

Indexing the original "color" field should also index the copy.

Example:

```
# Original field for filtering
field color_for_filtering type string {
            indexing: summary | attribute
}


# Clone field for matching with ngram
field color_for_matching_ngram type string {
            source: color_for_filtering
            indexing: summary | index
            match {
	      gram
	      gram-size: 3
            }
}

# Clone field for exact matching
field color_for_matching_exact type string {
            source: color_for_filtering
            indexing: summary | index
            match {
	      exact
            }
}
```

**Comment by jobergum** [comment]
I think what you ask for is already supported.  By defining fields outside of the document schema, they can take original document fields as input and have different transformation/match settings. 

```
schema foo {
   document foo {
      field x type string {..}   
    }
}
field x_attribute type string {
  indexing: input x | .. 
  match: ..
}
field x_foo type string {
  indexing: input x | .. 
  match .. 
}
```

Btw, `attribute` fields are also searchable.

**Comment by eostis** [comment]
@jobergum Brilliant.

For reference (https://docs.vespa.ai/en/reference/schema-reference.html):
"Fields can be declared outside the document block in the schema. These fields are not part of the document type but behave like regular fields for queries. Since they are not part of the document they cannot be written directly, but instead take their values from document fields, using the input expression: indexing: input my_document_field | embed | summary | index

This is useful e.g. to index a field in multiple ways, or to change the field value, something which is not allowed with document fields. When the document field(s) used as input are updated, these fields are updated with them.
"
