### ISSUE TITLE
Readiness probe not allowing to start query nodes 

### ISSUE THREAD

**Issue by Krithiraj** [vespa-engine/vespa#27892]
Trying to setup readiness probe for query nodes. Liveness probe is working fine. When we enable readiness probe, query node is not starting. Getting Bad Network Connectivity errors.

Readinessprobe configs

Path: /state/v1/health
Port 19092
Scheme:http

Initialdelayseconds: 50

Kindly help

**Environment (please complete the following information):**
 - Infrastructure: Kubernetes - Azure cluster

**Vespa version**
8.174.16
Include Vespa version(s) used.

**Additional context**

**Comment by bjormel** [comment]
@Krithiraj can you share the Kubernetes configuration files?

**Comment by Krithiraj** [comment]
![IMG_20230801_125636](https://github.com/vespa-engine/vespa/assets/90279480/ccdc3097-2c06-4dd0-b91b-1ef3e0b3ab80)

PFA

**Comment by bjormel** [comment]
Is it possible to verify/test this in a minikube?

If so, can you add steps to reproduce?
