### ISSUE TITLE
apps do not deploy with vespa-onnx-runtime (AWS GPU) 

### ISSUE THREAD

**Issue by stauntonjr** [vespa-engine/vespa#27945]
**Describe the bug**
App deployment fails to converge on GPU-enabled AWS EC2 instance

**To Reproduce**
Amazon Deep Learning AMI instance with Ubuntu 20.04
docker info: Total Memory: 30.89GiB
NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0
NVIDIA Container Toolkit CLI version 1.13.5 commit: 6b8589dcb4dead72ab64f14a5912886e6165c079

echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
nvidia-ctk cdi generate --device-name-strategy=type-index --format=json | sudo tee /etc/cdi/nvidia.json

vespa config set target local

sudo docker run --gpus all --detach --name vespa-cuda-sss --user vespa:vespa --hostname vespa-container --publish 8080:8080 --publish 19071:19071 vespaengine/vespa:8.198.18

sudo docker exec -u 0 -it vespa-cuda-sss /bin/bash

> dnf config-manager \
  --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
> dnf -y install vespa-onnxruntime-cuda

vespa clone simple-semantic-search myapp && cd myapp

vespa deploy --wait 300

<Fails to converge>

**Comment by ean** [comment]
Hi.

Please look at the output of `vespa-logfmt` executed from within your container. It should give some indications of what is failing. If that does not indicate what needs to be done, attach the log here, and we can give you a helping hand.

**Comment by stauntonjr** [comment]
[vespa.log](https://github.com/vespa-engine/vespa/files/12240611/vespa.log)
here is an example of a log from one of the unsuccessful deployments. In variably, there is an error where libcublasLt.so.12 cannot be found. That file is installed on the machine. But it is also not listed in the /etc/cdi/nvidia.json file where it looks like a lot of similar files are essentially mapped from the machine into the container.

**Comment by ean** [comment]
After reproducing this today, I have found that the CUDA library the container tries to load depends on the driver/CUDA version on the host. I reproduced your problem on Ubuntu 22.04, running with the latest Nvidia driver. If I installed an older one (version < 525) it loaded the installed CUDA library in the container (which is major version 11).

After that, I got some CUDNN initialization problems I could not solve. But I am unsure if that is some local problem on my setup or other incompatibilities between host and container.

You can give the driver downgrade a try, but keep in mind that we are testing this setup on RHEL 8 derivates, and if you can, I would advise you to try the same if you keep running into problems with the Ubuntu host / CentOS container setup.

We have tested the steps documented on https://docs.vespa.ai/en/vespa-gpu-container.html, and if you follow them, we can better provide help if any of the steps fail.

**Comment by stauntonjr** [comment]
We're working on a new AMI with RHEL8 as of today. Will keep you updated on progress. Not sure which driver to install. I presume that the instructions at https://docs.vespa.ai/en/vespa-gpu-container.html `dnf module install -y --enablerepo cuda-rhel8-x86_64 nvidia-driver:latest` are not correct? I believe I want to install this one https://www.nvidia.com/download/driverResults.aspx/200618/en-us/ based on the G4dn instance having a Tesla T4 according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html

**Comment by ean** [comment]
We are currently running with version 530, which will support all available NVIDIA GPUs on AWS, according to the link you pasted.

**Comment by stauntonjr** [comment]
Version 530 of the Nvidia driver? That is CUDA 12. We setup on Friday with RHEL8 on an AMI with a CUDA 11 compatible Nvidia driver version (470 if I recall, currently away from keyboard) and then got a version compatibility error (between container toolkit and driver). We worked through that only to get the same libcublasLt.so.12 error in the container log. 

Can vespa please provide detailed step-by-step end-to-end instructions of a fresh installation starting from of Nvidia driver, podman, CUDA and container toolkit etc. We have sunk a lot of time trying but the guide on your webpage is not reproducible, even with podman and RHEL. For example, the way the device is specified in the podman run command ( --device nvidia.com... ) throws syntax errors.

**Comment by ean** [comment]
I am following this up with other people on the team. Looks like there are multiple changes with newer versions of both driver and other libraries which is causing the current guide to fail.

I have been able to reproduce several of the issues you are seeing. We will get back to you with an updated guide as soon as we can.

**Comment by ean** [comment]
Hi

We now have a script that does all the required configuration of a RHEL8 host to give Vespa access to the GPU inside a container. The script uses `podman`, which we have tested with, and not `docker` to run the container.
Can you give it a try?

https://gist.github.com/ean/6f485303045cfeb553bf6fdb93bf6570

This script will create a new container image with the required ONNX packages tagged with `vespaengine/with-cuda`, you can use that instead of manually installing `vespa-onnxruntime-cuda` after starting the container.

The `libcublasLt.so.12` issue inside the container was related to a`cudnn` package with a dependency on major 12 version of `libcublasLt`. Hence the exact version specification of `libcudnn8-8.9.4.25-1.cuda11.8`. The rest of the changes are configuration changes on the host. 

We will also update the GPU documentation to include all required steps.

**Comment by stauntonjr** [comment]
Great news, I will try it out soon and report back. Thanks.

**Comment by stauntonjr** [comment]
`podman run --device nvidia.com/gpu=all --detach --name vespa --hostname vespa-pod1 -p 8080:8080 -p 19071:19071 vespaengine/with-cuda`

`Error: setting up CDI devices: unresolvable CDI devices nvidia.com/gpu=all`

**Comment by stauntonjr** [comment]
We used `--gpus all` instead

The
[vespa_ctr.log](https://github.com/vespa-engine/vespa/files/12337158/vespa_ctr.log)
 log is attached

**Comment by stauntonjr** [comment]
It looks like the shell script does actually exited prematurely (possibly at the step `checkrun nvidia-modprobe`?) and failed to even create the /etc/cdi directory, which could explain downstream issues. I'm trying to follow the subsequent steps in the script now, but 'nvidia-frontend' is not in /proc/devices

**Comment by ean** [comment]
If `nvidia-modprobe` then the nvidia driver likely failed to load, that should also explain why nvidia is not presnet in /proc/devices.

You can try to run `sudo modprobe nvidia`, or reboot the host to retry the attempt at loading the driver. If there are still problems `journalctl` might give you some indication of the problem.

Btw, we have now added the script above, and one for RHEL9 to our docker-image repository: https://github.com/vespa-engine/docker-image/tree/master/experimental . These will be kept up to date as we work on documenting the GPU usage properly.

**Comment by ean** [comment]
@stauntonjr - did you make any progress on this? 

We have updated our documentation to contain all required steps, including some notes of things to verify to ensure everything is configured correctly.

https://docs.vespa.ai/en/vespa-gpu-container.html

**Comment by jobergum** [comment]
Resolving this due to inactivity.
