### ISSUE TITLE
Define alias for a content cluster

### ISSUE THREAD

**Issue by Mahdi-Seeker** [vespa-engine/vespa#27980]
**Is your feature request related to a problem? Please describe.**
I'd want to test a new algorithm for a field in my content cluster. I'd like to have a new content cluster, index all of the data with new algorithm in that new content cluster, evaluate it, and if it performs better, then switch to that content cluster at search time. I do this often, and test new algorithms, and want to switch the searchable content cluster often.

**Describe the solution you'd like**
I want to have the ability to define an alias for the content cluster, then change it in vespa when it proved to be better.

**Describe alternatives you've considered**
I can change the content cluster name every time in my code (index code, and search code, which are separate modules), and that's not a good idea, specially if I want to do all of this flow in an automated workflow, which will need an script to automatically change the code (or config). If I can do that in vespa via cli, that's far more doable.

**Additional context**
Another feature I'd like to have is being able to truncate the old content cluster, via cli of course! I don't know if I can truncate a content cluster in Vespa at all.

**Comment by Mahdi-Seeker** [comment]
About the truncate problem:

I just removed a content cluster by commenting it out in services.xml and adding content-cluster-removal to validation-overrides.xml and deploying. But when I browse the data dir on the server, I see that the content cluster directory is still there, and is full of data! So it seems that content-cluster-removal doesn't actually delete the content cluster's data on the servers.

And the content cluster is still available in the clusters list in cluster controller's web interface at http://vespa:19050/clustercontroller-status/v1/ . When I open it, it says that the cluster is down, and it's OCT (Out of contact time) increases infinitely. It seems that the cluster is not *removed*, but only put out of reach, and if I remove the comments in services.xml, the cluster will be back with all of it's data (I didn't try that yet).

What should I do to really delete the cluster data and free up the space? (If I must open another feature request for truncating, let me know)

**Comment by Mahdi-Seeker** [comment]
This is the cluster controller page for the removed content cluster:
![image](https://github.com/vespa-engine/vespa/assets/110457025/a6230d83-c9f0-40e6-9768-ed83efe3263e)

**Comment by baldersheim** [comment]
Instead of removing the content cluster directly, you should remove the document types inside the cluster and redeploy. This will remove all data associated with the document types you remove.
Then you can remove the cluster afterwards.

**Comment by geirst** [comment]
The procedure is described under item 5 here: https://docs.vespa.ai/en/operations/batch-delete.html

**Comment by Mahdi-Seeker** [comment]
> The procedure is described under item 5 here: https://docs.vespa.ai/en/operations/batch-delete.html

Ok, I tried to do that, but failed! Because I have only 1 document type in my content cluster.
So I created a temp schema, and added that to content cluster, to be able to comment out the main one! And it worked! But it's not a clean way of doing this...

**Comment by kkraune** [comment]
As of today, you cannot define aliases for content clusters / schemas, and you cannot have two document types with the same schema in the same content cluster.

Let me take a step back (my understanding of this): What you want to achieve is to have different versions of the data set, select which one to use in queries, and be able to remove old versions of the data sets efficiently.

This is very close to what is documented at https://docs.vespa.ai/en/tutorials/models-hot-swap.html, using version fields, https://docs.vespa.ai/en/parent-child.html and auto garbage collection

With this, you tag documents with a version when feeding, and manage the serving version in a global document (meaning, it is one simple write operation to change the version used in queries)

Use the model-hot-swap doc as inspiration, and try to re-model your problem into using version fields - and configure the auto garbage collection to auto-remove older versions. I hope this helps

**Comment by Mahdi-Seeker** [comment]
> Let me take a step back (my understanding of this): What you want to achieve is to have different versions of the data set, select which one to use in queries, and be able to remove old versions of the data sets efficiently.
> 
> This is very close to what is documented at https://docs.vespa.ai/en/tutorials/models-hot-swap.html, using version fields, https://docs.vespa.ai/en/parent-child.html and auto garbage collection
> 
> With this, you tag documents with a version when feeding, and manage the serving version in a global document (meaning, it is one simple write operation to change the version used in queries)
> 
> Use the model-hot-swap doc as inspiration, and try to re-model your problem into using version fields - and configure the auto garbage collection to auto-remove older versions. I hope this helps

Thanks for the response, I'll try this approach.

**Comment by Mahdi-Seeker** [comment]
Does this approach have a negative performance impact on the whole vespa cluster? And specifically on that content cluster with multiple versions?

**Comment by kkraune** [comment]
The garbage collection runs on the content cluster and will consume more than 0% resources, but is designed to be light-weight. This is the normal way teams expire documents in Vespa, in particular for ease of use and no operational complexity. I suggest you test it and see for your use case

**Comment by kkraune** [comment]
Related: https://stackoverflow.com/questions/76571240/can-i-uses-an-alias-instead-of-the-schema-name
