### ISSUE TITLE
Can we use a shared onnx model with different components, without performance penalty?

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28009]
The need is to create two components "e5-1" and "e5-2" sharing the same model.

Each component is deployed independently for the need of two schemas schema1.sd and schema2.sd.
When an application does not require schema1.sd , it can remove it with component "e5-1", without impacting the application managing schema2.sd

(This example is more useful with tens of schemas managed by tens of applications)

```
<container id="default" version="1.0">
    <component id="e5-1" type="hugging-face-embedder">
        <transformer-model path="shared_path_to_onnx"/>
    </component>
    <component id="e5-2" type="hugging-face-embedder">
        <transformer-model path="shared_path_to_onnx"/>
    </component>
    ...
</container>

```

**Comment by eostis** [comment]
I love the many-to-many relationship between schema and embedder.

> If you define multiple embedder components, they can share the same path file, but that will still consume resources (e.g GPU memory) as it will be separate instances.

Basically, each embedder component (sharing model or not, configured in a schema or not) will consume its own resources?

**Comment by jobergum** [comment]
> Basically, each embedder component (sharing model or not, configured in a schema or not) will consume its own > >resources? No lazy loading?

Yes, each declared component becomes an instance that will consume resources regardless of pointing to the same file/URL/path resources.

**Comment by eostis** [comment]
Thanks.
