### ISSUE TITLE
Expression for converting a date to epoch time in an indexing statement

### ISSUE THREAD

**Issue by sergiomorenolopez** [vespa-engine/vespa#28019]
Hello vespa team.

I would like to create a derived field with an indexing statement. 
I would need to convert a date to epoch time.
Checking the documentation at https://docs.vespa.ai/en/reference/advanced-indexing-language.html, it seems there are no expressions for converting a date to epoch time.
A workaround would be using a docprocessor to populate the field.
However, everytime a similar situation takes place, a document reindexing would be needed to populate this field in all documents affected, increasing running costs in vespa cloud.

It would be really handy to have a new indexing expression that would convert from a date to epoch time.
This expression could be similar to **fromdateiso8601** from the jq tool (https://jqlang.github.io/jq/manual/v1.6/#dates).

Thank you.

**Comment by jobergum** [comment]
This will be available in a release =>  8.214.6. Details on the feature https://github.com/vespa-engine/documentation/pull/2818

**Comment by jobergum** [comment]
This feature is available in [8.215.17](https://hub.docker.com/layers/vespaengine/vespa/8.215.17/images/sha256-0f15bae2947466386d2054793eefc7fcdd019725ccfaf661abae6f0fc0ce4825?context=explore)
