### ISSUE TITLE
[FR] Automatic load/unload embedder components to save resources

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28028]
The general rule is to load a component if, and only if, used in a schema.

Keeping track of components after a lot of schema add/update/remove deployments can be difficult, especially in the context of distributed apps deploying with the REST API:
- Removing a component in use will lead to errors
- Leaving a component not in use will lead to resource overuse

Here is an example of automatic component management for a sequence of deployments:
- Add component1: component1 is not loaded 
- Add schema1 and schema2 with component1: component1 is loaded 
- Remove schema1: component1 keeps loaded
- Remove schema2: component1 is unloaded

**Comment by jobergum** [comment]
So there is a connection that can be tracked between embedder components and schema usage, but they can also be used programmatically (in searchers and in docprocs) and most importantly in queries so this is close to impossible.

**Comment by eostis** [comment]
And adding an attribute "autoload" true/false to components?

**Comment by jobergum** [comment]
>And adding an attribute "autoload" true/false to components?

So, for the lifetime of the running serving container, lazily load? That would probably work for indexing, but it would cause a bad user experience for queries.

**Comment by bratseth** [comment]
It might also move detection of issues from deployment time to runtime.

**Comment by eostis** [comment]
Thanks for suggesting: I was thinking of autoload on deployments, but on inference could be very interesting too :)

"autoload": "deployment"|"inference"

**Comment by jobergum** [comment]
What does autoload on deployment even mean?

**Comment by eostis** [comment]
`"autoload": "deployment"`
Loading and unloading of a component is done when deploying, based on # of references in schema files

`"autoload": "inference"`
=> Component is only loaded at inference, and unloaded after some delay if no inference

**Comment by bratseth** [comment]
If there is insufficient memory to hold the configured models it should fail at deployment time. An application which deployed successfully should not be dependent on requests arriving with a certain timing to not fail.

**Comment by eostis** [comment]
Kubernetes autopilot mode cannot be used to load/unload nodes?

**Comment by bratseth** [comment]
All nodes (in a cluster) have the same components, and a change to the node set is a deployment.

**Comment by eostis** [comment]
Understood. Closing now.

Thanks for your help!
