### ISSUE TITLE
Wrong access modifier of ai.vespa.client.dsl.NearestNeighbor#annotate

### ISSUE THREAD

**Issue by Heezer** [vespa-engine/vespa#28029]
The method should have the public access modifier instead of default one, otherwise there is no way to provide the annotation which leads to exception in `toString()` of the same class. And the latter will be invoked from `ai.vespa.client.dsl.Query#build`.

Version: 8.209.11

Reproduction:
`Q.select("field").from("source").where(Q.nearestNeighbor("vector", "q").annotate(A.a("targetHits", 10)))`

**Comment by bratseth** [comment]
You are right. Fixed in https://github.com/vespa-engine/vespa/pull/28031 which will be in 8.211 (or maybe 8.210), to be released the upcoming week.
