### ISSUE TITLE
New schema not ready to use right after deployment

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28040]
Steps:

- Prepare a new schema deployment
```
$this->api->put( '/application/v2/tenant/default/session/%s/prepared?applicationName=%s',
			[ $session_id, static::VESPA_DEFAULT_APPLICATION ],
			$settings);
```

- Activate the deployment session
```
$result = $this->api->put( '/application/v2/tenant/default/session/%s/active',
			[ $session_id ],
			$settings);
```

Dump of $result looks fine:
`{"deploy":{"from":"/opt/vespa/var/db/vespa/config_server/serverdb/tenants/default/sessions/664","timestamp":1692010676340,"internalRedeploy":false},"application":{"id":"default:default:default","checksum":"7ddfe5aaf89f28b913b773729174c69d","generation":666,"previousActiveGeneration":664},"tenant":"default","session-id":"666","message":"Session 666 for tenant 'default' activated.","url":"http://node1.vespanet:19071/application/v2/tenant/default/application/default/environment/prod/region/default/instance/default"}
`

-  Querying the new schema immediately returns an error:
`{"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"errors":[{"code":4,"summary":"Invalid query parameter","message":"Could not resolve source ref 'Dev8083862739835F'. Valid source refs are wpsolr."}]}}
`

After waiting like 30s, the same query is fine.
I noticed similar issue with other deployment types, for instance deploying a new field to the schema does not make it available immediately.

My question: is there a way to wait for the full deployment completion?

**Comment by kkraune** [comment]
Hi! Take a look at https://docs.vespa.ai/en/application-packages.html#convergence and see if that helps. I just added this doc, grateful for any feedback ;-)

**Comment by eostis** [comment]
Thanks! Worked like a charm.

It could be also mentioned on https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html, as this is where most visitors will look for this info.

**Comment by kkraune** [comment]
Good point, https://github.com/vespa-engine/documentation/pull/2804 fixes that - thanks!
