### ISSUE TITLE
Support <component> in pyvespa

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#28084]
In order to run https://github.com/vespa-engine/sample-apps/tree/master/multi-vector-indexing as a pyvespa app, one must be able to add this to services.xml:
```
        <component id="e5-small-q" type="hugging-face-embedder">
            <transformer-model path="model/e5-small-v2-int8.onnx"/>
            <tokenizer-model path="model/tokenizer.json"/>
        </component>
```

Discussed a little with @lesters , decided to add support for adding a generic Component to an app

CC @jobergum

**Comment by lesters** [comment]
Added in https://github.com/vespa-engine/pyvespa/pull/548
