### ISSUE TITLE
Documentation on ranking forgets to mention the goal

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28089]
In https://docs.vespa.ai/en/ranking.html

> Ranking is where Vespa does computing, or inference over documents

Is the goal missing in this description? (to order matched results with the greater ranking). Better description at https://docs.vespa.ai/en/query-api.html#ranking

**Comment by bratseth** [comment]
This could be improved, but that is not always the goal, or the only goal; any output from a function (/model) can be added to the returned result, whether or not you want to order by it.

**Comment by eostis** [comment]
Indeed, with match-features or summary-features. But https://docs.vespa.ai/en/ranking.html mostly showcases ranking phases, not ranking output.
