### ISSUE TITLE
Support for headers in system tests executed by vespa test

### ISSUE THREAD

**Issue by sergiomorenolopez** [vespa-engine/vespa#28092]
Hello Vespa team!

I have come across with the need of creating system tests with http requests with headers.

I would usually execute them with `vespa test` and a json file describing the test configuration.
However, it seems that http requests with headers are not supported with `vespa test` and I have found that the only way to test them are with Java API tests, as stated in https://docs.vespa.ai/en/testing.html.
The documentation suggests the Java API tests are for complex tests in mind, but I think just adding a header to an http request doesn't count as a complex situation at all and just adds too much complexity to simple system tests that just require adding an additional header.

Would it be possible to add the ability of executing http requests with headers for `vespa test` system tests?

What I had in mind was a configuration similar to this to execute an http request with headers:

```json
"steps": [
        {
            "name": "get documents",
            "request": {
                "method": "GET",
                "uri": "/document/v1",
                "parameters": {
                    "cluster": "music",
                    "selection": "true"
                },
                "headers": {
                    "context": "{\"key\": \"value\"}"       
                }
            }
        }
]
```

Thank you.

Kind regards,

Sergio Moreno López.

**Comment by mpolden** [comment]
The `headers` fields can now be set in tests. Available as of 8.265.12.
