### ISSUE TITLE
Tensor coredump when run 'vespa deploy'

### ISSUE THREAD

**Issue by ARSwhut** [vespa-engine/vespa#28127]
**Describe the bug**
When I run vespa deploy in Centos 8, I have a problem that tensor coredump.
**To Reproduce**
1. I have 3 nodes, 2 nodes for configserver and 3 nodes for services.
2. I only have 1 schema. Schema and service.xml are as followed.
item_i2i.sd:
schema item_i2i {

    document item_i2i {

        field attr_ado type float {
            indexing: attribute
        }

        field id type string {
            indexing: attribute
        }

        field index_time type long {
            indexing: attribute
        }

        field name type string {
            indexing: index
        }

        field namecus type string {
            indexing: index
        }

        field pname type string {
            indexing: index
        }
    }
}

services.xml:

<services version="1.0" xmlns:deploy="vespa" xmlns:preprocess="properties">
    <admin version="2.0">
        <configservers>
            <configserver hostalias="node0"/>
            <configserver hostalias="node1"/>
        </configservers>
        <cluster-controllers>
            <cluster-controller hostalias="node0"/>
            <cluster-controller hostalias="node1"/>
        </cluster-controllers>
        <slobroks>
            <slobrok hostalias="node0" />
            <slobrok hostalias="node1" />
        </slobroks>
        <adminserver hostalias="node0"/>
    </admin>

    <container id="feed" version="1.0">
        <document-api>
            <http-client-api>
                <threadpool>
                    <max-threads>512</max-threads>
                    <min-threads>100</min-threads>
                    <queue-size>1000</queue-size>
                </threadpool>
            </http-client-api>
        </document-api>
        <document-processing/>
        <nodes>
            <jvm options="-Xms30g -Xmx30g"/>
            <node hostalias="node0" />
            <node hostalias="node1" />
        </nodes>
    </container>

    <container id="query" version="1.0">
        <search/>
        <nodes>
            <jvm options="-Xms30g -Xmx30g"/>
            <node hostalias="node2" />
        </nodes>
    </container>

    <content id="item_i2i_sg8_200823" version="1.0">
        <redundancy>2</redundancy>
        <documents>
            <document type="item_i2i" mode="index"/>
            <document-processing cluster="feed" />
        </documents>
        <nodes>
            <node hostalias="node0" distribution-key="0" />
            <node hostalias="node1" distribution-key="1" />
            <node hostalias="node2" distribution-key="2" />
        </nodes>
        <tuning>
            <merges max-per-node="32" max-queue-size="100"/>
            <bucket-splitting max-documents="10240"/>
        </tuning>
    </content>
</services>

3. First I run '/opt/vespa/bin/vespa-start-configserver' in first 2 nodes.

4. Then I run '/opt/vespa/bin/vespa-start-services' in all nodes.

5. I maven my app and run 'vespa deploy', then I find that tensor coredump and get errors.

**Expected behavior**
No errors and deploy successfully.

**Screenshots**
![image](https://github.com/vespa-engine/vespa/assets/31820093/17d29384-935c-4495-8547-69c1f8b4e57c)

**vespa logs**
1692785798.406721 10-161-52-169 92491 searchnode stderr warning terminate called after throwing an instance of 'vespalib::IllegalArgumentException'
1692785798.421038 10-161-52-169 92491 searchnode stderr warning what(): IllegalArgumentException: Failed decoding value type from tensorspec(error) at value_from_spec in /builddir/build/BUILD/vespa-8.213.13/eval/src/vespa/eval/eval/value_codec.cpp:339
1692785798.421052 10-161-52-169 92491 searchnode stderr warning Backtrace:
1692785798.421056 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libvespalib.so(vespalib::IllegalArgumentException::IllegalArgumentException(vespalib::stringref, vespalib::stringref, int)+0x16) [0x7fab4bdd5da6]
1692785798.421061 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libvespaeval.so(+0x9d145) [0x7fab4bfdb145]
1692785798.421065 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libsearchlib.so(search::tensor::TensorAttribute::TensorAttribute(vespalib::stringref, search::attribute::Config const&, search::tensor::TensorStore&, search::tensor::NearestNeighborIndexFactory const&)+0x1e4) [0x7fab4f408864]
1692785798.421069 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libsearchlib.so(search::tensor::SerializedFastValueAttribute::SerializedFastValueAttribute(vespalib::stringref, search::attribute::Config const&, search::tensor::NearestNeighborIndexFactory const&)+0x50) [0x7fab4f404f90]
1692785798.421081 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libsearchlib.so(search::AttributeFactory::createSingleStd(vespalib::stringref, search::attribute::Config const&)+0x8b1) [0x7fab4ee456e1]
1692785798.421085 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libsearchlib.so(search::AttributeFactory::createAttribute(vespalib::stringref, search::attribute::Config const&)+0x30c) [0x7fab4ee25d1c]
1692785798.421088 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin(proton::AttributeFactory::create(vespalib::small_string<48u> const&, search::attribute::Config const&) const+0x1b) [0x67cd7b]
1692785798.421092 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin(proton::AttributeInitializer::createAndSetupEmptyAttribute() const+0x28) [0x6b08c8]
1692785798.421095 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin(proton::AttributeInitializer::init() const+0x8d) [0x6b0ded]
1692785798.421098 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin() [0x67daa1]
1692785798.421101 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin() [0x5f7997]
1692785798.421104 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libvespalib.so(vespalib::ThreadStackExecutorBase::run()+0x72) [0x7fab4be1af82]
1692785798.421107 10-161-52-169 92491 searchnode stderr warning /opt/vespa/sbin/vespa-proton-bin() [0x5a25f9]
1692785798.421110 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/libvespalib.so(+0x3cf2bf) [0x7fab4bdd12bf]
1692785798.421113 10-161-52-169 92491 searchnode stderr warning /lib64/libstdc++.so.6(+0xc2ba3) [0x7fab4011cba3]
1692785798.421116 10-161-52-169 92491 searchnode stderr warning /opt/vespa/lib64/vespa/malloc/libvespamalloc.so(+0x8c30) [0x7fab4f735c30]
1692785798.421120 10-161-52-169 92491 searchnode stderr warning /lib64/libpthread.so.0(+0x817a) [0x7fab4b7ac17a]
1692785798.421124 10-161-52-169 92491 searchnode stderr warning /lib64/libc.so.6(clone+0x43) [0x7fab3f7f7dc3]

**Environment (please complete the following information):**
 - OS: 
    LSB Version:	:core-4.1-amd64:core-4.1-noarch
    Distributor ID:	CentOSStream
    Description:	CentOS Stream release 8
    Release:	8
    Codename:	n/a
    Version: 4.18.0-147.el8.x86_64
 - Maven Version: Apache Maven 3.9.4
 - Java Version: 17.0.6-ea

**Vespa version**
vespa-8.213.13-1.el8.x86_64

**Additional context**

**Comment by jobergum** [comment]
Is this a fresh new deployment or have the nodes been used before, and that you have data structures on the nodes?

**Comment by ARSwhut** [comment]
> Is this a fresh new deployment or have the nodes been used before, and that you have data structures on the nodes?

Yes.There is previous data that has not been cleaned up. I cleaned up the data under the /opt/vespa/var/db/vespa/search path to solve this problem. Thanks

**Comment by jobergum** [comment]
Anything we can do to sanitize @geirst
