### ISSUE TITLE
Sample app "basic-search-on-gke" scripts fail to load K8s node

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28204]
App: https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/basic-search-on-gke

I used this app scripts a month ago with success.

Scripts now cannot start the node, with n1-standard-2 or n1-standard-4 machines:
<img width="1690" alt="image" src="https://github.com/vespa-engine/vespa/assets/1785759/95cb642d-aafe-4d88-8946-17d476180c70">

**Comment by kkraune** [comment]
I just ran through https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/basic-search-on-gke and it worked fine for me

The check that fails is https://github.com/vespa-engine/vespa/blob/master/client/go/internal/admin/vespa-wrapper/configserver/check.go#L23

Looking at https://github.com/vespa-engine/sample-apps/blob/master/examples/operations/basic-search-on-gke/deployments/configmap.yml#L7 it says

```
  VESPA_CONFIGSERVERS: "vespa-0.vespa-internal.default.svc.cluster.local"
```

In your error message, is says "vespa-0.vespa-internal.vespa-demos.svc.cluster.local"

I don't know where `vespa-demos` comes from, maybe you changed something?

**Comment by eostis** [comment]
Thanks.

I checked my config, and noticed that "vespa-demos" is my cluster namespace:
kubectl config set-context --current --namespace  "wpsolr-demos"


Does that mean we can only deploy on the "default" namespace?

If so, could we introduce a new namespace parameter to the scripts?
VESPA_CONFIGSERVERS: "vespa-0.vespa-internal.${5:-"default"}.svc.cluster.local"

**Comment by eostis** [comment]
I made some tests, but manipulating namespaces does not worth the complexity.
