### ISSUE TITLE
Request from Homebrew maintainers re: publishing

### ISSUE THREAD

**Issue by p-linnane** [vespa-engine/vespa#28255]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. It appears the publishing workflow for the Vespa CLI is not running `brew update` prior to opening PR's in our repo. This means that each PR starts off with a conflict that we must manually resolve. Can you please add `brew update` into the workflow prior to running `brew bump-formula-pr`? Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/140807

**Comment by mpolden** [comment]
Thanks for reporting this issue. It should be fixed by #28263.

**Comment by p-linnane** [comment]
Thank you!
