### ISSUE TITLE
Documentation and examples for HuggingFace cross-encoders

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28287]
I checked the documentation and the blog, but could not find HuggingFace cross-encoders.

I'm already using HuggingFace bi-encoders in first phase.

I'd like to use HuggingFace cross-encoders on second phase and/or global phase.

**Comment by jobergum** [comment]
Hey @eostis, 

Complete example https://github.com/vespa-engine/sample-apps/tree/master/transformers

Notice that we should

- rewrite it to use https://docs.vespa.ai/en/reference/embedding-reference.html#huggingface-tokenizer-embedder tokenizer instead of the word piece implementation
- Include a export script

**Comment by eostis** [comment]
> Notice that we should
> 
> rewrite it to use https://docs.vespa.ai/en/reference/embedding-reference.html#huggingface-tokenizer-embedder tokenizer instead of the word piece implementation
> Include a export script

Indeed, that was my point.

**Comment by eostis** [comment]
Do you think we could also use cross-encoders with https://docs.vespa.ai/en/reference/embedding-reference.html#huggingface-embedder ?

**Comment by jobergum** [comment]
No, cross-encoders take both the query and the document as input at inference time, so it does not fit.

**Comment by eostis** [comment]
Thanks for your time @jobergum. 

I'll deliver a first release of WPSOLR without the cross-encoders, and add it after more studying.
[Vespa's blog](https://blog.vespa.ai/pretrained-transformer-language-models-for-search-part-4/) is a very good starting point for that.

**Comment by jobergum** [comment]
Added [documentation](https://docs.vespa.ai/en/cross-encoders.html) on running different types of cross-encoders in Vespa.
