### ISSUE TITLE
Can rank profile inheritance cross schemas?

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28341]
I could not find the answer in the documentation.

# Context
I'm generating schemas for my Vespa application, and they all have the same structure. 
For instance, the code below shows a rank profile "rank_global" shared by 3 schemas, but with different expressions. 

# Question
A query on documents from schema1  with ranking rank_local will be ranked with bm25(field1)?
A query on documents from schema2 with ranking rank_local will be ranked with bm25(field2)?
A query on documents from schema3 with ranking rank_local will be ranked with bm25(field1) or bm25(field2)?

# Code
```
schema schema1 {
    rank-profile rank_global {
      first-phase {
              expression: bm25(field1)
          }
      }
    rank-profile rank_local  inherits rank_global {}
}

schema schema2 {
    rank-profile rank_global {
      first-phase {
              expression: bm25(field2)
          }
      }
    rank-profile rank_local  inherits rank_global {}
}

schema schema3 {
    rank-profile rank_local  inherits rank_global {}
}
```

**Comment by eostis** [comment]
Thanks @bjormel.

I was misleaded by https://docs.vespa.ai/en/schemas.html#schema-inheritance, which never mentions schema inheritance, only document inheritance.

```
schema items {
    rank-profile items_ranking_base {
        function title_score() {
            expression: fieldLength(title)
        }
        first-phase {
            expression: title_score
        }
        summary-features {
            title_score
        }
    }
}

## Missing "inherits items" here
schema books {
    rank-profile items_ranking inherits items_ranking_base {}

    rank-profile items_subschema_ranking inherits items_ranking_base {
        first-phase {
            expression: title_score + fieldMatch(author)
        }
        summary-features inherits items_ranking_base {
            fieldMatch(author)
        }
    }
}
```

**Comment by bjormel** [comment]
hmm, it seems like my knowledge on this is outdated, pleas disregard my previous comment. Will get back to you

**Comment by bjormel** [comment]
Updated https://docs.vespa.ai/en/schemas.html#schema-inheritance
