### ISSUE TITLE
Use the idf value from the largest index

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#28611]
Today we take the idf value from the current index when needing it for relevance scoring of a document. With uncommon terms and small memory indexes this can lead to idf values which are far from those of a representative corpus.

**Comment by geirst** [comment]
The current behavior in Vespa 8.337.85 (and newer), with this fix: https://github.com/vespa-engine/vespa/pull/30947. 

- When searching for a word in a single index field, we use a `SourceBlenderBlueprint` over all memory indexes and disk indexes for this field. The document frequency for the word is the max among all indexes.
- When searching for a word in a fieldset with multiple indexes, we use a `SourceBlenderBlueprint` (for each index) on top of multiple `OrBlueprint` instances (for each field). The `OrBlueprint` uses saturated sum to calculate the document frequency for the word.
