### ISSUE TITLE
MatchCount didn't calculate number of keywords occurs in text

### ISSUE THREAD

**Issue by tarashchuk** [vespa-engine/vespa#28628]
Hi, i have schema like this
```
schema search {
    document search {
        field Id type string {
            indexing: summary | attribute
            attribute: fast-search
        }
        field Name type string {
            indexing:  summary | attribute 
        
        }
    field NameArray type array<string> {
            indexing:   summary | attribute 
        }
    field NameLength type int {
            indexing:  summary | attribute 
        }
    }

    fieldset default {
        fields: Id
    }

    rank-profile default {
        first-phase {
            expression: nativeRank(Id, Name)
        }
    }

rank-profile searchByName {
        first-phase {
            expression: matchCount(Name)
        }
rank-profile searchByNameArray {
    first-phase {
        expression: matchCount(NameArray)
    }


}
}

```

If i try to find document use this request
```
{
    "hits": 150,
    "ranking": {
        
        "profile": "searchByName"
        
    },
    "offset": 0,
    "yql": "select * from search where Name matches '(?i).*cat.*' "
}
```
It give me relevance is 1. Example of document:
```
{
                "id": "id:search:search::tQtmaccKYmHkaaEA",
                "relevance": 1.0,
                "source": "clan",
                "fields": {
                    "sddocname": "search",
                    "documentid": "id:search:search::tQtmaccKYmHkaaEA",
                    "Id": "tQtmaccKYmHkaaEA",
                    "Name": "Test Cat cats Cat",
                    "NameArray": [
                        "Test",
                        "Cat",
                        "cats",
                        "Cat"
                    ],
                    "NameLength": 14,
                }
            }
```

How to get number of keywords, that occurs in field Name, for document like this(3 times)? Also can be work, if i can try search like:
`select * from search where Name matches '(?i).*ca.*`
Is this possible?

**Comment by jobergum** [comment]
Regular expression matching is supported against `attribute` fields, and it can only say if it matches. That is why matchCount is either 1.0 or 0.0.

**Comment by tarashchuk** [comment]
> Regular expression matching is supported against `attribute` fields, and it can only say if it matches. That is why matchCount is either 1.0 or 0.0.

Maybe Vepsa has some kind of ability to count the number of keywords found in the text? What needs to be fixed in my schema? Or when I store each word in an array<string> , is it possible to count how many elements match the query?

**Comment by jobergum** [comment]
I can recommend to read about the differences between `index` and `attribute` fields in this document for example https://docs.vespa.ai/en/tutorials/news-3-searching.html#matching---index-versus-attribute

For `attribute` fields, there is no support for `match:text` and tokenization.

**Comment by tarashchuk** [comment]
But this link doesn't answer my question - how calculate number of keywords found in the text? . And when i change from attribute to index and try to get any result using the same query - it is empty.

**Comment by jobergum** [comment]
>how calculate number of keywords found in the text?

To have a notion of keyword matching, you must use `index`, otherwise the text is not tokenized. Regarding changing from attribute to index, this requires re-indexing and does not support regular expression search, so you must use `contains` instead of `matches` in the YQL. Then you can get the occurrences count by `fieldTermMatch(name,n).occurrences`

**Comment by tarashchuk** [comment]
How to use  `fieldTermMatch(name, n).occurrences` ? Parameter `name` - name of field? And what is a `n`?

**Comment by tarashchuk** [comment]
Change my schema to
```
schema search {
    document search {
        field Id type string {
            indexing: summary | attribute
            attribute: fast-search
        }
        field Name type string {
            indexing: index | summary       
        }

    field NameLength type int {
            indexing:  summary | attribute 
        }
    }

    fieldset default {
        fields: Id
    }

    rank-profile default {
        first-phase {
            expression: nativeRank(Id, Name)
        }
    }

rank-profile searchByName {
        first-phase {
            expression: fieldTermMatch(Name,1).occurrences
        }
summary-features {
		queryTermCount
		fieldTermMatch(Name,1).occurrences
        }
    }
}
```

And using this query:
```
{
    "hits": 150,
    "ranking": {
        
        "profile": "searchByName"
        
    },
    "offset": 0,
    "yql": "select * from search where Name contains 'cat'"
}
```

`fieldTermMatch(Name,1).occurrences` every time is 0

**Comment by bratseth** [comment]
You need to refeed your data after making this change.

**Comment by tarashchuk** [comment]
How to make refeed? Need redeploy changes to Vespa or need to update documents? 
Also if use ` contains ({substring:true}"old")` for matching - it can help to search and calculate occurence use some part of words, like 'at' for serching words, like 'cats' or 'catsville'?

**Comment by bratseth** [comment]
Refeeding is to write the documents. Index does nit support substring.

**Comment by jobergum** [comment]
>fieldTermMatch(Name,1).occurrences
It counts from zero:

```
rank-profile searchByName {
        first-phase {
            expression: fieldTermMatch(Name,1).occurrences
        }
summary-features {
		queryTermCount
		fieldTermMatch(Name,0).occurrences
        }
    }
```
Term Frequency etc is included in high level text rank-features such as `bm25` and `nativeRank`

**Comment by tarashchuk** [comment]
Thanks for your help. I think, it will be good to implement this abbility with matching and attribute.

**Comment by jobergum** [comment]
Closing out this. On substring/relaxed matching, see https://github.com/vespa-engine/vespa/issues/25970.
