### ISSUE TITLE
HpackException when executing remove method in FeedClient

### ISSUE THREAD

**Issue by sergiomorenolopez** [vespa-engine/vespa#28690]
Hi Vespa team!

I have come accross an issue when using the method **remove(DocumentId documentId, OperationParameters params)** the class **FeedClient** present in the package **ai.vespa.feed.client**.

The issue is the following error message:
```
INFO: Circuit breaker is now half-open, as no requests have succeeded for the last 10011ms. The server will be pinged to see if it recovers. First failure was 'org.eclipse.jetty.http2.hpack.HpackException$SessionException: Could not hpack encode DELETE{u=[https://feed.abc.def.ghi.vespa-app.cloud:443/document/v1/xyz/zyx/docid/r06pudrfbanbept,HTTP/2.0,h=2,cl=-1,p=null}](https://feed.abc.def.ghi.vespa-app.cloud/document/v1/xyz/zyx/docid/r06pudrfbanbept,HTTP/2.0,h=2,cl=-1,p=null%7D)'.
```
Checking online about it I found this  [link](https://github.com/eclipse/jetty.project/issues/9168 ) where it is stated that specifying in the project **pom.xml** the library version 11 of **org.eclipse.jetty.http2.http2-hpack** would solve the problem, as it does.

The configuration added to pom.xml is:
```
<dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-hpack</artifactId>
      <version>11.0.16</version>
</dependency>
```
It seems to me that this behaviour is not an expected one, as automatic resolving the right version of a needed library would be done correctly when using vespa functionality.

Please, let me know it you would need further information.

Thank you.

**Comment by jonmv** [comment]
What version of the feed client did you see this with? We specify that version of that dependency in the current release.

**Comment by bjorncs** [comment]
Hi @sergiomorenolopez. As mentioned by @jonmv vespa-feed-client has been depending on version 11.0.16 of Jetty client artifacts since early September. If you do use the newest feed client release make sure that your Maven project resolves all Jetty artifacts to the correct version (`mvn dependency:tree -Dverbose`).

**Comment by jobergum** [comment]
I'm resolving this. Feel free to re-open if you need further assistance on this @sergiomorenolopez
