### ISSUE TITLE
Add ranking.rerankcount query parameter for global-phase similar to second-phase

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#28705]
Today we have the [ranking.rerankcount](https://docs.vespa.ai/en/reference/query-api-reference.html#ranking.rerankcount) query api parameter, which overrides the per content node `second-phase` `rerank-count`. We also need a similar parameter for the `global-phase` rerank-count.

**Comment by geirst** [comment]
We need to decide the parameter name.

**Comment by arnej27959** [comment]
current parameter is `ranking.rerankCount` so either `ranking.globalPhaseRerankCount` or `ranking.globalPhase.rerankCount` should work.

**Comment by jobergum** [comment]
`ranking.globalPhaseRerankCount` is fine with me.

**Comment by bratseth** [comment]
Maybe ranking.globalPhase.rerankCount is safer.

Would not love to end up with ranking.globalPhaseRerankCount and ranking.globalPhase.somethingElse ...

**Comment by geirst** [comment]
@arnej27959 please add reference documentation before closing.
