### ISSUE TITLE
Use io.airlift:aircompressor:0.25 instead of our own fork.

### ISSUE THREAD

**Issue by baldersheim** [vespa-engine/vespa#28748]
Drop building airlift ourselves.
ZstdInputStream is now part of https://github.com/airlift/aircompressor

**Comment by geirst** [comment]
@arnej27959 can you first evaluate if we can start using ZstdInputStream that is now part of aircompressor? Also check if its JDK 21 compatible.

**Comment by vekterli** [comment]
If we change the Zstd implementation we have to ensure that our current wrapper code in `com.yahoo.compress.ZstdCompressor` is thread safe. The current code assumes the underlying codec instances are stateless (and can thus be used through shared `static` instances). This does _not_ necessarily hold with the airlift implementation.

**Comment by arnej27959** [comment]
done.
