### ISSUE TITLE
Add information about storage_type to documentation

### ISSUE THREAD

**Issue by prasad-marne** [vespa-engine/vespa#28834]
**Is your feature request related to a problem? Please describe.**
Add information about storage_type to documentation

**Describe the solution you'd like**
Update the documentation

**Comment by kkraune** [comment]
Just to make sure, you mean `storage-type` as in https://cloud.vespa.ai/en/reference/services#resources ? Or something else?

**Comment by prasad-marne** [comment]
yes i mean **storage-type** in services resources

**Comment by kkraune** [comment]
ok. The documentation currently says:

> The type of storage to use. This is useful to specify local storage when network storage provides insufficient io operations or too noisy io performance:
local	Node-local storage is required.
remote	Network storage must be used.
any	Both remote or local storage may be used.

It is helpful if you can indicate what more information that will be helpful

**Comment by prasad-marne** [comment]
This is helpful. i was not able to find this information. Thanks for pointing it. We can close this issue

**Comment by kkraune** [comment]
all right! we are launching https://search.vespa.ai/ that will hopefully let users find this more easily. Thanks for reporting!
