### ISSUE TITLE
Missing linguistics dependency

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#28968]
**Describe the bug**
We are using KStemmer in our code. It is located in the linguistics package and we are adding it as a provided package in our pom.xml.

However, we are getting the following error:

```
com/yahoo/language/simple/kstem/KStemmer: 
    com.yahoo.language.simple.kstem.KStemmer not found by vlex-search
```
**To Reproduce**
1. Import com.yahoo.language.simple.kstem.KStemmer;
2. Create an instance of that class
3. See error

**Expected behavior**
We shouldn't see that error

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOs
 - Infrastructure: self-hosted
 - Versions 8.241.13

**Vespa version**
8.241.13

**Additional context**
None

**Comment by bjorncs** [comment]
Hi @danitico. The `KStemmer` is not part of Vespa's public API. Although not accessible directly you may utilize it through `com.yahoo.language.simple.SimpleTokenizer`.

**Comment by danitico** [comment]
Thanks @bjorncs !
