### ISSUE TITLE
nativeFieldMatch value is 0 for a field that is matching with query

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#28993]
**Describe the bug**
We were testing our custom ranking profile and noticed that the nativeFieldMatch for a field is coming as 0 for an index field. 

**_Parent Schema_**
`
           schema parentSchema  { 
           document parentSchema  {

            field  text_s type array<string> {
                indexing: summary | index
            }
			
            field  doc_id type array<string> {
                indexing: summary | index
            }

            field  date_int type int {
                indexing:  attribute
            }
            
    }

		field doc_id_attr type array<string> {
                indexing: input doc_id | attribute
                attribute: paged

	rank-profile custom-rank-profile inherits default {
			
            rank-properties {
                freshness(date_int).maxAge : 31040000
            }

            first-phase {
                expression: nativeRank * freshness(date_int).logscale
            }

            summary-features {
                nativeRank
                freshness(date_int).logscale
            }

        }	

 }
`

_**Child Schema**_
`schema childSchema inherits parentSchema {

    document childSchema  inherits parentSchema {

            field  child_field type array<string> {
                indexing: summary | index
            }			
			
			
        }

}`
	

> Yql - 
> {
>   "yql" : "select * from sources * where doc_id contains \"test-rank-id\" OR doc_id_attr matches \"^test\\\\-ranking.*\" limit 50 offset 0",
>   "ranking.profile" : "custom-rank-profile"
> }

In the documents that are matching with test-rankk-id we are seeing that the _**relevance score is 0.0**_. 
                    "summaryfeatures": {
                        "freshness(date_int).logscale": 0.0,
                        "nativeAttributeMatch": 0.0,
                        "nativeFieldMatch": 0.0,
                        "nativeProximity": 0.0,
                        "nativeRank": 0.0,
                        "freshness_score": 0.0,
                        "vespa.summaryFeatures.cached": 0.0
                    

For the documents matching the next part of the query we are nativeRank

                    "summaryfeatures": {
                        "freshness(date_int).logscale": 0.8122889685279547,
                        "nativeAttributeMatch": 0.00392156862745098,
                        "nativeFieldMatch": 0.0,
                        "nativeProximity": 0.0,
                        "nativeRank": 0.0017429193899782135,
                        "freshness_score": 0.001415754193512775,
                        "vespa.summaryFeatures.cached": 0.0
                    }

Sample docs -

**Vespa version**
8.221.29

**Comment by 107dipan** [comment]
Hi  Geir, 

Wondering if you were you able to reproduce the issue? Please let me know in case you need more details from our side.

**Comment by 107dipan** [comment]
Hi, We made minor changes in the schema and I have updated the description to reflect the same. I have also updated the yq; query. 

3 of the sample docs we were testing with - 

{
                    "doc_id ": [
                        "test-rankingA"
                    ],
                    "text_s": [
                        "This is a valid doc and should be ingested"
                    ], 
					"date_int": 1697573677
            }
            
			
			
			{
                    "doc_id ": [
                        "test-rankingB"
                    ],
                    "text_s": [
                        "This is a valid doc and should be ingested"
                    ], 
					"date_int": 1697570947
            }
			
			
			
			
			{
                    "doc_id ": [
                        "test-rank-id"
                    ],
                    "text_s": [
                        "This is a valid doc and should be ingested"
                    ], 
					"date_int": 1697570811
            }

**Comment by 107dipan** [comment]
Hi @geirst, 

Wondering if you were able to reproduce this issue with the provided information.

**Comment by 107dipan** [comment]
Hi @geirst,

The issue we are  seeing is a bit different. We are seeing that the nativeFieldMatch for the documents that are matching with the index field is 0. 

"summaryfeatures": {
                        "freshness(date_int).logscale": 0.0,
                        "nativeAttributeMatch": 0.0,
                        "nativeFieldMatch": 0.0,
                        "nativeProximity": 0.0,
                        "nativeRank": 0.0,
                        "freshness_score": 0.0,
                        "vespa.summaryFeatures.cached": 0.0
                    }

**Comment by geirst** [comment]
Ok, then you need to provide a single example (document(s) + query) that shows this, because we have not been able to reproduce that particular observation.
