### ISSUE TITLE
Unable to define rank profile in the parent schema

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#28991]
**Describe the bug**
Currently we are using parent child relationship to define our schemas. All our schemas inherit a single parent schema and are defining ranking profile using one of the field from the parent schema. 

**To Reproduce**
1. Define multiple schema with a parent child relationship. 
2. Define ranking profile in parent schema
3. Issue yql query with the deployed ranking profile
       

> rank-profile custom-rank-profile inherits default {
            rank-properties {
                freshness(date_int).maxAge : 31040000
            }
            first-phase {
                expression: nativeRank * freshness(date_int).logscale
            }
            summary-features {
                nativeRank
                freshness(date_int).logscale
            }
}

Error message in yql - 
{
                "code": 4,
                "summary": "Invalid query parameter",
                "source": "lexdoc",
                "message": "schema 'childDocType' does not contain requested rank profile 'custom-rank-profile'"
            

**Vespa version**
8.221.29

**Comment by kkraune** [comment]
The relevant documentation can be found at https://docs.vespa.ai/en/schemas.html#schema-inheritance

Can you include the .sd files for both schemas (parent and childDocType)? It is hard to tell from the excerpt above

**Comment by 107dipan** [comment]
**_Parent Schema_** - 

schema parentSchema  {

    document parentSchema  {

            field  text_s type array<string> {
                indexing: summary | index
            }
			
            field  doc_id type array<string> {
                indexing: summary | index
            }

            field  date_int type int {
                indexing: summary | attribute
            }
            
    }


		field doc_id_attr type array<string> {
                indexing: input doc_id | attribute
                attribute: paged
        }

		
		rank-profile custom-rank-profile inherits default {
			
            rank-properties {
                freshness(date_int).maxAge : 31040000
            }

            first-phase {
                expression: nativeRank * freshness(date_int).logscale
            }

            summary-features {
                nativeRank
                freshness(date_int).logscale
            }

        }

}

**Comment by 107dipan** [comment]
_Child schema_ 


schema childSchema  {

    document childSchema  inherits parentSchema {

            field  child_field type array<string> {
                indexing: summary | index
            }			
			
			
        }


}

**Comment by kkraune** [comment]
YQL query also please, so I can reproduce - thanks!

**Comment by 107dipan** [comment]
{
  "yql" : "select * from sources * where doc_id contains \"test-ranking-doc\" limit 50 offset 0",
  "ranking.profile" : "custom-rank-profile"
}

**Comment by bratseth** [comment]
The rank profile is not inside the document block and therefore you do not inherit it when you only inherit the document.

**Comment by 107dipan** [comment]
Let me try this out. Thanks!

**Comment by kkraune** [comment]
All right, let us know! Added an example to https://docs.vespa.ai/en/schemas.html#schema-inheritance as well
