### ISSUE TITLE
Add weight to a query clause

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#29040]
**Is your feature request related to a problem? Please describe.**
We want to assign weights to certain parts of the query. 

**Describe the solution you'd like**
 (( docId contains \"testDoc\" AND docId_attr matches \"^test\\\\-ranking.*\")) OR (( docId contains \"new-doc-testl\" AND docId_attr matches \"^test\\\\-ranking.*\"))

We would like at assign more weightage to the 1st OR query clause instead of the 2nd one. 

**Describe alternatives you've considered**
We are currently using the weight provided by vespa for assigning weights to terms if needed but we would also like to add weights to certain parts of the query

**Comment by kkraune** [comment]
duplicate / related #14171
