### ISSUE TITLE
Default parameters in global phase ranking are not working

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#29067]
**Describe the bug**
Hi Vespa team! We are experiencing query errors when trying to use a ranking profile that defines a global phase expression that uses a inputs parameter that has a default parameter.

```
{
    "root": {
        "id": "toplevel",
        "relevance": 1.0,
        "fields": {
            "totalCount": 0
        },
        "errors": [
            {
                "code": 4,
                "summary": "Invalid query parameter",
                "source": "sampleapp",
                "message": "missing query feature: weightParameter"
            }
        ]
    }
}
```

The ranking profile is the following one:

```
    rank-profile some_ranking inherits default {

        inputs {
            weightParameter: 0.3  # Weight for parameter
        }

        first-phase {
            expression: nativeRank + attribute(parameter) * query(weightParameter)
        }

        global-phase {
            expression: nativeRank + attribute(parameter) * query(weightParameter)
        }
    }
```
We also try to define it in the query request as input.query(weightParameter)=0.5 but we receive the same error.

**To Reproduce**
1. Define a schema with a rank-profile similar to that
2. Try to disable the global phase in the ranking profile and check that works
3. Try to enable the global phase in the ranking profile and check the error it shows

**Expected behavior**
It should not appear a Invalid query parameter error

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: macOs
 - Infrastructure: self-hosted
 - Versions 14

**Vespa version**
8.245.22

**Additional context**
It may be related with this PR https://github.com/vespa-engine/vespa/pull/29007

**Comment by arnej27959** [comment]
Can you try:

```
 rank-profile some_ranking inherits default {

        inputs {
            query(weightParameter) double: 0.3  # Weight for parameter
        }
```

**Comment by arnej27959** [comment]
also, you need https://github.com/vespa-engine/vespa/pull/29010 to make the default work, that one is present in 8.246.38

**Comment by arnej27959** [comment]
Getting the default value (your 0.3) fails like you reported in 8.245.22 but works in 8.246.38.

But you also said:
_We also try to define it in the query request as input.query(weightParameter)=0.5 but we receive the same error._

But that should already work.  I can't reproduce on 8.245.22; with your rank-profile I get:
```
$ vespa query 'select * from sources * where true' 'ranking.profile=some_ranking' 'input.query(weightParameter)=42'
...
        "children": [
            {
                "id": "id:myns:foo::1",
                "relevance": 84.0,
                "source": "search",
                "fields": {
                    "sddocname": "foo",
                    "documentid": "id:myns:foo::1",
                    "parameter": 2
                }
            }
```

**Comment by danitico** [comment]
Hi @arnej27959 ! It's working for us again after the new version! One more question, do you recommend us to define the type of parameter as you defined in your previous message? https://github.com/vespa-engine/vespa/issues/29067#issuecomment-1775857926

**Comment by arnej27959** [comment]
> do you recommend us to define the type of parameter as you defined in your previous message?

not really.  the short-form you used originally works, but I had recently tested the new global-phase with full explicit definition; personally I find it easier to see what's what with the explicit form.
Thank you for feedback!
