### ISSUE TITLE
Error while deploying application on mtls enabled vespa cluster(singlenode)

### ISSUE THREAD

**Issue by sunil924** [vespa-engine/vespa#29103]
**Describe the bug**
Container is not coming up after prepareandactivate of application.zip
In logs see following error:

ERROR  container [Container.com](http://container.com/).yahoo.jdisc.core.StandaloneMain   JDisc existing: Throwable caught: \nexception=\ncom.google.inject/ProvisionException: Unable to provision, see the following errors:\n\n1) [Guice/ErrorInjectingConstructor]: ConfigurationRuntimeException: Subscribe for 'name=cloud.config.slobroks, configId=default/container.0' timed out (timeout was 55000 ms): name=cloud. config.slobrokes, configId=default.container.0,  Current generation: 0, Generation changed: false, config changes:false \n at ConfiguredApplication.<init>(ConfiguredaApplication.java:149\n while locating  Configured Application\n\n Learn more:\n https://github.com/google/guice/woki/ERROR_INJECTING_CONSTRUCTORE \n \n==========\nFull classname legend:\n======\nCOnfigurationRuntimeException: "com.yahoo.config.ConfigurationRuntimeException"\nConfiguredApplication:  "com.yahoo.container.jdisc.ConfiguredApplication"\n======\nEnd of classname legend.......

**To Reproduce**
1. Create mtls enabled cluster
following curl command returns successful reponse:
 curl -s --key /var/tls/vespa/host.key --cert /var/tls/host.pem --cacert /var/tls/cacerts.pem \
    https://myhost.mydomain.com:19071/state/v1/health;
2. Create application.zip with https enabled. (https://docs.vespa.ai/en/jdisc/http-server-and-filters.html#tls)
`<http>
    <server id="default" port="8080" />
    <server id="secure" port="8443">
        <ssl>
            <private-key-file>/var/tls/host.key</private-key-file>
            <certificate-file>/var/tls/host.pem</certificate-file>
            <ca-certificates-file>/var/tls/cacerts.pem</ca-certificates-file>
            <client-authentication>want</client-authentication>
        </ssl>
    </server>
</http>`
3. prepareandactivate. Rest endpoint call is successful. It returns the message ""Session 18 from tenant 'default' prepared and activated"
4. Not able to connect to  https://myhost.mydomain.com:8080/state/v1/health  and https://myhost.mydomain.com:8443/state/v1/health
 curl -s --key /var/tls/vespa/host.key --cert /var/tls/host.pem --cacert /var/tls/cacerts.pem \
    https://myhost.mydomain.com:8080/state/v1/health;
 curl -s --key /var/tls/vespa/host.key --cert /var/tls/host.pem --cacert /var/tls/cacerts.pem \
    https://myhost.mydomain.com:8443/state/v1/health;

**Expected behavior**
Should be able to connect to 8080 and 8443 port

**Screenshots**

**Environment (please complete the following information):**
 - OS: Unix
 - Infrastructure: self hosted (Podman)

**Vespa version**
Include Vespa version(s) used.
8.x

**Additional context**
Using the same certificate, key, and cacerts for both mtls and https.

**Comment by jobergum** [comment]
Please try to format your issue report better, including the exact commands that you run and the exact configuration. The error you quote doesn't seem to be related to mTLS at all. See also https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA for a working example of setting up mTLS. 

See [formatting tips](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by sunil924** [comment]
To enable mtls and https for application endpoints, I am following the link shared by you.

I am not claiming that issue is related to mtls setup but This issue has started appearing since we enabled mtls on the cluster. We see the exception, mentioned in the issue description, in the vespa logs but not able to find out the root cause. 

Application activation is working fine when mtls was not enabled.
I have shared the config and command relevant to it.
Could you please be specific about the additional information you need?

Fyi, I can't provide the exact copy of the command due to the firm's compliance policy.

**Comment by jobergum** [comment]
Again, please try to format your issue description better and please include log messages using code blocks, you seem to have left out a significant portion of the log message, anything before or after. and please don't truncate the logs. 

You can should check that the referenced files are in fact present on the container instance, and are readable to the user you run vespa with.

Sample configuration https://github.com/vespa-engine/sample-apps/blob/master/examples/operations/multinode-HA/services.xml.secure#L35C13-L42C22

```
<server id="secure" port="8443">
                <ssl>
                    <private-key-file>/var/tls/host.key</private-key-file>
                    <certificate-file>/var/tls/host.pem</certificate-file>
                    <ca-certificates-file>/var/tls/ca-client.pem</ca-certificates-file>
                    <client-authentication>need</client-authentication>
                </ssl>
            </server>
```

Notice how these files are mapped into the running container using docker volume mapping. 

![image](https://github.com/vespa-engine/vespa/assets/20928528/3b741e03-b433-4433-9a0f-b9a95377e936)

**Comment by jobergum** [comment]
closing this out
