### ISSUE TITLE
Dynamic summary not working with query on input field

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#29219]
**Describe the bug**
Dynamic summary not working with query on input field

**To Reproduce**
1. Define a schema field with a summary attribute "wpsolr_title"
 ```
 field wpsolr_title type string {
      indexing: summary | index
      index: enable-bm25
      summary: dynamic
    }
```
3. Define a schema input field "wpsolr_input_text"
```
field wpsolr_input_text type string {
    indexing: (input wpsolr_text || "") . " " . (input wpsolr__id || "") . " " . (input wpsolr_id || "") . " " . (input wpsolr_title || "") . " " . (input wpsolr_post_status_s || "") . " " . (input wpsolr_content || "") . " " . (input wpsolr_snippet_s || "") . " " . (input wpsolr_author || "") . " " . (input wpsolr_author_s || "") . " " . (input wpsolr_post_author_s || "") . " " . (input wpsolr_type || "") . " " . (input wpsolr_meta_type_s || "") . " " . (input wpsolr_permalink || "") . " " . (input wpsolr_comments || "") . " " . (input wpsolr_categories || "") . " " . (input wpsolr_categories_str || "") . " " . (input wpsolr_category_str || "") . " " . (input wpsolr_tags || "") . " " . (input wpsolr_tags_str || "") . " " . (input wpsolr_post_tag_str || "") . " " . (input wpsolr_blog_name_str || "") . " " . (input wpsolr_post_thumbnail_href_str || "") . " " . (input wpsolr_post_href_str || "") . " " . (input wpsolr_title_s || "") . " " . (input wpsolr_post_sticky_s || "") . " " . (input wpsolr_is_excluded_s || "") . " " . (input wpsolr_flat_hierarchy_categories_str || "") . " " . (input wpsolr_non_flat_hierarchy_categories_str || "") . " " . (input wpsolr_product_visibility_str || "") . " " . (input wpsolr_product_stock_str || "") . " " . (input wpsolr_product_cat_str || "") . " " . (input wpsolr_flat_hierarchy_product_cat_str || "") . " " . (input wpsolr_non_flat_hierarchy_product_cat_str || "") | index
    index: enable-bm25
  }

```
**Expected behavior**
1. Querying wpsolr_input_text should but does not produce a dynamic summary for wpsolr_title
```
curl -X POST -H "Content-Type: application/json" --data '
{"query":"page", "yql":"select wpsolr_title from index1 where ([{\"defaultIndex\":\"wpsolr_input_text\"}]userInput(@query)) "}
' \
http://localhost:8080/search/
```
`{"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":5},"coverage":{"coverage":100,"documents":16,"full":true,"nodes":1,"results":1,"resultsFull":1},"children":[{"id":"index:wpsolr/0/c81e728db67e6fc24b6be56d","relevance":0.31803513173241105,"source":"wpsolr","fields":{"wpsolr_title":"Sample Page"}},...]}}
`

2. Querying wpsolr_title should and does produce a dynamic summary for wpsolr_title
```
curl -X POST -H "Content-Type: application/json" --data '
{"query":"page","yql":"select wpsolr_title from index1 where ([{\"defaultIndex\":\"wpsolr_title\"}]userInput(@query)) "}
' \
http://localhost:8080/search/

```
`{"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":1},"coverage":{"coverage":100,"documents":16,"full":true,"nodes":1,"results":1,"resultsFull":1},"children":[{"id":"index:wpsolr/0/c81e728db67e6fc24b6be56d","relevance":0.16343879032006284,"source":"wpsolr","fields":{"wpsolr_title":"Sample <hi>Page</hi>"}}]}}
`

**Environment (please complete the following information):**
 - Docker Vespa 8.253.3 self hosted on MacOS

**Comment by jobergum** [comment]
There must be a misunderstanding here. 

>Expected behavior
>Querying wpsolr_input_text should but does not produce a dynamic summary for wpsolr_title

This might be your expectation, but this is not how synthetic fields works. 

```
document doc {
   field foo type string {..}
}
  field foo_derived type string {
    indexing: input foo | something else
  }
```

Creates a new field `foo_derived` with the contents from `foo` and then some transformation. This is the context of `indexing`.  At query time, there is no reference to where or how the field contents was created during indexing.

**Comment by eostis** [comment]
I asked because it is a standard feature of Lucene engines that I already use.

Example with OpenSearch:

- "text" field defined as an input (copied from other fields, like title and description):
<img width="287" alt="image" src="https://github.com/vespa-engine/vespa/assets/1785759/a533befb-4607-4b1d-8bba-c417cf725482">

- Query on "text" returns highlighting on "title" field: 
<img width="1790" alt="image" src="https://github.com/vespa-engine/vespa/assets/1785759/aaffc106-6c3c-4216-a1ff-7079035a83e0">

**Comment by jobergum** [comment]
That you get with Vespa fieldsets which don’t require copying anything.
Synthetic fields outside of document using Input is just when you need
additional processing, like embedding or splitting.

**Comment by jobergum** [comment]
Closing this out - see [fieldset](https://docs.vespa.ai/en/schemas.html#fieldset) if you want to search multiple fields. This also avoids bloating the index by copying data to many field indexes.

**Comment by eostis** [comment]
Fieldsets have limitations that can only be overcome with input fields. 

[> I bet you get a deployment warning about the mismatch in match settings between the fields you include in the fieldsets. Fields bundled in a fieldset must have the same match settings, implicit (defaults) or explicit. This is because the query can only be transformed with one setting.
](https://github.com/vespa-engine/vespa/issues/27878#issuecomment-1648249391)

**Comment by jobergum** [comment]
It’s a convenience feature for searching string fields that share match
settings. For other cases one can simply expand the query to search
multiple fieldsets or fields using for example OR operator.

**Comment by eostis** [comment]
Thanks.
