### ISSUE TITLE
Improve documentation on feeding in bucket order caused by vespa visit

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#29296]
If you run `vespa visit`, which will visit documents in bucket order, and you feed this back to Vespa, the feed throughput will suffer significantly because of bucket lock contention. This is demonstrated [here](https://github.com/dainiusjocas/vespa-slow-feed) where the original data was produced by performing a `vespa visit`. Shuffling the data so that they are randomized (not bucket order) resolves this problem.

**Comment by vekterli** [comment]
Added a section about this to the visiting doc in https://github.com/vespa-engine/documentation/pull/3019
