### ISSUE TITLE
Using `fuzzy` search breaks bolding

### ISSUE THREAD

**Issue by dainiusjocas** [vespa-engine/vespa#29455]
**Describe the bug**
When the query contains a `fuzzy` search clause it breaks bolding of hits.

**To Reproduce**
Reproducible example is here https://github.com/dainiusjocas/vespa-fuzzy-bolding-problem.

**Expected behavior**
Using a `fuzzy` search clause should not impact bolding.

**Environment (please complete the following information):**
 - macos, docker

**Vespa version**
8.263.7

**Comment by toregge** [comment]
This problem was fixed by #29511 .

**Comment by geirst** [comment]
The fix is part of Vespa 8.267.29.
