### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [vespa-engine/vespa#29563]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ready-research) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by tokle** [comment]
Hi @psmoros, 

The Vespa bug bounty program is still organized under Yahoo’s program with either HackerOne or Intigriti. Feel free to submit through either of those.
https://hackerone.com/yahoo?type=team
https://app.intigriti.com/programs/yahoo/yahoobugbounty/detail

Best regards,
Morten Tokle

**Comment by psmoros** [comment]
Thanks @tokle! Will do :)
