### ISSUE TITLE
Use parent schema in document selection criteria for visit http api

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#29870]
**Describe the bug**
We are trying to use visit HTTP api for streaming documents based on a selection criteria. In the selection criteria we are using parent schema since this field is present in our parent schema. We have multiple child schemas but all of them inherit a single schema. This is not returning any documents. 
But if we use a child schema name with the same field the API is returning is documents. 
Example -> 
```
"selection=parentSchema.date_val >= (some long value)". 

Returns ->
{
    "pathId": "/document/v1/",
    "documents": [],
    "documentCount": 0
}
```

**Vespa version**
8.221.29

**Comment by jobergum** [comment]
Could you clarify this: a parent of our parent schema? What does it mean?

>  In the selection criteria we are using parent schema since this field is a parent of our parent schema.

**Comment by jobergum** [comment]
You can perform selections over imported fields in child document types [doc](https://docs.vespa.ai/en/reference/document-select-language.html#using-imported-fields-in-selections) - but you cannot visit the parent document type and expect that Vespa will return the child document types as there is a one-way mapping. A child document type can import a field from a parent schema, not vice versa.

**Comment by 107dipan** [comment]
Thanks a lot @jobergum. This was very helpful.

**Comment by baldersheim** [comment]
Resolved, closing.
