### ISSUE TITLE
Ignore inherited `match-features`

### ISSUE THREAD

**Issue by dainiusjocas** [vespa-engine/vespa#29949]
**Is your feature request related to a problem? Please describe.**
I have a parent rank-profile that defines `match-features` but in the child rank-profile I need not to return them. What also would be great is to ignore inherited `second-phase` and `global-phase`. 

**Describe the solution you'd like**
I'd like to specify that in the child rank-profile `match-features` inherited from the parent should not be included. Or maybe just providing `match-features {}` but currently the app deployment complaints.

**Describe alternatives you've considered**
Doing `match-features: firstPhase` but in the Vespa response I still have `matchfeatures` field present.

**Additional context**
I'm experimenting with multiple ways to do the ranking. I have a base ranking profile that contains all the function definitions and `match-features` for convenient debugging. It is very close to [this sample app ](https://github.com/vespa-engine/sample-apps/blob/master/commerce-product-ranking/application/schemas/product.sd). I've tried to create a separate rank-profile that would include only `match-features` and then inherit it into the "debug" ranking profiles that would inherit the ranking profile. But double inheritance doesn't work as the function names are defined twice.

**Comment by bratseth** [comment]
I think the logical solution is `match-features {}`

Should also be fixed for the other -features.

**Comment by arnej27959** [comment]
Usually people have the base profile without summary-features, and then make a debugging rank-profile inheriting the base profile but adding summary-features.   But I agree it should be possible to reset to empty list as well, if you want to do that.

**Comment by geirst** [comment]
Fixed in Vespa 8.290.51.
