### ISSUE TITLE
Make behaviour between `global` and `second` phase when `ranking.sorting=''` is given consistent

### ISSUE THREAD

**Issue by dainiusjocas** [vespa-engine/vespa#30175]
**Is your feature request related to a problem? Please describe.**
When a `global-phase` is combined with the `ranking.sorting=''` (i.e. an empty string) then hits are returned not in the order of the `relevance` value but the order of the previous phase ranking. When `ranking.sorting=''` is combined with the `second-phase` then docs a returned in the descending order of the `relevance` value. The difference is unexpected.

**Describe the solution you'd like**
The behavior would be consistent between the second and global phase. It can be: a 400 error, default to `-[relevance]`, etc.

**Describe alternatives you've considered**
Do not send `ranking.sorting=''`.

**Additional context**
Slack [thread](https://vespatalk.slack.com/archives/C01QNBPPNT1/p1707119063896879)
[Reproducibility](https://github.com/dainiusjocas/vespa-global-phase-empty-sorting-string-problem)

**Comment by arnej27959** [comment]
fixed by https://github.com/vespa-engine/vespa/pull/30182
