### ISSUE TITLE
Sorry couldn't find a discussion tab, so asking here. Can vespa be used as a primary database? 

### ISSUE THREAD

**Issue by kolinfluence** [vespa-engine/vespa#30327]
i saw the distribution cluster etc so was wondering if it's good enough to be used as a primary database for almost everything?

having asked so, it is advisable to use vespa in financial / banking services?

**Comment by kolinfluence** [comment]
@bratseth i know there are companies who use elasticsearch as a primary db. so maybe i should ask if anyone is doing so and the use case for it being used as such or caveats etc. do hope someday someone can mention here or write some articles for it being used as such.

**Comment by bratseth** [comment]
Yes, people do all sorts of things - it depends on the value of your data and your organization's appetite for risk.

Vespa has stronger guarantees on data consistency and retention than Elastic.
