### ISSUE TITLE
Evaluate onnx models with onnxruntime

### ISSUE THREAD

**Issue by misslorac** [vespa-engine/vespa#30382]
**Is your feature request related to a problem? Please describe.**
It seems vespa using the java based tensor library to load the external onnx models and evaluate the model during final global reranking.  The model inference is very expensive and it's better to use a dedicated inference engine. Why not directly use onnxruntime which is much faster for model inference during raking?

**Comment by jobergum** [comment]
This must be a misunderstanding; Vespa does use onnxruntime for the acceleration of inference with onnx models.

**Comment by misslorac** [comment]
sorry for my misunderstanding. Because I've seen the tensor lib written in Java.  It seems the tensor lib is only used for model IO instead of model inference ?

**Comment by bratseth** [comment]
It's used to evaluate Vespa tensor expressions, but not to evaluate onnx models.
