### ISSUE TITLE
Parse exception for regular expression

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#30444]
**Describe the bug**
We are trying to search on a array of string field for which the indexing type is defined as attribute. We are trying to use a regular expression for our search. 

{
  "yql" : "select * from sources * where fieldName matches \"(^|[^a-zA-Z0-9])[^\\w\\d]*c.*d($|[^\\w\\d])\""
}

**Vespa version**
8.294.50

Exception thrown -

> {
    "root": {
        "id": "toplevel",
        "relevance": 1.0,
        "fields": {
            "totalCount": 0
        },
        "errors": [
            {
                "code": 4,
                "summary": "Invalid query parameter",
                "message": "Could not create query from YQL: query:L1:80 no viable alternative at input 'imdamtestingDomainsyntheticField10_s_attr matches \"'",
                "stackTrace": "com.yahoo.processing.IllegalInputException: com.yahoo.search.yql.ProgramCompileException: query:L1:80 no viable alternative at input 'imdamtestingDomainsyntheticField10_s_attr matches \"'\n\tat com.yahoo.search.yql.YqlParser.parseYqlProgram(YqlParser.java:888)\n\tat com.yahoo.search.yql.YqlParser.parse(YqlParser.java:275)\n\tat com.yahoo.search.yql.MinimalQueryInserter.insertQuery(MinimalQueryInserter.java:95)\n\tat com.yahoo.search.yql.MinimalQueryInserter.search(MinimalQueryInserter.java:80)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat com.yahoo.processing.execution.Execution.process(Execution.java:112)\n\tat com.yahoo.search.searchchain.Execution.search(Execution.java:499)\n\tat com.yahoo.prelude.searcher.FieldCollapsingSearcher.search(FieldCollapsingSearcher.java:96)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat com.yahoo.processing.execution.Execution.process(Execution.java:112)\n\tat com.yahoo.search.searchchain.Execution.search(Execution.java:499)\n\tat com.yahoo.prelude.querytransform.PhrasingSearcher.search(PhrasingSearcher.java:60)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat com.yahoo.processing.execution.Execution.process(Execution.java:112)\n\tat com.yahoo.search.searchchain.Execution.search(Execution.java:499)\n\tat com.yahoo.prelude.statistics.StatisticsSearcher.search(StatisticsSearcher.java:235)\n\tat com.yahoo.search.Searcher.process(Searcher.java:134)\n\tat com.yahoo.processing.execution.Execution.process(Execution.java:112)\n\tat com.yahoo.search.searchchain.Execution.search(Execution.java:499)\n\tat com.yahoo.search.handler.SearchHandler.searchAndFill(SearchHandler.java:348)\n\tat com.yahoo.search.handler.SearchHandler.search(SearchHandler.java:393)\n\tat com.yahoo.search.handler.SearchHandler.handleBody(SearchHandler.java:269)\n\tat com.yahoo.search.handler.SearchHandler.handle(SearchHandler.java:178)\n\tat com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handle(ThreadedHttpRequestHandler.java:77)\n\tat com.yahoo.container.jdisc.ThreadedHttpRequestHandler.handleRequest(ThreadedHttpRequestHandler.java:87)\n\tat com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.processRequest(ThreadedRequestHandler.java:191)\n\tat com.yahoo.container.jdisc.ThreadedRequestHandler$RequestTask.run(ThreadedRequestHandler.java:185)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: com.yahoo.search.yql.ProgramCompileException: query:L1:80 no viable alternative at input 'imdamtestingDomainsyntheticField10_s_attr matches \"'\n\tat com.yahoo.search.yql.ProgramParser$ErrorListener.syntaxError(ProgramParser.java:91)\n\tat org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)\n\tat org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)\n\tat org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)\n\tat org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)\n\tat com.yahoo.search.yql.yqlplusParser.logical_OR_expression(yqlplusParser.java:2746)\n\tat com.yahoo.search.yql.yqlplusParser.expression(yqlplusParser.java:2488)\n\tat com.yahoo.search.yql.yqlplusParser.where(yqlplusParser.java:2135)\n\tat com.yahoo.search.yql.yqlplusParser.select_statement(yqlplusParser.java:888)\n\tat com.yahoo.search.yql.yqlplusParser.query_statement(yqlplusParser.java:804)\n\tat com.yahoo.search.yql.yqlplusParser.source_statement(yqlplusParser.java:513)\n\tat com.yahoo.search.yql.yqlplusParser.output_statement(yqlplusParser.java:447)\n\tat com.yahoo.search.yql.yqlplusParser.statement(yqlplusParser.java:398)\n\tat com.yahoo.search.yql.yqlplusParser.program(yqlplusParser.java:335)\n\tat com.yahoo.search.yql.ProgramParser.parseProgram(ProgramParser.java:111)\n\tat com.yahoo.search.yql.ProgramParser.parse(ProgramParser.java:122)\n\tat com.yahoo.search.yql.YqlParser.parseYqlProgram(YqlParser.java:886)\n\t... 29 more\n"
            }
        ]
    }
}

**Comment by jobergum** [comment]
Try using proper JSON 

```json
{
"yql" : "select * from sources * where fieldName matches \"(^|[^a-zA-Z0-9])[^\\w\\d]*c.*d($|[^\\w\\d])\""
}

**Comment by 107dipan** [comment]
Thanks a lot!! This was very helpful.
