### ISSUE TITLE
Clarification on ColbertV2 support for end-to-end

### ISSUE THREAD

**Issue by jens-totemic** [vespa-engine/vespa#30664]
Looking at the announcement for Colbert embedding support [here](https://blog.vespa.ai/announcing-colbert-embedder-in-vespa/) I'm still a little unclear if Vespa supports the full end-to-end retrieval of ColBERT. 

Examples I've seen seem to use it for re-ranking of other results or employ a re-ranker after using ColBERT. The example referenced in the blog [here](https://github.com/vespa-engine/sample-apps/tree/master/colbert) is also using embeddings from e5-small-v2 in addition to ColBERT.

Can you clarify if it is also usable for the full end-to-end retrieval without additional embeddings or re-ranker afterwards? Basically similar as how ColbertV2 is recommended to be used in https://github.com/stanford-futuredata/ColBERT#retrieval - but through Vespa in this case?

**Comment by jobergum** [comment]
Hey @jens-totemic, 

Relevant sections from the  [colbert blog announcement](https://blog.vespa.ai/announcing-colbert-embedder-in-vespa/):

> Why didn’t you expose the ColBERT 2 [PLAID](https://arxiv.org/abs/2205.09707) retrieval optimization in Vespa?

>Primarily because Vespa is designed for low-latency real-time indexing, and the [PLAID optimization](https://arxiv.org/abs/2205.09707) requires batch processing the document token vectors to find centroids. This centroid selection would not work well in a real-time setting where our users expect outstanding performance from document number one to billions of documents. With Vespa, users can use different retrieval mechanisms and still enjoy the power of ColBERT in ranking phases.

>How does ColBERT relate to Vespa’s support for nearestNeighbor search? 

>It does not directly relate to Vespa’s [nearestNeighbor](https://docs.vespa.ai/en/nearest-neighbor-search.html) support. The nearestNeighbor search operator could be used to retrieve hits in the first stage of a ranking pipeline and where ColBERT is used in a [second-phase](https://docs.vespa.ai/en/phased-ranking.html) expression. Vespa’s native embedders map text to a tensor representation, which can be used in ranking; independent of the query retrieval formulation.

>Can you clarify if it is also usable for the full end-to-end retrieval without additional embeddings or re-ranker afterwards?

The ColBERT-v1 and v2 are both multi-phase pipelines, not a single-stage ranker like BM25 or a single-vector embedding model. With so many different models supported for efficient retrieval in Vespa, we did not expose the retrieval stage. I

It can be implemented, but at a much higher cost, by building index structures for retrieval. 

The follow-up [announcement](https://blog.vespa.ai/announcing-long-context-colbert-in-vespa/) demonstrated great results running Colbert as a ranking model on top of candidates retrieved by BM25.

**Comment by jens-totemic** [comment]
Thank you @jobergum for your quick response! 

Sorry, I'm very new to Vespa and I'm still trying to understand its architecture. Based on your explanations, is the recommended approach then to use Colbert as the re-ranker after a first stage using e.g. a regular embedding? Or is there also a possibility to use let's say a "Colbert-like" approach in the first stage - meaning not using the PLAID storage but just the basic idea of Colbert with one embedding per token, stored using Vespa's native indexing mechanisms. Basically I'd like to benefit of the full end-to-end pipeline but I'm pretty flexible about how the token embeddings are actually stored.

**Comment by jobergum** [comment]
Hey @jens-totemic, 

> based on your explanations, is the recommended approach then to use Colbert as the re-ranker after a first stage using e.g. a regular embedding?

You can use vanilla BM25 in Vespa without an additional single-vector text embedding model. Depending on your data and use case. In [colbert](https://github.com/vespa-engine/sample-apps/tree/master/colbert) we demonstrate with using a single vector text embedding model for retrieval. In [colbert-long](https://github.com/vespa-engine/sample-apps/tree/master/colbert-long) we use BM25. 

Also, depending on the number of documents you want to search over and your query throughput scale, it's possible to simply rank all documents in the collection using colbert. Meaning there is no shortlisting/retrieval stage. Just rank all documents matching the filters. 

```
vespa query 'yql=select * from doc where true'\
 'input.query(qt)=embed(colbert, @query)' 
```

**Comment by jobergum** [comment]
I'm resolving this, feel free to re-open if you have further questions on colbert. We also have a slack space linked to from https://vespa.ai/support
