### ISSUE TITLE
Performance of vespa

### ISSUE THREAD

**Issue by misslorac** [vespa-engine/vespa#30714]
I haven't seen a full performance test and it's not clear exactly how the vespa performs. I noticed that manticoresearch claims it performs dozens of times faster than elasticsearch, so how about vespa? Also, I've noticed that both vespa, and elasticsearch, use DaaT for their searches, obtaining a document per iteration and scoring it, which is what the vast majority of search engines do. However, I noticed that manticoresearch is fetching documents one batch at a time in an iteration, about 32 of them, so doc id and term frequency are unpacked a batch at a time, I'm not sure if this improves performance significantly, does vespa have a plan to do this?

**Comment by bratseth** [comment]
If you are interested in performance I suggest reading https://docs.vespa.ai/en/performance/practical-search-performance-guide.html - it's a too big topic to cover here.

Some other comments:
- DaaT enables ranking functions which are non-linear over the query items, is often necessary to produce the desired relevance/behavior.
- For text fields searched with multiple terms specifically, Vespa by default uses a WAND operator, which does its own early dropping based on item-internal linear ranking (same with Elastic). The whole DaaT/TaaT distinction on the word level really became obsolete with the invention of WAND imo.
- For general, cases where early dropping of documents for performance is more important than non-linear ranking across fields, Vespa provides [match-phase](https://docs.vespa.ai/en/reference/schema-reference.html#match-phase).

**Comment by misslorac** [comment]
> * For text fields searched with multiple terms specifically, Vespa by default uses a WAND operator, which does its own early dropping based on item-internal linear ranking (same with Elastic). The whole DaaT/TaaT distinction on the word level really became obsolete with the invention of WAND imo.

It seems vespa has implemented WAND instead of BlockMax WAND according to the [code](https://github.com/vespa-engine/vespa/tree/master/searchlib/src/vespa/searchlib/queryeval/wand)?   Since BlockMax WAND has been a default in elasticsearch since [2019](https://www.elastic.co/cn/blog/faster-retrieval-of-top-hits-in-elasticsearch-with-block-max-wand), while BlockMax WAND is several times faster than WAND but requires the index posting to store some extra impact score at a block level. As a result, have you evaluate the performance of WAND compared with that from other alternatives?

**Comment by bratseth** [comment]
We could likely get some small boost from that, but once you get the early drop from WAND this just isn't a large part of the total resource usage of queries in real applications. Most of those find that Vespa is faster for other reasons such as moving away from the multi-segment approach to approach realtime indexing a decade ago.
