### ISSUE TITLE
Add secondPhase/globalPhase ranking features

### ISSUE THREAD

**Issue by andreer** [vespa-engine/vespa#30722]
**Is your feature request related to a problem? Please describe.**
Result from first phase ranking is available as firstPhase ranking feature. But result from second phase and global phase is not.

With global phase, secondPhase score is not necessarily the one output in the results. But getting this value as an output feature, or input to global phase, can be valuable. Same with globalPhase in case the final relevance score is determined by custom result processing code.

**Describe the solution you'd like**
Make these available as secondPhase and globalPhase rank features.

**Describe alternatives you've considered**
Can define the firstPhase or globalPhase expressions in a function and use this.

**Comment by geirst** [comment]
The `secondPhase` rank feature is available in Vespa 8.344.63.
Documentation: https://docs.vespa.ai/en/reference/rank-features.html#secondPhase
PRs: https://github.com/vespa-engine/vespa/pull/31227, https://github.com/vespa-engine/system-test/pull/3941

We concluded that `globalPhase` is of less interest as it is the last rank phase. This feature hasn't been implemented at this point.
