### ISSUE TITLE
Short form for indexed tensors representing binary data requires "values" 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#30738]
From [doc](https://docs.vespa.ai/en/reference/document-json-format.html#tensor) 

> Short form for indexed tensors representing binary data (with int8 cell value type): May use a string with a hex dump of the cell values:

>"tensorfield": "FF00118022FE"
>can be used to represent the value tensor<int8>(x[6]):[-1,0,17,-128,34,-2].

But this fails

```
{ "put": "id:doc:doc::1", "fields": {"tensorfield":"FF00118022FE"}}
```

```
feed: got status 400 ({"pathId":"/document/v1/doc/doc/docid/1","message":"Error in document 'id:doc:doc::1' - could not parse field 'tensorfield' of type 'tensor<int8>(x[6])': Expected class 'com.yahoo.document.datatypes.TensorFieldValue', got 'java.lang.String'.: Expected class 'com.yahoo.document.datatypes.TensorFieldValue', got 'java.lang.String'."}) for put id:doc:doc::1: not retryable
```

However, the legacy format works.

```
{ "put": "id:doc:doc::1", "fields": {"tensorfield": { "values": "FF00118022FE"}}}
```

```
vespa document get id:doc:doc::1
{
    "pathId": "/document/v1/doc/doc/docid/1",
    "id": "id:doc:doc::1",
    "fields": {
        "tensorfield": {
            "type": "tensor<int8>(x[6])",
            "values": [
                -1,
                0,
                17,
                -128,
                34,
                -2
            ]
        }
    }
}
```

**Comment by geirst** [comment]
Please also add a system test.

**Comment by geirst** [comment]
The documentation should also be updated to include details on hex value support for vectors of type bfloat16, float, double. The bit representation of a single value should be part of these details (e.g. `java.lang.Float.intBitsToFloat()` and `java.lang.Double.longBitsToDouble()` is used).

**Comment by arnej27959** [comment]
this should work in most contexts now.
