### ISSUE TITLE
No 'input' query param when use "vespa query yql=xxx"

### ISSUE THREAD

**Issue by zshnb** [vespa-engine/vespa#30907]
**Describe the bug**
try to use vespa query 'yql=select * from sources * where true' to get all documents, but get error

No 'input' query param

**To Reproduce**
1. using docker start vespa
2. vespa query 'yql=select * from sources * where true'
3. See error

**Expected behavior**
output all documents

**Screenshots**
<img width="1342" alt="image" src="https://github.com/vespa-engine/vespa/assets/17894980/c2e83c9e-5186-4141-a131-fd90acc2275d">

**Environment (please complete the following information):**
 - OS: MacOS
 - Infrastructure: self-hosted
 - Versions 14.4.1

**Vespa version**
8.328.24

**Additional context**
none

**Comment by jobergum** [comment]
This is because you are using a sample app that expects that there is a query input passed in `input` and that rejects the request if it's not present.  You can run your query by passing the search chain and use the build in `vespa` chain. Add  `searcChain=vespa`

**Comment by jobergum** [comment]
https://github.com/vespa-engine/sample-apps/blob/master/text-image-search/src/main/java/ai/vespa/example/TextEmbeddingSearcher.java

**Comment by thomasht86** [comment]
Did you sort this out? 
Here is the reference to [searchChain](https://docs.vespa.ai/en/reference/query-api-reference.html#searchchain)
[Here](https://github.com/vespa-engine/sample-apps/blob/d2d111710713bce620cf2c2faafdc01be73a56b6/text-image-search/src/main/application/services.xml#L15), you can see that this app is using `mychain` which directs query to `TextEmbeddingSearcher`, which needs `input` as a paremeter.

**Comment by zshnb** [comment]
yes I've solve this
