### ISSUE TITLE
Potential Memory Leak Issue in PrometheusModel class

### ISSUE THREAD

**Issue by niharmaheshwari** [vespa-engine/vespa#30927]
**Describe the bug**
There seems to be a memory leak caused because of the class : `metrics-proxy/src/main/java/ai/vespa/metricsproxy/metric/model/prometheus/PrometheusUtil.java
`
Whenever a request to the prometheus metrics endpoint is made, this class execution results in the creation of ~400K objects which seem to stay in memory and the garbage collection for these objects does not happen in a timely manner. As a result whenever a new request comes in, the heap usage keeps on increasing which leads to the services eventually running out of heap space.

What we observe is that even the 2nd consecutive request made to the endpoint results in a OOM issue.

**To Reproduce**
1. Used a custom application that uses vespa for search.
2. Hit the `prometheus/v1/values` endpoint at regular intervals of 1 min
3. The metrics-proxy service eventually runs OOM
4. We see that we additionally run out of disk space as well due to the flooding of `opt/vespa/var/crash` folder with multiple `.hprof` files generated for each OOM occurrence. 

**Expected behavior**
The `prometheus/v1/values` endpoint consistently responds with the correct response without an OOM.

**Environment (please complete the following information):**
 - OS: linux [ rhel 8 ]
 - Infrastructure: self hosted on podman containers
 - Versions : 8.270.8

**Vespa version**
8.270.8

**Additional context**
Discussed the issue over slack as well.

**Comment by baldersheim** [comment]
Memory footprint somewhat reduced in https://github.com/vespa-engine/vespa/pull/30928

**Comment by baldersheim** [comment]
Probably not a leak. It was probably still executing the first request when the second came in.
Thois should have been fully streamed. I will see if that is possible.

**Comment by baldersheim** [comment]
With #30936 prometheus format is generated in a streaming fashion. Each MetricFamily is fully generated before processing to the next. Prometheus format should now have the same footprint as the other formats.
This will be part of 8.332.5
