### ISSUE TITLE
Node coming up with latest deployed application version after being down

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#30937]
**Describe the bug**
Is there a way we can ensure that when a node which was down during the last application deployment comes back up, it gives a healthy response only if it is able to come back up with the latest deployed version in the Vespa cluster and not with the version that it was running on when it went down. 
We would ideally want it to give an unhealthy response if it is unable to run with the latest vespa version. 

While deploying our application, we check if all the nodes have the correct version before marking our deployment successful. With this behavior we will be able to deploy even with few nodes down since once the node comes back up it will run with the latest version. 

**Environment (please complete the following information):**
 - Infrastructure: Podman

**Vespa version**
8.294.50

**Comment by kkraune** [comment]
Great question! you will be monitoring https://docs.vespa.ai/en/operations-selfhosted/monitoring.html#/state/v1/health

When nodes come up again, they will get the latest config from the config server. There are ways to inspect detailed config, see https://docs.vespa.ai/en/operations-selfhosted/config-proxy.html#inspecting-config - I have not seen teams using this, though, it is maybe on a too detailed level.

As long as the nodes query the same set of config servers, they will start using the most recent config, and /state/v1/health will be OK once started.

**Comment by bratseth** [comment]
You can also use the [convergence API](https://docs.vespa.ai/en/application-packages.html#convergence) to check when the deployment is complete.

**Comment by 107dipan** [comment]
@bratseth - We are currently using the convergence API to check the same. But if one node is down during application deployment our deployment is marker failed since the convergence API return it returns false. 
If it is guaranteed that whenever a down node comes back up, it shows healthy only with the latest deployed application we can ignore the result from the convergence API when one of the nodes is down since it is guaranteed that node will come back up with the latest.

**Comment by bratseth** [comment]
Yes, that is guaranteed.
