### ISSUE TITLE
Configurable max token length

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#30942]
If clients feed very long tokens, or long text in fields without tokenization (match:exact/word), Vespa will produce an index containing them which is wasteful and possibly damaging.

- Add a max token length configuration.
- Set a reasonable default.

**Comment by geirst** [comment]
This is available in Vespa 8.342.10.

- The default `max-token-length` is 1000 (characters). Longer tokens are silently ignored, and will not be part of the index.
- Configurable per field: https://docs.vespa.ai/en/reference/schema-reference.html#max-token-length.
