### ISSUE TITLE
Add deploy time warning about combining paged attributes with index (hnsw) or fast-search

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#31056]
People don't read [paged-attributes-disadvantages](https://docs.vespa.ai/en/attributes.html#paged-attributes-disadvantages) and we keep re-iterating why `paged` doesn't play well in combination with `index`. 

Suggestion - add deploy time warning when schema has any of:

- Fields that combine `paged` with `fast-search` 
- Fields that combine `paged` with `index` (for type tensor fields)

Optional:
- See if any `paged` attributes are used in first-phase ranking expressions where there is no enforced limit on number of documents that are evaluated.

**Comment by geirst** [comment]
Fields that combine `paged` with a HNSW index results in a warning in Vespa 8.362.16 and later (https://github.com/vespa-engine/vespa/pull/31627). The warning links to https://docs.vespa.ai/en/attributes.html#paged-attributes-disadvantages.

Fields that combine `paged` with `fast-search` are fine, as the memory used for the inverted index is **_not_** paged. Only the raw attribute data is.
