### ISSUE TITLE
Unable to install Vespa version 8.334.22, dependencies not found

### ISSUE THREAD

**Issue by yriveiro** [vespa-engine/vespa#31083]
**Describe the bug**
Vespa version 8.334.22 rpm is pointing to non-existing version of packages `jllama` and `onnxruntime`

**To Reproduce**
1. Install Vespa
```sh
[root@33a062b3c536 ffuser]# microdnf install -y --nobest vespa-8.334.22
error: Could not depsolve transaction; 1 problem detected:
 Problem: package vespa-8.334.22-1.el9.x86_64 from vespa-farfetch-rpm-epel requires vespa-libs = 8.334.22-1.el9, but none of the providers can be installed
  - conflicting requests
  - nothing provides vespa-jllama = 3.0.0 needed by vespa-libs-8.334.22-1.el9.x86_64 from vespa-farfetch-rpm-epel
  - nothing provides vespa-onnxruntime = 1.17.1 needed by vespa-libs-8.334.22-1.el9.x86_64 from vespa-farfetch-rpm-epel
```
2.  As we can see the only available version is 1.17.3 and not 1.17.1 for `onnxruntime` and 3.0.1 for `jllama`
```sh
[root@33a062b3c536 ffuser]# microdnf repoquery vespa-onnxruntime
vespa-onnxruntime-1.17.3-1.el9.src
vespa-onnxruntime-1.17.3-1.el9.x86_64

[root@33a062b3c536 ffuser]# microdnf repoquery vespa-jllama
vespa-jllama-3.0.1-1.el9.src
vespa-jllama-3.0.1-1.el9.x86_64
vespa-jllama-3.0.1-2.el9.src
vespa-jllama-3.0.1-2.el9.x86_64

```
3. Reviewing the spec file of Git tag 8.334.22, indeed the packages required are the ones miss.

https://github.com/vespa-engine/vespa/blob/624c19d3e1dc81e81bd1384e5293fd6f140d23a6/dist/vespa.spec#L209

**Expected behavior**
`microdnf install -y vespa` install Vespa without errors

**Screenshots**

**Environment (please complete the following information):**
 - OS: Almalinux
 - Infrastructure: Docker
 - Versions: 9.3

**Vespa version**
 8.334.22

**Comment by hmusum** [comment]
Vespa 8.337.85 is out now, dependencies seem to be updated and resolve correctly:

`# rpm -qa | grep -E 'vespa-8|llama|onnx'
vespa-onnxruntime-1.17.3-1.el8.aarch64
vespa-8.337.85-1.el8.aarch64
vespa-jllama-3.0.1-2.el8.aarch64`
