### ISSUE TITLE
Sort ASC by a field should give those results without that field value

### ISSUE THREAD

**Issue by nehajatav** [vespa-engine/vespa#31106]
**Describe the bug**
Currently none of sort ascending and sort descending are giving the right result

**To Reproduce**
Add doc1 with field f1 as a, 
add doc2 with field f1 as b,
add doc3 with field f1 missing

**Expected behavior**
Ascending should give order 
doc3,doc1, doc2

**Comment by baldersheim** [comment]
You have to provide the schema definition, 3 documents and the query.
This is ancient functionality that see extensive use, so you must provide something reproducible.

**Comment by nehajatav** [comment]
If the field is long then?

**Comment by bjormel** [comment]
If the field is unset for a document, the sort value for that document will be lower than the value for any other document with a value set. 
See [Quick Start, using Docker](https://docs.vespa.ai/en/vespa-quick-start.html), for an easy way to experiment with Vespa at a small scale.

If you need another behaviour you can use a document processor to set a value when it is missing when ingesting data.
See [Fields](https://docs.vespa.ai/en/documents.html#fields)
> A field can not be defined with a default value. Use a [document processor](https://docs.vespa.ai/en/document-processing.html) to assign a default to document put/update operations.

**Comment by baldersheim** [comment]
Correct, if you sort ascending unset document will come first, descending it will come last.

**Comment by baldersheim** [comment]
This is not something that we can change without a major version, and it is not clear what is correct either.

**Comment by baldersheim** [comment]
Or is it ? @bratseth could we change this so sorting on unset values always sorted last, similar to what we do for NaN rank ?

**Comment by bratseth** [comment]
I would say people shouldn't reasonably depend on this.
But that said, lots of people ask for ways to find documents with an unset value of some field. We have never told them about this way of doing it (as far as I know), but maybe some found it by themselves?
