### ISSUE TITLE
Inheritable rank-profile inputs 

### ISSUE THREAD

**Issue by mziv** [vespa-engine/vespa#31488]
It would be rad if inputs could be inherited in the same way `summary-features` and `match-features` are inherited between rank profiles. We have some queries with a lot of inputs, and copy-pasting them between rank-profiles is verbose. As far as I can tell this isn't currently supported - would love for that to be the case!

**Comment by bratseth** [comment]
Hi Maya. Rank profiles does inherit the inputs of its inherited profiles, was there anything specific that led you to conclude otherwise?

**Comment by mziv** [comment]
Apologies, I should have been more specific - specifically being able to inherit the inputs of a parent rank profile and then define additional inputs for the child rank profile is what I'd love to be able to do. For instance, if I have rank profiles like:

```
rank-profile A {
	inputs {
		query(a) float: 0.0
    }

	summary-features {
        closeness(field1)
   }
}

rank-profile B inherits A {
	inputs inherits A {
        # query(a) still accepted
		query(b) float: 0.0
    }

    summary-features inherits A {
        # closeness(field1) is still output
        closeness(field2)
    }
}
```

Right now, as far as I can tell, this behavior is supported for summary-features, but is not for inputs. At least, when I try to define `inherits` on the inputs field, I get an error. 

Very possible I'm mistaken and inputs actually isn't overridden, in which case it might be nice to add a note about that in the [rank-profile inheritance](https://docs.vespa.ai/en/schemas.html#rank-profile-inheritance) section of the documentation.

Thanks so much!

**Comment by bratseth** [comment]
The inputs are always inherited from an inherited profile so there's no need for an explicit inherits.
This is because I don't think it makes sense to remove or any of them in a child profile since other parts of the profile which are also inherited will depend on them. Stuff like summary-features are different - nothing else in the profile depends on it so it makes sense to make them redefinable in child profiles.

**Comment by mziv** [comment]
Ah okay wonderful, so this is just me misreading documentation! Thanks so much for clarifying - I'll put up a PR to clarify that on the page I was looking at. :) Cheers!
