### ISSUE TITLE
Unable to set top-k-probability as 1.0

### ISSUE THREAD

**Issue by adityaverma21** [vespa-engine/vespa#31638]
**Describe the bug**
Unable to set top-k-probability as 1.0
**To Reproduce**
1. Added this in services.xml in content section

        <tuning>
            <dispatch>
                <top-k-probability>1.0</top-k-probability>
            </dispatch>
        </tuning>

2. Deployed the application
3. Checked the top-k-probability with this command 
**vespa-get-config -n vespa.config.search.dispatch -i feed/component/dispatcher.doc | grep topKProbability**
Still getting 0.9999

**Expected behavior**
top-k-probability should be updated

**Environment (please complete the following information):**
 - RHEL8
 - Podman

**Vespa version**
8.221.29

**Comment by baldersheim** [comment]
I tried to reproduce, but failed.
This is the definition of my content and container cluster and 
```
<content id="mycluster" version="1.0">
  <tuning>
       <dispatch>
         <top-k-probability>1.0</top-k-probability>
       </dispatch>
      </tuning>
....
<container id="mycc" version="1.0">
   <search/>
....
```

Then I run 2 commands to verify, first to verify top-k-probability, and then to verify that I have nodes just to ensure that I have used the correct config id.
`vespa-get-config -n vespa.config.search.dispatch -i **mycc**/component/dispatcher.**mycluster**`
```
minActivedocsPercentage 97
distributionPolicy "ADAPTIVE"
maxHitsPerNode 2147483647
topKProbability 1
redundancy 2
minSearchCoverage 100
minWaitAfterCoverageFactor 0
maxWaitAfterCoverageFactor 1
numJrtTransportThreads 8
numJrtConnectionsPerNode 8
warmuptime 5
summaryDecodePolicy "EAGER"
```
[balder@6a83fa79a024 java-dispatch]$ vespa-get-config -n vespa.config.search.dispatch-nodes -i ```
mycc/component/dispatcher.mycluster
node[0].key 0
node[0].group 0
node[0].host "6a83fa79a024"
node[0].port 19109
node[1].key 1
node[1].group 0
node[1].host "6a83fa79a024"
node[1].port 19121
node[2].key 2
node[2].group 0
node[2].host "6a83fa79a024"
node[2].port 19133
```

**Comment by adityaverma21** [comment]
`<content id="mydoc" version="1.0">
<redundancy>1</redundancy>
<engine>
<proton>
<resource-limits> </resource-limits>
<searchable-copies>1</searchable-copies>
<tuning>
<searchnode>
<feeding>
<concurrency>1.0</concurrency>
</feeding>
<requestthreads>
<search>8</search>
<persearch>4</persearch>
<summary>4</summary>
</requestthreads>
<flushstrategy>
<native>
<component>
<maxage>86400</maxage>
</component>
</native>
</flushstrategy>
</searchnode>
</tuning>
<sync-transactionlog>true</sync-transactionlog>
</proton>
</engine>
<tuning>
<cluster-controller>
<transition-time>3600</transition-time>
</cluster-controller>
<min-node-ratio-per-group>1</min-node-ratio-per-group>

<dispatch>
<top-k-probability>1.0</top-k-probability>
</dispatch>
</tuning>
<documents>
...
</documents>
</content>`

**Comment by baldersheim** [comment]
This is still working for me, you need to provide a complete services.xml and exact command and output that you run to verify it, including the2 I ran above.

**Comment by adityaverma21** [comment]
Complete services.xml
`<services xmlns:deploy="vespa" xmlns:preprocess="properties" version="1.0">
<admin version="2.0">
<adminserver hostalias="dev1-hot-config-0"/>
<configservers>
<configserver hostalias="dev1-hot-config-0"/>
</configservers>
<logserver hostalias="dev1-hot-config-0"/>
<cluster-controllers>
<cluster-controller hostalias="dev1-hot-config-0"/>
</cluster-controllers>
<slobroks>
<slobrok hostalias="dev1-hot-config-0"/>
</slobroks>
</admin>

<container id="default" version="1.0">
<http>
<server port="8080" id="main-server">
<config name="jdisc.http.connector">
<tcpNoDelay>false</tcpNoDelay>
</config>
</server>
</http>
<document-api/>
<search>
<threadpool>
<max-threads>6</max-threads>
<min-threads>4</min-threads>
<queue-size>0</queue-size>
</threadpool>
<config name="container.qr-searchers">
<tag>
<bold>
<open><b></open>
<close></b></close>
</bold>
<separator>...</separator>
</tag>
</config>
</search>
<nodes>
<jvm options="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=0.0.0.0 -Djavax.net.ssl.trustStore=/vespa-db/vespa/jdk-11-lts-11.0.6.b8/lib/security/cacerts" allocated-memory="50%"/>
<node hostalias="dev1-hot-config-0"/>
</nodes>
</container>

<content id="contentdoc" version="1.0">
<redundancy>1</redundancy>
<engine>
<proton>
<resource-limits> </resource-limits>
<searchable-copies>1</searchable-copies>
<tuning>
<searchnode>
<feeding>
<concurrency>1.0</concurrency>
</feeding>
<requestthreads>
<search>8</search>
<persearch>4</persearch>
<summary>4</summary>
</requestthreads>
<flushstrategy>
<native>
<component>
<maxage>86400</maxage>
</component>
</native>
</flushstrategy>
</searchnode>
</tuning>
<sync-transactionlog>true</sync-transactionlog>
</proton>
</engine>
<tuning>
<cluster-controller>
<transition-time>3600</transition-time>
</cluster-controller>
<min-node-ratio-per-group>1</min-node-ratio-per-group>

<dispatch>
<top-k-probability>1.0</top-k-probability>
</dispatch>
</tuning>
<documents>
<document type="test" mode="index"/>
</documents>
<group name="contentDoc-group">
<distribution partitions="*"/>
<group name="group0" distribution-key="0">
<node hostalias="dev1-hot-content-0" distribution-key="0"/>
</group>
</group>
</content>
</services>`
