### ISSUE TITLE
Vespa feed not throttling enough during slow ingestion

### ISSUE THREAD

**Issue by viantirreau** [vespa-engine/vespa#31798]
Hi Vespa Team,
I'm currently experimenting with embedding long documents at feed time, both with colbert and a dense embedding model using `vespa feed` and a JSONL dataset. I sorted this dataset by ascending length, so that smaller documents are quickly processed at first and it gets progressively slower as the rows are fed. The thing is eventually the processing gets quite slow (using CPU at the moment), and the feed utility enters some kind of "desperate" mode. It tries to feed documents but as it gets a 429 error, it immediately retries with all the documents in the queue in a never ending fashion, consuming even more resources and finally halting the ingestion completely. 

![imagen](https://github.com/vespa-engine/vespa/assets/42223959/812a6da4-da1b-4b7f-82cb-f224251fd77e)
(the lines are scrolling like crazy in this screenshot)

I noticed that feeding a small file of 10-50 documents with similar length to the ones that get rejected by 429s, is able to get completely processed, slowly, but it finishes after all without triggering errors.
My first instinct was to limit the number of connections to just one to not overload the server, but with the full dataset this still goes into panic mode and brings the progress to a stop.

When I fed the small file, I noticed that the average processing rate was e.g. 0.75 docs/s, so I switched from a command along the lines of 
```bash
vespa feed --progress 10 --connections 1 --verbose feed_file.jsonl
```
to reading the dataset from STDIN and limiting the speed at which lines are ingested by `vespa feed` with a perl one-liner I found in [StackOverflow](https://superuser.com/a/526249):
```bash
perl -pe "system 'sleep 1'" feed_file.jsonl | vespa feed --progress 10 --connections 1 --verbose -
```
The first command before the `|` pipe just prints one line per second, and lo and behold, `vespa feed` takes a lot longer to enter panic mode and retry after 429s start appearing. A premature sign that this was going to happen was that the `feeder.inflight.count` kept increasing due to the ingestion of 1 document per second, but the processing taking ever so slightly longer. 
Because the average rate at this document length is closer to 0.75 docs/s, I increased the `perl` sleep to `1.33` seconds and it worked flawlessly, processing the dataset in its entirety without ever entering the retry loop.

![imagen](https://github.com/vespa-engine/vespa/assets/42223959/e142d4eb-a416-477c-98ba-64c4e67c2e48)
... and after several minutes, still zero errors ...
![imagen](https://github.com/vespa-engine/vespa/assets/42223959/aeeb6e58-65a2-452d-b23b-1d3356c44738)

Is there any native way of limiting the "hammering" of 429s to prevent the processing from halting?

Thanks in advance!

**Comment by mpolden** [comment]
`vespa feed` has an automatic throttling mechanism which should take 429s into account, and throttle accordingly. We'll look into it.

**Comment by mpolden** [comment]
Great!
