### ISSUE TITLE
Support dumping documents from 1 content node

### ISSUE THREAD

**Issue by dainiusjocas** [vespa-engine/vespa#31827]
**Is your feature request related to a problem? Please describe.**

I have a Vespa deployment with ~a billion of documents spread among ~20 content nodes and I need to evaluate can we (or what would it take to) support search by image feature (think CLIP embeddings) with the current set of hardware (on prem setup, 1 type of available servers).

My thinking is that search latencies of ANN with filters depend a lot on data distribution in an individual content node. I want to leverage the fact that in Vespa one content node gets as many requests as all the others content nodes in a group. So, if one content node can support X RPS, then a content group can support X RPS.

**Describe the solution you'd like**
My life would be easy (working with ~50M docs instead of 1B) if could just take a snapshot of all docs from one content node, attach image embeddings, store docs on some similarly sized 1 Vespa content node, and run some perf tests to get average latencies (I’m aware about running multiple threads per search and its impact for latency/resources) and other metrics. Having that I could extrapolate the results to the need for hardware.

**Describe alternatives you've considered**
One approach I also consider is to run visiting with 20 slices and take only slice 0. But that would produce not an exact data distribution. Another approach I've considered is to leverage the `[model.searchPath](https://docs.vespa.ai/en/reference/query-api-reference.html#model.searchpath)` and get docs from one content node but I have too many documents per content node.

**Additional context**
Slack [discussion](https://vespatalk.slack.com/archives/C01QNBPPNT1/p1719952935681529).

**Comment by baldersheim** [comment]
You should just get 1/20th of the corpus and worry about which node it came from. The distribution well defined, but unspecified.

However that is a tiny issue compared to your task at hand. ANN is hard to benchmark and reason over.
ANN cost can be considered as a fixed cost, close to independent of corpus size on the node. The ideal solution is to a single large node with all the 1B docs with only the ANN data. The query cost for the ANN part will be approximately the same on a 1B node as on a 50M node.
This holds as long as you are not applying any filters. If you apply filters there is a linear component.
But this is inherently hard to find an efficiently sized setup.

Good luck :)

**Comment by dainiusjocas** [comment]
Thanks!

Unfortunately, filters are unavoidable with most of my use cases. Also, 1B docs to embed for an experiment is a bit too much.

What about the visiting for a particular content node functionality support? Should we expect it arriving at some time in the future, or this is from the series of "very nice to have" that it would be a waste to work on?

**Comment by baldersheim** [comment]
Having that as a supported feature is not worth the effort. So highly unlikely that it will be implemented.

**Comment by vekterli** [comment]
Vespa will by default distribute documents pseudo-randomly and—most importantly—uniformly across nodes using hashing. This means that statistically speaking the contents of 1 content node out of 20 represents a uniformly randomly sampled unspecified subset of an 1/20 of the document corpus. But this property should also hold if you just visit 1/20 of the corpus directly—it's just a different subset (with very high probability).

So if you're just looking for a representative sample of 1/20 of your corpus, sliced visiting should give you what you're looking for. Please let me know if you have any other specific use cases where the exact document set of a particular content node is useful.

**Comment by dainiusjocas** [comment]
I'm happy with the answers. Thanks a lot!

**Comment by jobergum** [comment]
Thanks @dainiusjocas, resolving this - thanks for the discussion.
