### ISSUE TITLE
Namespace, document type support in container feed metrics

### ISSUE THREAD

**Issue by buinauskas** [vespa-engine/vespa#31837]
**Is your feature request related to a problem? Please describe.**

Vespa containers expose minimal information about [feeding metrics](https://docs.vespa.ai/en/reference/container-metrics-reference.html) in Prometheus format:
```
# HELP feed_latency_count 
# TYPE feed_latency_count untyped
feed_latency_count{metrictype="standard",instance="container",status="OK",api="documentV1",operation="REMOVE",clustername="feed",vespa_service="vespa_container",} 11.0 1720056501838
feed_latency_count{metrictype="standard",instance="container",status="OK",api="documentV1",operation="PUT",clustername="feed",vespa_service="vespa_container",} 13.0 1720056501838
# HELP feed_latency_sum 
# TYPE feed_latency_sum untyped
feed_latency_sum{metrictype="standard",instance="container",status="OK",api="documentV1",operation="REMOVE",clustername="feed",vespa_service="vespa_container",} 0.034 1720056501838
feed_latency_sum{metrictype="standard",instance="container",status="OK",api="documentV1",operation="PUT",clustername="feed",vespa_service="vespa_container",} 0.036 1720056501838
# HELP feed_operations_rate 
# TYPE feed_operations_rate untyped
feed_operations_rate{metrictype="standard",instance="container",status="OK",api="documentV1",operation="REMOVE",clustername="feed",vespa_service="vespa_container",} 0.18333333333333332 1720056501838
feed_operations_rate{metrictype="standard",instance="container",status="OK",api="documentV1",operation="PUT",clustername="feed",vespa_service="vespa_container",} 0.21666666666666667 1720056501838
```

It's impossible to plot feed rate per namespace or document type at the vespa level, meaning the only way to do so is at the application level. I was trying to build Grafana dashboards to compare feeding rates at the application level and the vespa but that was not possible, the only way to do so was to compare totals.

**Describe the solution you'd like**

feed-related metrics to expose namespace and document type labels, which are usually fairly stable labels with low cardinality, meaning they should not overwhelm the Prometheus metric store.

**Describe alternatives you've considered**

Track such metrics at the application client level.

**Comment by kkraune** [comment]
Ola, is this a matter of using the "consumer" parameter?

**Comment by olaaun** [comment]
https://docs.vespa.ai/en/reference/prometheus-v1.html#request-parameters

The consumer parameter specifies which set of metrics will be returned. You'll get a more complete metric set if you use the `Vespa` consumer. The set should include the metric `documents_processed_rate`, which is the number of documents processed per document type. We do not have anything per namespace AFAICT.

You can also define your own [consumer](https://docs.vespa.ai/en/reference/services-admin.html#metrics)

**Comment by buinauskas** [comment]
Hey, I think that `documents_processed_rate` should do the trick, it contains the document type which is what I am after, thank you!
