### ISSUE TITLE
tensor<bfloat16>(t{}, x[1024]) query VespaError tensor query(q_colbert) must have exactly 1, indexed dimension, but was: tensor<bfloat16>(qt{},x[1024])

### ISSUE THREAD

**Issue by jiangsiYang** [vespa-engine/vespa#31848]
# .sd
schema act_tag {
    document act_tag {
        field act_id type string {
            indexing: summary
        }
        field text type string {
            indexing: summary | index
            index: enable-bm25
        }
        field lexical_rep type tensor<bfloat16>(t{}) {
            indexing: summary | attribute
        }
        field dense_rep type tensor<bfloat16>(x[1024]) {
            indexing: summary | attribute
            attribute {
                distance-metric: angular
            }
        }
        field colbert_rep type tensor<bfloat16>(t{}, x[1024]) {
            indexing:  attribute | summary
            attribute {
                distance-metric: angular
            }
        }
    }
    fieldset default {
        fields: text
    }
    rank-profile m3hybrid {
        inputs {
            query(q_dense) tensor<bfloat16>(x[1024])             
            query(q_lexical) tensor<bfloat16>(t{})             
            query(q_colbert) tensor<bfloat16>(qt{}, x[1024])             
            query(q_len_colbert) float             
        
        }
        function dense() {
            expression {
                cosine_similarity(query(q_dense), attribute(dense_rep),x)
            }
        }
        function lexical() {
            expression {
                sum(query(q_lexical) * attribute(lexical_rep))
            }
        }
        function max_sim() {
            expression {
                sum(reduce(sum(query(q_colbert) * attribute(colbert_rep) , x),max, t),qt)/query(q_len_colbert)
            }
        }
        first-phase {
            expression {
                0.4*dense + 0.2*lexical +  0.4*max_sim
            }
        }
        match-features {
            dense
            lexical
            max_sim
            bm25(text)
        }
    }
}

#start query
from FlagEmbedding import BGEM3FlagModel

#To use this model on the CPU we set use_fp16 to False, for GPU inference, it is recommended to use use_fp16=True for accelerated inference.
model = BGEM3FlagModel("BAAI/bge-m3", use_fp16=False)

query = ["BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction."]
query_embeddings = model.encode(
    query, return_dense=True, return_sparse=True, return_colbert_vecs=True
)

query_length = query_embeddings["colbert_vecs"][0].shape[0]

colbert_vecs = query_embeddings["colbert_vecs"][0]

q_colbert = {
    str(index): vec.tolist()
    for index, vec in enumerate(colbert_vecs)
}

query_fields = {
    "input.query(q_lexical)": {
        key: float(value)
        for key, value in query_embeddings["lexical_weights"][0].items()
    },
    "input.query(q_dense)": query_embeddings["dense_vecs"][0].tolist(),
    "input.query(q_colbert)": q_colbert,
    "input.query(q_len_colbert)": query_length,
}

response: VespaQueryResponse = app.query(
    yql="select act_id, text from act_tag where ({targetHits:10}nearestNeighbor(colbert_rep,q_colbert))",
    ranking="m3hybrid",
    query=query[0],
    body={**query_fields},
)
assert response.is_successful()
print(json.dumps(response.hits[0], indent=2))

# output error,but why?
VespaError: [{'code': 3, 'summary': 'Illegal query', 'source': 'qjl_content', 'message': 'NEAREST_NEIGHBOR {field=colbert_rep,queryTensorName=q_colbert,hnsw.exploreAdditionalHits=0,distanceThreshold=Infinity,approximate=true,targetHits=10} tensor query(q_colbert) must have exactly 1, indexed dimension, but was: tensor<bfloat16>(qt{},x[1024])'}]

**Comment by jobergum** [comment]
Could you please try to format your issue better? Working end2end example here https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/mother-of-all-embedding-models-cloud.ipynb

You can only use the single dense vector representation for nearestNeighbor operator, not the colbert representation. 

>must have exactly 1, indexed dimension, but was: tensor(qt{},x[1024])

It expects just a tensor(x[1024])

**Comment by jiangsiYang** [comment]
> Could you please try to format your issue better? Working end2end example here https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/mother-of-all-embedding-models-cloud.ipynb
> 
> You can only use the single dense vector representation for nearestNeighbor operator, not the colbert representation.
> 
> > must have exactly 1, indexed dimension, but was: tensor(qt{},x[1024])
> 
> It expects just a tensor(x[1024])

thanks
