### ISSUE TITLE
Grouping with order on struct key doom query

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#32014]
From slack (my highlight):

> Here's an example of a grouping statement that works in Vespa 7:
> all(group(predefined((my_map{\"my_key\"}.struct_value,bucket(1,inf))) max(1) precision(1) order(-max(my_map{\"my_key\"}.struct_value)) each(max(1) each(output(summary()))))
> We use this pattern to pick out a subset of documents that have a certain map key from a query that does not filter on that key more generally; and order to avoid returning the group:null whose results we dont care about.
> However in Vespa 8 this fails, and does so in a way that a single such **query causes our test cluster to be marked unhealthy/unavailable**. It fails in this way even if the query has a filter condition limiting to a single document for which my_map{\"my_key\"}.struct_value exists.
> If we remove the order(...) from the grouping the problem goes away; so that's our mitigation for now.  However I wanted to check if this is a known issue, and also if there is a better way to implement this use case in Vespa 8.

**Comment by bjorncs** [comment]
From the description it sounds like the content nodes crashed. The Vespa log will likely give some clues what went wrong. Which version was this? A similar bug was fixed on 8 a while a go.

**Comment by bjorncs** [comment]
This is fixed in 8.358.34 release.
- https://github.com/vespa-engine/vespa/pull/32070
- https://github.com/vespa-engine/system-test/pull/4161

**Comment by raincoastchris** [comment]
@bjorncs can you confirm that version number? Afaict 8.358.34 predates this issue.

**Comment by bjorncs** [comment]
> @bjorncs can you confirm that version number? Afaict 8.358.34 predates this issue.

That was a typo. It's 8.385 not 8.358.
