### ISSUE TITLE
[Slack] Vespa Bot should be available in DMs (e.g. when I talk to myself)

### ISSUE THREAD

**Issue by radu-gheorghe** [vespa-engine/vespa#32137]
**Is your feature request related to a problem? Please describe.**
I want to ask Vespa Bot questions, but I don't want to spam everyone.

**Describe the solution you'd like**
When I call @Vespa Bot in a DM with myself, it should answer.

**Describe alternatives you've considered**
Tried DMing Vespa Bot directly, but it says I'm not allowed. If it replies instead, it would solve the problem for me.

**Comment by sebastiannberg** [comment]
This feature has now been added

**Comment by radu-gheorghe** [comment]
Amazing, thanks! I just started a beautiful DM friendshipt with Vespa Bot 😁
