### ISSUE TITLE
Add support for hex representation for mixed tensors in queries

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#32231]
We support [hex format](https://docs.vespa.ai/en/reference/document-json-format.html#tensor) in document JSON but not for queries. 

```json
{
    "put": "id:doc:doc::1",
    "fields": {
        "text": "To transport goods on water, use a boat",
        "embedding": {
            "0": "3DE38E393E638E393EAAAAAB",
            "1": "3EE38E393F0E38E43F2AAAAB",
            "2": "3F471C723F638E393F800000"
        }
    }
}
```
Is valid, but attempting to send this format in queries will throw a 400 bad request

```bash
vespa query 'yql=select * from doc where true' 'ranking=full' 'input.query(qt)={"0":"3DE38E393E638E393EAAAAAB"}'
```

```json
{ "errors": [
            {
                "code": 3,
                "summary": "Illegal query",
                "message": "Could not set 'ranking.features.query(qt)' to '{\"0\":\"3DE38E393E638E393EAAAAAB\"}': Could not parse '{\"0\":\"3DE38E393E638E393EAAAAAB\"}' as a tensor of type tensor<float>(querytoken{},v[3]): At value position 0: Expected a '[' but got '\"'"
            }
]}
```

**Comment by jobergum** [comment]
I still experience the same with [8.424.11]

**Comment by arnej27959** [comment]
use 'input.query(qt)={"0":3DE38E393E638E393EAAAAAB}'

**Comment by jobergum** [comment]
It's IMHO unfortunate that one then needs one format for JSON feed and one string format without quotes for queries. When I have a dict<string,string> - now I need to write a custom routine to produce a string for the query and not use the JSON representation of the dict<string,string>.

**Comment by bratseth** [comment]
Maybe we should support inputting tensors in JSON format somehow?

**Comment by jobergum** [comment]
I understand that not all tensor formats translate to something representable in JSON, but I do think that mixed tensors with one mapped dimension and one indexed dimension could.  Now I need two functions, one for feed and one for queries.

**Comment by arnej27959** [comment]
the format you wanted should work in most contexts now.
