### ISSUE TITLE
[Slack] Vespa Bot has an issue while parsing escape characters

### ISSUE THREAD

**Issue by radu-gheorghe** [vespa-engine/vespa#32281]
**To Reproduce**
I've DMed Vespa Bot with:
```
vespa query \
  "select * from music where true" \
  "ranking=rank_albums" \
  "ranking.features.query(user_profile)={{cat:pop}:0.8,{cat:rock}:0.2,{cat:jazz}:0.1}"
for this if the query is passed as body for search (rest api), where can i find how to change this into body(object specifically for ranking) ?
```

And the reply was:
```
Failed to get abstract when handling query:
```
Plus the original text.

@johansolbakken @sebastiannberg any ideas?

**Comment by sebastiannberg** [comment]
I've looked into this and it seems like the Vespa Docuementation search backend is sensitive to newlines and backticks (´) in the query

I'm looking into how we can parse it in the vespa slack bot to avoid this issue

**Comment by radu-gheorghe** [comment]
Thanks for looking into this @sebastiannberg 🙏

**Comment by johansolbakken** [comment]
This is fixed 😃

**Comment by radu-gheorghe** [comment]
Awesome, thanks! I can confirm that it works for me.
