### ISSUE TITLE
[Slack] Vespa Bot puts language (in plain text) in the code cells

### ISSUE THREAD

**Issue by radu-gheorghe** [vespa-engine/vespa#32333]
Take this question:
```
How do I write a query that searches in multiple fields? Give me an example
```

Part of the response looks like this:
-----
You have defined a schema with multiple fields, such as title, content, and tags. You can create a fieldset that includes these fields as follows:
```
xml
schema example {
    document example {
        field title type string {
            indexing: index
```
-----
Note the `xml` element at the beginning of the code snippet. Pretty much all code snippets have that kind of thing - I assume it's because OpenAI tries to render some sort of Markdown which Slack can't render (it doesn't know what to do with that `xml`).

I don't see a good solution to this other than simply removing those tags. What do you think @johansolbakken @sebastiannberg ?

**Comment by johansolbakken** [comment]
Good catch @radu-gheorghe ! We have removed the language from the output. Unfortunately, we found no support for specifying the language in Slack.

**Comment by radu-gheorghe** [comment]
That is fine. Thanks a lot for looking into it!
