### ISSUE TITLE
From sources clause not working as expected in yql

### ISSUE THREAD

**Issue by adityaverma21** [vespa-engine/vespa#32353]
**Describe the bug**
select * from sources * and select * from sources doc1, doc2 returning different results

**To Reproduce**
Difficult to reproduce. It started happening today and we started seeing issues on some queries.

**Expected behaviour**
There are only two content clusters which are doc1, doc2 but while running the query we are getting correct count only when we use *. We can see results are coming from doc2 but finding 0 docs when using select * from doc2

**Environment (please complete the following information):**
 - RHEL 8
 - Podman
 

**Vespa version**
8.332.5

**Additional context**
I have seen this issue mostly in case of multi content clusters.

**Comment by adityaverma21** [comment]
We have 2 content clusters doc1 and doc2 while querying we query like select * from doc1.*,doc2.* <query> but it’s giving 0 results whereas when we do the same query with select * from sources * its giving results.

**Comment by bratseth** [comment]
You have two content clusters with id's "doc1" and "doc2" and they have schemas named "doc1" and "doc2" respectively?

**Comment by adityaverma21** [comment]
Maybe if it helps the query is something like select * from sources * where name contains equiv(phrase(\”Stitching\”, \”Memorandum\”), phrase({stem:false}\”Stitching\”,{ stem:false}\”Memorandum\”))

**Comment by nehajatav** [comment]
What do you think could be the issue? @bratseth 
Last time we had reverse issue

**Comment by bratseth** [comment]
Can you run this with tracelevel=3 and see if that tells you what's going on?
Also, feel free to share it here or privately.

**Comment by adityaverma21** [comment]
@bratseth  I ran the query with traceLevel 3 . Seems like the issue is with case sensitive field. So when we are running the above queries **name** is getting converted to **NAME** in the tracelogs when we specify the sources. But it remains as name in select * from sources *.
 I can see the content cluster has some schemas with field NAME and some with field name. Then why is vespa behaving differently in terms of what is getting passes in sources. It automatically converts lowercase into uppercase.

**Comment by adityaverma21** [comment]
So we only have two content cluster. Saying select * from sources * and select * from sources doc1.*, doc2.* is essentially the same thing then why is vespa chaging the queries to different case in these scenarios where smaller case is given in both the cases. This is the main issue.

**Comment by bratseth** [comment]
`sources` may specify either content clusters or  schemas. If your content clusters have ids "doc1" and "doc2" then yes, 
`select * from sources doc1, doc2`
and 
`select * from sources *`
will both select _all_ document types. 

(Above you have also used the syntax `sources doc1.*, doc2.*` and `sources doc1., doc2.`, these are equivalent to `sources doc1, doc2`, and invalid respectively. If you want to restrict only on document type, not cluster, use the restrict parameter instead (outside the YQL statement).)

It is still possible that you end up with differently parsed queries in these two cases _if_ you have conflicting definitions of the same fields in two different document types you are searching, as behavior then is undefined (there is no correct option). Specifically this may happen if the schemas happen to be considered in a different order when using `select * from sources doc1, doc2` vs `select * from sources`.

**Comment by adityaverma21** [comment]
But we support cross index search. So we will specify all the document types when querying. It is possible for a field say **test_s** present in a schema, to be also present in other schema with different case i.e **TEST_s**.

In the above case we atleast want to get results on the basis of fieldnames we specify during the query i.e vespa internally shouldn't change test_s to TEST_s which is happening in our case in the above scenarios.

As such is it possible to raise a feature request for vespa to search across the field provided during query time in yql.

**Comment by hmusum** [comment]
System test showing this issue added in https://github.com/vespa-engine/system-test/pull/4204

**Comment by nehajatav** [comment]
@arnej27959  works, thanks. Do we have an ETA? @bratseth

**Comment by bratseth** [comment]
This is in 8.418.48 and later. We are expecting it to be released by tomorrow.
