### ISSUE TITLE
Words with accent leading to issues in search

### ISSUE THREAD

**Issue by adityaverma21** [vespa-engine/vespa#32374]
**Describe the bug**
Not able to search a word indexed with the same language due to accent

**To Reproduce**
We are setting the language of the entire document in the schema using set_language on the basis of main text field. When we set the language as en and index a doc containing a field like relationship_s with value congés , i am unable to search with the query relationship_s contains congés with language en. We have stemming: multiple defined for this field in schema. I suspect its due to normalisation happening

**Expected behavior**
Expectation is that it should be searchable if language is same during indexing and search. Also since stemming is multiple original form of the word should be stored so it should match with stem: false param which is also not happening. 

**Environment (please complete the following information):**
 - RHEL 8
 - Podman

**Vespa version**
8.332.5

**Additional context**
It gives the search when we pass relationship_s contains conges without accent. Also i see stemming happening before normalisation during query which is leading to not returning correct stemmed words.But then it should be consistent in indexing and search

**Comment by jobergum** [comment]
Please see https://docs.vespa.ai/en/linguistics.html - set language at query time and feel free to provide more detailed instructions on how to reproduce, you can also trace queries.

**Comment by adityaverma21** [comment]
As i have mentioned above i have passed same language at query time which is en in which the field was indexed. 

To reproduce:
Deploy a schema which contains field relationship_s with stemming multiple. Use set language at the top of schema and pass that value as en during ingestion. Ingest relationship _s as congés and then search with relationship_s contains congés and pass model.language as en. 

Issue:
Issue here is when words have accent the values are not matching in wiery even though indexing and search have the same language set.

**Comment by bratseth** [comment]
You are right. This is a case where OpenNLP does not end up with the same tokens when tokenizing vs. when  stemming+normalizing. It should, but we'll look into how to handle it when they dont.
