### ISSUE TITLE
Container crash after startup with exitcode=6 when using vespa-sentinel-cmd on on-prem Podman setup

### ISSUE THREAD

**Issue by asutoshprasad** [vespa-engine/vespa#32466]
When creating and starting a container on an on-prem host , we are seeing the container health status transition from initialization to up. However, shortly after, the container crashes. It exits with an exitcode=6.

**Steps to Reproduce**
Create a container on an on-prem host using Podman.
Start the container using **vespa-sentinel-cmd start container**.

Observe the logs and notice the following :
Container health status changes from initialization to up.
"Starting cluster monitor thread" appears in the logs.
GS logs appear but do not going more then 19ms.
The container crashes.
Running the process manually results in exitcode=6.

**Expected Behavior**
The container should start and remain stable after the up status is reached, and the process should not exit with an error.

**Actual Behavior**
The container crashes shortly after the "Starting cluster monitor thread" message appears. The process exits with exitcode=6

**Environment"**
Podman: version 4.4.1
Vespa-> 8.301.19
On-prem host OS: Linux 8.8

Please provide guidance on interpreting exitcode=6 or steps to further diagnose the issue. Any help with potential configuration issues or log file analysis would be appreciated.

**Comment by kkraune** [comment]
I think we need some more info to reproduce this. Thanks

**Comment by nehajatav** [comment]
Thats the issue, we need more info too but lack of logs isnt helping. Can you check if all your exit conditions are covered with adequate logging?

**Comment by arnej27959** [comment]
first, run `vespa-stop-services` and verify that no vespa processes are running afterwards.

Then, after `vespa-start-services` run `vespa-logfmt -f -N -l all` to tail the log.
Paste here what you see.  We don't have any exit conditions that would cause the container to exit without any log messages.

**Comment by arnej27959** [comment]
exitcode=6 is probably from this code:
```
        } catch (Throwable e) {
            log.log(Level.SEVERE, "JDisc exiting: Throwable caught: ", e);
            System.exit(6);
```

**Comment by nehajatav** [comment]
Is this an async logger? Because we havent seen this log
We have tried to do vespa-sentinel-cmd stop and start with `vespa-logctl container all=on` but that didnt result in any additional logs?

**Comment by arnej27959** [comment]
logging is sync, so what *do* you see from `vespa-logfmt -l all` ?

**Comment by nehajatav** [comment]
@arnej27959 we dotn have that output captured now, however, irresp, SEVERE logs are turned on by default and yet there was nothing. Hence we urge you to check if there are other exit conditions without any logs

**Comment by arnej27959** [comment]
this is the only place with exit code 6.  re-open when you reproduce it and has the output that I asked for, there's no information to work with as is.
