### ISSUE TITLE
Feed Performance Bottleneck Issue

### ISSUE THREAD

**Issue by asutoshprasad** [vespa-engine/vespa#32495]
We are trying to test out feed performance with 12 container nodes and 10 content nodes, running on on-prem hosts with 8 cores.  We are running 12 feed clients concurrently, with a maximum of 4 connections per endpoint and 128 streams per connection. However, we are encountering a plateau in the feeder, and we see that none of the CPU and RAM usage is maxing out. How can we determine whether we have hit the disk throughput limit? . What other factors could be impacting our performance?

**Environment:**
Podman: version 4.4.1
Vespa-> 8.301.19
On-prem host OS: Linux 8.8

**Additional Information:**
Please suggest any changes or improvements that could help us in this performance issue.

**Comment by jobergum** [comment]
This document is a good [start](https://docs.vespa.ai/en/performance/sizing-feeding.html)

**Comment by jobergum** [comment]
Usually this is related to either IO performance (every operation is synced for durability in the TLS so high latency network attached disks can limit throughput) or mutating operations that cannot be parallelized, see the [bottlenecks](https://docs.vespa.ai/en/performance/sizing-feeding.html#bottlenecks) section.
