### ISSUE TITLE
Windows: Vespa yql -  query curl conversion error

### ISSUE THREAD

**Issue by John42506176Linux** [vespa-engine/vespa#32514]
**Describe the bug**
On a Windows machine, vespa queries do not convert quotes correctly causing errors with queries requiring quotes.
For example vespa query -v 'yql=select * from news where default contains "music"'.

**To Reproduce**
1. Used sample application vespa news Step - applications, feeding and querying
2. Query 'vespa query -v 'yql=select * from news where default contains "music"'' fails
3. See Error

**Expected behavior**
Successful query

**Screenshots**
![image](https://github.com/user-attachments/assets/c7695d9e-4297-4116-a5c4-8f83876bbb40)

**Environment (please complete the following information):**
 - OS: Windows
 - Infrastructure: Self-hosted

**Vespa version**
Vespa CLI 8.416.42

**Additional Context**
Error does not occur on WSL.

**Comment by arnej27959** [comment]
this is not a vespa CLI problem; the issue is that you must quote in the way that the windows "cmd" command line will handle.  The correct syntax for that command line shell is
`vespa query "yql=select * from news where default contains ""music"""`
