### ISSUE TITLE
What about using LSP4IJ ?

### ISSUE THREAD

**Issue by angelozerr** [vespa-engine/vespa#32583]
I notice that you have implemented  your own LSP.

 Please note that we have released https://github.com/redhat-developer/lsp4ij which is a free IntelliJ LSP support plugin.  

You can see plugins which are based on LSP4IJ at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#who-is-using-lsp4ij

I suggest that you read https://idetools.dev/blog/lsp4ij-announcement/ article to have an overview of LSP4IJ.

If you want to evaluate it, check out the following documentation:

* LSP4IJ's [LSP Support](https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md)
* [Developer's Guide](https://github.com/redhat-developer/lsp4ij/blob/main/docs/DeveloperGuide.md)
* [LSP Console](https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md)

And if you want to quickly evaluate LSP4IJ without developing a plugin but just by filling a parameter in your ls startup command, please check https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md

All lsp features like completion, sem1ntic tokens, rename etc that you have implemented are supported by lsp4ij 

Hope you could be interested with LSP4IJ

**Comment by theodorklauritzen** [comment]
Thank you for the great feedback, @angelozerr! I’ve updated our IntelliJ plugin to use LSP4IJ, which seems to be working better than the built-in features in the Ultimate edition. I noticed in the guide that we’re instructed to exclude LSP4J as a dependency. Do you know if this is necessary when our LSP4J instance is in a separate JAR, run by a separate process?

**Comment by angelozerr** [comment]
> Thank you for the great feedback, @angelozerr! I’ve updated our IntelliJ plugin to use LSP4IJ, which seems to be working better than the built-in features in the Ultimate edition. 

Wow that's great!

> I noticed in the guide that we’re instructed to exclude LSP4J as a dependency. Do you know if this is necessary when our LSP4J instance is in a separate JAR, run by a separate process?

I think it is better to do that because if your LSPJ version is not the same that LSPJ version from LSP4IJ you will have some problem.

Could you please:

 * add your plugin in https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#who-is-using-lsp4ij
 * if you think that LSP4IJ isgood, add a review at https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/reviews to help us to promote LSP4IJ, thanks!

**Comment by theodorklauritzen** [comment]
Perfect! I've crated a PR in LSP4IJ to add our plugin there and I'll write a review.
