### ISSUE TITLE
Error validating schema when populating a field from a struct using get_field

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#32685]
**Describe the bug**
In version 8.430.10 , we are seeing an error where the deploy step fails saying that a field doesn't exists within a struct defined in the same schema. This is not happening in version 8.429.19

**To Reproduce**
1. Define the following struct and field:
```txt
        struct someFantasticStruct {
            field identifier type int { }
            field aStringField type string { }
        }

       field arrayOfFantasticStructs type array<someFantasticStruct> {}

       field stringsConcatenated type array<string> {
          indexing: input arrayOfFantasticStructs | for_each {
            get_field aStringField
          } | attribute
        }
```
2. Try to deploy an application with that schema:
3. See error

```txt
Error: invalid application package (status 400)
Invalid application:
For schema 'exampleSchema', field 'stringsConcatenated':
For expression 'get_field aStringField':
Input field 'aStringField' not found.
```

**Expected behavior**
No error shouldn't be happening.

**Screenshots**
Not applicable

**Environment (please complete the following information):**
 - OS: macOS
 - Infrastructure: self-hosted
 - Versions 15.0.1

**Vespa version**
Since 8.430.10 version

**Additional context**
I think this is solved by https://github.com/vespa-engine/vespa/pull/32673 but I am not sure

**Comment by bratseth** [comment]
Yes, this was a bug on our side as part of making the type verification in indexing more comprehensive. It was fixed in https://github.com/vespa-engine/vespa/pull/32673 and we'll unpin you when this rolls out during today. Sorry for the trouble!
