### ISSUE TITLE
setNumTargetHits sets hits but not targetHits - is this a bug?

### ISSUE THREAD

**Issue by drei34** [vespa-engine/vespa#32739]
Hi,

My understanding is this method on a query is supposed to change targetHits but it seems to change hits. Is this intended? In java code, what is the proper way to change targetHits. targetHits affects Vespa multinode retrieval (not ranking), am I correct? 

Thank you!

I found this but it does not seem right: https://stackoverflow.com/questions/67700811/dynamic-targethits-in-vespa-yql

Code is here for this method: https://javadoc.io/doc/com.yahoo.vespa/container-search/latest/com/yahoo/prelude/query/NearestNeighborItem.html

**Comment by hmusum** [comment]
How do you come to the conclusion changing `targetHits` changes `hits`? It doesn't. But maybe you are seeing something that looks like that is the case? If so, please provide some queries, responses (and query profile if you use that).

The doc for this is https://docs.vespa.ai/en/reference/query-language-reference.html#targethits.  The answers in https://stackoverflow.com/questions/67700811/dynamic-targethits-in-vespa-yql also describes in detail how `targetHits` works. Setting this in Java code is done as described in the last answer in that thread
