### ISSUE TITLE
Vespa search returns 200 OK even response does not have any document field

### ISSUE THREAD

**Issue by sunil924** [vespa-engine/vespa#32800]
**Describe the bug**
Vespa Seach query with order by clause and limit gives 200 OK response, but the response result has no field other than id field.
In logs we see following stderr msg

> searchnode stderr warning E0000 00:00:1730955617.063340   539  message_lite.cc:511] searchlibb.searchprotocol.protobuf.DocsumReply exceeded maximum protobuf size of 2GB: 3349495761

**To Reproduce**
**Query** 
```
{
  "yql": "SELECT * FROM sources mydoc.* WHERE (range (lastModifiedDate_t, 1726125503000, 1726730303000) ORDER BY lastModifiedDate_t ASC, '[docid]' DESC) LIMIT 1000 OFFSET 0",
  "timeout": "60s",
  "ranking.profile": "my-rank-profile",
  "presentation": {
    "bolding": "false",
    "summary": "mySummary"
  },
  "model.searchPath": "/1",
  "model.language": "en"
}
```

**See response:**
```
{
    "root": {
	   "id": "toplevel",
       "relevance": 1.0,
	   "fields": {
            "totalCount": 746
        },
	   "coverage": {
            "coverage": 100,
            "documents": 18403204,
            "full": true,
            "nodes": 144,
            "results": 48,
            "resultsFull": 48
        },
         "children": [
			{
				"id": "index:mydoc/0/f09e03d24033c288c11996cd",
				"relevance": 0.0,
				"value": "mydoc"
			},
			{
				"id": "index:mydoc/0/bef4e4ab2074fe79faecdfb5",
				"relevance": 0.0,
				"value": "mydoc"
			},
				"id": "index:mydoc/0/b1bcfa1e76623587947dabcb",
				"relevance": 0.0,
				"value": "mydoc"
			}
			.
			.
			.
			.
			.
			.<746 children>
		]
        
    }
}
```

**Expected behavior**
Response code should be non 2XX

Environment:
Podman: version 4.4.1
Vespa-> 8.301.19
On-prem host OS: Linux 8.8

Content node logs: (<img width="936" alt="vespa_logs" src="https://github.com/user-attachments/assets/1e332cae-24ec-4af6-b731-dc302992a4a0">)

**Comment by arnej27959** [comment]
fixed in version 8.447.14 by https://github.com/vespa-engine/vespa/pull/32916
