### ISSUE TITLE
Schema API issue

### ISSUE THREAD

**Issue by maximzubkov** [vespa-engine/vespa#33034]
Hello, Vespa Team!

Following the [Schema API issue](https://github.com/vespa-engine/vespa/issues/31696) I tried to reproduce the steps listed in the [documentation](https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#content-get), however for some reason I keep getting an empty list from the API. Here is what I did
1. Created a session
```bash
curl -X POST --header Content-Type:application/zip localhost:7006/application/v2/tenant/default/sessio
```
the output was like
```json
{
    "log":[],
    "tenant":"default",
    "session-id":"38",
    "prepared":"http://localhost:19071/application/v2/tenant/default/session/38/prepared",
    "content":"http://localhost:19071/application/v2/tenant/default/session/38/content/",
    "message":"Session 38 for tenant 'default' created."
}
```
2. used the `session-id` (38 in the example above) to get the schema data
```
curl -X GET "localhost:7006/application/v2/tenant/default/session/38/content/schemas/
```
but as an output I get an empty list like `[]`, while at the same time `vespa query`, `vespa curl`, `vespa document get` and other features work well for me. Did I do something wrong?

**Comment by hmusum** [comment]
A session has a lifetime, so if you just prepare it (do not activate it) as you do above, it will be deleted after session lifetime has expired (1 hour by default). Try getting the current active session (`/application/v2/tenant/default/application/default/` in your case) and do the same request with the generation/session found in the response. A request for content with the currently active session should always work.

**Comment by maximzubkov** [comment]
Hey @hmusum, thanks for the prompt response! I just tried this
```bash
curl -X GET --header Content-Type:application/zip localhost:7006/application/v2/tenant/default/application/default/
``` 
but the API returns this 
```
{"generation":44,"applicationPackageFileReference":"","modelVersions":[...]}
```

**Comment by hmusum** [comment]
Yes, so does `curl -X GET "localhost:7006/application/v2/tenant/default/session/44/content/schemas/` work? (generation is used for configs and is identical to an the session id for an active application)

**Comment by maximzubkov** [comment]
ah, I see `generation` is a `session-id`, sorry, I thought it was something different. thanks! I think we can close it unless you want to maybe make some updates to the documentation about it

**Comment by hmusum** [comment]
Great, thanks! The doc at https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html states when a session id is valid in the introduction.
