### ISSUE TITLE
Add support for returning docs from more than one bucket per request when visiting via Document V1 API

### ISSUE THREAD

**Issue by vekterli** [vespa-engine/vespa#3394]
Visiting via the container Document V1 REST API returns documents from only 1 bucket at a time, giving back a continuation token that lets the client continue visiting from the successor bucket in its next request. There is currently no way of specifying you want the request to cover _more_ than a single bucket.

In systems with a lot of data, this returns a chunk of 500-1000 docs per request, which is a nicely manageable amount. However, in systems with few documents each request ends up returning only a handful of documents. For example, the corpus used in the Vespa tutorial with 10 documents returns 1 document per request, requiring 10 individual requests.

I suggest adding a query parameter for overriding the minimum number of documents returned, which allows for batching up multiple buckets and reducing the number of roundtrips. Default behavior should remain 1 bucket at a time, as this is the most common production scenario. We should also enforce an upper bound on the parameter to avoid OOM-ing the container during response buffering.

**Comment by bratseth** [comment]
Good idea. Do we need both a min and max documents? How about just having a target-document-chunk or similar?

**Comment by vekterli** [comment]
I'm all in favor of reducing the number of knobs and dials to turn, so a target chunk size sounds like a good approach.

**Comment by vekterli** [comment]
Concrete suggestion: add `minDocs=<positive integer>` query parameter. Max doc count is implementation defined and cannot be set by user.

Since we only allow setting minimums, this fits nicely in with visiting only processing documents at bucket granularity. If a bucket has 500 documents and a hypothetical "max documents" parameters was set to 10, we have no way of returning 10 docs and giving out a continuation token which returns from the remaining set of 490 in the next request. `minDocs=10` would return 500 docs and  you'd just have to Deal With It™.

**Comment by bratseth** [comment]
Sounds good to me, but if you have less than minDocs matching documents you'll get less and have to Deal With It™, which is why I suggested targetDocuments. Not important though.

**Comment by vekterli** [comment]
I agree. I casually gravitated towards `minDocs` because the name implies some form of cardinality. `targetDocuments` could _potentially_ be interpreted as a set of document IDs to fetch. `targetDocumentCount` is even more explicit and semantically "correct". But maybe a bit on the long side?

**Comment by bratseth** [comment]
wantedDocs?

**Comment by tiberiusteng** [comment]
How about `batchSize` ?

**Comment by bratseth** [comment]
Agree, that's good.

**Comment by vekterli** [comment]
`batchSize` works for me, though the biggest challenge with picking any name here is minimizing user surprise when they specify a batch size of 2 and they get 1000 docs back (or vice versa).

Naming stuff is _hard_, guys. 😨

**Comment by bratseth** [comment]
wantedDocumentCount then. I don't think we can have both short and indicates it's an integer && indicates it is not an absolute.

**Comment by vekterli** [comment]
`wantedDocumentCount` going once, going twice... Sold! To the man in the back with the eclectic Spotify playlist!

**Comment by geirst** [comment]
Please add reference documentation

**Comment by vekterli** [comment]
Parameter documentation added in https://github.com/vespa-engine/documentation/pull/216
