### ISSUE TITLE
TLS support in fbench

### ISSUE THREAD

**Issue by bjorncs** [vespa-engine/vespa#3469]
Add TLS support to fbench

**Comment by baldersheim** [comment]
How much work is this I wonder. Are there some other hhtp benchmark suites out there that are able to do that ? Or is it fairly simple.

**Comment by vekterli** [comment]
We could wrap the connect/read/write/shutdown logic in fbench with OpenSSL `SSL_*` calls, or alternatively create a new TLS socket implementation in FastOS (fbench uses FastOS sockets today) to make it more generally available. Either way we'd need some kind of key/certificate store and ability to pass keys/certs to the application.

For other tools, it seems both [wrk](https://github.com/wg/wrk) and [httperf](https://github.com/httperf/httperf) support TLS, but I have no prior experience with either of them.

**Comment by harryjackson** [comment]
[wrk](https://github.com/wg/wrk) is blazingly fast compared to "ab" and I think it's faster than httperf. When doing quick comparisons on my local machine it would outperform anything else I used and is now my default http performance testing tool.

**Comment by spyker237** [comment]
Hi, how can I contribute to this project? I know very little java. Where should I start?

**Comment by bratseth** [comment]
By learning Java (or C++) I guess?

**Comment by vekterli** [comment]
Implemented in #7288
