### ISSUE TITLE
Adding <document-api> to basic-search-java causes error when running mvn package

### ISSUE THREAD

**Issue by trygve** [vespa-engine/vespa#3479]
`   
<jdisc version="1.0">
        <document-api/>
        <processing>
            <chain id="default">
                <processor id="com.mydomain.example.ExampleProcessor" bundle="basic-search-java">
                    <config name="com.mydomain.example.example-processor">
                        <message>Hello, services!</message>
                    </config>
                </processor>
            </chain>
        </processing>
        <nodes>
            <node hostalias="node1"/>
        </nodes>
    </jdisc>
`

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.27 sec <<< FAILURE! - in com.mydomain.example.ApplicationTest
requireThatResultContainsHelloWorld(com.mydomain.example.ApplicationTest)  Time elapsed: 1.27 sec  <<< ERROR!
java.lang.IllegalArgumentException: Could not create a component with id 'com.yahoo.document.restapi.resource.RestApi'. Tried to load class directly, since no bundle was found for spec: vespaclient-container-plugin. If a bundle with the same name is installed, there is a either a version mismatch or the installed bundle's version contains a qualifier string.
	at com.mydomain.example.ApplicationTest.requireThatResultContainsHelloWorld(ApplicationTest.java:21)

**Comment by bratseth** [comment]
Welcome back Trygve :-)
@gjoranv this is why we should do the "container-dev" -> "container" thing I mentioned.

I guess it won't happen that soon - should we just add vespaclient-container-plugin dep to basic-search to avoid this, or add it to the documentation, or ...?

**Comment by gjoranv** [comment]
@bratseth This is the test classpath, not provided/runtime. I'll add vespaclient-container-plugin as a dependency in application for now, and move it to container-test when that is ready.

**Comment by huihuang01** [comment]
Has this issue been fixed or not? I encountered the same problem and fixed it by manually adding the dependency. Not sure if other people know how to do or not ...

**Comment by gjoranv** [comment]
This is work in progress. New maven artifacts for 3rd party developers will be available soon.

**Comment by Shastick** [comment]
One of the sample applications fails with a similar exception (see SO question at https://stackoverflow.com/q/46772244/1997056). Is it related to this problem?

**Comment by gjoranv** [comment]
@Shastick, your problem is not related to this issue. I'll test the sample app and get back to you on SO.

**Comment by gjoranv** [comment]
From version 6.158.42, you can remove all dependencies with groupId `com.yahoo.vespa` from  your project's pom.xml file, and instead insert the following:

```
        <dependency>
            <groupId>com.yahoo.vespa</groupId>
            <artifactId>container</artifactId>
            <version>${vespa_version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.yahoo.vespa</groupId>
            <artifactId>container-test</artifactId>
            <version>${vespa_version}</version>
            <scope>test</scope>
        </dependency>
```
Please make sure that you have the `vespa_version`or similar property defined in your pom.xml and update it to 6.158.42 or newer.

@trygve or @huihuang01 , could you please try to apply the proposed changes to your pom.xml?Thanks!

**Comment by gjoranv** [comment]
All sample apps have been updated to use 'container' and 'container-test' since https://github.com/vespa-engine/sample-apps/pull/28
