### ISSUE TITLE
Quickstart doesn't work on macOS

### ISSUE THREAD

**Issue by wiradikusuma** [vespa-engine/vespa#3560]
Quickstart (http://docs.vespa.ai/documentation/vespa-quick-start.html), from **Step 4**:

	osx:vespa wiradikusuma$ docker exec vespa bash -c '/opt/vespa/bin/vespa-deploy prepare /vespa-sample-apps/basic-search/src/main/application/ && \ 
	>     /opt/vespa/bin/vespa-deploy activate'

		Uploading application '/vespa-sample-apps/basic-search/src/main/application/' using http://localhost:19071/application/v2/tenant/default/session?name=application
		Session 2 for tenant 'default' created.
		Preparing session 2 using http://localhost:19071/application/v2/tenant/default/session/2/prepared
		Session 2 for tenant 'default' prepared.
		bash:  : command not found
		Activating session 2 using http://localhost:19071/application/v2/tenant/default/session/2/active
		Session 2 for tenant 'default' activated.
		Checksum:   9af875d625b18c84d3dd6daa748c9484
		Timestamp:  1506523079488
		Generation: 2

	osx:vespa wiradikusuma$ curl -s --head http://localhost:8080/ApplicationStatus

		HTTP/1.1 200 OK
		Date: Wed, 27 Sep 2017 14:38:24 GMT
		Content-Type: application/json
		Transfer-Encoding: chunked

	osx:vespa wiradikusuma$ curl -s -X POST --data-binary @${VESPA_SAMPLE_APPS}/basic-search/music-data-1.json \
	>     http://localhost:8080/document/v1/music/music/docid/1 | python -m json.tool

		{
		    "id": "id:music:music::1",
		    "pathId": "/document/v1/music/music/docid/1"
		}

	osx:vespa wiradikusuma$ curl -s -X POST --data-binary @${VESPA_SAMPLE_APPS}/basic-search/music-data-2.json \
	>     http://localhost:8080/document/v1/music/music/docid/2 | python -m json.tool

		{
		    "id": "id:music:music::2",
		    "pathId": "/document/v1/music/music/docid/2"
		}

	osx:vespa wiradikusuma$ curl -s http://localhost:8080/search/?query=bad | python -m json.tool

		No JSON object could be decoded

	osx:vespa wiradikusuma$ curl -s http://localhost:8080/document/v1/music/music/docid/2 | python -m json.tool

		No JSON object could be decoded

**Comment by vekterli** [comment]
I just ran through the quickstart from scratch and got the following (expected) output:
```
$ curl -s http://localhost:8080/search/?query=bad | python -m json.tool 
{
    "root": {
        "children": [
            {
                "fields": {
                    "artist": "Michael Jackson",
                    "documentid": "id:music:music::1",
                    "duration": 247,
                    "sddocname": "music",
                    "title": "Bad",
                    "year": 1987
                },
                "id": "id:music:music::1",
                "relevance": 0.254574922399675,
                "source": "music"
            },
            {
                "fields": {
                    "artist": "Eminem",
                    "documentid": "id:music:music::2",
                    "sddocname": "music",
                    "title": "So Bad",
                    "year": 2010
                },
                "id": "id:music:music::2",
                "relevance": 0.05447959677335429,
                "source": "music"
            }
        ],
        "coverage": {
            "coverage": 100,
            "documents": 2,
            "full": true,
            "nodes": 0,
            "results": 1,
            "resultsFull": 1
        },
        "fields": {
            "totalCount": 2
        },
        "id": "toplevel",
        "relevance": 1.0
    }
}
$ curl -s http://localhost:8080/document/v1/music/music/docid/2 | python -m json.tool
{
    "fields": {
        "album": "Recovery",
        "artist": "Eminem",
        "title": "So Bad",
        "year": 2010
    },
    "id": "id:music:music::2",
    "pathId": "/document/v1/music/music/docid/2"
}
```
This is on macOS 10.12.6 running Docker version 17.06.2-ce.

What kind of output do you get from the curl command directly, i.e. omitting `| python -m json.tool`?

Also, what resource limits have you set for Docker? I ran the above with 4 CPUs and 4GiB.

**Comment by wiradikusuma** [comment]
After trying for the 3rd time, with slower copy-paste pace (I wanted to do screencast to show the issue), it's now working. I'll close this. Thanks!

(for those who are curious, here's the screencast: https://cl.ly/1A291i222I2f)

**Comment by jobergum** [comment]
Thanks a lot for sharing the screencast @wiradikusuma and for trying out Vespa! We'll review the quick start guide and improve it based on your feedback! Keep us posted!
