### ISSUE TITLE
pom.xml from basic-search-java fails in Eclipse Neon

### ISSUE THREAD

**Issue by KnowledgeGarden** [vespa-engine/vespa#3580]
It's a lifecycle issue, something about m2e connectors, but Eclipse is not able to resolve it. Eclipse did download the dependencies, but there is still an error in the pom. Eclipse says something about "Resolve Later". The error message is this:
Plugin execution not covered by lifecycle configuration: com.yahoo.vespa:bundle-plugin:6.145.90:generate-bundle-classpath-mappings (execution: default-generate-bundle-classpath-mappings, phase: process-test-resources)

I did install one m2e connector. Nothing changed.
What am I missing?

**Comment by kkraune** [comment]
@gjoranv any ideas?

**Comment by bjorncs** [comment]
Hi @KnowledgeGarden. Thanks for your report 👍  We do not have any experience with Vespa development on Eclipse. Most developers at the Vespa team are currently using IntelliJ CE/Ultimate, with some masochists using vim/emacs. Feel free to report back if you find a solution :)

**Comment by KnowledgeGarden** [comment]
My question about this on StackExchange got marked as duplicate since lifecycle stuff is old-hat to eclipse and the m2e tribe, except the fix, while it makes the error message go away, doesn't fix another problem. The fix is simply to use the Eclipse QuickFix and tell Eclipse to ignore it. I think that knowing *that* fix allows me to close this issue and open another one.
