### ISSUE TITLE
search-definition: ignore fields

### ISSUE THREAD

**Issue by shwetanks** [vespa-engine/vespa#3582]
is there some way to indicate vespa-deloy to ignore fields not mapped in search-definition file?

e.g. (in an arbitrary dataset)

    {
      "ignore_field": null,
      "usable_field_1": "sd_fl_1"
    }

and in search-definition

    arbitdataset.sd

    search simplex {
        document simplex {
            field usable_field_1 type string {
                indexing: summary
            }
        ....
        }
    }

throws 
    Detail resultType=FATAL_ERRORexception='Could not get field "ignore_field" in the structure of type "simplex"

please point me to any document explaining this

ref:
http://docs.vespa.ai/documentation/reference/search-definitions-reference.html#match

**Comment by shwetanks** [comment]
-- please excuse. can someone create few SO tags for vespa so i can take it up there. or point it out if any already exist and just couldn't find.

**Comment by jobergum** [comment]
Hi @shwetanks, 

Thank you for interest in Vespa.ai. There is currently no support for ignoring fields not found in the document schema(s). 

We have https://stackoverflow.com/questions/tagged/vespa but no questions yet.

**Comment by shwetanks** [comment]
@jobergum thanks for answering. i'll put it up there and if i can, will raise a PR. might take me some time though to sift through the source and find appropriate handlers.

**Comment by shwetanks** [comment]
![image](https://user-images.githubusercontent.com/1411867/31005658-4d4b90b8-a517-11e7-980a-05f14f9b08c2.png)

you might want to look at the SO tag though. seems unavailable

**Comment by jobergum** [comment]
Vespa is strongly-typed and ignoring fields we don't know could lead to issues. If we accept unknown fields we also gonna see people complaining after feeding 1B documents and figuring out some fields where not spelled correctly :)
