### ISSUE TITLE
Running on Kubernetes

### ISSUE THREAD

**Issue by F21** [vespa-engine/vespa#3588]
This is more of a question but I think it would also be a nice addition to the documentation.

I am interested in running vespa on a Kubernetes cluster. In the documentation, there is a [list of vespa processes](http://docs.vespa.ai/documentation/reference/files-processes-and-ports.html) and which nodes they should run on. There are 4 types of nodes in the list.

However, in the `Vespa start / stop` section, there is a command to start all services and a command to start the config server, giving me the impression that there are only 2 types of nodes.

In addition, there is the vespa/vespa image for running vespa in docker.

1. Is the vespa/vespa docker image suitable for production?
2. If I am running vespa on kubernetes, can I use the vespa/vespa image to deploy multiple instances?
3. Is it not recommended to run processes listed under different hosts on the same host? For example, running the `container` service on a `content cluster` host?

**Comment by smorgrav** [comment]
The host column in the documentation you mentioned is more like a mental model for where you would expect to see the processes. You can run everything on one host but in a larger production environment it makes sense to split up accordingly to reason about resource usage and handle lifecycle events. 

For your questions, I would say 1) yes, 2) yes and 3) there is nothing technical why you should not run them on the same hosts. 

As for Kubernetes we have limited experience with it - feedback on this would be very interesting.

**Comment by jobergum** [comment]
On start/stop: There are only two different start/stop commands as you can see. The  services should be started on all nodes in your cluster and configuration server on a fewer set of nodes (e.g 3) but configuration server can also run on the same node(s) as the services. 

start services will start the Config sentinel process which needs the configuration server address to know which services it should start on a given node which again is configured in the application package which describes which high level services should where http://docs.vespa.ai/documentation/cloudconfig/application-packages.html. 

We try to demonstrate this in the quick start http://docs.vespa.ai/documentation/vespa-quick-start.html but maybe the AWS multi-node guide is more informative on this http://docs.vespa.ai/documentation/vespa-quick-start-multinode-aws.html

**Comment by aressem** [comment]
You can also take a look in the [multinode AWS ECS guide](http://docs.vespa.ai/documentation/vespa-quick-start-multinode-aws-ecs.html). There you will see the two types of containers (which should correspond to two types of Kubernetes pods). The docker image is given a command to either be a configserver or services. Please note that you will have to know the hostnames of your config servers upfront and pass these in the environment variable described.

**Comment by jobergum** [comment]
@F21 Any updates on this?

**Comment by F21** [comment]
@jobergum I haven't had a chance to try this out yet, but I hope to give it a spin before the end of the month.

**Comment by humayun0156** [comment]
Hi @aressem the link you've given http://docs.vespa.ai/documentation/vespa-quick-start-multinode-aws-ecs.html returns 404
I'm in need of a solution to run multinode vespa on Kubernetes.

**Comment by aressem** [comment]
@humayun0156 This is a 5-year-old issue. Living documentation move around. You can search for Kubernetes in current vespa doc here:
https://docs.vespa.ai/search.html?q=kubernetes

Good starting point is https://docs.vespa.ai/en/vespa-quick-start-kubernetes.html
