### ISSUE TITLE
build java error

### ISSUE THREAD

**Issue by sundaywill** [vespa-engine/vespa#3597]
build java error below:
`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Building Vespa Maven plugins.
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/root/maven-plugins/pom.xml) has 1 error
[ERROR]     Non-readable POM /root/maven-plugins/pom.xml: /root/maven-plugins/pom.xml (No such file or directory)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException`

build go on just do like below:
`cd vespa && ./bootstrap.sh java`

**Comment by bratseth** [comment]
The error message says "/root" and "/root/maven-plugins/pom.xml" which indicates that you ran bootstrap.sh from the directory /root, not the directory you checked out vespa to.

Make sure you really cd to the directory containing the root of the module tree of vespa and run bootstrap.sh java from that directory.

**Comment by jobergum** [comment]
Did you make any progress on this @sundaywill ? Thanks

**Comment by sundaywill** [comment]
@jobergum Yes, it's my miss, I missed something of the doc, and it was solved by the mention from Bratseth, and it's ok now, Thank you very much.
