### ISSUE TITLE
Duplicate "Chained Components" in the sidebar of vespa doc

### ISSUE THREAD

**Issue by huihuang01** [vespa-engine/vespa#3598]
See the screenshot below

![vespa_doc](https://user-images.githubusercontent.com/32382241/31044226-14962bbe-a591-11e7-92f3-3d4076edc523.jpg)

**Comment by jobergum** [comment]
Thanks @huihuang01! Addressed in https://github.com/vespa-engine/documentation/pull/162

Keep em coming 👍
