### ISSUE TITLE
yum install vespa error

### ISSUE THREAD

**Issue by sundaywill** [vespa-engine/vespa#3599]
Okay.....Uhm.....My Eng is pool, so i hoop you can understand what i said below. 
I did this: 
`yum -y install yum-utils epel-release              
    yum-config-manager --add-repo               
https://copr.fedorainfracloud.org/coprs/g/vespa/vespa/repo/epel-7/group_vespa-vespa-epel-7.repo
    yum -y install vespa`

and error comes out like this: 
`Error: Package: vespa-6.149.44-1.el7.centos.x86_64 (group_vespa-vespa)         
           Requires: libboost_system-gcc62-mt-1_59.so.1.59.0()(64bit)        
Error: Package: vespa-6.149.44-1.el7.centos.x86_64 (group_vespa-vespa)          
           Requires: libboost_program_options-gcc62-mt-1_59.so.1.59.0()(64bit)         
Error: Package: vespa-6.149.44-1.el7.centos.x86_64 (group_vespa-vespa)         
           Requires: libboost_filesystem-gcc62-mt-1_59.so.1.59.0()(64bit)          
Error: Package: vespa-6.149.44-1.el7.centos.x86_64 (group_vespa-vespa)         
           Requires: libboost_thread-gcc62-mt-1_59.so.1.59.0()(64bit)`

I tried to installed "Development Tools", and the error is the same one. 

And if I did like this: 
`yum-config-manager --add-repo http://repo.enetres.net/enetres.repo         
yum install boost-devel`

Sth came out like this: 
`--> Finished Dependency Resolution         
Error: Package: libboost_log1_59_0-1.59.0-1.x86_64 (enetres)         
           Requires: libicuuc.so.42()(64bit)          
Error: Package: libboost_locale1_59_0-1.59.0-1.x86_64 (enetres)           
           Requires: libicudata.so.42()(64bit)           
Error: Package: libboost_regex1_59_0-1.59.0-1.x86_64 (enetres)         
           Requires: libicudata.so.42()(64bit)         
Error: Package: libboost_locale1_59_0-1.59.0-1.x86_64 (enetres)          
           Requires: libicui18n.so.42()(64bit)          
Error: Package: libboost_log1_59_0-1.59.0-1.x86_64 (enetres)          
           Requires: libicudata.so.42()(64bit)            
Error: Package: libboost_graph1_59_0-1.59.0-1.x86_64 (enetres)             
           Requires: libicuuc.so.42()(64bit)            
Error: Package: libboost_regex1_59_0-1.59.0-1.x86_64 (enetres)              
           Requires: libicuuc.so.42()(64bit)          
Error: Package: libboost_graph1_59_0-1.59.0-1.x86_64 (enetres)           
           Requires: libicui18n.so.42()(64bit)           
Error: Package: libboost_locale1_59_0-1.59.0-1.x86_64 (enetres)         
           Requires: libicuuc.so.42()(64bit)          
Error: Package: libboost_regex1_59_0-1.59.0-1.x86_64 (enetres)           
           Requires: libicui18n.so.42()(64bit)           
Error: Package: libboost_log1_59_0-1.59.0-1.x86_64 (enetres)            
           Requires: libicui18n.so.42()(64bit)            
Error: Package: libboost_graph1_59_0-1.59.0-1.x86_64 (enetres)           
           Requires: libicudata.so.42()(64bit)         
 You could try using --skip-broken to work around the problem            
 You could try running: rpm -Va --nofiles --nodigest`

So, what should I do ? I have no idea.......

for help....

Uh! And the os id centos 7.0

**Comment by jobergum** [comment]
Thank you for the detailed report! We are looking into this.

**Comment by aressem** [comment]
Problem found. Need to rebuild the Vespa rpm. Should be able to release this within 2 hours.

**Comment by aressem** [comment]
New Vespa rpms and docker images available. I have verified that the rpm and Docker images work as expected.
