### ISSUE TITLE
It's just a Slack chat invite link for discussing and learning

### ISSUE THREAD

**Issue by sundaywill** [vespa-engine/vespa#3871]
https://join.slack.com/t/vespasearchengine/shared_invite/enQtMjYxNDY2NzMzNjgzLTY4NzgwODFkZDMyYTdiMGQ5ZjFiYjc1ZmIzMGRkODVlYzRkNjViNWJjNDQ5MmYyOTYyNjIzM2QwNDY1NDI1NjQ

Ummm>>>>>>

I created a slack workspace, just for discussing and learning Vespa engine.

**Comment by sundaywill** [comment]
Btw, anybody know that the 'Geo search' result show 10 items at most ?

searching like this:

`http://host:8080/search/?query=a&pos.ll=N30.234532;E100.123432&pos.radius=1000km&limit=5&offset=5`

And it seems 'limit' does not work.

**Comment by jobergum** [comment]
limit is not a search api parameter, see http://docs.vespa.ai/documentation/reference/search-api-reference.html#hits

**Comment by sundaywill** [comment]
@jobergum Thank you very much.
