### ISSUE TITLE
Metrics API Improvent

### ISSUE THREAD

**Issue by mnagaya** [vespa-engine/vespa#4071]
I would like to get the average metric value of past 5 minutes.  However vespa does not support it.
Could you add SUM values to metrics api?

I am planning to calculate metric value of past 5 minutes from the SUM value by using prometheus.

Thanks,

**Comment by arnej27959** [comment]
you don't need any special vespa support for this, as long as you sample the vespa metrics every minute and insert it into prometheus you can do the averaging there (just use the standard prometheus sum/count expression from the prometheus documentation).

note that this is exactly how yahoo's internal metrics monitoring / graphing system does it also, so this is the use case that current vespa setup is intended for, and should work very well.

**Comment by mnagaya** [comment]
I think it works fine when LAST metrics is supported.However, some vespa metrics do not have LAST but only AVG metrics. For example search_connections does not support it.

Can we add SUM metrics to they?

**Comment by arnej27959** [comment]
can't you do the sum of averages?  from the prometheus docs it looks like you want to use their 'summaries' concept to do the summing for you:
https://prometheus.io/docs/practices/histograms/

you shouldn't do summing or averaging of the LAST metric, that will sometimes yield incorrect results, since it will repeat the last value seen when there's no new measurements in a period.

**Comment by mnagaya** [comment]
rate() can calculates the per-second average rate of increase of the time series:
https://prometheus.io/docs/prometheus/latest/querying/functions/#rate()

**Comment by mnagaya** [comment]
It seems I misunderstood the specification of metrics API of Vespa. Sorry for confusion. Now I understood the correct specification, and I will try to calculate what I need using "rate" and "average" metrics currently available.

Thank you for your explanation.
