### ISSUE TITLE
Multi-application or multi-tenant

### ISSUE THREAD

**Issue by zoyvind** [vespa-engine/vespa#4271]
Hi guys. I am searching the documentation for clues on how to run multiple applications on the same set of nodes. How should this be modelled? multi-application in the same tenant or multi-tenant?

Please point me in the right direction.

Thanks

--Øyvind

**Comment by bratseth** [comment]
Not sure you should try to do that, what are you trying to achieve?

If you really need to do it I would use Docker. You either need to assign one ip per Docker node and map the network on the host, or assign ports manually in each application (not really transparent multitenancy).

**Comment by zoyvind** [comment]
As as sysadm I am trying to give developers access to a Vespa cluster (a set of nodes where I preinstall the software) where they can test all their separate applications. But I also wanted to see if this was an option for production, to run many separate Vespa applications on a small number of VMs.

**Comment by bratseth** [comment]
There's no multi-tenant hosting available out of the box. If you use VM's anyway I would just use separate VM's per application.
