### ISSUE TITLE
Could Vespa been an underlying semantic search engine for automatic answering robots

### ISSUE THREAD

**Issue by theseusyang** [vespa-engine/vespa#4273]
Hi team,

I found that Vespa is a great search engine for big data times.
And have a question that does Vespa become an underlying semantic search engine for automatic answering robots? without regard to semantic modeling section.

**Comment by bratseth** [comment]
Thanks. Not sure I fully understand your question, but if you mean whether it can be used effectively to search and rank nodes/edges in an annotated graph of semantic information then the answer is yes. There is a least one large application doing this with a semantic graph of a couple of hundred million elements, and doing a couple of thousand requests over it per second.
