### ISSUE TITLE
Is vespa useful in a autocomplete scenario ?

### ISSUE THREAD

**Issue by lundin** [vespa-engine/vespa#4278]
Hi, 
I am not sure github issues is the right place to ask so you might want to tag "question" or something but very curious.

Anyway, before starting testing i would like some insights on a autocomplete scenario.

Due to the disk index data structure, instead of memory (only attribute) is it worth even trying to use vespa for a autocomplete solution ? Or does some results gets into the page cache or something so it is still useful ?
  
As far as i understand exact and ngram/prefix index mappings are available right now. Can you please show how ngram<size> is applied to a field as i think this is not by default with the index statement in the .sd file ?
The docs talks about the indexing script and the mapping of the fields but not sure how this applies.

A "good" suggestions will require more than just the contents of the term dictionary, would it be possible to either configure the rank or the GROUP BY to only return n results of each attribute (for example category when searching for "clothes" i get n results under man/women/children category attribute)

Edit-i read about the streaming search
http://docs.vespa.ai/documentation/streaming-search.html
Which might be useful. But how does one add the groupname/number value to i can query it ?
I always get _"Streaming search needs one and only one of these query parameters to be set: streaming.userid, streaming.groupname, streaming.selection"_
http://docs.vespa.ai/documentation/documents.html
tried just add it to the .sd file
id:<namespace>:<document-type>:<key/value-pairs>:<user-specified>i.e
id:music:music:g=mysongs
but it get parsed wrong.

Thanks!
I really enjoyed reading the docs though and looking to try vespa.

**Comment by bratseth** [comment]
Hi, there's also https://stackoverflow.com/tags/vespa which mat be better for general questions.

Disk index caching: Yes, disk indexes get cached in memory - all available memory will be used for that. It's not unusual to get average response times of about 10 ms.

N-gram: Add "match: gram" to the field - that's all (see http://docs.vespa.ai/documentation/reference/search-definitions-reference.html#match).

Prefix: Add * to the end of the term in the query ("foo*"), or turn it on for all queries by adding "match: prefix" to the field.

Diversity/grouping: Yes, you can use grouping to get n result of each unique attribute value (e.g each category): 
/search/?yql=select (…) | all(group(category) each(max(n) each(output(summary()))));
See http://docs.vespa.ai/documentation/reference/grouping-syntax.html#examples

Querying groups with streaming search:
Either add to the query http request &streaming.groupname=yourgroup or (to query multiple groups) &streaming.selection=id.group=="yourgroup1" AND id.group=="yourgroup2"
(where of course the parameter value (the string after "streaming.selection=") must be HTTP-encoded).

Note that streaming search is only useful if your data is statically divided into small groups (e.g users), and in any query you only want to search one or a few of these groups. One use case for this is actually suggest/autocomplete with personal data - there is one very large application using Vespa for that.

**Comment by lundin** [comment]
Cool! Tried various, works great!
Will use SO for questions in the future.

Many thanks for the answer and the cool project!
