### ISSUE TITLE
yum upgrade - config overwritten

### ISSUE THREAD

**Issue by zoyvind** [vespa-engine/vespa#4291]
Hi guys,

I just discovered that after a 'yum upgrade' the file /opt/vespa/conf/vespa/default-env.txt is overwritten.

This made our nodes loose its 'override VESPA_CONFIGSERVER' setting and the cluster went down.

Is this intentional? Where should I put this setting to make it persistent?

Thanks

--Øyvind

**Comment by zoyvind** [comment]
BTW, I got vespa-6.176.233-1.el7.centos.x86_64

I also notice that /etc/profile.d/vespa.sh is missing in this rpm.

**Comment by zoyvind** [comment]
According to the spec file, it removes /etc/profiles.d/vespa.sh during postun step. How is that working in an upgrade scenario?

```
Running transaction
  Updating   : vespa-6.177.31-1.el7.centos.x86_64                                                                             1/2
  Cleanup    : vespa-6.176.233-1.el7.centos.x86_64                                                                            2/2
userdel: user vespa is currently used by process 13714
warning: %postun(vespa-6.176.233-1.el7.centos.x86_64) scriptlet failed, exit status 8
Non-fatal POSTUN scriptlet failure in rpm package vespa-6.176.233-1.el7.centos.x86_64
  Verifying  : vespa-6.177.31-1.el7.centos.x86_64                                                                             1/2
  Verifying  : vespa-6.176.233-1.el7.centos.x86_64                                                                            2/2

Updated:
  vespa.x86_64 0:6.177.31-1.el7.centos
```

**Comment by aressem** [comment]
Fix in https://github.com/vespa-engine/vespa/pull/4347 . Please note that the problem with removal of the user and /etc/profile.d/vespa.sh will still be a problem with the first release including this fix. This is because the post uninstall script is wrong for the current version.
