### ISSUE TITLE
filedistribution troubleshooting

### ISSUE THREAD

**Issue by zoyvind** [vespa-engine/vespa#4310]
Hi guys

We have seen an issue with filedistribution, where a bundle is not distributed to all nodes.

```
warning	java.lang.RuntimeException: Could not install bundle 'file 'e2073ca9724e747eee33f478a67828d721ea16c5''
...
com.yahoo.filedistribution.fileacquirer.TimeoutException: Timed out waiting for file 'e2073ca9724e747eee33f478a67828d721ea16c5' after 15 minutes
```
This is confirmed with vespa-status-filedistribution tool

```
$ vespa-status-filedistribution
No value found for 'services.addr_configserver' or 'vespa_base.addr_configserver'; using 'vespa-test-1.c.zedge-dev.internal'
Waiting for the following hosts:
vespa-test-2.c.zedge-dev.internal  (Downloading, 0/1 file completed)
vespa-test-3.c.zedge-dev.internal  (Downloading, 0/1 file completed)
vespa-test-4.c.zedge-dev.internal  (Downloading, 0/1 file completed)
vespa-test-5.c.zedge-dev.internal  (Downloading, 0/1 file completed)
```

We enabled debug logging on filedistributor service on node 1 (which has the files) and node 3, but it is still not clear what the issue is.

I include a section of the vespa.log on these nodes.
https://gist.github.com/zoyvind/bb189878c451c88b5f97ac7c9a7d37aa

We also read the troubleshooting section of the docs for filedistribution about multiple versions of files, but since we only have 3-4 versions we assume this is not the issue.

Please advise.

Thanks

--Øyvind

**Comment by hmusum** [comment]
I assume vespa-test-1.c.zedge-dev.internal is the config server?

From logs I can see that vespa-test-3 starts downloading 'e2073ca9724e747eee33f478a67828d721ea16c5', but the timestamps indicate that this is before the log for vespa-test-1 says that it has downloaded it successfully. I also see that it discovers that vespa-test-{1-5} are peers. No error in log, which is strange. If you try to deploy again with 'vespa-deploy prepare <app> && vespa-deploy activate', could you please attach logs with debug for filedistributorservice for vespa-test-3 from that time and until it gives up (15 minutes later)? 

Might be some connectivity issue, as it finds what to download through zookeeper and config. Could you check if port 19093 on the other servers can be reached from vespa-test-3?

**Comment by zoyvind** [comment]
Hi Harald.

Thanks for looking into this. I have verified connectivity with telnet and tcpdump between the nodes on port 19093.

Here is a logfile from vespa-test-3:
https://gist.github.com/zoyvind/36b254e87c96ae4b54a00c59b383ac34

I was expecting to see a lot of torrent chatting on this port in the period after deploy, but it was very silent. Could it be that vespa-test-3 is not adding the other peers, and its smart enough not to talk to itself?

Thanks

--Øyvind

**Comment by hmusum** [comment]
Seems like we get to the point where the torrents should be downloaded, but nothing happens, no info in logs. Will try to reproduce.

**Comment by hmusum** [comment]
Reproducible with multinode Centos setup. @zoyvind what os is this running on?

**Comment by zoyvind** [comment]
We are running vespa on CentOS7 in GCE. Installed vespa using yum, like the AWS EC2 multinode example in the docs.

**Comment by hmusum** [comment]
A workaround is to add the line `override cloudconfig_server__disable_filedistributor true` to `/opt/vespa/conf/vespa/default-env.txt` and do `service vespa-configserver restart`. From version 6.183 this workaround should not be needed anymore.

**Comment by zoyvind** [comment]
We have tested the workaround on our last few deploys, and the bundles/files are showing up on all nodes as expected. You can close this ticket.

**Comment by zhengzhejun** [comment]
I add `override cloudconfig_server__disable_filedistributor true` in `/opt/vespa/conf/vespa/default-env.txt` and restart configserver, but filedistribution looks like not work well too.

**Comment by hmusum** [comment]
@zhengzhejun which version are you using? If you are using 6.183 it should not be necessary to add any override. filedistributor should not be running at all on any node in this case, so if you are seeing that it seems like the change has not had effect. You need to run `vespa-deploy prepare` and `vespa-deploy activate` if you have upgraded Vespa or done the override you mentioned. I wouldn't look more into the filedistributor issue, as we are not using that code with 6.183 or later versions of Vespa

**Comment by zhengzhejun** [comment]
@hmusum thanks for attention. I use compile and install vespa with master branch. Should I download codes from tags like vespa-6* for installation? 
So without using filedistributor, which part will in use for file transmission among nodes?

**Comment by zhengzhejun** [comment]
@hmusum I use code from from vespa-6.192.4 vesion, and files are transmitted successfully.
