### ISSUE TITLE
Cannot use a Duration as a timeout in SyncSession.get()

### ISSUE THREAD

**Issue by zhaakhi** [vespa-engine/vespa#4446]
If I pass e.g `Duration.ofMillis(1000)` as a timeout to `SyncSession.get()`, it throws an `UnsupportedTemporalTypeException`.
It seems to originate from `MessageBusSyncSession.SyncSend()`, which calls `timeout.get(ChronoUnit.MILLIS)`.

I cannot find any standard `TemporalAmount` implementation that supports this, is there a special time unit I'm supposed to use?

**Comment by bjorncs** [comment]
No, this is indeed a bug. The API is intended to accept `Duration` instances. Thanks for the report.
