### ISSUE TITLE
Cannot get com.yahoo.vespa:bundle-plugin:6-SNAPSHOT from repository http://yahoo.bintray.com/maven

### ISSUE THREAD

**Issue by zhengzhejun** [vespa-engine/vespa#4557]
As say in title, from today, I cannot get com.yahoo.vespa:bundle-plugin:6-SNAPSHOT from maven repository http://yahoo.bintray.com/maven.  And I notice that this repository do not have bundle-plugin. Has some changes happened in this maven repository?

**Comment by aressem** [comment]
@zhengzhejun Could you provide some more information about what you are trying to do ? We do not publish snapshots to  http://yahoo.bintray.com/maven.

**Comment by zhengzhejun** [comment]
I find out reason of this problem. I forget run "bootstrap.sh java" command before I compile the whole project with maven. Without "bootstrap.sh java", there is no bundle-plugin.jar in my local maven repository. Sorry and thanks for answer my question.

**Comment by gjoranv** [comment]
@zhengzhejun, thanks for the update. It's an easy thing to forget. I'll keep this in mind for the next time someone encounters the same problem.
