### ISSUE TITLE
Error happened when compile vespa with -O0 optimizer flag 

### ISSUE THREAD

**Issue by zhengzhejun** [vespa-engine/vespa#4565]
I use code from version 6.192.4 and in order to debug vespa with gdb, I modified c++ compile optimization flag in `build_settings.cmake` file at line 27 as follow
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g **-O3** -fno-omit-frame-pointer ${C_WARN_OPTS} -fPIC ${VESPA_CXX_ABI_FLAGS} -DBOOST_DISABLE_ASSERTS
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g **-O0** -fno-omit-frame-pointer ${C_WARN_OPTS} -fPIC ${VESPA_CXX_ABI_FLAGS} -DBOOST_DISABLE_ASSERTS

then I got error when building vespa.
`/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++_nonshared.a(cow-stdexcept.o): In function `std::__sso_string::__sso_string(std::string const&)':
(.text._ZNSt12__sso_stringC2ERKSs+0x8): undefined reference to `std::__sso_string::__sso_string(char const*, unsigned long)'
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++_nonshared.a(cow-stdexcept.o): In function `std::_V2::error_category::_M_message(int) const':
(.text._ZNKSt3_V214error_category10_M_messageEi+0x30): undefined reference to `std::__sso_string::__sso_string(char const*, unsigned long)'
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: config_print_test_app: hidden symbol `_ZNSt12__sso_stringD2Ev' isn't defined
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [config/src/tests/print/config_print_test_app] Error 1
make[1]: *** [config/src/tests/print/CMakeFiles/config_print_test_app.dir/all] Error 2`

As error log said, error comes from phase of linking __sso_string in devtoolset-7/libstdc++_nonshared.a. I google this error, and found that it may be caused by a bug in devtoolset-7.  [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1519073). I found that in the early version of vespa, it use devtoolset-6, and with devtoolset-6, I can build project with **-O0** flags successfully. 
So is there any other way to build project with **-O0** optimizer flags in latest version?

**Comment by baldersheim** [comment]
No, we have not built with -O0 for many years. We use -Og instead if we need it to be debuggable.  I guess redhat will fix their bug soon.
I will give it a go with -O0 to see if I get the same error.

**Comment by zhengzhejun** [comment]
Thanks for your help. I have tried to build project with -Og, and it works and can be debuggable. you can close this issue.

**Comment by baldersheim** [comment]
Thanks for reporting. I will consider adding -O0 to the list of tests we do before changing compiler.
