### ISSUE TITLE
Some tools not working in Docker image

### ISSUE THREAD

**Issue by zhaakhi** [vespa-engine/vespa#4584]
The `vespaengine/vespa` Docker image includes some tools that appear to be missing files or config.

`vespa-query-profile-dump-tool`, mentioned in http://docs.vespa.ai/documentation/query-profiles.html, outputs
```
env: /opt/vespa/bin/vespa-query-profile-dump-tool-bin: No such file or directory
```

`vespa-validate-application basic-search/src/main/application/`  outputs
```
  Error: Unable to access jarfile /opt/vespa/lib/jars/jing.jar
  Error: Unable to access jarfile /opt/vespa/lib/jars/jing.jar
```

`vespa-run-as-vespa-user echo` outputs
```
FATAL error: user 'yahoo' missing in passwd file
```

**Comment by arnej27959** [comment]
these issues should be fixed by changes in:
https://github.com/vespa-engine/vespa/pull/4625
