### ISSUE TITLE
Error happend when import third part java library

### ISSUE THREAD

**Issue by zhengzhejun** [vespa-engine/vespa#4604]
Hi guys, I encounter errors when I import third part java library in my application.
my pom.xml is [here](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/pom.xml). xiaomi-common-zookeeper, hbase-client, commons-codec are the dependencies I want to import. And when I package my application, prepare and activate, I found that there are some error happened. vespa error log is [here](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/vespa.log). Do these kinds of errors means I need more specific configuration in my pom.xml?

**Comment by baldersheim** [comment]
@gjoranv Can you have a go at this one.

**Comment by gjoranv** [comment]
@zhengzhejun The error message:
```
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle duokanexample [54]: Unable to resolve 54.0: missing requirement [54.0] osgi.wiring.package; (&(osgi.wiring.package=net.jpountz.xxhash)(version>=1.3.0)(!(version>=2.0.0)))
```
means that your bundle needs the java package `net.jpountz.xxhash`version [1.3.0, 2.0.0). This is probably because one of the xiaomi libraries refer to it. (I'm unable to build your project or investigate further because those libs are not available from the central maven repo.)

I sent a [PR](https://github.com/zhengzhejun/vespa-sample/pull/1) to resolve this issue. If you see more 'unresolved constraint' errors, you can try to search [maven central](http://search.maven.org/#search%7Cga%7C1%7Cfc%3Anet.jpountz.xxhash) to find the correct maven artifact to add to your pom.xml.

**Comment by zhengzhejun** [comment]
@gjoranv thanks for your advise. I added `net.jpountz.lz4:lz4:1.3.0` dependency in my pom.xml and it works. 
you guessed that my third part library may refer to net.jpountz.lz4. But when I use `mvn dependency:tree -Dverbose` to find out where net.jpountz.lz4 comes from, and I see that net.jpountz.lz4 just comes from several vespa submodule. [here](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/dependency-tree.log) is dependency tree log.

**Comment by zhengzhejun** [comment]
After successfully add third part libray, I haved encontered another errors. In my application, we need to go through kerberos authentication. but I have the problem as blow.
`Caused by: java.lang.ClassNotFoundException: sun.security.krb5.Config not found by duokanexample`. the detail log is [here](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/vespa-kerberos-error.log). I google that problem and find some relative discussion about this error. [How to access the internal sun.security class from an OSGI bundle?
](https://stackoverflow.com/questions/4462154/how-to-access-the-internal-sun-security-class-from-an-osgi-bundle). Have you guys encounter such problems before?

**Comment by gjoranv** [comment]
That package is in rt.jar, and not exported via OSGi from the Vespa container. I'm not sure it's a good idea to use that class. But if you have no alternative, please try the following `config` hack in your services.xml (under the `jdisc` element, as shown below):

```
<jdisc version="1.0">
    <config name="search.config.qr-start">
        <jdisc>
            <export_packages>sun.security.krb5</export_packages>
        </jdisc>
    </config>
    ...
</jdisc>
```

**Comment by zhengzhejun** [comment]
Hi @gjoranv as you said, I add jdics config in my application [services.xml](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/src/main/application/services.xml) and I got such error when I prepare my application.

`Preparing session 2 using http://localhost:19071/application/v2/tenant/default/session/2/prepared
Request failed. HTTP status code: 400
Invalid application package: default.default: Error loading model: container2 cannot reserve port 8080 on host 'tj1-s-staging-rec06.kscn': Already reserved for container. You must set port explicitly for all instances of this service type, except the first one. Next available port is: 19105 ports used: {8080=container on host 'tj1-s-staging-rec06.kscn', 19100=container on host 'tj1-s-staging-rec06.kscn', 19101=container on host 'tj1-s-staging-rec06.kscn', 19102=container on host 'tj1-s-staging-rec06.kscn', 19103=container on host 'tj1-s-staging-rec06.kscn', 19104=container on host 'tj1-s-staging-rec06.kscn'}`

the detail log file is [here](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/vespa-jdisc-error.log)

I guess I put <jdisc> config in error place.

**Comment by gjoranv** [comment]
@zhengzhejun Sorry, I forgot that the official name of the element is 'container'. (It used to be 'jdisc' some time back.) You probably already have a 'container' element in your services.xml, so please try moving the config inside that element instead.

**Comment by zhengzhejun** [comment]
@gjoranv I fix my [services.xml](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/duokan-example/src/main/application/services.xml) as you say. but it does not work.

**Comment by gjoranv** [comment]
Yes, you are right. I created a PR for you with the necessary configuration to the bundle-plugin:
https://github.com/zhengzhejun/vespa-sample/pull/2

**Comment by zhengzhejun** [comment]
@gjoranv it works. thanks again, you provide great help to me, and you can close this issue.

**Comment by gjoranv** [comment]
Great, thanks for the update!
