### ISSUE TITLE
Is there any design documents?

### ISSUE THREAD

**Issue by mjason3** [vespa-engine/vespa#4686]
Hi, I am trying to understand the design of vespa. Is there any detailed design doc or architecture diagram?

**Comment by kkraune** [comment]
I'd start with:

http://docs.vespa.ai/documentation/overview.html

http://docs.vespa.ai/documentation/elastic-vespa.html is also good wrt stateful components

The search core: http://docs.vespa.ai/documentation/proton.html

stateless container: http://docs.vespa.ai/documentation/container-intro.html

please feed back suggestions for improvement / make PRs :-) Thanks

**Comment by bratseth** [comment]
This will give you some information, but there is no coherent design documentation of the internals of the engine unfortunately, only use level documentation.

If you have specific questions/areas of interest feel free to ask here.

**Comment by mjason3** [comment]
thanks @kkraune @bratseth for the kind reply. i think that's pretty good for me to start with. I am from search team of an e-commerce company, so my perspective of understanding different search engines is from its design and design consideration. Vespa is quite interesting and want to know deeper(maybe I need to read more source code)
