### ISSUE TITLE
Build and document Play with Docker tutorial

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#4715]
The [Play with Docker](https://labs.play-with-docker.com/) service allows you to spin up several Docker containers with shell (and even SSH access) in your browser using a predefined config file. This means we could build a Vespa tutorial where the user with a single click could get up both single- and multi-node applications inside their browser window in seconds without installation of git, docker, etc. on their local machine - on any OS. You could play with Vespa from your Chromebook without going through the AWS setup.

The sessions are limited to four hours, but should be sufficient to start testing and to achieve the "instant gratification effect".

More information: http://training.play-with-docker.com/
Inspiration: https://github.com/portainer/portainer-demo/blob/master/play-with-docker/docker-stack.yml

**Comment by frodelu** [comment]
@aressem : FYI

**Comment by aressem** [comment]
I have created a basic search example that uses Docker Swarm here:
https://github.com/vespa-engine/sample-apps/tree/master/basic-search-on-docker-swarm

This tutorial can be executed on [Play with docker](https://labs.play-with-docker.com/).
