### ISSUE TITLE
Pre-computed dataset for Vespa Tutorial pt.3 is not available

### ISSUE THREAD

**Issue by abmo** [vespa-engine/vespa#4836]
Hi!
According to the dataset generation script, "blog-tutorial-shared/src/R/generateDataset.R", some JSON files are necessary to create the training dataset.
I would like to know if that necessary JSON content is contained into all RDD data files generated in previous steps of the tutorial pt.2 and located in "blog-job" folder. In affirmative case, could it be possible to transform the RDD data to an only JSON file that it is required by the generateDataset.R script? 
Thank you!

**Comment by lesters** [comment]
Hi! The data required should indeed be generated in part 2. There is also some auxiliary information here: https://github.com/vespa-engine/sample-apps/tree/master/blog-tutorial-shared#train-model-with-tensorflow.

We have not made this pre-computed dataset available yet, though we have discussed this. Would it be of help to you if we did?

**Comment by abmo** [comment]
Hi! Thanks for your quick response :)
Until this point of the tutorial, I did all previous steps according your documentation. But when I have tried to run the script generateDataset.R, I've realized that the *.json files are not generated, but the RDD files.
Since I am new with Spark and Pig, I am not sure if it is possible to modify the scripts in order to generate the JSON and not the RDD files.

**Comment by lesters** [comment]
Ok, I see. After running the step to tune the model in the 2nd part (http://docs.vespa.ai/documentation/tutorials/blog-recommendation.html#model-tuning-and-offline-evaluation), you have a directories `blog-job/user_item_cf_cv/product_features` and `blog-job/user_item_cf_cv/user_features`. The files under those directories (part-0000*) are in fact the files that you use in `generateDataset.R`, as they are files with one JSON per line. 

Simply concatenate those files together. So, in the `sample-apps/blog-recommendation` directory after running the Spark jobs:

```
$ cat blog-job/user_item_cf_cv/product_features/part-0000* > blog-job/user_item_cf_cv/product.json
$ cat blog-job/user_item_cf_cv/user_features/part-0000* > blog-job/user_item_cf_cv/user.json
$ cat blog-job/training_and_test_indices/training_set_ids/part-000* > blog-job/training_and_test_indices/train.txt

$ r --vanilla < ../blog-tutorial-shared/src/R/generateDataset.R
```

That should get this script running. I'll update the tutorial and readme with this.

**Comment by abmo** [comment]
Yes! That's right! It is running now!
Thank you so much for your response ;)

**Comment by lesters** [comment]
No problem, have fun!
