### ISSUE TITLE
A problem when third part java library imported into Container

### ISSUE THREAD

**Issue by zhengzhejun** [vespa-engine/vespa#4925]
Hi I have some problem when I need to import third part library into my application container.
In my application, I use a class named Perfcounter.java from a third part library. So when I prepare and activate my application, the Perfcounter.java will be loaded as part of application bundle by felix, and Perfcounter.java will **start a thread to execute some task periodically**.
And problem comes out when I secondly prepare and activate my application, Vespa will uninstall the old application, and install new application bundle, and It will cause Perfcounter.java will be loaded second time, **and start a new thread without stopping the old thread** which is not acceptable.
Is there some way to solve such problem?
My current idea abount this problem is that I can install the third part libray when my applicaiton container initialization step. But I have not tried this idea. Is there any other better solutions?

**Comment by jobergum** [comment]
Hi! Please see the section about 'Resource management' in http://docs.vespa.ai/documentation/jdisc/container-components.html
