### ISSUE TITLE
yum install failed vespa-libtorrent-devel and vespa-zookeeper-c-client-devel

### ISSUE THREAD

**Issue by zhengzhejun** [vespa-engine/vespa#5007]
I have successfully install vespa-6.192.4 with this [script](https://github.com/zhengzhejun/vespa-sample/blob/hbase-test/vespa-install.sh) serveral days before. I write this script based on this [dockerfile](https://github.com/vespa-engine/docker-image-dev/blob/master/Dockerfile).
But today I tried to install vespa in another machine, and There is a error that `Error: No Package found for vespa-libtorrent-devel >= 1.0.11-6
Error: No Package found for vespa-zookeeper-c-client-devel >= 3.4.9-6` 
Is vespa-libtorrent-devel and vespa-zookeeper-c-client-devel not available recently?

**Comment by hmusum** [comment]
vespa-libtorrent-devel  and vespa-zookeeper-c-client-devel are not used anymore, you should remove them from your script (dockerfile has been updated). Thanks for the report!
