### ISSUE TITLE
No Search Results

### ISSUE THREAD

**Issue by harryjackson** [vespa-engine/vespa#5202]
I've loaded about 109,000 documents using the client jar for bulk loading and it appears to load fine ie I get this:

]# java -jar /opt/vespa/lib/jars/vespa-http-client-jar-with-dependencies.jar --verbose --validate  --file /app/contacts.json --host localhost --port 8080 --whenVerboseEnabledPrintMessageForEveryXDocuments 1000
...
Sun Mar 04 05:58:07 UTC 2018 Result received: 106000 (0 failed so far, 106008 sent, success rate 13333.33 docs/sec).
Sun Mar 04 05:58:07 UTC 2018 Result received: 107000 (0 failed so far, 107007 sent, success rate 12195.12 docs/sec).
Sun Mar 04 05:58:08 UTC 2018 Result received: 108000 (0 failed so far, 108009 sent, success rate 12987.01 docs/sec).
Sun Mar 04 05:58:08 UTC 2018 Result received: 109000 (0 failed so far, 109010 sent, success rate 13333.33 docs/sec).
Waiting for all results, sent 109486 docs.
...

If I search I have nothing:

$ curl -s http://localhost:8080/search/?query=e |python -m json.tool

{
    "root": {
        "coverage": {
            "coverage": 100,
            "documents": 0,
            "full": true,
            "nodes": 1,
            "results": 1,
            "resultsFull": 1
        },
        "fields": {
            "totalCount": 0
        },
        "id": "toplevel",
        "relevance": 1.0
    }
}

I'm sure I'm being daft but cannot for figure out how to search the docs I just loaded.

**Comment by bratseth** [comment]
What's in your search definition?

**Comment by harryjackson** [comment]
search contact {

    document contact {

        field firstname type string {
            indexing: summary | index
        }

        field lastname type string {
            indexing: summary | index
        }

        field middlename type string {
            indexing: summary | index
        }

        field nickname type string {
            indexing: summary | index
        }

        field jobtitle type string {
            indexing: summary | index
        }

        field department type string {
            indexing: summary | index
        }
        
        field emails type string {
            indexing: summary | index
        }

        field phonenumbers type string {
            indexing: summary | index
        }

    }

    fieldset default {
        fields: firstname, lastname, middlename, nickname, jobtitle, department, emails, phonenumbers 
    }

    rank-profile person inherits default {
        first-phase {
            expression:nativeRank(emails,firstname,phonenumbers,lastname,department)
        }
    }
}

**Comment by harryjackson** [comment]
I noticed I had --validate in the original command. Removing it made no difference :(. I then noticed this command

vespa-feeder /app/contacts.json

and it seemed to load the documents just fine but using

java -jar /opt/vespa/lib/jars/vespa-http-client-jar-with-dependencies.jar --verbose --file /app/contacts.json --host localhost --port 8080

with the same doc set doesn't load anything and give me the following output.

INFO: Problem with Handshake localhost:8080 ssl=false: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused): Connection refused (Connection refused)
Mar 05, 2018 7:51:45 PM com.yahoo.vespa.http.client.core.communication.IOThread cycle
INFO: Problem with Handshake localhost:8080 ssl=false: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused): Connection refused (Connection refused)
Mar 05, 2018 7:51:45 PM com.yahoo.vespa.http.client.core.communication.IOThread cycle
INFO: Problem with Handshake localhost:8080 ssl=false: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused): Connection refused (Connection refused)
Mar 05, 2018 7:51:45 PM com.yahoo.vespa.http.client.core.communication.IOThread cycle
INFO: Problem with Handshake localhost:8080 ssl=false: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused): Connection refused (Connection refused)

**Comment by bratseth** [comment]
Yes, with --validate you're not really feeding anything just validating.
Your search definition looks fine.
So, you managed to feed the data with vespa-feeder, and search it - correct?

If so, we're left with why the document HTTP interface does not work for you (vespa-feeder uses another API). Perhaps you haven't added the document API to your container (<document-api/>)?

**Comment by harryjackson** [comment]
This is my services.xml. I believe "<document-api />" is all that's required to add the api.

<?xml version="1.0" encoding="utf-8" ?>
<services version="1.0">

  <container id="default" version="1.0">
    <document-api />
    <search />
    <nodes>
      <node hostalias="node1" />
    </nodes>
  </container>

  <content id="contact" version="1.0">
    <redundancy>1</redundancy>
    <search>
       <visibility-delay>10.0</visibility-delay>
    </search>
    <documents>
      <document type="contact" mode="index" />
    </documents>
    <nodes>
      <node hostalias="node1" distribution-key="0" />
    </nodes>
    <engine>
      <proton>
         <searchable-copies>1</searchable-copies>
         <resource-limits>
           <disk>0.80</disk>
           <memory>0.95</memory>
         </resource-limits>
      </proton>
    </engine>
  </content>

</services>

**Comment by bratseth** [comment]
Yes, all that's needed is to have the <document-api> tag.
Connection refused means your client cannot even connect to localhost:8080, I don't think you see that a time when you can issue a query to that container.

Run vespa-logfmt -l warning,error to see why the HTTP server has not come up, perhaps the port is bound by some other process

**Comment by jobergum** [comment]
@harryjackson were you able to proceed ?

**Comment by harryjackson** [comment]
I used vespa-feeder and it worked fine. The method in the docs didn't work.

**Comment by harryjackson** [comment]
I can close this if you want since I'm unblocked?
