### ISSUE TITLE
Container exiting due to error "No support for packet 220"

### ISSUE THREAD

**Issue by knowmara** [vespa-engine/vespa#5247]
hi all,
we met a fatal error on container which describes as follow:
          `java.lang.IllegalArgumentException: No support for packet 220
	at com.yahoo.fs4.PacketDecoder.decode(PacketDecoder.java:56)
	at com.yahoo.fs4.PacketDecoder.decodePacket(PacketDecoder.java:65)
	at com.yahoo.fs4.PacketDecoder.extractPacket(PacketDecoder.java:197)
	at com.yahoo.fs4.mplex.FS4Connection.extractPackets(FS4Connection.java:241)
	at com.yahoo.fs4.mplex.FS4Connection.read(FS4Connection.java:225)
	at com.yahoo.io.Listener.performRead(Listener.java:503)
	at com.yahoo.io.Listener.selectLoop(Listener.java:309)
	at com.yahoo.io.Listener.run(Listener.java:267)
`
looking forward to some advice.
thanks

**Comment by baldersheim** [comment]
This I have never seen.....
Do you have the query issued causing this ?

**Comment by baldersheim** [comment]
Hmm, I see that code 220 is a PingPacket that should never be sent there.
Could you attach your services.xml file and also provide the output of 
vespa-model-inspect hosts
and
vespa-model-inspect host `hostname`

**Comment by knowmara** [comment]
Thanks for your reply.
So sorry,i I solved it but i did not save the exception scene.I found that the top-level-dispacher was down for port occupation by another process on the host where we encountered the error,when i  cleared out the port,the error disappear.
Does it mean something?

**Comment by baldersheim** [comment]
That explains the error. It received a message intended for the top-level-dispatcher.
Closing issue then.

**Comment by knowmara** [comment]
Thanks,but i have some doubts.
Why the ping packet is sent to a container process when the TLD down, and who sends it?
In my opinion, container can find the TLD from Cluster Controller.When TLD is down,anyone can not find the fs4 port,how can one send a ping packet.Even if one knew the fs4 port, the port of container is different from the TLD fs4 port,so how can a container receive the ping packet?

**Comment by baldersheim** [comment]
You said that TLD was down due to someone else occupying the port. I guess the container was the one occupying the port. The purpose of the Ping packet is to verify if the TLD is up and is sent to the port the TLD should be listening too. But since someone else listens on this port they will then receive the PingPacket intended for the TLD.

**Comment by knowmara** [comment]
In fact,the local slobrok occupied the port at that moment.
Where does the container get the port of TLD?

**Comment by baldersheim** [comment]
That is propagated through config at the time you deploy your application.

**Comment by knowmara** [comment]
Thanks.
If just read the static configuration, I feel there will be inconsistencies like I encountered before.

**Comment by baldersheim** [comment]
When you deployed the new application package you should have gotten a message saying that some services would require a restart.
Some of the services will detect that they need to restart and do that automatically. However there might be situations where the system will be in an inconsistent state for a shorter period of time causing issue like you saw here.

However this should only happen where you do topological changes where the set of services running on a host is changed.

**Comment by knowmara** [comment]
Thanks a lot ~
