### ISSUE TITLE
Write Datadog integration for Vespa metrics

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#5322]
In order to allow collection of Vespa metrics into [Datadog](https://www.datadoghq.com/), we should have a [Datadog integration](https://docs.datadoghq.com/developers/integrations/) that would grab metrics from the metricsproxy and forward into Datadog.

**Comment by gjoranv** [comment]
PR: https://github.com/DataDog/integrations-extras/pull/466

**Comment by frodelu** [comment]
I believe this can be closed at this point, @gjoranv ?

**Comment by gjoranv** [comment]
Certainly, thanks!
