### ISSUE TITLE
Provide a changelog and upgrade guide

### ISSUE THREAD

**Issue by bratao** [vespa-engine/vespa#5371]
Hello, 

First of all, thank you so much for this project. This has been an Elastic Search killer for me. I´m delighted about the performance and reliability. I will release soon a Python and PHP lib we developed internally for communicating with Vespa.

But one thing is missing for me is a changelog, and a upgrade guide so I can plan my deployment. What is the best practice ? Should keep continually upgrade Vespa? What If I upgrade my nodes a year from now, it will be a supported path ?

Thank you again for this awesome project!

**Comment by kkraune** [comment]
Hi, thanks for the nice words and thanks for contributing!

Find details on Vespa versioning at http://docs.vespa.ai/documentation/vespa-versions.html. In short, take care when upgrading across major versions. Some more on the process itself: http://docs.vespa.ai/documentation/operations/live-content-cluster-upgrade.html (note to self: this doc needs to be freshened up)

Generally it is better to to smaller updates, often. This reduces risk of errors as changes are smaller - and you get access to new features. The APIs should let you build automation for this without too much work.

We do not keep a changelog, we try to use issues for the relevant changes, but I know this can be a bit hard to track.

I will think a bit more about documentation for upgrades, thanks for the reminder

**Comment by bratao** [comment]
Thank you!

We going to adopt an rolling upgrade process!

Feel free to close the ticket!
