### ISSUE TITLE
One host for only one tenant?

### ISSUE THREAD

**Issue by FrankYu0502** [vespa-engine/vespa#5425]
Hello guys,

I created two tenants (yfrapp, yfrapp1) and deploy two different applications with same container nodes and content nodes in services.xml. Then I got a error like this.

Session 2 for tenant 'yfrapp' created.
Preparing session 2 using http://localhost:19071/application/v2/tenant/yfrapp/session/2/prepared
Request failed. HTTP status code: 400
Invalid application package: yfrapp.default: Error loading model: 'yfrapp' tried to allocate host 'tj-s-staging-rec09.kscn', but the host is already taken by 'yfrapp2

Is that means one host could only be taken by one tenant?

Thanks!

**Comment by FrankYu0502** [comment]
Could one sentinel start multiple containers, protons, distributors for more than one application in one host?

**Comment by bratseth** [comment]
One application (= one application package) requires unique hosts. That application can have multiple clusters and those clusters can use the same hosts.

If you want to deploy multiple independent applications to the same physical hosts I recommend splitting them up into multiple logical hosts using Docker.
