### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by elgalu** [vespa-engine/vespa#5448]
Hi, I was trying to figure out how to deploy this with auto-scaling in Kubernetes but only found a small quick start without any scaling capabilities:
http://docs.vespa.ai/documentation/vespa-quick-start-kubernetes.html

Do you plan to maintain K8s manifests for Vespa production deployments?

**Comment by bratseth** [comment]
Eventually yes, but we won't have time to work on it for a while. You're welcome to contribute  :-)

**Comment by mjason3** [comment]
Any plan on this？

**Comment by kkraune** [comment]
No short term plans, but contributions are welcome :-)

**Comment by griseau** [comment]
Hi guys, I'm currently working on a GKE version with multi nodes set-up. 

Still some stuff to work on, but I have a first working version that I'm happy to share if you want !

**Comment by griseau** [comment]
I've been pretty busy in the last few months, but finally : https://github.com/vespa-engine/sample-apps/pull/359

**Comment by bratseth** [comment]
Great work, thanks!
