### ISSUE TITLE
Documentation not searchable when using https

### ISSUE THREAD

**Issue by zhaakhi** [vespa-engine/vespa#5506]
https://docs.vespa.ai/search.html?q=foo

Logs an error in the browser console:

```jquery.min.js:4 Mixed Content: The page at 'https://docs.vespa.ai/search.html?q=foo' was loaded over HTTPS, but requested an insecure script 'http://doc-search.vespa.ai/vespa_documentation_search_proxy/search/?jsoncallback=jQuery2240877675790577271_1523268842851&query=foo&hits=400&ranking=documentation&_=1523268842852'. This request has been blocked; the content must be served over HTTPS.```

**Comment by frodelu** [comment]
Officially, ["HTTPS is not supported for GitHub Pages using custom domains"](https://help.github.com/articles/securing-your-github-pages-site-with-https/) so I must admit I was surprised to learn that https://docs.vespa.ai/ even worked. 😃 

Seems GitHub is the process or rolling out Let's Encrypt certificates for custom domains, but if you look at https://vespa.ai/ it is still (as of writing) giving the generic *.github.com certificate and thus insecure.

Short answer; we haven't done the work needed to support HTTPS for our docs pages yet, but I'll keep this issue open so we can address that. Shouldn't be too much work.

**Comment by frodelu** [comment]
In the meantime, I'm afraid you'll have to use insecure version, i.e.:
http://docs.vespa.ai/search.html?q=foo

**Comment by frodelu** [comment]
@lesters : Resetting milestone in light of both https://docs.vespa.ai and https://vespa.ai now properly working and our plan to move a bit around on the doc search shortly anyway.

**Comment by lesters** [comment]
This has now been fixed: https://docs.vespa.ai/search.html?q=foo should now work as intended.
