### ISSUE TITLE
Don't autostart config servers in Docker image

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#5586]
Currently our images autostarts both services and vespa-config-server. 
This makes quickstarts simpler but makes it harder to create a working multinode system, or to understand what to do to restart Vespa.

How to start and stop services and config servers are documented only in http://docs.vespa.ai/documentation/reference/files-processes-and-ports.html
which is too hard to find.

**Comment by jazoom** [comment]
It's a difficult decision since if you remove that from the Docker image I'll just have to add it back in my own custom Docker image, won't I? That makes it not just an issue of learning curve and findable information but also one of implementation convenience.

**Comment by bratseth** [comment]
Yes, I think we should autostart services but not config servers, and link to how to start/stop from the quickstarts.

**Comment by aressem** [comment]
@bratseth The image entry point takes an argument which allow you to specify what to start. This will start only services and not the configserver:
```
docker run -d -e VESPA_CONFIGSERVERS=<your configservers> vespaengine/vespa services
```
Is this an acceptable solution ?

**Comment by bratseth** [comment]
Yes, I think so. Would be nice to document that in the multinode setup doc.
