### ISSUE TITLE
Cannot create a new service when another one already exists

### ISSUE THREAD

**Issue by jazoom** [vespa-engine/vespa#5596]
I previously followed along with the quick start and ended up with a `music` service.

I decided to then change all the application files to test out my own data set and got this error when trying to deploy:
`Invalid application package: default.default: Error loading model: content-cluster-removal: Content cluster 'music' is removed. This will cause loss of all data in this cluster`

I then found this information: https://docs.vespa.ai/documentation/reference/vespa-cmdline-tools.html

That talks about `vespa-remove-index`, which I then used to remove the `music` index. Unfortunately it only removed the index on one the particular node it was run from, so I had to `docker exec` into each individual node's container and remove the index. That was quite a bit of work so I'm assuming there's a better way to do that?

Though, perhaps it wasn't even the correct thing to do since I *still* get the same error when trying to deploy my new package.

I then read through this information: https://docs.vespa.ai/documentation/operations/admin-procedures.html

>Add or remove services on a node
If changing the services on a given host, stop Vespa on the given host before running vespa-deploy activate.

So I ran `/opt/vespa/bin/vespa-stop-services` and tried again to deploy my new application.

*Again*, the same error.

I must be completely missing something here.

Sure, I *could* wipe the docker volumes and start again from scratch, but this is pretty basic admin stuff here that I need to get sorted out before I ever put this thing into production.

**Comment by jobergum** [comment]
This is exactly what you want to prevent disasters in production. http://docs.vespa.ai/documentation/reference/validation-overrides.html

**Comment by knowmara** [comment]
In my opinion,It was caused for the reason that one node only can be allocated to one application,maybe you need to delete the application you deployed on the past before you deploy a new one:
   `DELETE /application/v2/tenant/[tenant name]/application/[application name]`
Then vespa-stop-services-->vespa-start-services-->deploy the new application
I did it like above, I succeeded. I don't know it's right or wrong.So, @jobergum  how can I completely delete an application I ever deployed and which is now running?

**Comment by jobergum** [comment]
The invalid application package deploy error can be workaround by adding a validation override as described in http://docs.vespa.ai/documentation/reference/validation-overrides.html. This is a mechanism to prevent removing a content cluster from a production cluster. 

If you want to wipe all state from a playground type of installation you can wipe configuration server state on all configuration server instances by 

- vespa-configserver-remove-state described in http://docs.vespa.ai/documentation/cloudconfig/configuration-server.html. Run on all configuration instances
- Wipe content node state by the vespa-remove-index utility described https://docs.vespa.ai/documentation/reference/vespa-cmdline-tools.html. Run on all content node instances.

**Comment by jobergum** [comment]
On the documentation format and navigation, I agree that it's not super easy to navigate. Contributions on this would be appreciated. The 404 for the reference we could fix by adding a new toc through a index file but the left pane navigation issue would still be the same. 

We try to add and update documentation as we get feedback, e.g we just added documentation on docker swarm based on recent feedback on multi-node docker installation issues. 
 https://github.com/vespa-engine/sample-apps/tree/master/basic-search-on-docker-swarm

**Comment by jazoom** [comment]
It's not just the finding of this page, since I didn't even know I should be looking for such a concept. It might be worth mentioning somewhere in the first several introductory documents that the database has this protection mechanism and that there is a way to override it.

> Contributions on this would be appreciated.

Probably a lot of people (myself included) would be happy to contribute eventually but we have to actually understand how things work first. I actually much prefer your documentation to most other databases I've used in the past. Everything is (or at least seems to be) reachable from the one docs page, and there is only one docs page. I know this is a new open source project and the community is small. I really like the ideas and experience that have gone into this database and I want to support it.

> We try to add and update documentation as we get feedback, e.g we just added documentation on docker swarm based on recent feedback on multi-node docker installation issues.

Yes, your team is very responsive. Often feedback on open source projects is met with defensiveness, which discourages further feedback. I feel that even though your primary responsibility is to keep it working well for Yahoo, your team also genuinely wants to make this open source project work.

**Comment by bratseth** [comment]
Good point about changing applications during development. I added section on that to the intro doc on application packages. It actually mentions validation-overrides already, but only in passing. https://github.com/vespa-engine/documentation/pull/285

Regarding having all the doc pages in the toc: We tend to go back and forth on that issue. A complete toc make it so long that it loses the property of providing an overview. On the other hand if we leave something out we have this issue.

**Comment by jazoom** [comment]
> Regarding having all the doc pages in the toc: We tend to go back and forth on that issue. A complete toc make it so long that it loses the property of providing an overview. On the other hand if we leave something out we have this issue.

Yes, it's already too long as it is. May I suggest using collapsible menu headers? You already have the headers there. Use them as toggles. It would immediately be easier to navigate *plus* you would be able to add more links to useful information.

The only downside I can think of is you would no longer be able to `ctrl + f` to find the topic you're looking for, but that can easily be fixed by adding an `Expand All` toggle up top.
