### ISSUE TITLE
Fields with no summary in indexing statement are added to default Summary Fields

### ISSUE THREAD

**Issue by SarathKumar-k** [vespa-engine/vespa#5619]
Initially, Have defined few fields (for eg. x,y,z) to be part of summary in their indexing statement. Deployed the application and verified that the fields (x,y,z) are coming as part of response.
In the next version, removed the summary for the above said fields(x,y,z) in their indexing statement and added document summaries (for eg. x_summary with only field x, y_summary with only field y). Re-deployed the application. On each request post the deployment, fields (x,y,z) are returned as part of every request if no summary is specified in the query. If summary is specified (by appending &summary=x_summary), it's returning only the fields that are specified in the document summary in search definition.

When inspected the summary.cfg file inside the config folder of document, these entries are available

defaultsummaryid 1034559025
classes[0].id 1034559025
classes[0].name "**default**"
classes[0].fields[0].type "longstring"
classes[0].fields[0].name "x"
classes[0].fields[1].type "longstring"
classes[0].fields[1].name "y"
classes[0].fields[2].type "longstring"
classes[0].fields[2].name "z"
classes[1].id 103598991
classes[1].name "**x_summary**"
classes[1].fields[0].type "jsonstring"
classes[1].fields[0].name "x"
classes[2].id 173977422
classes[2].name "**y_summary**"
classes[2].fields[0].type "longstring"
classes[2].fields[0].name "y"

As per understanding, only the fields other that built-in fields (documentId ect) that are marked as summary in their indexing statement should be returned as part of response if no summary is specified in the query.

**Comment by jobergum** [comment]
There is no support for controlling the default summary class and every field which has been marked as available for summary is going to be added to the default summary (either by explicit summary in the indexing statement or referred in a explicit document-summary 

e.g 

```
search foo {
 document foo {
  field x type string {
   indexing: index
  }
 field y type string {
   indexing: summary | index
   summary-to:x
  }
 }
 document-summary x {
  summary x type string {
     source: x
   }
 }
}
```
Both x and y will be part of the default summary. It's a catch all fields.

**Comment by SarathKumar-k** [comment]
In the initial version search definition was 

search foo {
 document foo {
  field x type string {
   indexing: summary | index
  }
 field y type string {
   indexing: summary | index
  }
 }
}

With this schema, default summary includes both x and y. Understood.

Later, revised the scheme to below

search foo {
 document foo {
  field x type string {
   indexing: index
  }
 field y type string {
   indexing: index
  }
 }
document-summary x {
  summary x type string {
     source: x
   }
 }
document-summary y {
  summary y type string {
     source: y
   }
 }
}

With this schema, default summary shouldn't include x and y right? summary.cfg file 

defaultsummaryid 1034559025
classes[0].id 1034559025
classes[0].name "**default**"
classes[0].fields[0].type "longstring"
classes[0].fields[0].name "x"
classes[0].fields[1].type "longstring"
classes[0].fields[1].name "y"
classes[1].id 103598991
classes[1].name "**x_summary**"
classes[1].fields[0].type "longstring"
classes[1].fields[0].name "x"
classes[2].id 173977422
classes[2].name "**y_summary**"
classes[2].fields[0].type "longstring"
classes[2].fields[0].name "y"

**Comment by jobergum** [comment]
Yes, as I wrote in my response. The default is a catch all fields that are available for summary and when you add y to document-summary y it also becomes available in default as default catches all.

**Comment by SarathKumar-k** [comment]
This behaviour applies to import fields too from other document?

**Comment by jobergum** [comment]
imported fields http://docs.vespa.ai/documentation/reference/search-definitions-reference.html#import-field are not added to the default summary for the child document type no.

**Comment by SarathKumar-k** [comment]
Thanks. Understood.
