### ISSUE TITLE
Document ranking.matchPhase, ranking.softtimeout and ranking.diversity in the search API reference

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#5728]
These three are missing from http://docs.vespa.ai/documentation/reference/search-api-reference.html

**Comment by bratseth** [comment]
> in this document I also find some diversity - is this what you mean by ranking.diversity, @bratseth ?

Those attributes are to ensure diversity in the context of using matchPhase only: matchPhase is a feature which throws away hits. The matchPhase.diversity feature tells Vespa to prefer keeping hits which increases diversity.

**Comment by kkraune** [comment]
@jobergum FYI

**Comment by bratseth** [comment]
Done
