### ISSUE TITLE
Add general search latency rank profile metric with rank-profile name as dimension

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#5750]
Currently we have these :

proton.doctypes.<doc-type>.matching.querylatency
proton.doctypes.<doc-type>.<rank-profile>.match_time

Instead we should do 

proton.doctypes.matching.querylatency with doc-type as a dimension 
proton.doctypes.ranking.querylatency with doc-type and rank-profile as dimensions 

Should be added and not re-named as this is a public api

**Comment by geirst** [comment]
The matching metrics with new naming schema are as follows:
"content.proton.documentdb.matching.*", with dimension "documenttype"
"content.proton.documentdb.matching.rank_profile.*", with dimensions "documenttype", "rankProfile"
"content.proton.documentdb.matching.rank_profile.docid_partition.*", with dimensions "documenttype", "rankProfile", "docidPartition"

Available in Vespa >= 6.239.35

**Comment by geirst** [comment]
Subset of new matching metrics exposed in default metric set. Available in Vespa >= 6.241.33.
