### ISSUE TITLE
Error logging in Vespa Http Client

### ISSUE THREAD

**Issue by Flakesz** [vespa-engine/vespa#5782]
More of a suggestion than an issue. I have been using the FeedClient to feed into my cluster for a while now (quite stable, big plus) but when it stops working it usually requires a debugger because of the poor error logging (sadly). 

**Log example (Stock app):** 
`Failure: Result for 'wsr_1525370035020`

With this, the operator basically knows, yeah this document failed to  be stored but no further information. Even tho the result object (whose id is printed here) already contains details which could be printed like: 
`result.exception.detailMessage= "ReturnCode(NO_SPACE, Put operation rejected for document '<id here>': 'diskLimitReached: { action: "add more content nodes", reason: "disk used (0.815407) > disk limit (0.8)", stats: { capacity: 25954394112, used: 21163384832, diskUsed: 0.815407, diskLimit: 0.8}}')" `

Which would make the issue directly visible from the logs.
The logging of this happens in `SimpleLoggerResultCallback` Line 99 (invoked by OperationProcessor (Line 199) (Version 6.211.26).

**Comment by jobergum** [comment]
Thanks for the great feedback! Agreed, the sample should print the detailed message.

**Comment by bratseth** [comment]
Thanks for pointing this out. Fixed in https://github.com/vespa-engine/vespa/pull/5804

FYI @vekterli
