### ISSUE TITLE
Summarise comparison with similar projects

### ISSUE THREAD

**Issue by elgalu** [vespa-engine/vespa#5854]
Hi, would it be possible to have a summary of the main differences between this project and similar ones? I've complied a list:

* https://github.com/SeldonIO/seldon-core
* https://github.com/IBM/FfDL
* https://github.com/polyaxon/polyaxon
* https://github.com/PipelineAI/pipeline
* https://github.com/riseml/riseml
* https://www.h2o.ai/driverless-ai/

Do you plan to integrate with [Kubeflow](https://github.com/kubeflow/kubeflow)?

**Comment by bratseth** [comment]
Thanks for the pointer - some of these look interesting.

Vespa is for the use case where you want to make separate inferences - quickly - over many different data points ("documents") for each query. It leds to many challenges, such as incorporating distributed storage of the data to make inferences, distributing models to the data nodes and scattering queries to all data partitions, as it becomes too slow to look up data elsewhere and send it over the wire for inference. I don't think that use case is covered by any of those projects. 

I would guess Vespa is also at a different maturity level than most of them as more than 100M$ is already spent on developing it, and it has been in use for a long time powering large services.

No plans regarding Kubeflow at the moment. We have a quick start with Kubernetes but are not planning to do anything more there at the moment, unless some of the current large users who deploy with Kubernetes contribute something.
