### ISSUE TITLE
DocumentOperation created on Processors not persisted in storage

### ISSUE THREAD

**Issue by aguereca** [vespa-engine/vespa#5898]
Issue:
    Having a `Processor` handling a request from a custom `HttpRequestHandler`, any `DocumentOperation` objects generated on it are not persisting the `Document` in storage.

I've updated one of the sample-apps to showcase this scenario:
https://github.com/vespa-engine/sample-apps/pull/44

Expected result:
    When calling the handled endpoint, if a 200 OK response is returned, then any DocumentOperation generated by Processor pipeline should be persisted. 

How to reproduce:
    - Deploy demo app to Docker
    - Hit custom endpoint: 
           `curl 'http://localhost:8080/demo?terms=1%202%203%204'`
    - Verify if document was inserted: 
           `curl -v "http://localhost:8080/document/v1/default/music/docid/10"`

**Comment by bratseth** [comment]
You need to use the document access APi to write documents: http://docs.vespa.ai/documentation/document-api-guide.html#document-access

**Comment by aguereca** [comment]
Thanks for the help, I've sample-app is not updated to reflect the solution, I'll close the issue.
