### ISSUE TITLE
why remove nodes from repository when flavor type is DOCKER_CONTAINER

### ISSUE THREAD

**Issue by knowmara** [vespa-engine/vespa#5901]
Hi,
I have some doubts about this statement 

> This method is used by the REST API to handle readying nodes for new allocations. For tenant docker containers this will remove the node from node repository, otherwise the node will be moved to state ready.

This method refers to `markNodeAvailableForNewAllocation` which is used by class `NodesApiHandler`

In my opinion, docker node is more suitable for node-repository...

**Comment by bratseth** [comment]
Docker nodes can be created on demand, so in contrast to nodes which have a physical manifestation on the real world there's no reason to keep their representation around when they are not needed.

**Comment by bratseth** [comment]
The purpose of the dirty state is to locally clean old state before the nodes become ready for use again.

Dirty docker containers are simply deleted. Docker containers (nodes) are never ready, they are created on the fly during allocation from free capacity on Docker hosts.

**Comment by knowmara** [comment]
It sounds that node-repository is also responsible for container arrangement,feeling a bit heavy

**Comment by bratseth** [comment]
Yes, that is where that decision-making belongs. But I'm not selling it to you  :-)

**Comment by knowmara** [comment]
Thanks.
I encountered another question when I tried node-repository.
When I deployed application,I was prompted `Access-control must be enabled for write operations to container clusters in production zones:[]`,and then I added `http` element in the services.xml,another error came:

> java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454)
at com.yahoo.container.http.filter.FilterChainRepository.toJDiscChain(FilterChainRepository.java:91)
at com.yahoo.container.http.filter.FilterChainRepository.lambda$addAllChains$1(FilterChainRepository.java:72)

But I really added a request-chain,services.xml in the attachment
[services.txt](https://github.com/vespa-engine/vespa/files/2030435/services.txt)
> //TODO: FilterChainRepository should instead always be set up in the model.
    private final FilterChainRepository defaultFilterChainRepository =
            new FilterChainRepository(new ChainsConfig(new ChainsConfig.Builder()),
                                      new ComponentRegistry<>(),
                                      new ComponentRegistry<>(),
                                      new ComponentRegistry<>(),
                                      new ComponentRegistry<>());


Does the code segment of Class ConfiguredApplication mean that this feature has not been implemented? If so, what should I do?

**Comment by bratseth** [comment]
@gjoranv could you answer the above?

**Comment by gjoranv** [comment]
That was a bug we discovered recently. The filter chain associated with access-control is only populated in our internal applications, and the filter chains repository fails upon empty chains.

The bug should be fixed here: https://github.com/vespa-engine/vespa/pull/5909
but it will not be available until Vespa 6.243, probably early next week.

**Comment by knowmara** [comment]
Okay,thanks.
