### ISSUE TITLE
count() underreports number of groups in grouping query

### ISSUE THREAD

**Issue by zhaakhi** [vespa-engine/vespa#5989]
According to http://docs.vespa.ai/documentation/reference/grouping-syntax.html#counting-unique-groups, 

    The following query outputs the number of groups, which is equivalent to the number of unique values for attribute "a".

    /search/?yql=select (…) |
             all(group(a) output(count()))

But this query seems to often underestimate the real number of unique values.
The following steps should reproduce this in a fresh vespaengine/vespa docker image.

```sh
mkdir -p app/searchdefinitions
cat <<EOF > app/searchdefinitions/my_documents.sd
search my_documents {
  document my_documents {
        field unique_field type int {
            indexing: attribute
        }
  }
}
EOF
cat <<EOF > app/services.xml
<?xml version="1.0" encoding="utf-8" ?>
<services version="1.0">
  <container id="container" version="1.0">
    <document-api />
    <search />
    <nodes>
      <node hostalias="node1" />
    </nodes>
  </container>

  <content id="my_documents" version="1.0">
    <redundancy>1</redundancy>
    <documents>
      <document type="my_documents" mode="index" />
    </documents>
    <nodes>
      <node hostalias="node1" distribution-key="0" />
    </nodes>
  </content>

</services>
EOF
vespa-deploy prepare app
vespa-deploy activate
sleep 30
for I in {1..1000}; do
  curl -s -X POST -H "Content-Type:application/json" --data-binary '{"fields":{"unique_field":'$I'}}' "http://localhost:8080/document/v1/default/my_documents/docid/$I" > /dev/null
done
# SELECT * FROM my_documents WHERE unique_field > 0 | all(group(unique_field) output(count()));
curl 'http://localhost:8080/search/?hits=0&yql=SELECT%20%2A%20FROM%20my_documents%20WHERE%20unique_field%20%3E%200%20%7C%20all%28group%28unique_field%29%20output%28count%28%29%29%29%3B' | python -m json.tool
```

Output:
```json
{
    "root": {
        "children": [
            {
                "continuation": {
                    "this": ""
                },
                "fields": {
                    "count()": 985
                },
                "id": "group:root:0",
                "relevance": 1.0
            }
        ],
        "coverage": {
            "coverage": 100,
            "documents": 1000,
            "full": true,
            "nodes": 1,
            "results": 1,
            "resultsFull": 1
        },
        "fields": {
            "totalCount": 1000
        },
        "id": "toplevel",
        "relevance": 1.0
    }
}
```

Expected result: count() and totalCount should both be 1000, since every document has a unique value for unique_field.

Actual result: totalCount is 1000 as expected, but count() only reports 985 results.

**Comment by bratseth** [comment]
Yes, the count is an approximation using a data sketch: https://en.wikipedia.org/wiki/HyperLogLog
This is because an exact unique count across multiple nodes is very expensive with large number of values as all the unique values of each node needs to be collected into one set.

**Comment by zhaakhi** [comment]
That is cool then, I got the impression from the documentation that it would be exact. Is there any way to force an exact count, or to tweak the precision?

**Comment by geirst** [comment]
We should update the documentation

**Comment by bratseth** [comment]
There's no way to tweak accuracy from the grouping expression at the moment. Du you really need it or just asking?

**Comment by zhaakhi** [comment]
I was just curious. For cases where we can use an estimate the default precision is probably OK.
