### ISSUE TITLE
Update vespa-http-client example to use SSL

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#6094]
Since we should expect SSL to be the default going forward, we should update our example in the [vespa-http-client documentation](http://docs.vespa.ai/documentation/vespa-http-client.html) to use SSL.

We should also add `--useTls` in the command line example.

**Comment by jobergum** [comment]
Care must be taken here as in some envs you might feed through a proxy layer with ssl termination and in other envs you might feed directly against vespa containers and in the latter case the vespa containers needs to be configured with SSL and certificates.

**Comment by kkraune** [comment]
I think we can close this with the new https://docs.vespa.ai/en/vespa-feed-client.html , right @jonmv ?

**Comment by jonmv** [comment]
Sort of. So this requires each container to set up TLS, and terminating at a proxy is not an option (unless the proxy again uses TLS against the containers).

**Comment by johans1** [comment]
use new client

**Comment by kkraune** [comment]
docs and sample apps are being rewritten to use vespa-feed-client, no need to change for vespa-http-client - closing
