### ISSUE TITLE
How well does vespa handle time series data, compared to, say, prometheus?

### ISSUE THREAD

**Issue by ggservice007** [vespa-engine/vespa#6144]
The Prometheus can power your metrics and alerting with a leading open-source monitoring solution.

https://prometheus.io/.

**Comment by bratseth** [comment]
We haven't compared to Prometheus. 
It's in the "analytics" category, so I think these general observations vs. Vespa (big data serving) would hold: https://docs.google.com/presentation/d/1znKqKemQC_qlEm1SD_AnpKuDEPd0z1JSic0DK9bqBcI/edit#slide=id.g38758d6b17_0_434

**Comment by ggservice007** [comment]
Thanks.
I want to know it is nice for using vespa to store time series data.

**Comment by bratseth** [comment]
Functionally, yes. Is it the cheapest and easiest solution? Depends on your use case. How much data, how will you query it, what's the read and write load, what latency do you need, etc.

**Comment by ggservice007** [comment]
Thanks a lot. I see. 
Later, I will test it.
