### ISSUE TITLE
Fix searchnode tuning doc options for index 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#6152]
http://docs.vespa.ai/documentation/content/setup-proton-tuning.html#index

Incorrectly lists mlock as an valid option for io.search. If you try 'mlock' it will fallback to 'normal' but pass xml schema validation. Also mmap is the default and the others like directio etc has limited test coverage so I'm suggesting to simply remove the io.search options and only allow mmap as io.search option. Instead add a flag for the POPULATE mmap option which is more common in use.

**Comment by baldersheim** [comment]
Fixed in 7.423.20
