### ISSUE TITLE
Wrong spelling in the document.  Bug Data -> Big Data

### ISSUE THREAD

**Issue by ggservice007** [vespa-engine/vespa#6200]
<img width="862" alt="aa" src="https://user-images.githubusercontent.com/9192908/41385926-2d89abec-6fb1-11e8-83ae-68322e02f8e7.png">

https://docs.google.com/presentation/d/1znKqKemQC_qlEm1SD_AnpKuDEPd0z1JSic0DK9bqBcI/edit#slide=id.g31f9f20639_0_5

<img width="1017" alt="bb" src="https://user-images.githubusercontent.com/9192908/41386009-b8d3db1e-6fb1-11e8-97f7-0e637bc2dd31.png">

**NL features**  should be ML features ?

**Comment by bratseth** [comment]
Thanks! Fixed the "bug" one.
The other one is as intended, NL = natural language.
