### ISSUE TITLE
Can Vespa save images/pictures or process image searching?

### ISSUE THREAD

**Issue by theseusyang** [vespa-engine/vespa#6218]
Hi team,

Can Vespa save  images/pictures to its server or execute the image searching like other search engine?

thanks!

**Comment by jobergum** [comment]
Vespa can and is in use for image search (Flickr) but storing the binary data in Vespa does not make sense even it can also be done.  Vespa can index the meta data (Both text and image feature vectors as document tensors).

**Comment by theseusyang** [comment]
@jobergum Great! Can you give me a demo  that how to insert a jpg into Vespa and index the image meta data? 

Thank you very much!

**Comment by jobergum** [comment]
You need to define a document model (search definition) and you you can feed the binary image data along with meta data like anchor text, title of the page it was found as examples of meta data which is outside of the binary image itself. You can use e.g base64 encoding and vespa's raw field for the binary data itself and during document processing you can use java libraries for extracting meta data out of the raw binary data and populate fields in the Vespa document. See e.g  https://docs.vespa.ai/documentation/document-processing-overview.html

**Comment by theseusyang** [comment]
OK, I try it. Additionally, How to generate an image feature vectors in Vespa?by TensorFlow API?

**Comment by bratseth** [comment]
That's independent of Vespa, you can find (or learn) models that do it both in TensorFlow and other tools, e.g PyTorch.

**Comment by theseusyang** [comment]
OK, Thanks! @bratseth
