### ISSUE TITLE
Access Maps & Structs in Group clause

### ISSUE THREAD

**Issue by SarathKumar-k** [vespa-engine/vespa#6281]
1. Currently, only attributes in the document can be accessed in the group clause. Since Maps & Structs are not allowed to be defined as attributes, these can't be accessed in the group clause. 
provide support for fetching the values from Maps & structs by taking an variable inside the group clause. 

For Ex: There are two fields in the document defined as below
search music {
document music {
   field title type string {
    indexing: index | summary
  }
   field sla type int {
      indexing: attribute
   }
   field mymap type map<int,float>{
    indexing: attribute
   }
 }
}

Query: select title from music where title contains "Erased" | all (group by (math.log(mymap{attribute(sla)})))

2. Please provide access to summary features too in the group clause for ex. accessing relevance scores calculated in both first phase and second phase.

**Comment by baldersheim** [comment]
We will discuss this when we have the rest of the team back from vacation. This will require some work and is not an simple one liner. Will provide an ETA end of next week.

**Comment by geirst** [comment]
This functionality has just been added and is part of Vespa 6.286.5. Reference documentation with description of new syntax: https://docs.vespa.ai/documentation/reference/grouping-syntax.html#map

**Comment by kkraune** [comment]
From requestor:

it seems that the issue has been fixed (map type field didn’t support grouping syntax), but not sure how to access struct field in ranking profile

Geir please comment

**Comment by geirst** [comment]
Please consider the following example:
`field my_map type map<string, int> {
  indexing: summary
  struct-field key { indexing: attribute }
  struct-field value { indexing: attribute }
}`
In this case we have two internal attribute vectors 'my_map.key' (array of string) and 'my_map.value' (array of int). These can be used as any other attribute vector in a ranking expression using the `attribute(my_attribute_name)` rank feature (https://docs.vespa.ai/documentation/reference/rank-features.html).
