### ISSUE TITLE
Does tensor's label must be an identifier or integer?

### ISSUE THREAD

**Issue by FrankYu0502** [vespa-engine/vespa#6305]
When I was using vespa-http-client to feed data, I got following errors:

Failure: Result for 'id:duokan:item::359587
1530176248947 Trace starting 
1530176249828 Asked about retrying for cluster ID 0, number of retries is 1 Detail:
Detail resultType=FATAL_ERRORexception='Error in document 'id:duokan:item::359587' - could not parse field 'read_location' of type 'tensor(x{})': label must be an identifier or integer, not '中爪哇省': label must be an identifier or integer, not '中爪哇省'' endpoint=localhost:8080 ssl=false resultTimeLocally=1530176249828
1530176249828 Got detail: Detail resultType=FATAL_ERRORexception='Error in document 'id:duokan:item::359587' - could not parse field 'read_location' of type 'tensor(x{})': label must be an identifier or integer, not '中爪哇省': label must be an identifier or integer, not '中爪哇省'' endpoint=localhost:8080 ssl=false resultTimeLocally=1530176249828

**Comment by FrankYu0502** [comment]
Hello guys,

In the previous version of vespa, it allows us to using string to be tensor's label. However, after I update vespa to version 6.252.3-1, string doesn't work.

**Comment by bratseth** [comment]
Yes, but it's just a validation check. I don't think there's any major drawback to allowing all unicode word characters and not just [a-zA-Z0-9_]. I'll make that change if you think it is useful.

**Comment by FrankYu0502** [comment]
If it's just a validation check. I could change it by myself.

Thanks!
