### ISSUE TITLE
Submit ONNX tutorial for Vespa

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#6329]
To better promote Vespa's ONNX support, we should consider submitting a tutorial for using Vespa with ONNX in their GitHub repo: https://github.com/onnx/tutorials.

**Comment by jobergum** [comment]
https://github.com/onnx/tutorials/pull/252

**Comment by jobergum** [comment]
Above PR is merged and onnx/tutorials now links to stateless model sample app and ms marco sample app with many onnx models. https://github.com/onnx/tutorials/
