### ISSUE TITLE
PMML / PFA support? 

### ISSUE THREAD

**Issue by alvaromuir** [vespa-engine/vespa#6360]
Hey gang,
Any plans for supporting (pMML)[http://dmg.org/pmml/v4-3/GeneralStructure.html] or (PFA)[http://dmg.org/pfa/index.html]? 

Happy to lend a hand.

**Comment by bratseth** [comment]
No plans, but I'm not opposed to it. Do you have a concrete need for it or know that anybody does?

> Happy to lend a hand.

Excellent ... you could look at the Onnx and TensorFlow integration and do the same:

1) Importers:
https://github.com/vespa-engine/vespa/tree/master/searchlib/src/main/java/com/yahoo/searchlib/rankingexpression/integration/ml

2) Integration of those into the ranking expression language:
https://github.com/vespa-engine/vespa/blob/master/config-model/src/main/java/com/yahoo/searchdefinition/expressiontransforms/TensorFlowFeatureConverter.java
https://github.com/vespa-engine/vespa/blob/master/config-model/src/main/java/com/yahoo/searchdefinition/expressiontransforms/OnnxFeatureConverter.java

**Comment by alvaromuir** [comment]
Thanks @bratseth. Most of our data citizens/scientists/engineers have more access to tools that write models to pMML format. 

Where can I look at Onnx integration in the source?
