### ISSUE TITLE
Vespa 7 OpenNlp for stemming and language detection

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#6403]
Jefim Matskin @jefimm 11:11
@jobergum Would you/team be interested in integrating org.apache.opennlp for linguistics?

Jon Bratseth @bratseth 12:09
Maybe … it seems to do a lot more than Vespa needs natively (tokenization and stemming), and I couldn’t find what languages it supports?

Jefim Matskin @jefimm 12:11
Stemming is supported for https://github.com/apache/opennlp/blob/master/opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/SnowballStemmer.java#L24 languages
for lang detection https://github.com/optimaize/language-detector could be integrated

**Comment by bratseth** [comment]
Documentation: https://github.com/vespa-engine/documentation/pull/318

**Comment by johans1** [comment]
Consider making default

**Comment by bratseth** [comment]
This was made default on Vespa 7.
