### ISSUE TITLE
Can vespa support ik-analyzer?

### ISSUE THREAD

**Issue by ggservice007** [vespa-engine/vespa#6445]
Can vespa support the Chinese Word Segmentation(中文分词)?

Can integrate with ik-analyzer?

http://code.google.com/p/ik-analyzer/

**Comment by bratseth** [comment]
Yes, you could do it yourself: https://docs.vespa.ai/documentation/linguistics.html

If you submit it back to Vespa that would be great. Here's another PR which adds support for a linguistics library, you could follow that:
https://github.com/vespa-engine/vespa/pull/6407

**Comment by ggservice007** [comment]
nice. Thank you so much.

**Comment by bratseth** [comment]
Closing, please submit back when you have this ready.
