### ISSUE TITLE
FATAL_ERRORexception='Document type blog_post does not exist

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#6528]
Detail resultType=FATAL_ERRORexception='Document type blog_post does not exist' endpoint=localhost:8080 ssl=false resultTimeLocally=1533804606621
1533804606622 Got detail: Detail resultType=FATAL_ERRORexception='Document type blog_post does not exist' endpoint=localhost:8080 ssl=false resultTimeLocally=1533804606621

**Comment by bratseth** [comment]
I think you'll need to provide some more context than this.
