### ISSUE TITLE
Custom Searching using Searcher class in vespa

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#6693]
Please go through my query [there](https://stackoverflow.com/questions/52053894/implementing-custom-searcher-in-vespa). 
How should I get custom result of my requirements? And, what am I doing wrong in application or is missing something from my peace of code?I am just creating a very simple searching app in vespa.

**Comment by msunny03** [comment]
After executing http://localhost:8080/search/?query=good&tracelevel=9 . I got the response
{
    "trace": {
        "children": [
            {
                "message": "No query profile is used"
            },
            {
                "message": "Resolved properties:\ntracelevel=9 (value from request)\nquery=good (value from request)\n"
            },
            {
                "message": "Invoking chain 'default' [com.mydomain.example.ExampleSearcher@default]"
            },
            {
                "children": [
                    {
                        "timestamp": 0,
                        "message": "Invoke searcher 'com.mydomain.example.ExampleSearcher in default'"
                    },
                    {
                        "timestamp": 0,
                        "message": "com.mydomain.example.ExampleSearcher in default Dependencies{provides=[ExampleSearcher, com.mydomain.example.ExampleSearcher], before=[], after=[]}"
                    },
                    {
                        "message": "com.mydomain.example.ExampleSearcher in default Dependencies{provides=[ExampleSearcher, com.mydomain.example.ExampleSearcher], before=[], after=[]}"
                    },
                    {
                        "timestamp": 0,
                        "message": "Return searcher 'com.mydomain.example.ExampleSearcher in default'"
                    },
                    {
                        "message": "Invoke fill(null) on searcher 'com.mydomain.example.ExampleSearcher in default'"
                    },
                    {
                        "message": "Ignoring fill(null): Hits are unfillable: result.hits().getFilled()=null"
                    },
                    {
                        "message": "Return fill(null) on searcher 'com.mydomain.example.ExampleSearcher in default'"
                    },
                    {
                        "message": "Query parsed to: select * from sources * where default contains \"good\";"
                    },
                    {
                        "message": "Query time query 'good': 0 ms"
                    },
                    {
                        "message": "Summary fetch time query 'good': 0 ms"
                    },
                    {
                        "message": "Vespa version: 6.240"
                    },
                    {
                        "message": "Request attributes: {jdisc.request.X509Certificate=null, com.yahoo.jdisc.http.server.jetty.AccessLoggingRequestHandler_access-log-entry=com.yahoo.container.logging.AccessLogEntry@2c5323cf[adInfos=<null>,spaceID=<null>,ipV4AddressInDotDecimalNotation=172.17.0.1,timeStampMillis=0,durationBetweenRequestResponseMillis=0,numBytesReturned=0,uri=/search/?query=good&tracelevel=9,remoteAddress=172.17.0.1,remotePort=58302,peerAddress=<null>,peerPort=0,cookieType=<null>,cookie=<null>,weekOfRegistration=<null>,profile=<null>,internationalInfo=<null>,contentAttribute=<null>,webfactsDigitalSignature=<null>,errorMessage=<null>,fileName=<null>,userAgent=PostmanRuntime/7.1.5,referer=<null>,user=<null>,hitCounts=<null>,requestExtra=<null>,responseExtra=<null>,resultFromCache=<null>,httpMethod=GET,httpVersion=HTTP/1.1,partner=<null>,adRationale=<null>,incrementSlotByOneRequest=<null>,zDataIncrementSlotByOneRequest=<null>,hostString=localhost:8080,statusCode=0,scheme=http,localPort=8080,principal=<null>,sslPrincipal=<null>,rawPath=/search/,rawQuery=query=good&tracelevel=9,keyValues=<null>]}"
                    }
                ]
            }
        ]
    },
    "root": {
        "id": "toplevel",
        "relevance": 1,
        "fields": {
            "totalCount": 0
        }
    }
}

**Comment by jobergum** [comment]
Resolved by adding inherits="vespa" to the default search chain.

**Comment by msunny03** [comment]
Thanks @jobergum its working
