### ISSUE TITLE
Abilityt to store only index and not original document source/fields

### ISSUE THREAD

**Issue by ddorian** [vespa-engine/vespa#6786]
Hi,

Looking at the docs, seems like the fields are always stored. Is it possible to not store the original source (which will also disable update etc) ?

**Comment by kkraune** [comment]
Vespa uses the documents in the store for elasticity, e.g. copy the document to new nodes as needed - so not possible to not store the document. What is the use case?

You can modify the document in Document Processing, like dropping fields, if the goal is to save space and the data is not needed to generate indices / used in summaries

**Comment by ddorian** [comment]
The use case is for a lot of data with low query rate. And the original data can be queried from original-db.

**Comment by kkraune** [comment]
Ok. The only option is to trim to the minimal field set needed to create the indices, then. Remember, the document store is compressed: https://docs.vespa.ai/documentation/document-summaries.html#document-store - so might not be a big issue, depends on the data ...

**Comment by ddorian** [comment]
@kkraune I understand. Is it possible to at return only `id` so you don't incur a disk-read for the document-store ?

**Comment by kkraune** [comment]
OK - then the key is to make all data needed for document summaries available in attributes. So
* put the document ID (or whatever you need as a key to look up data elsewhere) in a field that is also defined as an attribute (= memory access)
* define a summary class with only this field
* specify this summary class in queries so only this field is returned

https://docs.vespa.ai/documentation/attributes.html
https://docs.vespa.ai/documentation/document-summaries.html
https://docs.vespa.ai/documentation/reference/search-api-reference.html#presentation.summary (you can use a query profile for this)

So, reading IDs from memory is supported - hope this helps

**Comment by ddorian** [comment]
@kkraune that's perfect. Means I can use the custom `id` to also query for the exact document (like get) and getting in-memory read.
