### ISSUE TITLE
Verify quick start tutorial on latest Docker on Mac

### ISSUE THREAD

**Issue by frodelu** [vespa-engine/vespa#7153]
Per @bsandvik, the [quick start tutorial](https://docs.vespa.ai/documentation/vespa-quick-start.html) doesn't work out of the box with the latest version of Docker on Mac due to some port (forwarding?) issues.

Someone need to upgrade to the latest Docker version and verify that the quick start actual works. Perhaps @bsandvik can shed some more light on what was problematic?

**Comment by kkraune** [comment]
Guide verified, updated https://docs.vespa.ai/documentation/vespa-quick-start.html in https://github.com/vespa-engine/documentation/pull/372

**Comment by kkraune** [comment]
@bsandvik I could not find any issues, please report your findings
