### ISSUE TITLE
Use JavaCPP Preset for ONNX

### ISSUE THREAD

**Issue by EmergentOrder** [vespa-engine/vespa#7326]
The [JavaCPP Preset for ONNX](https://github.com/bytedeco/javacpp-presets/tree/master/onnx) contains everything that you get from the implementation generated from the protobuf that is currently used. You also get the ability to ["polish"](https://github.com/onnx/onnx/blob/v1.3.0/onnx/utils.py#L14) and convert the version of a model (in this [PR](https://github.com/bytedeco/javacpp-presets/pull/622) ) as well as access to the operator schemas, the ONNX IR, ONNX-ML (Classical Machine Learning extension), ONNXIFI and more.

**Comment by bratseth** [comment]
What's the ask or suggestion here?
