### ISSUE TITLE
Add support for importing position fields from parent document type

### ISSUE THREAD

**Issue by geirst** [vespa-engine/vespa#7573]
Assume the following parent and child document types:
```
search parent {
  document parent {
    field latlong type position {
      indexing: attribute
    }
  }
}

search child {
  document child {
    field parent_ref type reference<parent> {
      indexing: attribute | summary
    }
  }
  import field parent_ref.latlong as my_latlong {}
  }
}
```

Deploying an application with these document types gives the following error:

> Invalid application package: default.default: Error loading model: For search 'child', import field 'my_latlong': Field 'latlong' via reference field 'parent_ref': Is not an attribute field. Only attribute fields supported

**Comment by kkraune** [comment]
This depends on the struct support in #7206, so must come after that

**Comment by geirst** [comment]
https://github.com/vespa-engine/vespa/pull/7823

**Comment by geirst** [comment]
This feature is complete and is part of Vespa 6.320.33.
Reference documentation: https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#import-field

**Comment by geirst** [comment]
Importing such fields from a grandparent via an imported field in the parent is tracked in https://github.com/vespa-engine/vespa/issues/7930.
