### ISSUE TITLE
Blog Search tutorial broken?

### ISSUE THREAD

**Issue by theconnectionist** [vespa-engine/vespa#7686]
Tried to get started with the [Blog Search Tutorial](https://docs.vespa.ai/documentation/tutorials/blog-search.html) but the Kaggle dataset no longer seems to be available. I logged into Kaggle, accepted their terms, got a key, and tried downloading using the kaggle api client. Also tried downloading from the site. If the data is no longer available, perhaps make a copy of the data available elsewhere or use a different dataset.

**Comment by lesters** [comment]
Just tested this and the data is still available. You need to be logged on, and after that the direct link https://www.kaggle.com/c/predict-wordpress-likes/download/trainPosts.zip should work. I haven't tested their api client. 

Alternatively, you can try to go to https://www.kaggle.com/c/predict-wordpress-likes/data, and click on the trainPosts.zip and use the download button there.

**Comment by theconnectionist** [comment]
Thanks for the response lesters. I'll try downloading again. Maybe the kaggle site had a bad day when I tried the download.

**Comment by theconnectionist** [comment]
I tried again, this time with Chrome in addition to Firefox. I go to the page where I accept the license, click the button, but it doesn't do anything. Disabled my popup blocker; no luck.

I understand this is not Vespa's problem, but posting the follow up here to alert you to potential problem. Your links may be working if you already had access, but appears new requests are no longer going through. I strongly urge you to use data that you control and own rather than rely on a third party who may or may not understand how their dataset is being used.

**Comment by lesters** [comment]
Sorry to hear your problems with Kaggle. Did you try logging in through a Google or Facebook or Yahoo account? Anyway, there is a small sample data file in the repository that might unblock you: https://github.com/vespa-engine/sample-apps/tree/master/blog-tutorial-shared

**Comment by theconnectionist** [comment]
I used my Google account to sign in. I can see and download other data. In any case I'll prepare data that I intend to evaluate Vespa with, so this data set won't block me.

Thank you for your follow-up.
