### ISSUE TITLE
How to apply now() function in yql query

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#7825]
Below is the search definition of my document. I have field "expire" which is a timestamp in my document.Now I want to search documents using yql query if isActive="1" and test.expire - now() > 0.Can I achieve this by query?

search test {
    document test {
                field Id type string {
                    indexing: index|summary
                }

                field isActive type string {
                    indexing: index|summary
                }

                field expire type long {
                   indexing: index | summary
                }

                field detail type string {
                   indexing: summary
                }
}
}

If yes then what would be my query? How can I apply now() in my query?Please help

**Comment by bratseth** [comment]
Answered in https://stackoverflow.com/questions/53554482/how-to-apply-test-and-set-condition-in-yql-query
