### ISSUE TITLE
Auto update of document in vespa

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#7840]
Is there any way to auto update any field of document in vespa. Lets I have to update "status" field to 0 when "currentTime" > "expiryTime". I dont want to call any API for that.

"fields": {

                    "expiryTime": 1543503600000,
                    "currentTime": 1543503400000,
                    "status" : 1
                }
After currentTime > expireTime, "status" field must be auto updated to 1. "fields": {

                "expiryTime": 1543503600000,
                "currentTime": 1543503800000,
                "status" : 0
            }

**Comment by kkraune** [comment]
answered in https://stackoverflow.com/questions/53588530/auto-update-of-document-in-vespa/53589603#53589603

**Comment by msunny03** [comment]
I have added a comment there.Please look at there.
