### ISSUE TITLE
Update document in Processor on the condition based

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#7870]
{
  "status":1,
  "expire":15349870000,
  "detail1":"test1",
  "detail2":"test2"
}
{
  "status":0,
  "expire":15349870000,
  "detail1":"test1",
  "detail2":"test2"
}
I have two different documents of same data type, I want to update status, detail1 and detail2 on conditions

if(status==0 and expire > now()) then status = 1 and detail1 = "good"
if(status==1 and expire > now()) then status = 2 and detail2 = "bad"

But all this I want to do in Processor. So how can I apply a check in processor as I am unable to get value of fields in processor?

@Override
    public Progress process(Processing processing) {
        for (DocumentOperation op : processing.getDocumentOperations()) {
            if (op instanceof DocumentUpdate) {
                DocumentUpdate documentUpdate = (DocumentUpdate) op;
 if(?){
 documentUpdate.addFieldUpdate(FieldUpdate.createAssign(documentUpdate.getDocumentType().getField("detail1"), new StringFieldValue("good")));
}
else if(?){
 documentUpdate.addFieldUpdate(FieldUpdate.createAssign(documentUpdate.getDocumentType().getField("detail2"), new StringFieldValue("bad")));
}
            }

 }
        return Progress.DONE;
 }
Please help!

**Comment by vekterli** [comment]
One option is to fetch the document on-demand from the backend as part of your update processing using the Document API.

Another option is if you could reformulate your problem as a [conditional update](https://docs.vespa.ai/documentation/reference/document-json-format.html#conditional-updates-test-and-set), as these are executed in the backend and don't require you to fetch the document yourself. `DocumentUpdate` has a `setCondition` method that can be used to do this programmatically. See the [document selector language](https://docs.vespa.ai/documentation/reference/document-select-language.html) for the syntax and options available. Note that a condition applies to a _whole_ `DocumentUpdate` and cannot be set on individual `FieldUpdate`s, so the use case might not match yours.

**Comment by jobergum** [comment]
I think this has been answered on SO? https://stackoverflow.com/questions/53626784/update-document-in-processor-on-the-condition-based
