### ISSUE TITLE
Support of different languages in vespa

### ISSUE THREAD

**Issue by msunny03** [vespa-engine/vespa#7883]
Is there any feature to get same document in different languages?

Here is my use case : If I am in USA then I should get data in english language and if I am in China I should get data in chinese language.

I don't want to feed different documents for different languages.

**Comment by kkraune** [comment]
you mean an auto-translation of document content?

**Comment by msunny03** [comment]
Not auto translation, Just I want to feed store data in different languages but in same document, But If I query I should get data according to my country ie en or ch

**Comment by kkraune** [comment]
I notice you published on https://stackoverflow.com/questions/53648187/support-of-different-languages-in-vespa as well - closing this
