### ISSUE TITLE
Vespa 8: Weighted set representation differs in document API and search results

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#8251]
This is inconsistent, consider using same in search as in doc api:

Insert or get document through document API (GET or POST /document/v1/….): format is ```{"key1": 1, "key2": 2}```

Using search API (GET /search/): format is ```[{"item": "key1", "weight": 1}, {"item": "key2", "weight": 2}]``` - In a search result the weighted set is represented as an array of item/weight pairs, see https://docs.vespa.ai/documentation/reference/inspecting-structured-data.html

**Comment by geirst** [comment]
Consider adding new rendering format for weighted sets for search API on Vespa 7 that can be turned on by the client.
