### ISSUE TITLE
How to set query term weights in yql

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#8354]
Hi,
Is there a way to set query term weights in yql, and get weights in rank profile? I wan't to rerank or filter docments after matching. set query=large shoes!200 seems not work in yql.

**Comment by jobergum** [comment]
Weight can be passed down per query term using the weight annotation. See https://docs.vespa.ai/documentation/query-language.html. You have access to the term(n).weight as a rank feature https://docs.vespa.ai/documentation/reference/rank-features.html

**Comment by bratseth** [comment]
Specifically, 

`select foo from bar where baz contains ([ {"weight": 200} ] "shoes");`

It is often better to build such queries inside Vespa, by adding a Searcher, than constructing a YQL string from the outside. https://docs.vespa.ai/documentation/searcher-development.html
