### ISSUE TITLE
Cannot download vespa-http-client-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#8377]
https://docs.vespa.ai/documentation/vespa-http-client.html documents use of _vespa-http-client-jar-with-dependencies.jar_

This is not found on https://search.maven.org - only artifacts like _com.yahoo.vespa:vespa-http-client:7.6.98_ - and using this gives:

`$ java -jar ~/Downloads/vespa-http-client-7.6.98.jar --host localhost --port 8080 < artist-feed.json 
no main manifest attribute, in /Users/XXX/Downloads/vespa-http-client-7.6.98.jar`

It would make feeding to Vespa easier if one could download this jar - now one must build Vespa to get it

**Comment by bratseth** [comment]
It's enough to install Vespa to get it, but yes, this should be simpler.

**Comment by kkraune** [comment]
true - using 

`docker exec vespa bash -c 'java -jar /opt/vespa/lib/jars/vespa-http-client-jar-with-dependencies.jar  --host localhost --port 8080 < vespa-sample-apps/album-search/artist-feed.json'`

for now (feeding from inside docker container) - the importance of this issue is low

**Comment by aressem** [comment]
Deploying the fat jar which should fix this:
https://github.com/vespa-engine/vespa/pull/16767

**Comment by aressem** [comment]
This should be available in Vespa 7.369.x when that version is released to Maven Central.

**Comment by aressem** [comment]
Available now:
https://repo.maven.apache.org/maven2/com/yahoo/vespa/vespa-http-client/7.369.27/vespa-http-client-7.369.27-jar-with-dependencies.jar
