### ISSUE TITLE
Is there any documentation about how to migrate to vespa7?

### ISSUE THREAD

**Issue by mnagaya** [vespa-engine/vespa#8394]
Hi, I am trying to update private JDisc components for vespa7.  Is there any documentation about how to migrate to vespa7?

Thanks,

**Comment by kkraune** [comment]
Please review the release notes at https://docs.vespa.ai/documentation/vespa7-release-notes.html

As Vespa 7 runs on JDK-11, I just something like

```docker run -v "$HOME/.m2":/root/.m2 -v `pwd`:/approot -w /approot \
  maven:3.6.0-jdk-11 \
  mvn -s /root/.m2/settings.xml clean package```

to build and unit test.

I am not sure from which version you are migrating - depending on that, I can provide more info. Thanks!

**Comment by mnagaya** [comment]
Thank you for your quick reply. I will check it out and try to update KuromojiLinguistics.

**Comment by mnagaya** [comment]
KuromojiLinguistics supported Vespa7. (https://github.com/yahoojapan/vespa-kuromoji-linguistics/pull/2)

Thank you for your support.

**Comment by kkraune** [comment]
Thanks for testing and making sure KuromojiLinguistics works for Vespa 7 :-)
