### ISSUE TITLE
Indexing For Imported Reference Field Doesn't Appear To Be Working

### ISSUE THREAD

**Issue by connected-jcaruso** [vespa-engine/vespa#8590]
I've followed the steps in the following 2 articles and the indexing on the imported field doesn't appear to be working. Searching for terms that only appear in the imported field does not surface any documents that reference the parent document.

http://blog.vespa.ai/post/174589826190/parent-child-in-vespa
https://docs.vespa.ai/documentation/parent-child.html

I'm wondering if the referenced docs are out of date and there is an additional step that I am missing. Essentially, how do we ensure an imported field gets indexed, and how can we ensure that imported field is queried against?

**Comment by geirst** [comment]
Hi! Can you please provide the search definition files you ended up using so we can see if there is something wrong?

This should work as specified in those two articles. For example, in https://docs.vespa.ai/documentation/parent-child.html, the ad document type imports the field `name` from the salesperson document (via the reference `salesperson_ref)` and names the imported field `salesperson_name`. The imported field can be used in a query like this:
`select * from ad where salesperson_name contains "john";`

Also note that only attribute fields can be imported (https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#import-field), but your application will not deploy if something else is used.

**Comment by connected-jcaruso** [comment]
thread.sd (in services.xml this is referenced with global="true")
```
search thread {

    document thread {

        field threadId type int {
            indexing: summary
        }

        field title type string {
            indexing: summary | attribute
        }
    }

    fieldset default {
        fields: title
    }

    rank-profile thread inherits default {

        first-phase {
            expression:nativeRank(title)
        }

    }

}
```
post.sd
```
search post {

    document post {

        field thread_ref type reference<thread> {
           indexing: attribute | summary
        }

        field postId type int {
            indexing: summary
        }

        field threadId type int {
            indexing: summary
        }

        field userId type int {
            indexing: summary
        }

        field username type string {
            indexing: index | summary
        }

        field postDate type int {
            indexing: summary | attribute
        }

        field message type string {
            indexing: summary | index | attribute
        }
    }

    import field thread_ref.title as thread_title {}

    fieldset default {
        fields: message, username
    }

    document-summary default {
        summary thread_title type string {}
        summary postId type int {}
        summary threadId type int {}
        summary userId type int {}
        summary username type string {}
    }

    rank-profile post inherits default {

        first-phase {
            expression:nativeRank(message,username)
        }

    }

}
````

I know the reference is working because when I search for a Post document with a word that exists in the "message" field it returns the thread_title field. The issue I'm having is that thread_title is not searchable: 

`select * from post where thread_title contains "business"`

That returns no results, even though there is a thread with title 'business' and a post that references it. I've updated the documents multiple times after applying the changes to the vespa application.

I tried adding the thread_title field to the default fieldset for Post, but I get the following error:
`WARNING: For search 'post', field 'thread_title': The matching settings for the fields in fieldset 'default' are inconsistent (explicitly or because of field type). This may lead to recall and ranking issues.`

**Comment by geirst** [comment]
Thanks for the detailed explanation. Note that attribute fields only support word-match/exact-match search (https://docs.vespa.ai/documentation/attributes.html, https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#match). If the `title` field contains more than 'business' you will not get a match.

What is the exact content of the `title` field in the `thread` document?

**Comment by connected-jcaruso** [comment]
That would explain it then. There was an entire sentence in the `title` field; 'business' was just one word in there.

Thanks for the clarification.

**Comment by jobergum** [comment]
Maybe @geirst we should clarify on this in the documentation on parent child as many find the parent child interesting but as demonstrated here text match is not supported as only attribute fields can be imported from the parent.
