### ISSUE TITLE
Your project vespa-engine vespa is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDUSELAB2** [vespa-engine/vespa#8788]
Hi, there!

We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.

We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information. We have analyzed the api call related to the following libraries and found one library that is using the API call that might invoke buggy methods in the library of the history.
1. commons-codec commons-codec
version: 1.4
API call in your project:org.apache.commons.codec.binary.Base64.setInitialBuffer(byte[],int,int)

Jira issues:
[Base64InputStream#read(byte[]) incorrectly returns 0 at end of any stream which is multiple of 3 bytes long](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-101?filter=allopenissues)
version:1.4
[ArrayIndexOutOfBoundsException when doing multiple reads() on encoding Base64InputStream](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-105?filter=allopenissues)
version:1.4
[Base64 encoding issue for larger avi files](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-108?filter=allopenissues)
version:1.4
[org.apache.commons.codec.net.URLCodec.ESCAPE_CHAR isn't final but should be](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-111?filter=allopenissues)
version:1.2;1.3;1.4
[org.apache.commons.codec.language.RefinedSoundex.US_ENGLISH_MAPPING should be package protected MALICIOUS_CODE](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-113?filter=allopenissues)
version:1.4
[org.apache.commons.codec.language.Soundex.US_ENGLISH_MAPPING should be package protected MALICIOUS_CODE](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-114?filter=allopenissues)
version:1.4
[Caverphone encodes names starting and ending with "mb" incorrectly.](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-117?filter=allopenissues)
version:1.4
[All links to fixed bugs in the "Changes Report" http://commons.apache.org/codec/changes-report.html point nowhere; e.g. http://issues.apache.org/jira/browse/34157. Looks as if all JIRA tickets were renumbered.](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-76?filter=allopenissues)
version:1.1;1.2;1.3;1.4
[Regression:  Base64.encode(chunk=true) has bug when input length is multiple of 76](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-80?filter=allopenissues)
version:1.4
[DigestUtils: MD5 checksum is not calculated correctly on linux64-platforms](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-87?filter=allopenissues)
version:1.3;1.4
[new Base64().encode() appends a CRLF; and chunks results into 76 character lines](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-89?filter=allopenissues)
version:1.4
[Base64 encode() method is no longer thread-safe; breaking clients using it as a shared BinaryEncoder](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-96?filter=allopenissues)
version:1.4
[Base64 default constructor behaviour changed to enable chunking in 1.4](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-97?filter=allopenissues)
version:1.4
[Base64InputStream causes NullPointerException on some input](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-98?filter=allopenissues)
version:1.4
[Base64.encodeBase64String() shouldn't chunk](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-99?filter=allopenissues)
version:1.4
2. org.apache.httpcomponents httpclient
version: 4.4.1
Jira issues:
[Failed to parse cookie max-age attribute ](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1640?filter=allopenissues)
version:4.4.1
[fluent api not kept CookieSpecs from RequestConfig for HttpClients.custom for fluent.Executor ](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1645?filter=allopenissues)
version:4.4.1
[Caching of proxy auth schemes is broken](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1649?filter=allopenissues)
version:4.4.1
[HttpClient 4.4.1 sends RST instead of proper FIN ACK sequence when using non-persistant connections](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1655?filter=allopenissues)
version:4.4.1
[OSGiRoutePlanner examines only the first proxy exception and also crashes processing IP address exception](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1710?filter=allopenissues)
version:4.4.1;4.5;5.0
[OSGiCredentialsProvider.java compares the Authscope by .equals() instead of .match()  ](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1718?filter=allopenissues)
version:4.4.1;5.0 Alpha1
[OSGiProcyConfiguration proxy user field is known as 'proxy.user' to the metadata but the class uses the 'proxy.username'](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1719?filter=allopenissues)
version:4.4.1;5.0 Alpha1
[The deprecated SSLSocketFactory does not contain the SNI fix found in the SSLConnectionSocketFactory class](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1726?filter=allopenissues)
version:4.4.1;4.5.1
[org.apache.http.impl.client.AbstractHttpClient#createClientConnectionManager Does not account for context class loader](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1727?filter=allopenissues)
version:4.4.1;4.5;4.5.1;4.5.2
[Memory Leak in OSGi support](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1749?filter=allopenissues)
version:4.4.1;4.5.2
[PoolingHttpClientConnectionManager has no option to close long leased connections](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1760?filter=allopenissues)
version:4.4.1;4.5
3. org.apache.httpcomponents httpclient
version: 4.5
Jira issues:
[NTLM auth failed because NTLMEngineImpl strip domain to base domain name](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1662?filter=allopenissues)
version:4.5
[RequestBuilder ignores Charset ](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1667?filter=allopenissues)
version:4.5
[connectTimeout used as socketTimeout in Request](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1668?filter=allopenissues)
version:4.5
[org.apache.http.entity.mime.content is missing from exports of OSGi bundle](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1673?filter=allopenissues)
version:4.5
[307 redirect throws ClientProtocolException using POST method](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1680?filter=allopenissues)
version:4.5
[ZipException occurs when content-encoding-header is set for 304-response ](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1690?filter=allopenissues)
version:4.5
[OSGiRoutePlanner examines only the first proxy exception and also crashes processing IP address exception](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1710?filter=allopenissues)
version:4.4.1;4.5;5.0
[org.apache.http.impl.client.AbstractHttpClient#createClientConnectionManager Does not account for context class loader](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1727?filter=allopenissues)
version:4.4.1;4.5;4.5.1;4.5.2
[PoolingHttpClientConnectionManager has no option to close long leased connections](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1760?filter=allopenissues)
version:4.4.1;4.5
4. commons-logging commons-logging
version: 1.1.1
Jira issues:
[Unit tests fail on linux with java16](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-117?filter=allopenissues)
version:1.1.1
[deadlock on re-registration of logger](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-119?filter=allopenissues)
version:1.1.1
[Potential missing privileged block for class loader](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-130?filter=allopenissues)
version:1.1.1
[Log4JLogger uses deprecated static members of Priority such as INFO](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-142?filter=allopenissues)
version:1.1.1
[LogFactory/LogFactoryImpl ingore Throwable](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-144?filter=allopenissues)
version:1.1.1
[LogFactory.nullClassLoaderFactory is not properly synchronized](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-146?filter=allopenissues)
version:1.1.1
[SimpleLog.log - unsafe update of shortLogName](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-147?filter=allopenissues)
version:1.1.1
[BufferedReader is not closed properly](https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-163?filter=allopenissues)
version:1.1.1;1.2
5. commons-cli commons-cli
version: 1.2
Jira issues:
[Unable to select a pure long option in a group](https://issues.apache.org/jira/projects/CLI/issues/CLI-182?filter=allopenissues)
version:1.0;1.1;1.2
[Clear the selection from the groups before parsing](https://issues.apache.org/jira/projects/CLI/issues/CLI-183?filter=allopenissues)
version:1.0;1.1;1.2
[Commons CLI incorrectly stripping leading and trailing quotes](https://issues.apache.org/jira/projects/CLI/issues/CLI-185?filter=allopenissues)
version:1.1;1.2
[Coding error: OptionGroup.setSelected causes java.lang.NullPointerException](https://issues.apache.org/jira/projects/CLI/issues/CLI-191?filter=allopenissues)
version:1.2
[StringIndexOutOfBoundsException in HelpFormatter.findWrapPos](https://issues.apache.org/jira/projects/CLI/issues/CLI-193?filter=allopenissues)
version:1.2
[HelpFormatter strips leading whitespaces in the footer](https://issues.apache.org/jira/projects/CLI/issues/CLI-207?filter=allopenissues)
version:1.2
[OptionBuilder only has static methods; yet many return an OptionBuilder instance](https://issues.apache.org/jira/projects/CLI/issues/CLI-224?filter=allopenissues)
version:1.2
[Unable to properly require options](https://issues.apache.org/jira/projects/CLI/issues/CLI-230?filter=allopenissues)
version:1.2
[Download link gives HTTP/1.1 403 Forbidden](https://issues.apache.org/jira/projects/CLI/issues/CLI-232?filter=allopenissues)
version:1.2
[OptionValidator Implementation Does Not Agree With JavaDoc](https://issues.apache.org/jira/projects/CLI/issues/CLI-241?filter=allopenissues)
version:1.2
6. commons-cli commons-cli
version: 1.3.1
Jira issues:
[Optional argument picking up next regular option as its argument](https://issues.apache.org/jira/projects/CLI/issues/CLI-265?filter=allopenissues)
version:1.3.1
[HelpFormatter#setOptionComparator(null) doesn't display the values in inserted order](https://issues.apache.org/jira/projects/CLI/issues/CLI-266?filter=allopenissues)
version:1.3.1
7. commons-collections commons-collections
version: 3.2.1
Jira issues:
[Inconsistent Javadoc comment and code in addIgnoreNull(Collection<T>; T) in org.apache.commons.collections.CollectionUtils](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-400?filter=allopenissues)
version:3.2.1
[ListUtils.subtract is very slow ](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-406?filter=allopenissues)
version:3.2.1
[ListOrderedSet.removeAll() is slow](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-407?filter=allopenissues)
version:3.2.1
[ListOrderedSet.addAll() is very slow](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-409?filter=allopenissues)
version:3.2.1
[Performance problem in DualHashBidiMap](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-413?filter=allopenissues)
version:3.2.1
[AbstractLinkedList.removeAll() is very slow](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-415?filter=allopenissues)
version:3.2.1
[AbstractLinkedList.retainAll() is very slow](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-417?filter=allopenissues)
version:3.2.1
[Surprising exception by CompositeSet in a situation where CompositeCollection works fine](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-424?filter=allopenissues)
version:3.2.1
[performance problem in ListOrderedMap.remove()](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-425?filter=allopenissues)
version:3.2.1
[performance problem in ListOrderedSet.retainAll()](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-426?filter=allopenissues)
version:3.2.1
[performance problem in SetUniqueList.retainAll()](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-427?filter=allopenissues)
version:3.2.1
[SetUniqueList may become inconsistent](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-444?filter=allopenissues)
version:3.2.1
[findBugs Warnings: several classes in package functors may expose their internal representation](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-453?filter=allopenissues)
version:3.2.1
[findBugs Warning: Flat3Map - 3 iterators which are "both an Iterator and a Map.Entry"](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-454?filter=allopenissues)
version:3.2.1
[wasted work in AbstractMapBag.containsAll()](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-472?filter=allopenissues)
version:3.2.1
[ListOrderedSet can have duplicates](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-524?filter=allopenissues)
version:3.2.1;4.0
[ExtendedProperties causes AccessControlException when framework is called from a script](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-538?filter=allopenissues)
version:3.2.1
8. commons-io commons-io
version: 2.4
Jira issues:
[IOUtils copyLarge() and skip() methods are performance hogs](https://issues.apache.org/jira/projects/IO/issues/IO-355?filter=allopenissues)
version:2.3;2.4
[CharSequenceInputStream#reset() behaves incorrectly in case when buffer size is not dividable by data size](https://issues.apache.org/jira/projects/IO/issues/IO-356?filter=allopenissues)
version:2.4
[[Tailer] InterruptedException while the thead is sleeping is silently ignored](https://issues.apache.org/jira/projects/IO/issues/IO-357?filter=allopenissues)
version:2.4
[IOUtils.contentEquals* methods returns false if input1 == input2; should return true](https://issues.apache.org/jira/projects/IO/issues/IO-362?filter=allopenissues)
version:2.4
[Apache Commons - standard links for documents are failing](https://issues.apache.org/jira/projects/IO/issues/IO-369?filter=allopenissues)
version:2.4
[Links are broken on User Guide....](https://issues.apache.org/jira/projects/IO/issues/IO-370?filter=allopenissues)
version:2.4
[FileUtils.sizeOfDirectoryAsBigInteger can overflow](https://issues.apache.org/jira/projects/IO/issues/IO-390?filter=allopenissues)
version:2.4
[Regression in FileUtils.readFileToString from 2.0.1](https://issues.apache.org/jira/projects/IO/issues/IO-453?filter=allopenissues)
version:2.1;2.2;2.3;2.4
[Correct exception message in FileUtils.getFile(File; String...)](https://issues.apache.org/jira/projects/IO/issues/IO-479?filter=allopenissues)
version:2.4
[org.apache.commons.io.FileUtils#waitFor waits too long](https://issues.apache.org/jira/projects/IO/issues/IO-481?filter=allopenissues)
version:2.4
[getPrefixLength return -1 if unix file contains colon](https://issues.apache.org/jira/projects/IO/issues/IO-483?filter=allopenissues)
version:2.4
[FilenameUtils should handle embedded null bytes](https://issues.apache.org/jira/projects/IO/issues/IO-484?filter=allopenissues)
version:2.4
[Exceptions are suppressed incorrectly when copying files.](https://issues.apache.org/jira/projects/IO/issues/IO-502?filter=allopenissues)
version:2.4;2.5
9. commons-codec commons-codec
version: 1.6
Jira issues:
[QuotedPrintableCodec does not support soft line break per the 'quoted-printable' example on Wikipedia](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-121?filter=allopenissues)
version:1.5;1.6
[BeiderMorseEncoder OOM issues](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-132?filter=allopenissues)
version:1.6
[BeiderMorse phonetic filter give uncertain results ](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-147?filter=allopenissues)
version:1.6
[DigestUtils.getDigest(String) looses the orginal exception](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-152?filter=allopenissues)
version:1.6
[DigestUtils.getDigest(String) should throw IllegalArgumentException instead of RuntimeException](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-155?filter=allopenissues)
version:1.6
[DigestUtils: add APIs named after standard alg name SHA-1](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-156?filter=allopenissues)
version:1.6
[BaseNCodecOutputStream only supports writing EOF on close()](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-183?filter=allopenissues)
version:1.6
10. commons-codec commons-codec
version: 1.10
Jira issues:
[Internal Server Error in Download area](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-197?filter=allopenissues)
version:1.10
[Bug in HW rule in Soundex](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-199?filter=allopenissues)
version:1.10
[Charsets Javadoc breaks build when using Java 8](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-207?filter=allopenissues)
version:1.10
[Javadoc for SHA-224 DigestUtils methods should mention Java 1.8.0 restriction instead of 1.4.0](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-209?filter=allopenissues)
version:1.10
[Don't deprecate Charsets Charset constants in favor of Java 7's java.nio.charset.StandardCharsets](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-219?filter=allopenissues)
version:1.10
[HmacUtils.updateHmac calls reset() unnecessarily](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-221?filter=allopenissues)
version:1.10
[InputStream not closed](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-225?filter=allopenissues)
version:1.10;1.11
[StringUtils.newStringxxx(null) should return null; not NPE](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-229?filter=allopenissues)
version:1.10
[URLCodec.WWW_FORM_URL should be private](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-230?filter=allopenissues)
version:1.10
[StringUtils.equals(CharSequence cs1; CharSequence cs2) can fail with String Index OBE](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-231?filter=allopenissues)
version:1.10
[URLCodec is neither immutable nor threadsafe](https://issues.apache.org/jira/projects/CODEC/issues/CODEC-232?filter=allopenissues)
version:1.10
11. org.apache.commons commons-lang3
version: 3.1
Jira issues:
[NumberUtils#isNumber() returns false for "+2" and true for "-2"](https://issues.apache.org/jira/projects/LANG/issues/LANG-1038?filter=allopenissues)
version:3.1;3.3.2
[NumberUtils.createNumber() behaves inconsistently with NumberUtils.isNumber()](https://issues.apache.org/jira/projects/LANG/issues/LANG-1205?filter=allopenissues)
version:3.1
[TypeUtils.getTypeArguments() misses type arguments for partially-assigned classes](https://issues.apache.org/jira/projects/LANG/issues/LANG-775?filter=allopenissues)
version:3.1
[TypeUtilsTest contains incorrect type assignability assertion due to lost/skipped type variable information during the decision process](https://issues.apache.org/jira/projects/LANG/issues/LANG-776?filter=allopenissues)
version:3.1
[SerializationUtils throws ClassNotFoundException when cloning primitive classes](https://issues.apache.org/jira/projects/LANG/issues/LANG-788?filter=allopenissues)
version:3.1
[SystemUtils.IS_OS_WINDOWS_2008; VISTA are incorrect](https://issues.apache.org/jira/projects/LANG/issues/LANG-794?filter=allopenissues)
version:3.1
[LocaleUtils - unnecessary recursive call in SyncAvoid class](https://issues.apache.org/jira/projects/LANG/issues/LANG-802?filter=allopenissues)
version:3.1
[RandomStringUtils.random(count; 0; 0; false; false; universe; random) always throws java.lang.ArrayIndexOutOfBoundsException](https://issues.apache.org/jira/projects/LANG/issues/LANG-805?filter=allopenissues)
version:2.5;2.6;3.1
[StringUtils.join() endIndex; bugged for loop](https://issues.apache.org/jira/projects/LANG/issues/LANG-810?filter=allopenissues)
version:3.1
[StringUtils.equalsIgnoreCase doesn't check string reference equality](https://issues.apache.org/jira/projects/LANG/issues/LANG-813?filter=allopenissues)
version:3.1
[[Method|Constructor]Utils.invoke*(*; Object... args) variants cannot handle null values](https://issues.apache.org/jira/projects/LANG/issues/LANG-814?filter=allopenissues)
version:3.1
[Add org.apache.commons.lang3.SystemUtils.IS_OS_WINDOWS_8](https://issues.apache.org/jira/projects/LANG/issues/LANG-817?filter=allopenissues)
version:3.1
[NumberUtils#createNumber - bad behaviour for leading "--"](https://issues.apache.org/jira/projects/LANG/issues/LANG-822?filter=allopenissues)
version:3.1
[FastDateParser does not handle non-ASCII digits correctly](https://issues.apache.org/jira/projects/LANG/issues/LANG-826?filter=allopenissues)
version:3.1
[FastDateParser does not handle non-Gregorian calendars properly](https://issues.apache.org/jira/projects/LANG/issues/LANG-828?filter=allopenissues)
version:3.1
[FastDateFormat and FastDatePrinter generates Date objects wastefully](https://issues.apache.org/jira/projects/LANG/issues/LANG-849?filter=allopenissues)
version:3.1
[LocaleUtils.toLocale does not parse strings starting with an underscore](https://issues.apache.org/jira/projects/LANG/issues/LANG-865?filter=allopenissues)
version:3.1
[LocaleUtils test fails with new Locale "ja_JP_JP_#u-ca-japanese" of JDK7](https://issues.apache.org/jira/projects/LANG/issues/LANG-879?filter=allopenissues)
version:3.1
[LookupTranslator accepts CharSequence as input; but fails to work with implementations other than String](https://issues.apache.org/jira/projects/LANG/issues/LANG-882?filter=allopenissues)
version:3.1
[CLONE - DateFormatUtils.format does not correctly change Calendar TimeZone in certain situations](https://issues.apache.org/jira/projects/LANG/issues/LANG-916?filter=allopenissues)
version:3.1
[Add ArrayUtils#nullToEmpty(Class<?>[])](https://issues.apache.org/jira/projects/LANG/issues/LANG-920?filter=allopenissues)
version:3.1
[BooleanUtils.xor(boolean...) produces wrong results](https://issues.apache.org/jira/projects/LANG/issues/LANG-921?filter=allopenissues)
version:3.1
[Test DurationFormatUtilsTest.testEdgeDuration fails in JDK 1.6; 1.7 and 1.8; BRST time zone](https://issues.apache.org/jira/projects/LANG/issues/LANG-943?filter=allopenissues)
version:3.1;3.2;3.2.1
[Fragments are wrong by 1 day when using fragment YEAR or MONTH](https://issues.apache.org/jira/projects/LANG/issues/LANG-951?filter=allopenissues)
version:3.1
[NumberUtils#createNumber() returns positive BigDecimal when negative Float is expected](https://issues.apache.org/jira/projects/LANG/issues/LANG-1087?filter=allopenissues)
version:3.x
12. org.apache.commons commons-lang3
version: 3.4
Jira issues:
[TypeUtils.ParameterizedType#equals doesn't work with wildcard types](https://issues.apache.org/jira/projects/LANG/issues/LANG-1114?filter=allopenissues)
version:3.3.2;3.4
[DateUtilsTest.testLang530 fails for some timezones](https://issues.apache.org/jira/projects/LANG/issues/LANG-1116?filter=allopenissues)
version:3.4
[StringUtils.stripAccents from "Ł" and "ł"](https://issues.apache.org/jira/projects/LANG/issues/LANG-1120?filter=allopenissues)
version:3.4
[No release notes for version 3.4](https://issues.apache.org/jira/projects/LANG/issues/LANG-1125?filter=allopenissues)
version:3.4
[JsonToStringStyle doesn't handle chars and objects correctly](https://issues.apache.org/jira/projects/LANG/issues/LANG-1128?filter=allopenissues)
version:3.4
[ReflectionToStringBuilder doesn't throw IllegalArgumentException when the constructor's object param is null](https://issues.apache.org/jira/projects/LANG/issues/LANG-1132?filter=allopenissues)
version:3.4
[StrLookup.systemPropertiesLookup() no longer reacts on changes on system properties](https://issues.apache.org/jira/projects/LANG/issues/LANG-1141?filter=allopenissues)
version:3.4
[StringUtils#capitalize: Javadoc says toTitleCase; code uses toUpperCase](https://issues.apache.org/jira/projects/LANG/issues/LANG-1142?filter=allopenissues)
version:3.4
[Multiple calls of org.apache.commons.lang3.concurrent.LazyInitializer.initialize() are possible](https://issues.apache.org/jira/projects/LANG/issues/LANG-1144?filter=allopenissues)
version:3.4;3.5
[EnumUtils *BitVector issue with more than 32 values Enum](https://issues.apache.org/jira/projects/LANG/issues/LANG-1147?filter=allopenissues)
version:3.4
[StringUtils#equals fails with Index OOBE on non-Strings with identical leading prefix](https://issues.apache.org/jira/projects/LANG/issues/LANG-1162?filter=allopenissues)
version:3.4
[There are no tests for CharSequenceUtils.regionMatches](https://issues.apache.org/jira/projects/LANG/issues/LANG-1163?filter=allopenissues)
version:3.4
[ArrayUtils.removeAll(Object array; int... indices) should do the clone; not its callers](https://issues.apache.org/jira/projects/LANG/issues/LANG-1178?filter=allopenissues)
version:3.4
[TypeUtils.isAssignable throws NullPointerException when fromType has type variables and toType generic superclass specifies type variable](https://issues.apache.org/jira/projects/LANG/issues/LANG-1190?filter=allopenissues)
version:3.4
[FastDateFormat does not support the week-year component (uppercase 'Y')](https://issues.apache.org/jira/projects/LANG/issues/LANG-1192?filter=allopenissues)
version:3.4
[ordinalIndexOf("abc"; "ab"; 1) gives incorrect answer of -1 (correct answer should be 0)](https://issues.apache.org/jira/projects/LANG/issues/LANG-1193?filter=allopenissues)
version:3.4
[Fix implementation of StringUtils.getJaroWinklerDistance()](https://issues.apache.org/jira/projects/LANG/issues/LANG-1199?filter=allopenissues)
version:3.4
[parseDateStrictly does't pass specified locale](https://issues.apache.org/jira/projects/LANG/issues/LANG-1202?filter=allopenissues)
version:3.4
[ClassUtils.getClass(ClassLoader; String) fails for "void"](https://issues.apache.org/jira/projects/LANG/issues/LANG-1214?filter=allopenissues)
version:3.4
[NumberUtils.isNumber bug](https://issues.apache.org/jira/projects/LANG/issues/LANG-1216?filter=allopenissues)
version:3.4
[FastDateFormat doesn't respect summer daylight in localized strings](https://issues.apache.org/jira/projects/LANG/issues/LANG-1219?filter=allopenissues)
version:3.4
[StringUtils#normalizeSpace does not trim the string anymore](https://issues.apache.org/jira/projects/LANG/issues/LANG-1226?filter=allopenissues)
version:3.4
[DiffBuilder: Add null check on fieldName when appending Object or Object[]](https://issues.apache.org/jira/projects/LANG/issues/LANG-1232?filter=allopenissues)
version:3.4
[FastDatePrinter Memory allocation regression](https://issues.apache.org/jira/projects/LANG/issues/LANG-1248?filter=allopenissues)
version:3.4
[SerializationUtils.ClassLoaderAwareObjectInputStream should use static initializer to initialize primitiveTypes map.](https://issues.apache.org/jira/projects/LANG/issues/LANG-1251?filter=allopenissues)
version:3.2;3.3;3.4
[NumberUtils.isNumber and NumberUtils.createNumber resolve inconsistently](https://issues.apache.org/jira/projects/LANG/issues/LANG-1252?filter=allopenissues)
version:3.4
[ArrayUtils.contains returns false for instances of subtypes](https://issues.apache.org/jira/projects/LANG/issues/LANG-1261?filter=allopenissues)
version:3.4
[CompareToBuilder.append(Object;Object;Comparator) method is too big to be inlined](https://issues.apache.org/jira/projects/LANG/issues/LANG-1262?filter=allopenissues)
version:3.4
[StrBuilder#replaceAll ArrayIndexOutOfBoundsException](https://issues.apache.org/jira/projects/LANG/issues/LANG-1276?filter=allopenissues)
version:3.2.1;3.4;3.5
[NumberUtils#createNumber() returns positive BigDecimal when negative Float is expected](https://issues.apache.org/jira/projects/LANG/issues/LANG-1087?filter=allopenissues)
version:3.x
13. commons-lang commons-lang
version: 2.6
Jira issues:
[Remove unnecessary synchronization from registry lookup in EqualsBuilder and HashCodeBuilder](https://issues.apache.org/jira/projects/LANG/issues/LANG-1230?filter=allopenissues)
version:2.6
[LocaleUtils - DCL idiom is not thread-safe](https://issues.apache.org/jira/projects/LANG/issues/LANG-803?filter=allopenissues)
version:2.6
[RandomStringUtils.random(count; 0; 0; false; false; universe; random) always throws java.lang.ArrayIndexOutOfBoundsException](https://issues.apache.org/jira/projects/LANG/issues/LANG-805?filter=allopenissues)
version:2.5;2.6;3.1
[Exception when combining custom and choice format in ExtendedMessageFormat](https://issues.apache.org/jira/projects/LANG/issues/LANG-917?filter=allopenissues)
version:2.5;2.6

**Comment by mpolden** [comment]
Looks like we exclusively use commons-codec for base64 encoding.

Maybe we can switch to using `BaseEncoding` from Guava and get rid of commons-codec completely. What do you think, @gjoranv?

**Comment by vekterli** [comment]
Any particular reason why we can't just use `java.util.Base64`? Maybe we have our own custom encoding alphabet (ybase64 etc)?

**Comment by mpolden** [comment]
Sure, that's even better. I think it's only standard base64, no custom alphabets that I could find.

**Comment by bjorncs** [comment]
All libraries listed here are now either updated or removed.
