### ISSUE TITLE
Vespa 8: remove Document compression

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#8928]
ref https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#compression - is this needed anymore?

I have discussed this with @vekterli 
* Documents are compressed in larger chunks in the summary store
* Documents are compressed over RPC as well

So I think there is really no need for the per-document compression, and it should be removed. Maybe have read-support for it for a long time, if such docs are persisted. (Are they, @baldersheim  - could docs be double compressed in the summary store?)

Please add considerations here (@bratseth ++) - if you agree, I would like to deprecate use of this from now on

**Comment by baldersheim** [comment]
I think the only use was once upon a time in perhaps some experiments by @jobergum .
So I agree, let it go.

**Comment by bratseth** [comment]
Agree

**Comment by kkraune** [comment]
@hmusum : can you add a deprecation warning for app packages with this in the search def?

**Comment by hmusum** [comment]
Added in https://github.com/vespa-engine/vespa/pull/8940

**Comment by bjorncs** [comment]
Done by @baldersheim
