### ISSUE TITLE
Vespa 7:  short sentence match

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#9012]
I am using vespa in video search system.  The average length of video meta text is less than 5 and minimum field length factor of nativeRank is 6, so nativeRank score is not sensitive to matching percent for short sentence.
Okapi BM25 may be better for short sentence matching and it works fine in our system.
Will vespa support BM25 and other similarities in ES in future?
if not,  is there any suggestions on settings of boost tables for short sentence matching?

**Comment by kkraune** [comment]
Hi!

@geirst and the team has started looking into this, so he can give you an update on the plan in a week or two, when the current sprint is done - assigning to him

**Comment by dsisds** [comment]
@kkraune @geirst Looking forward to your plans. 
Despite the new score similarity，is there any suggestions on settings of nativeRank boost tables for short sentence matching?

**Comment by bratseth** [comment]
> so nativeRank score is not sensitive to matching percent for short sentence.

I don't think that's the right conclusion. There's no matching percent ("field completeness") in nativeRank at all, but there is first and number of occurrences. These two matters for short fields as well, it's just that they matter precisely the same way in a field that is 6 tokens long and one which is shorter. This is just to avoid making the scores too sensitive to the exact length of the field for short lengths. I think the default boost tables should work well for this.

Matching percentage is what we call "field completeness". This is not part of nativeRank itself, but you can get it by using this ranking expression for the field:
`nativeRank(field) * matchCount(field) / fieldLength(field)
 `

Alternatively you can use fieldMatch instead, as it has completeness (field- and query-) built in. fieldMatch is more expensive than nativeRank, but not so much for short fields. (For the very best relevance you want to not use fieldMatch as-is but machine-learn and expression combining the fine-grained features it aggregates.)

**Comment by dsisds** [comment]
@bratseth  I add completeness feature to my xgboost model and it works well. 

Thanks.

**Comment by bratseth** [comment]
Thanks for the update, closing.
