### ISSUE TITLE
Multiple Disks Support 

### ISSUE THREAD

**Issue by zttaotao2013** [vespa-engine/vespa#9209]
I am puzzled that how to do in vespa when multiple disks in one node should be utilized? I can't find item to confiure in the whole vespa configuration.I know the defalt dir of vespa's store is $VESPA_HOME/var/db/vespa/search,can this be changed? How can I do when I want to write data to multiple disks in one content node?

**Comment by kkraune** [comment]
Options:

1: stripe disks (RAID)
2: virtualize the host into logical hosts, having one disk each (or a RAID), and run one content node in each logical host
3: one the host, run multiple instances of content nodes

The important point it, proton (the content node process) can only be configured with one path for the persisted data.

In practice, it is operationally a good idea to map disks and content nodes 1-1, as disks are error prone and more often fail than other components

I hope this helps - plmk if you need more input, we have much experience with questions like this, and knowing your use case can help us provide a recommendation

**Comment by baldersheim** [comment]
Most IO is sequential reads and writes and that scales very well with RAID setups. Raid 0 or 10 is recomended.

**Comment by zttaotao2013** [comment]
thanks for your reply, I know .

**Comment by zttaotao2013** [comment]
@kkraune I have another question about the deployment mode of disks and content nodes 1-1  map . In this mode,the data replication will be distributed in different disks of one machine ,such as 2 replicas， the data will be not available when one machine go wrong. what can i do when this happen?

**Comment by kkraune** [comment]
yes if you run multiple content nodes on one host, the host is single point of failure. Vespa Team stripes disks to one logical disk, and runs only one instance of a content node per application per host, so one host can go down at all times

**Comment by bratseth** [comment]
You should never run multiple content nodes in the same cluster on the same physical host for this reason. If you want to use the entire host for that cluster just make a single, larger node. Vespa can use all the resources effectively in a single content node instance (it's not Java).

**Comment by zttaotao2013** [comment]
if I stripe all disks of a host to one logical disk(using raid0) for making a large node,perhaps there is another question that it will cost very much time for recovering data using  replication when any one disk in the physical  host  damage ,because in raid0 mode,one disk damaged will cause the entire logical disk damaged.  In my case, the volume of logical disk can reach(48T), if these data will be recovering , the time that cost perhaps  would exceed our expectation.

**Comment by kkraune** [comment]
correct - that will give a recovery time of days - we normally limit size to just a few TBs just for this reason

**Comment by bratseth** [comment]
Usually the number of documents you can put on a node without running out of memory for attributes or cpu budget for query execution will limit you long before you get close to 48T. 

To reach that you need a very small fraction of attribute data to total data and either unusually few matching documents per query or unusually high latency budget.
