### ISSUE TITLE
Support sorting for type bool fields

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#9296]
`[2019-05-07 10:06:33.013] WARNING : searchnode       proton.search.attribute.sortresults    Attribute vector 'in_stock' is not valid. Skipped in sorting`

For field defined as type bool

```
field in_stock type bool {
  indexing: summary | attribute
}
```

**Comment by baldersheim** [comment]
I am not able to reproduce. User error ?
Perhaps 2 searchdefinitions without restricting search ....

**Comment by baldersheim** [comment]
Verified it works just fine in https://github.com/vespa-engine/system-test/pull/118
