### ISSUE TITLE
fuzzy match under index support 

### ISSUE THREAD

**Issue by zttaotao2013** [vespa-engine/vespa#9371]
hello,i have a question about fuzzy  match . attribute support fuzzy match but cost a lot of memory ，it will use all memory of content node under mass data. Index will not cost many memory ,but seems only support text\word\exact\gram models， fuzzy match for term not support, lucence can support fuzzy match under index model，can vespa support this match model?

**Comment by jobergum** [comment]
The various match modes supported is described here https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#match. 
n-gram indexing is supported for index fields which I think could be categorised as fuzzy matching.

**Comment by zttaotao2013** [comment]
under n-gram indexing, could the string "hi blue"(gram-size is 2) be search for "blu" or "lue"?

**Comment by bratseth** [comment]
That would be 3-grams. See https://github.com/vespa-engine/vespa/blob/master/linguistics/src/main/java/com/yahoo/language/process/GramSplitter.java if you are interested in the details of how tokens are generated. This is done automatically both on indexing and query time if a field is set to n-gram matching.

By default the query over the grams uses AND matching. You may want to use OR instead (or perhaps NEAR/ONEAR or WAND). To do that you need to replace the NGramSearcher in the "local" search chain (which you use by default) by a subclass which returns another composite item than AndItem as the root item, see https://github.com/vespa-engine/vespa/blob/master/container-search/src/main/java/com/yahoo/search/querytransform/NGramSearcher.java#L139

Let me know if you need help with that. I would like to make that controllable by a config parameter instead but haven't gotten around to it yet.

**Comment by zttaotao2013** [comment]
@jobergum @bratseth thanks your reply, I practice n-gram in cluster,it take effect in most fuzzy matching  scenes,but it does not take effect in that  scene such as the string "hi blue" (gram-size is 3)  be searched for substing ("i b"),but it can mostly satisfy my requirement。
I have an other question about attribute，it store in memory from cluster  start and never be cleared， when the docments insterted  becomes more and more,the attribute will use all the memory of the mechine，and the cluster become not available ，how can I slove this problem？  Today I insert 5  hundred million to cluster，there are 20 index filed and 20 attribute ,the ram of machine(64G) is eat up,and the service of cluster become not available。

**Comment by jobergum** [comment]
If you are running out of memory you need to add more nodes or increase the memory per available per node. Fields which are attributes are in memory for fast random access during search/ranking/sorting/grouping. 

Some resources on attributes and sizing:

- https://docs.vespa.ai/documentation/performance/sizing-search.html
- https://docs.vespa.ai/documentation/attributes.html
- https://docs.vespa.ai/documentation/performance/attribute-memory-usage.html

**Comment by zttaotao2013** [comment]
Is there some mechanism  for attribute that it clear unused memory when the memory reach the limit，then fetch the data from the disk when the data is required，similar with Cache. if vespa can do this, we don't worry that memory is eat up，trade off a litte query efficiency。

**Comment by jobergum** [comment]
There is no such mechanism in Vespa currently for attribute fields. What type of attribute fields do you have ? Numeric types or primary strings?

**Comment by zttaotao2013** [comment]
now the type that I test is strings,length is 20-30

**Comment by jobergum** [comment]
For my understanding, the primary reason you want to use attribute for these string fields is?

**Comment by zttaotao2013** [comment]
My scene is descripted  as follows:
I have 3 mechine with 4T*6 SATA disks and  64G memery， I start one content node on every disk，18  content node is put together to comprise one cluster. the average size of document is  1K，the field num is 150，the index and attribute num is each 20，most is string type. I found that the memory is eat up when I insert  5 hundred million docments，but these documents size  stored in disks is only 23G in one content node，this num is  far away with 2T. In this case，it appear that  a lot of disks couldn't be used because the memory is eat up. 
This is the problem I now meet，could you give some good suggest？

**Comment by jobergum** [comment]
In this case you don't have memory enough to support this amount of documents. 

 Do you have the output of 'top' (Use shift-m to sort process output by memory usage).

**Comment by bratseth** [comment]
Why do you make these strings attributes? Storing most of it on disk is precisely what "index" fields do, while attributes are always in memory to support fast forward lookup (access during aggregation/ranking). Forward lookup is usually not that useful for text fields.

**Comment by zttaotao2013** [comment]
@jobergum  yes，the output of top is that memory is used up to 8G * 6 , mostly nealy 64G, that is to say that  in this case, if this is not enough memory , vespa can't process and store so much data. In my understand, the amount of the yahoo's data is very large, it should  exceed very a lot of my case,how should you  deal with these data？or there is a little of fields  for group\order\sum in yahoo's in business? if this ,should vespa is suitable for realtime query ,but not suitable  to compute for more fields?

**Comment by zttaotao2013** [comment]
@baldersheim  if i  pick up the int field as  attribute，in my case，the memory used also is very large，we can figure that it cost  almost 96 G (4T/1k * 4B /1k/1k/1k * 6 ) in one machine for one int attribute. if there is four attribute,it will cost 96*4=384 G . the most machine server doesn't have these amount of memory.

**Comment by baldersheim** [comment]
It sounds like you are starting the sizing in the wrong end.
You need to figure out what is the limiting factor first. Disk space I have never experienced to be a limiting factor. It is either cpu or memory.
I assume that you have a latency requirement. Based on that you can see how many documents makes sense to have on a single node.
I have never seen the need for more than 1T disk on any node. Long before that you will have used all available cpu, or memory.

**Comment by bratseth** [comment]
> it should exceed very a lot of my case,how should you deal with these data？or there is a little of fields for group\order\sum in yahoo's in business? if this ,should vespa is suitable for realtime query ,but not suitable to compute for more fields?

Make large fields (i.e text) index, not attribute. Only structured text such as numbers and enum values are suitable for grouping and aggregation and they don't require much memory.

**Comment by zttaotao2013** [comment]
could I  be gave some suggestions about how to select the volume of memory and disk of a content node at general scene?

**Comment by zttaotao2013** [comment]
thanks for your reply . 
could I be gave some suggestions about how to select the volume of memory and disk of a content node at general scene?
@baldersheim  do you mean that in your content node ,the volume of disk doesn't exceed 1T，and  if there is 500T data,perhaps it needs at least 500 content node，and every content node correspond to one machine ？ if this , in my work scene，the data size is far more then 500T，perhaps I need far more content node and machine.

**Comment by kkraune** [comment]
> perhaps I need far more content node and machine.

probably yes. maybe you can open a separate ticket for the sizing, with relevant data and load numbers - and we can get you started and design a load testing experiement

**Comment by zttaotao2013** [comment]
I got it，thanks for your valuable reply .

**Comment by bratseth** [comment]
For others who find this issue:
An example <search> block from in services.xml that replaces the NGram searcher for a content cluster called "mycontent":

    <search>
        <chain id='default'>
            <federation id='federationSearcher'>
                <source id='local'/>
            </federation>
        </chain>
        <provider cluster='mycontent' excludes='com.yahoo.search.querytransform.NGramSearcher' id='local' type='local'>
            <searcher bundle='basic-application' id='ai.vespa.example.OrNGramSearcher'/>
        </provider>
    </search>

And the searcher:

```
package ai.vespa.example;

import com.yahoo.search.Query;
import com.yahoo.prelude.query.CompositeItem;
import com.yahoo.prelude.query.OrItem;
import com.yahoo.search.querytransform.NGramSearcher;
import com.yahoo.language.Linguistics;

/**
 * Changes NGram recall from AND to OR
 */
public class OrNGramSearcher extends NGramSearcher {

    public OrNGramSearcher(Linguistics linguistics) {
        super(linguistics);
    }

    @Override
    protected CompositeItem createGramRoot(Query query) {
        return new OrItem();
    }

}
```

**Comment by tkaessmann** [comment]
Fuzzy matching is now officially support since vespa `7.585`. #21689
See: https://docs.vespa.ai/en/reference/query-language-reference.html#fuzzy

**Comment by Nistha314e** [comment]
Hi. Can we stop n-gram matching at the time of querying?
My requirement is to use fuzzy matching in case of index fields, which I am possibly doing with the help of n-gram indexing. But it is again giving some results which we don't want because of n-gram matching. So, I want to do a simple search first without any gram matching and then do fuzzy matching using n-gram indexing. Is there any possible way to achieve that?

**Comment by jobergum** [comment]
Not with the same field, as once you gram it, that has happened during indexing, so you cannot switch between exact and gram matching. You need to define an additional field:

```
schema doc {
  document doc {
    field foo type string {
       indexing: summary |  index
    } 
  } # end document 
  field foo_fuzzy type string {
      indexing: input foo | index
      match {
        gram
        gram-size: 3
      }
  }
}
```

**Comment by Nistha314e** [comment]
Thanks for the reply @jobergum 
I also had one more doubt. I am facing a problem while doing fuzzy matching through n-gram matching. I am doing 3-gram matching in a string field. When I am searching for **"archetype"**, it is giving me the desired results, but when I am searching for "**archtype**" i.e skipping an e, it is not performing fuzzy matching and not giving any results.
Interestingly, when I am searching for "**achetype**" i.e removing an r in the start, it is giving me the desired results.
I wanted to understand, how exactly this n-gram matching is happening and how this particular test case can be resolved.
Thanks for your help.

**Comment by kkraune** [comment]
Hi @Nistha314e  I suggest using https://docs.vespa.ai/en/query-api.html#query-tracing to understand exactly how the query is tokenized using n-gram, and see https://docs.vespa.ai/en/text-matching-ranking.html for how to inspect the tokens in the index - then you can do a controlled experiment to understand n-gram tokenization and matching.

Finally, this is a closed ticket and has already multiple topics. If you have questions after trying the above, maybe create a question on https://stackoverflow.com/questions/tagged/vespa for n-gram matching in Vespa? It helps if the schema, data and query is posted so people can reproduce also

**Comment by bratseth** [comment]
Ngram matching is by AND by default - did you switch to OR as detailed in [this comment above](https://github.com/vespa-engine/vespa/issues/9371#issuecomment-725399737)?

**Comment by Nistha314e** [comment]
@bratseth 
Hey, I would like to know where should we add this searcher code.
```
package ai.vespa.example;

import com.yahoo.search.Query;
import com.yahoo.prelude.query.CompositeItem;
import com.yahoo.prelude.query.OrItem;
import com.yahoo.prelude.query.HasIndexItem;
import com.yahoo.search.querytransform.NGramSearcher;
import com.yahoo.language.Linguistics;

/**
 * Changes NGram recall from AND to OR
 */
public class OrNGramSearcher extends NGramSearcher {

    public OrNGramSearcher(Linguistics linguistics) {
        super(linguistics);
    }

    @Override
    protected CompositeItem createGramRoot(HasIndexItem term, Query query) {
        return new OrItem();
    }

}
```

**Comment by jobergum** [comment]
See [doc](https://docs.vespa.ai/en/searcher-development.html) or better look at this [sample app](https://github.com/vespa-engine/sample-apps/tree/master/album-recommendation-java). 

Note that changing to OR will dramatically increase the number of hits queries will produce.

**Comment by bratseth** [comment]
Use a standard maven layout on your vespa application project files, as done in the Vespa sample apps which includes Java code. This means you code will be placed somewhere under src/main/java.
