### ISSUE TITLE
Query timeout

### ISSUE THREAD

**Issue by yyangliu** [vespa-engine/vespa#9389]
Hello!  I have a question about query timeout, when I search using "http://localhost:8080/search/?timeout=200", the query results  can be returned in less than 200s, from the results, I found that only part of the whole documents had been scanned when executing searching, and the "timeout" is true, I wonder why the query can not be executed until the timeout I set to scan as many docs as possible. Firstly, it seems that the arg"timeout" does not work. Secondly, I want to find a way to scan all documents  when doing search.
I'm eager to get your help! Thank you very much!

**Comment by jobergum** [comment]
Hello, so timeout=200 means 200 seconds and is the upper bound and if soft timeout is enabled (default true) the search core will return whatever it has ranked.  How long does it take? And what are you doing that takes 200 seconds? :) Could you include the time it takes and the actual coverage element in the json response. 

See https://docs.vespa.ai/documentation/graceful-degradation.html for documentation on timeout and soft timeout behaviour.

**Comment by yyangliu** [comment]
Thanks for your guide, I tested and found that when some content nodes were unhealthy, timeout didn't take effect, coverage was less than 100% and when the cluster was OK, timeout took effect, coverage could reach 100%, So I guess nodes problem lead to my query issue.
I found proton process on the bad node was down, when I tried to start it, an exception "Failed creating domain 'im' on TLS 'tcp/vespa7:19113'" was thrown out, I checked network and other cluster envs and found nothing bad, can u give me any ideas? thank u very much again!

**Comment by jobergum** [comment]
Thanks for the feedback on the timeout/coverage guide. 

On the node could you check 'vespa-proton-cmd --local getProtonStatus'. See https://docs.vespa.ai/documentation/reference/vespa-cmdline-tools.html#vespa-proton-cmd

The TLS component is the transaction log service which proton talks to.

**Comment by yyangliu** [comment]
Thanks for your reply. I'll check next time when the error occurs again.
