### ISSUE TITLE
Shopping use-case error when deploy the application

### ISSUE THREAD

**Issue by lundin** [vespa-engine/vespa#9411]
Hi,

I followed all the steps here:
https://github.com/vespa-engine/sample-apps/tree/master/use-case-shopping

However when uploading the application it says:

Preparing session 8 using http://localhost:19071/application/v2/tenant/default/session/8/prepared

Request failed. HTTP status code: 400
Invalid application package: default.default: Error loading model: Could not parse search definition file 'searchdefinitions/item.sd': Encountered " <IDENTIFIER> "from-disk "" at line 58, column 9.
Was expecting one of:
    "\n" ...
    "summary" ...
    "}" ...
    
At position:
        from-disk
        ^: Encountered " <IDENTIFIER> "from-disk "" at line 58, column 9.
Was expecting one of:
    "\n" ...
    "summary" ...
    "}" ...
    
At position:
        from-disk
        ^`

Removing that, what is from-disk anyway ?

Request failed. HTTP status code: 400
Invalid application package: default.default: Error loading model: Could not parse search definition file 'searchdefinitions/item.sd': Encountered " "function" "function "" at line 73, column 9.
Was expecting one of:
    "\n" ...
    "rank-type" ...
    "weight" ...
    "rank-degradation-frequency" ...
    "rank-degradation" ...
    "rank" ...
    "ignore-default-rank-features" ...
    "}" ...
    "match-phase" ...
    "first-phase" ...
    "second-phase" ...
    "macro" ...
    <SUMMARYFEATURES_SL> ...
    <SUMMARYFEATURES_ML> ...
    <RANKFEATURES_SL> ...
    <RANKFEATURES_ML> ...
    "rank-properties" ...
    "num-threads-per-search" ...
    "min-hits-per-thread" ...
    "num-search-partitions" ...
    "termwise-limit" ...
    "constants" ...
    
At position:
        function inline average_rating() {
        ^: Encountered " "function" "function "" at line 73, column 9.
Was expecting one of:
    "\n" ...
    "rank-type" ...
    "weight" ...
    "rank-degradation-frequency" ...
    "rank-degradation" ...
    "rank" ...
    "ignore-default-rank-features" ...
    "}" ...
    "match-phase" ...
    "first-phase" ...
    "second-phase" ...
    "macro" ...
    <SUMMARYFEATURES_SL> ...
    <SUMMARYFEATURES_ML> ...
    <RANKFEATURES_SL> ...
    <RANKFEATURES_ML> ...
    "rank-properties" ...
    "num-threads-per-search" ...
    "min-hits-per-thread" ...
    "num-search-partitions" ...
    "termwise-limit" ...
    "constants" ...

was using 4GB Docker, Mac OS X, java 11.

**Comment by lesters** [comment]
Hi, so `from-disk` is a hint to Vespa that it is ok to retrieve the summary from disk, so it doesn't have to keep the fields in memory: https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#document-summary

I just tested this now and it is working as intended for me at least. Have you edited the `item.sd` file in any way? It is also strange that you keep getting parse errors after removing this line. For me:

```
$ docker pull vespaengine/vespa
Using default tag: latest
latest: Pulling from vespaengine/vespa
8ba884070f61: Already exists 
e347bdade816: Pull complete 
f57f5ba8d2d9: Pull complete 
b9a3ac5b098e: Pull complete 

$ docker run --detach --name shopping --hostname vespa-container --privileged --volume `pwd`:/apps --publish 8080:8080 vespaengine/vespa
9ce0deaa32fa403abff2b7c2fb3cff0a7b913522093fa2801210e6abfa0bdd60

$ docker exec shopping bash -c '/opt/vespa/bin/vespa-deploy prepare /apps/target/application.zip && /opt/vespa/bin/vespa-deploy activate'
Uploading application '/apps/target/application.zip' using http://localhost:19071/application/v2/tenant/default/session
Session 2 for tenant 'default' created.
Preparing session 2 using http://localhost:19071/application/v2/tenant/default/session/2/prepared
WARNING: Host named 'vespa-container' may not receive any config since it is not a canonical hostname
Session 2 for tenant 'default' prepared.
Activating session 2 using http://localhost:19071/application/v2/tenant/default/session/2/active
Session 2 for tenant 'default' activated.
Checksum:   1cdfd29222a72e79d0c73a064acf2ef2
Timestamp:  1557906306935
Generation: 2
```

**Comment by lundin** [comment]
Hi @lesters many thanks!! It seems that it indeed work and that i had too low memory in Docker...i have tricked myself with this before...

Sorry for the false alarm and keep up the good works!
