### ISSUE TITLE
Vespa 8: Fields from inherited documents are not shown in search results

### ISSUE THREAD

**Issue by pmuens** [vespa-engine/vespa#9434]
Hey everyone,
first of all: Thanks for open sourcing Vespa :+1:

I'm currently working on a setup in which I want to have a `base` document containing fields my `item` documents should inherit. Those fields are `id`, `created_at` and `updated_at`.

Indexing `item` documents which use the inherited fields works fine. However when I query `item` documents I don't see the inherited fields in the results.

Do I need to import the `base` fields and hence create a parent-child relationship between my `base` document and my `item` documents?

Do I need to wrap my `base` document in a `search` block or is the `document` block sufficient since I don't search the `base` document but rather use it as a basis for types to inherit?

Here are my files:

```
# base.sd

# search base { # <-- IS THIS NEEDED IF IT'S JUST A DOCUMENT?
    document base {
        field id type string {
            indexing: attribute
        }
        field created_at type long {
            indexing: attribute
        }
        field updated_at type long {
            indexing: attribute
        }
    }
# }
```

```
# item.sd

search item {
    document item inherits base {
        field title type string {
            indexing: summary | index
        }
        field url type string {
            indexing: summary
        }
    }

    fieldset default {
        fields: title
    }

    rank-profile item inherits default {
        first-phase {
            expression:nativeRank(title)
        }
    }
}
```

```xml
<!-- services.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<services version="1.0">
   ...
  <content id="content" version="1.0">
    <redundancy>1</redundancy>
    <search>
      <visibility-delay>1.0</visibility-delay>
    </search>
    <documents>
      <document mode="index" type="base"></document>
      <document mode="index" type="item"></document>
    </documents>
    ...
  </content>

</services>
```

Some best practices / advice is greatly appreciated! Thanks in advance 👍

**Comment by baldersheim** [comment]
You have not specified 'summary' on the fields in your inherited document. That is necessary for them to end up in the 'default' summary class.
However we discourage depending on the 'default' summary class.
Instead define and explicit summary class and use that in the query with &summary='my_summary_class'

See https://docs.vespa.ai/documentation/document-summaries.html
Note that the documentation also refers to the ancient summary-to for creating implicit summary classes. This is strongly discourage and will go away soon.

**Comment by jobergum** [comment]
https://docs.vespa.ai/documentation/parent-child.html touches on the summary settings for imported fields as well.

**Comment by pmuens** [comment]
Great! Works like a charm 👌

Thanks for helping out @baldersheim and @jobergum!
