### ISSUE TITLE
Vespa configserver 

### ISSUE THREAD

**Issue by yyangliu** [vespa-engine/vespa#9681]
Hello!  I installed a vespa cluster, in the services.xml I configed admin cluster as follows:

\<services version="1.0"\>
  \<admin version="2.0"\>
    \<adminserver hostalias="admin0"\/\>
    \<configservers\>
      \<configserver hostalias="admin0"\/\>
    \</configservers\>
  \</admin\>
  ...
\</services\>

Only one configserver "admin0" was added, but I can see  a configserver process on every content node, I'm confused about this, can you help? Thank u very much!

**Comment by yyangliu** [comment]
By the way, when I execute vespa-deploy and activate, a WARING: Host named 'vespa1' may not receive any config since it is not a canonical hostname.  What does it mean?

**Comment by jobergum** [comment]
What distribution are you running? Docker vespa image or rhel packages (see https://docs.vespa.ai/documentation/vespa-quick-start-multinode-aws.html). The configuration server should not run on any node, but there is a configuration proxy service on each node. 

The warning is issued when the registered dns (fqdn) does not match the hostname of the node.

**Comment by yyangliu** [comment]
Thanks for your reply,!
 I followed the guide in https://docs.vespa.ai/documentation/multinode-systems.html to install my cluster.  I'm running vespa image on 3 nodes and each node has 2 vespa docker installed, I configed only one configserver. I think vespa-deploy prepare and activate should only be executed on the configserver node, but it doesn't take effect.
As to the "WARING: Host named 'vespa1' may not receive any config since it is not a canonical hostname.", I checked fqdn matches the hostname of the node.

**Comment by jobergum** [comment]
If you want to run docker and a multi node setup each docker container instance needs a IP address and that each running docker instance can talk to each other. See also https://github.com/vespa-engine/sample-apps/tree/master/basic-search-on-docker-swarm

**Comment by yyangliu** [comment]
Thanks very much for your reply, I checked the source code about "WARING: Host named 'vespa1' may not receive any config since it is not a canonical hostname." and found that when hostname has no dot, this warning will be printed.

**Comment by yyangliu** [comment]
Hello, I have another 

> Hello! I installed a vespa cluster, in the services.xml I configed admin cluster as follows:
> 
> <services version="1.0">
> <admin version="2.0">
> <adminserver hostalias="admin0"/>
> <configservers>
> <configserver hostalias="admin0"/>
> </configservers>
> </admin>
> ...
> </services>
> 
> Only one configserver "admin0" was added, but I can see a configserver process on every content node, I'm confused about this, can you help? Thank u very much!

hello! As to <adminserver hostalias="admin0"/>, I didn't understand what the adminserver is for? and I found no adminserver process? What's the difference between adminserver and configserver?

**Comment by jobergum** [comment]
Great question, there is no adminserver process. It's just a logical syntax so if you define it and don't define e.g configserver/logserver  services they are placed on the node defined with adminserver.

**Comment by yyangliu** [comment]
OK, Thx very much!
