### ISSUE TITLE
Add approximate nearest neighbour search over tensors in Vespa 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#9747]
Sample libraries and performance comparison https://github.com/erikbern/ann-benchmarks

Currently tensors can only be used for ranking and not for searching so adding some high level tensor math functions for various distance functions like euclidian would be easy and does not need any specific integration work but would still be brute force over all matched documents. Adding support for doing an approximate *search* over tensors would be nice, returning the k closest documents give a input query tensor. 

```
field vector type tensor(x[10000]) {
    indexing: attribute | summary
    attribute:ann
}
```
where the attribute:ann directive tells the search core to build data structures needed for fast approximate nearest neighbour search for the vector tensor.

**Comment by bratao** [comment]
This would open Vespa to MANY awesome use cases 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by bratao** [comment]
Hi Vespa Team , @johans1 @jobergum 

Are you planning to develop this feature? 
ElasticSearch is coming closer to some Vespa use-cases with the dense vectors feature (https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch) 
An ANN would put Vespa far ahead in the game again. We had to develop a similar text feature, and unfortunately had to use an external ANN lib ( FAISS) because a naive comparative would be too slow for us.

**Comment by bratseth** [comment]
Yes, we'll get to it, but no firm timeline yet.

**Comment by jobergum** [comment]
@bratao appreciate the ping on this and we are on it but no timeline.

That being said; We at VerizonMedia have been running various text embedding models where we at run time compute the nn using euclidian distance in production with *very* strict latency requirements on Vespa for years now with large size data updated in real time.  See e.g https://www.youtube.com/watch?v=OD47cvofdcI

**Comment by bratao** [comment]
@jobergum Me and my team are following your example and trying to use only Vespa. We are struggling to create a ranking formula representing the euclidian distance. Do you mind sharing with us the ranking formula?

**Comment by lesters** [comment]
@bratao Euclidian distance between vectors A and B: `sqrt(sum(map(A - B, f(x)(x * x))))`

**Comment by jobergum** [comment]
@bratao 
Vespa 7.147 has the first version of approximate nn with a new ann query operator called nearestNeighbor. More optimizations to come during Q1 but wanted to give you an early notice since you seemed interested :) No official documentation on this yet, but feedback is welcome. 

https://hub.docker.com/layers/vespaengine/vespa/7.147.12/images/sha256-caa0487f01e14fb400599480351a8410199175e98b0e9ffa0d0ced35a59f50b9

See https://github.com/vespa-engine/system-test/blob/master/tests/search/nearest_neighbor/nearest_neighbor.rb#L72

The nearestNeighbor(document_tensor,query_tensor) uses euclidian distance.

**Comment by bratao** [comment]
Thank so much @geirst @jobergum and all the Vespa Team. You guys are awesome!!! ❤️ ❤️ ❤️ ❤️

**Comment by jobergum** [comment]
ANN is now available. See https://docs.vespa.ai/documentation/nearest-neighbor-search.html and https://docs.vespa.ai/documentation/approximate-nn-hnsw.html. Also see https://blog.vespa.ai/approximate-nearest-neighbor-search-in-vespa-part-1/. 

Will see some follow up blog posts on performance so stay tuned! Thank you for all the interest in this feature!
