### ISSUE TITLE
javadoc.io latest version resolves to version 6.313.35 

### ISSUE THREAD

**Issue by bjormel** [vespa-engine/vespa#9774]
E.g. the link to the javadoc found at https://docs.vespa.ai/documentation/searcher-development.html, [Container javadoc](http://javadoc.io/page/com.yahoo.vespa/container-search/latest/com/yahoo/search/package-summary.html). The URL for the landing page is https://static.javadoc.io/com.yahoo.vespa/container-search/6.313.35/com/yahoo/search/package-summary.html

**Comment by bjormel** [comment]
@kkraune fyi
@aressem

**Comment by aressem** [comment]
Too strict filtering on the generation of javadoc caused it to only be available for a subset of the modules. I have now fixed this and it is available starting with version 7.73.13.

**Comment by bjormel** [comment]
Thanks 😺
