### ISSUE TITLE
Short query timeout caused 503 errors

### ISSUE THREAD

**Issue by mnagaya** [vespa-engine/vespa#9891]
Our vespa cluster sometimes returns 503 errors when using a timeout of url parameter shorter than 50 msec even when the maximum response time is shorter than 30 msec.

Reulst of timeout=30ms
```
connection reuse count -- 53267
***************** Benchmark Summary *****************
clients:                      25
ran for:                      10 seconds
cycle time:                    0 ms
lower response limit:          0 bytes
skipped requests:              0
failed requests:               0
successful requests:       53292
cycles not held:           53292
minimum response time:      1.59 ms
maximum response time:     25.24 ms
average response time:      4.68 ms
25 percentile:              4.10 ms
50 percentile:              4.60 ms
75 percentile:              5.10 ms
90 percentile:              5.70 ms
95 percentile:              6.20 ms
99 percentile:              8.90 ms
actual query rate:       5331.87 Q/s
utilization:               99.85 %
zero hit queries:           3136
http request status breakdown:
       200 :    51782 
       503 :     1510 
```

Reulst of timeout=60ms
```
*** HTTP keep-alive statistics ***
connection reuse count -- 53646
***************** Benchmark Summary *****************
clients:                      25
ran for:                      10 seconds
cycle time:                    0 ms
lower response limit:          0 bytes
skipped requests:              0
failed requests:               0
successful requests:       53671
cycles not held:           53671
minimum response time:      1.51 ms
maximum response time:     22.36 ms
average response time:      4.65 ms
25 percentile:              4.10 ms
50 percentile:              4.60 ms
75 percentile:              5.10 ms
90 percentile:              5.70 ms
95 percentile:              6.10 ms
99 percentile:              8.73 ms
actual query rate:       5370.03 Q/s
utilization:               99.85 %
zero hit queries:           3157
http request status breakdown:
       200 :    53665 
       503 :        6 
```

I think that there is a problem with the difference between the FRT/FNET implementation of C and Java.

Here is a patch for this:
```
git diff
diff --git a/jrt/src/com/yahoo/jrt/Scheduler.java b/jrt/src/com/yahoo/jrt/Scheduler.java
index 57b5ac4..7b4d43c 100644
--- a/jrt/src/com/yahoo/jrt/Scheduler.java
+++ b/jrt/src/com/yahoo/jrt/Scheduler.java
@@ -3,7 +3,7 @@ package com.yahoo.jrt;
 
 
 class Scheduler {
-    private static final int TICK  = 100;
+    private static final int TICK  = 10;
     private static final int SLOTS = 512;
     private static final int MASK  = 511;
     private static final int SHIFT = 9;
@@ -61,7 +61,7 @@ class Scheduler {
         if (seconds < 0.0) {
             throw new IllegalArgumentException("cannot schedule a Task in the past");
         }
-        int ticks = 1 + (int) (seconds * 10.0 + 0.5);
+        int ticks = 1 + (int) (seconds * (double) (1000 / TICK) + 0.5);
         if (isActive(task)) {
             linkOut(task);
         }
```

Any ideas?

Thanks,

**Comment by mnagaya** [comment]
Added PR #9899 for fix this issues.

**Comment by havardpe** [comment]
While reducing the tick size will hide the issue, I think the real problem is that we underestimate the minimal time to execution when the timeout is not dividable by the tick size.

**Comment by havardpe** [comment]
PR #9935 should fix the 30ms case shown above. However, the 60ms case also shows a few 503, which could be caused by slot detection skew: When nothing happens, the event loop is allowed to idle for TICK size (100ms in Java) before waking up and checking the scheduler. This means that slot boundaries are not detected as soon as possible, but rather lazily. This in turn might make us underestimate the actual time when scheduling new tasks. Reducing the tick size from 100ms to 10ms might help a bit here, since having the timeout span more slots will make slot detection skew less severe when it happens. Other options are to add an extra 'safety slot' when scheduling, effectively extending all timeouts with an extra tick, or to sample the actual time when scheduling tasks (this is what we have tried to avoid with the current design, since clock sampling historically has been very expensive).

**Comment by mnagaya** [comment]
Thanks for your reply. I will test  #9935 today for the 30ms case.

**Comment by havardpe** [comment]
short summary:
* #9935 will round up all requested timeouts to full ticks to avoid short timeouts being rounded down to nothing (which happened with the 30ms case)
* #9936 will use a more conservative  estimate for the current time to avoid premature timeouts when the event loop was idle (which could explain the 503 responses in the 60ms case)
* The scheduling strategy now tries harder to not run tasks too early, which will make tasks run later than before.

**Comment by mnagaya** [comment]
vespa-7.68.36-1 works fine for me. Thank you for fixed issues.

**Comment by havardpe** [comment]
thank you for reporting this issue
